### ISSUE TITLE
Functionality from GT++ that maybe can be carried over

### ISSUE THREAD

**Issue by mtesseracttech** [GTNewHorizons/NewHorizons#1013]
GT++ has some interesting features that could be interesting for the pack, these include (but are not limited to):
GT-style Electric Crafting Table
Long distance high EU transport
Alternate Helium Source
Personal Cloaking Device
Some extra alloys to add some more flavor to tool material choice

Porting some of these features might be cool (especially the crafting tables, GT5 is the only GT without its own crafting tables).

**Comment by Dream-Master** [comment]
Will ask the mod dev.

**Comment by Dream-Master** [comment]
https://github.com/draknyte1/GTplusplus

**Comment by Dream-Master** [comment]
@draknyte1 is this possible?
I dont want to add the whole mod.

**Comment by draknyte1** [comment]
No.. Just disable the features you don't want with the config file. It's why I wrote it..

**Comment by Dream-Master** [comment]
The loading time is very long +200 Mods. If Parts of the Mod are disabled will it be ignored or loaded into the game too?

**Comment by draknyte1** [comment]
Ignored. 

I understand long load times are nobodies friend, but it's not a big mod..  It's entirely configurable so that you can use a single feature if you so desire..

**Comment by mtesseracttech** [comment]
That's cool, I wasn't aware of the extent of the configurability of GT++,

**Comment by Dream-Master** [comment]
Will look later into it. for 1.4.0.0 maybe.

**Comment by draknyte1** [comment]
Keep me up to date if you need support for anything.
Will happily make some changes to get it support on your GT builds. :D

**Comment by Dream-Master** [comment]
Sure. After I release 1.3.0.0 I will look inside this for sure. Hope weg a nice new reactor.

**Comment by Technus** [comment]
Reactor and portable GT energy blocks - idk why, batterybuffers do the same with batteries.

(i could just make the buffers hold content on break to get the same effect.)

**Comment by draknyte1** [comment]
Battery buffers suck. They don't hold enough lol. 

The buffers aren't portable, battery buffers are portable energy storage as far as I'm concerned.

**Comment by Dream-Master** [comment]
Will add this Mod in verion 1.5.0.0 for sure!

**Comment by Technus** [comment]
@draknyte1 
Checkout the Turbochargers in https://github.com/GTNewHorizons/NewHorizonsCoreMod

yes batterybuffers suck at low tiers but later their capacity is quite ok due to the batteries.

and yes buffers are prtable, via the mechanism of batteries that were inside still hold charge, you lose some power (internal storage capacity tho),

don't think i hate the true portable solution (saves some decent amount of inventory space that would be used to carry all the batts)

you might also want to checkout the EM2 branch, it has some neat features that are soo WIP (might get moved to separete mod),


back to GT5u, the base code is altered to "properly" work for tiers UV+, some examples of even more power hungry machines are in coeMod EM2 branch tho.


PS:yes the text above is pure chaos

**Comment by draknyte1** [comment]
Why only discuss one feature of my mod?
Not sure if you've looked into it in the past 6mo or spoken to DMXXL, but I add like 100 machines, 35+ real world alloys, more pipes, cables, tools. All of which are completely configurable, some things even have unique NH features. 

If you're implying I look to add said features to my own mod, I won't disagree. But as is, I'm trying to finish a handful of machines which are a tad overdue. Tree farm and a thorium reactor for example.

**Comment by Technus** [comment]
Probably i looked at something old yes.

**Comment by Dream-Master** [comment]
@Technus i will go over the stuff for the next 1.5.0.0 in deep. Hope you can help me too.

**Comment by Dream-Master** [comment]
TODO:

- [ ]

**Comment by Dream-Master** [comment]
hope we get a few fixes here. @draknyte1
