### ISSUE TITLE
Catwalks Need Recipe Tweak

### ISSUE THREAD

**Issue by mtesseracttech** [GTNewHorizons/NewHorizons#1015]
The catwalks mod is pretty cool, but a bit expensive right now. The current recipe for the steel grate is 5 steel rods and 3 steel screws, altogether this comes down to somewhere between 3 and 4 steel ingots per grate. Now we consider that a lot of the blocks from the mod cost even more steel and a few grates and that makes it very expensive at around 4-5 steel ingots per block.

Suggestion: make the grates a bit more affordable, like... 2 - 4 grates per craft.

**Comment by Excaerious** [comment]
I agree with this. Its not like the mod provides some sort of insane benefit - its simply some nice aesthetic blocks. Also considering you can make similar blocks insanely cheap using Architecturecraft or Microblocks, the actual use of Catwalks becomes limited even aesthetically due to it's insanely high cost.

For reference you can make many many slab, panels, or balustrades from Architecturecraft (between 8 and 16) per single block.
