### ISSUE TITLE
add Fullscreen Windowed (Borderless) for Minecraft to the pack """"SUGGESTION"""" 

### ISSUE THREAD

**Issue by Mylezz** [GTNewHorizons/NewHorizons#1057]
[Full screen Border less windowed Is Awesome and its only when u press F11 otherwise its not active ](https://mods.curse.com/mc-mods/minecraft/227441-fullscreen-windowed-borderless-for-minecraft)

**I use it and for some reason i get more FPS when using it.**

_Before i was using it i got a solid 300-340 mid render max Fancy max lighting
now on Mid render and max fancy and lighting i get 340-360_ 

_i think its to do with minecraft not having to Scale it down from 1920x1080 to fit into Windowed mode_

_Or something to do with render in general but just thought i was a nice suggestion_

**Comment by Dream-Master** [comment]
@Namikon, @bigbass1997 , @Technus , @Drobac

**Comment by Namikon** [comment]
This is a clientside mod. And since we don't have the ability to provide "optional" mods, well, you are free to use it if you want.
But not everyone will want to have it. I don't think this should be added to the default mod-collection we ship (And maintain if bugs occur)
Also, to be honest, to mention a difference between 300-340 and 340-360 frames is nothing but a joke...

**Comment by Bryfer** [comment]
Can we get an sub forum for texture packs and other client side like this one? 
Would be nice to have users submitting their own mod-addons and tips to increase FPS etc

**Comment by Namikon** [comment]
Here you go:
http://gtnewhorizons.enjin.com/forum/m/36844562/viewforum/7969672

**Comment by Mylezz** [comment]
Thanks

**Comment by Mylezz** [comment]
But around alot of my base from 300 to 360 is huge
