### ISSUE TITLE
Salis mundis duplication not working

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#1116]
Can't get the salis mundis duplication from thaumic bases to work, not in crucible and not in the thaumatorium

**Comment by Dream-Master** [comment]
Thaumic Bases is untouched in thing of nerfs. Will look into it when I am on this mod.

**Comment by Dream-Master** [comment]
We get a new forked version so we need to try it again.

**Comment by Dream-Master** [comment]
try with newest version

**Comment by Kortako** [comment]
@Dream-Master This issue is super old, but I didn't want to make a duplicate. This is still not working I guess (2.0.4.6).  I'm not sure if the intent is for it to be disabled or if the duplication is just bugged.  The research shows in the book but the actual recipe doesn't work.  If it should be disabled, then remove the research from the book, or if it's just bugged, can it be fixed?

**Comment by Dream-Master** [comment]
guess Zoko not touche this recipe in the scripts. Need to investigate.
