### ISSUE TITLE
Suggestion: Two default config changes

### ISSUE THREAD

**Issue by killslash** [GTNewHorizons/NewHorizons#1178]
In gregtech the below config is default:

 I:MaxEqualEntitiesAtOneSpot=3

I believe that is quite low. Just breeding a small pen of cows causes them to kill themselves trying to reach the player. Babies especially with their low hp will quickly be brutally murdered by the hungry herd. 

I think this should be higher default so early game vanilla animal pens don't kill themselves moving around, and especially when breeding them.

In Pam's harvestcraft the below is default:

  I:gardenspreadRate=100

I am of the opinion that this can be increased as default spread rate can be many real world hours with few or even 0 spread. 

Neither of these will harm progression or anything major.

**Comment by Bryfer** [comment]
having alot of entities on the same spot would cause massive lag if it wasnt solved easily, since they would push each other all the time. and if everyone on the server had 2-3 farms with lots of pushing cows, pigs etc... yeah that would generate alot of unnessesary load on the server.

I'd suggest intreasing the size of the farm instead and/or using an Railcraft Feeding station to automate the feeding process.

About the gardens personally I didnt have any issues with growing them. Yes they take time to grow, but you dont have to grow that many, and you can always find more gardens while exploring. Easy way to grow them is to just place em down near your base and do other stuff and then come back a when you have done a few quests (or similar stuff), replant the grown garden further away and repeat for infinite gardens
And you only have to get 1 of each plant, growing plants takes time too, but I see no reason for that to be changed either, the modpack shouldn't be too easy - food is an early game problem that shouldn't be solved too easy with gardens :)

quote from; http://harvestcraftmod.wikia.com/wiki/Garden
> Gardens can spread up to 3 blocks away from their own (a 7x7 area around the original, as well as one block above/below them), and gardens will not spread if there are 5 or more of the same type of garden in this 7x7 space. This means that when farming gardens, you should keep the same type of garden away from each other so more can grow, but pack together different types because they do not hinder each others growth (so long as the 7x7 has free space for more to spread, of course).

**Comment by killslash** [comment]
I am not suggesting removing the entity limit, just increase it. Right now even a small cow pen will have cows killing themselves trying to breed.

Increasing spreadrate wouldnt increase easiness very much if at all, in my opinion. There are plenty of wild ones you can punch for seeds right now for pams crops.

**Comment by Dream-Master** [comment]
I don't see an issue here. I never have problems with farms or pams gardens. If I am honest I would say pams gardens should have a spread rate by 0.

**Comment by killslash** [comment]
Just my opinions on some changes I feel would be better. I remember having like 6 cows and they were killing themselves with plenty of space. Pams gardens can also take several real life hours to spread which i feel is too much in my opinion.

I guess no one else seems to share it, so I can close this.
