### ISSUE TITLE
1.4.0.1 update: shadow (tainted magic) tinker tools turned to "shadow iron"

### ISSUE THREAD

**Issue by ghoulsblade** [GTNewHorizons/NewHorizons#1180]
1.4.0.1 was applied to the server i play on today, tinker tool parts that were made of "shadow" from tainted magic were turned to "shadow steel" instead

**Comment by Dream-Master** [comment]
This is a known issue.
@Drobac How it can be fixed ?

**Comment by Drobac** [comment]
This is the issue with Tinkers Gregworks that happens every major update

**Comment by ghoulsblade** [comment]
does that mean any and all gregworks tool parts are effectively trashed every update ?

**Comment by Ugachaga** [comment]
all quests and recipes with gregworks parts too

**Comment by Dream-Master** [comment]
Quests ?

**Comment by Ugachaga** [comment]
Like:
Diamond Spear Quest requered ArrowHead with meta 97.
Diamond Spear crafting recipe requered ArrowHead with meta 72.
Actual meta 95.

**Comment by Dream-Master** [comment]
Ok why that shuffle so much. I not add more materials so far i know. What could change the ids?

**Comment by Namikon** [comment]
After looking at the TGregWorks code, my first guess is that the Material-IDs are assigned on each startup, and not persisted in any file. This will corrupt any existing Tools and parts as soon as the *sGeneratedMaterials* List of Gregtech changes order. (This might happen by recompiling the mod, or adding / removing / changing materials, or because of magic)

This is, by itself, perfectly fine for GregTech, as the MaterialIDs are persisted, and it doesn't matter if Iron comes before Nikolite or not; They always keep their same MaterialID.
But this is not the case in TGregWorks.

See source snippet here:
https://github.com/Vexatos/TinkersGregworks/blob/master/src/main/java/vexatos/tgregworks/integration/TGregRegistry.java#L48-L76
@Technus Can you please confirm my guess? I think this would be rather easy to fix, if this happens to be the problem

**Comment by Dream-Master** [comment]
Vexatos made an Update so i will test it later.

**Comment by Dream-Master** [comment]
https://github.com/Vexatos/TinkersGregworks/commit/75b4255c3492dc43dc0af323b97c5b30c2b6b7e8

**Comment by Dream-Master** [comment]
Will be fixed in the Next update hopfully. Need some testings here.
