### ISSUE TITLE
Mod additions

### ISSUE THREAD

**Issue by nosknut** [GTNewHorizons/NewHorizons#1196]
Here are some mods that would be great for complexity and the time it takes to "complete" the game:

"Warpdrive Mod" allows for building custom ships that can warp/"teleport" trugh space.

"Mekanism" is great for industrialization, and introduces some incredible power genertion, storage and management systems.

"Big-Reactors" is a mod containing reactors and turbines. They are very effective, and if you do not use turbines, it will prevent extreme amounts of lag and loss of tps and fps.

"Modular Powersuits" is basically a musthave mod everywhere. As the name suggests it adds a piece of armour, very often compared to the ironman suit. Vareous components can be added to this such as jetpack, speed increasing equipment, autofeeders, nightvision etc.

Links to all of the mods:

Warpdrive:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2510855-1-6-4-1-7-10-warpdrive-custom-ships-laser-cannons

Mekanism:
http://mod-minecraft.net/mekanism-mod/

Big-Reactors:
https://minecraft.curseforge.com/projects/big-reactors/files

Modular Powersuits:
http://machinemuse.net/download.php

**Comment by bigbass1997** [comment]
Warpdrive:
I'm not sure who would ever actually use this. Also as far as I understand, this could be used to circumvent the tiering system we use with rockets and planet tiers.

Mekanism:
Is there something in this that GregTech doesn't already have?

Big-Reactors:
I see no use for this mod in this modpack. Big Reactors generate RF, very few things in this modpack uses RF, and such can just be powered with GregTech EU anyways. On top of that we already have Nuclear Reactors through IC2, as well as Naquadah and Fusion reactors through GregTech.

Modular Powersuits:
I could maybe see this being added, but understand that most of the recipes would probably made decently mid-high tier due to the powerful components that the Powersuit can provide.

**Comment by nosknut** [comment]
The warpdrive mod if you have not seen the video is incredibly useful when you first get into it. I have played around with it, and the power is in the programs that players make to controll their ships. You uave multiple weapons systems and components such as teleporters that can be tiered. Also, it works in a different kind of space then galacticraft. Everything is different about it. Warpdrive is concidderably more complex, and alot more interresting for those who spend time developing. Also, the mod is basically completly ntegrated with ic2 ...

**Comment by Dream-Master** [comment]
Mekanism we dont need so far i cansay.
Big Reactor is to complex and mostly RF based.
Modular Powersuit i using in a previeous Modpack in 1.6.4. We have Gravisuit with a shield and many other armors.

The only mod idk is Warpdrive but i remeber we have Achimedis Ships before which lag the Server and we decide to take it off. I will look into the video and look what this mod offers.

What the other thnink. @Namikon , @Technus @Drobac

**Comment by Namikon** [comment]
Mekanism: As bigbass said, Gregtech covers everything Mekanism has. Really no need. If you want the simplicity of machines, you can use the EnderIO machines that have been tweaked for GT Ores and our progression

BigReactors: That really is a RF-ModPack mod. We have spent countless hours on tweaking and adding PowerGen to GTNH no other pack has.

Modular Powersuits: GraviSuit (Which is, like most powergen in GT, a unique Version only to be found in our pack), Bloodasp's Dynamic armor system, Tinkers, Nano/QuantumChest, there is plenty of choice already

Warpdrive: That concept sounds interesting, and could possibly be a replacement for the weird DimensionLoading system Galacticraft is utilizing (And thus causing a lot of Server impact)
But in order to add this, It really must be evaluated with utter attention. If it allows, in any way, to skip progression or causes Lag like Archimedes did, it shouldn't be added.

**Comment by nosknut** [comment]
Thx for conciddering the warpdrive mod, and i can say there are very few things that can make it buggy. I can tell you that solar cells do crash some times, so i would reccomend to ban them in the space dimmension. Also, repeated jumps on planets can cause tps to drop over time, so i also reccomend doubbling the cooldown time. Other then that there arent many problems as most of them are alreddy solved in the mod itself. I understand why the rest whont be added ...

**Comment by Dream-Master** [comment]
I guess the pack is full maybe we add it later.
