### ISSUE TITLE
Quest Coins are Broken. Impossible to progress in quest book.

### ISSUE THREAD

**Issue by Bryfer** [GTNewHorizons/NewHorizons#1202]
8192 The Technician coins is needed to advance into IV tier, but sadly I used all the coins me (and Ghengis) has collected thru the entire questing line unlocking EV tier, which cost 2048 The Technician coins. We have also unlocked a few other questing lines aswell, but none that was this expensive. and they dosnt give enough coins back.

Right now I got 241 The Technician coins, so I need about 8000 more of the The Technician coins to advance into IV tier, but there isn't any quests that can give me so many coins. Most quests available gives no coins or the wrong kind of coins.

In tier 5 (EV) you can collect a total of 140 "The Technician coins" and it costs 2048 to unlock it.

The only way I could get coins, without doing every optional quest in every questing tier is killing monsters that is the only (?) repeatable quest available.
hunting and killing 10 pigmen, zombies, blaze, enders, witches, spiders, skeletons and creepers each day would give me 40 coins/day, so it would take me 200 days to advance into IV tier, using this method.

**Comment by bigbass1997** [comment]
I have always been confused by the use of these coins to restrict progression through the quest book. They do not add anything meaningful to the questing experience. I would have to say that the number one most frequently asked question I get from new players to the modpack is what those coins are even used for.

The inherent properties of a quest line already establish a flow of progression through the modpack, as well as properly restricting the player from progressing too fast. There is no reason to have these coins that simply restrict progression and cause people to either cheat or grind repeatable quests, and possibly even causing them to stop playing entirely.

Back when the coins were only used for the Legendary Quests, I was sorta okay with that, but still confused why the coins were used to restrict progression instead of the actual main quest line. As you would have to be doing the quest line to get enough coins to unlock the Legendary quests anyways.

If the purpose of the quest coins are to force players to go back and finish optional quests, why are the quests "optional" in the first place?

On top of all of this, as far as I can see and have heard from people in Discord, the new changes to the quest coins make it practically impossible to progress at some points.

**Comment by Dream-Master** [comment]
Mh ok so i need to rewiew the whole system.
If i not gated Questsline with the Coins i will give them a better use.
@bigbass1997 Any idea ? Buy maby some items with it?
I can add a Tooltips for the Coins to explain the usage.

**Comment by VermillionX** [comment]
Perhaps add coin-specific loot bags in the rewards area of the quest book for spending the coins?
Split up the types of coins obtained from quests to something other than technician coins, and allow the purchasing of Technician/Cook/Chemist/Survivor/Wizard/Beekeeper loot bags in tier I, II and III relative to the coin type and level used. Not cheap loot bags, make 'em expensive so people don't rely on them.
Currently most quests, including mob-killing quests give technician coins, even though tech has nothing to do with them.

**Comment by Valdevon** [comment]
Like what Vermillion said, I think it would be nice to be able to exchange the coins for resources. I.E using the forestry/farming coins to buy food/seeds and using the technician coins to buy bronze/steel (or maybe even simple components like motors and cables)

**Comment by Dream-Master** [comment]
Ok only Legendary Quests need Coins.
