### ISSUE TITLE
Aluminum is useless once it's in the smeltery. [Suggestion]

### ISSUE THREAD

**Issue by Exo594** [GTNewHorizons/NewHorizons#1208]
Molten Aluminum is useless for anything other than aluminium brass or alumite at once it's been melted down in the smeltery. However, it's far more convenient to melt down masses of aluminum ore-berries at once than to macerate them individually when at early tech levels.

Perhaps you could add an "aluminium sponge" ingot or block that is equivalent to several berries or dusts, which would be poured from the smeltery into a casting table or basin, then players would have several orders of magnitude fewer things to macerate if they are using berries as a source of aluminium.

**Comment by bigbass1997** [comment]
First I would like to note the distinction between Tinker's Construct and GregTech. Both mods implement a type of Alumin(i)um. Tinker's Construct implements Aluminum, and GregTech implements Aluminium, see the spelling difference.

There is a good reason why it is impossible to craft Aluminium or Aluminum ingots in the smeltery. The reason is that it would allow players to skip crafting the Electric Blast Furnace and ultimately most of LV tier.

If you are already at LV or MV tier right now, and you are trying to use Aluminum ore berries to make Aluminium dust, then simply make more macerators. It does not take that long to macerate berries.

On top of that, there are many easier ways to get much larger amounts of Aluminium dust even as early as LV tier using the centrifuge to centrifuge various ore dusts. At MV the process becomes even easier by utilizing the MV Electrolyzer.

**Comment by Exo594** [comment]
I'm not suggesting making GT Aluminium be craftable through Tinkers', as I am well aware of how that would break progression. What I'm suggesting is a buff to the near-uselessness of the Tinkers' Smeltery, and a fix to the annoyance that is the irreversible process of melting alumin(i)um in a Smeltery. So many processes in this pack on the GT side of things are reversible: Don't want this plate any more? Furnace it back into an ingot.

I would be happy to have the option of sitting around, watering my oreberry bushes for several minutes instead of having to go out to one of my 9000 mines to mine for stuff when I all might need is a few ingots of aluminium. Having some mass-processing step that makes use of previously built infrastructure seems like a wonderful way to make that more viable.

Or, hell, let us re-cast the oreberries using a nugget mold. At least then people can get molten Al out of their smelteries.

**Comment by bigbass1997** [comment]
Going back to your initial statement

> However, it's far more convenient to melt down masses of aluminum ore-berries at once than to macerate them individually when at early tech levels.

Maybe so for ore-berries, but using ore-berries is far less effective than using the methods I mentioned already, the Centrifuge and Electrolyzer.

> I would be happy to have the option of sitting around, watering my oreberry bushes for several minutes instead of having to go out to one of my 9000 mines to mine for stuff when I all might need is a few ingots of aluminium.

What at low tiers requires only a few ingots? And assuming that statement means you are already at MV tier and capable of making the dust into Ingots at all, you also have that capability to make the MV Macerator and the MV Electrolyzer. The Macerator will process one ore-berry every 10 seconds, which is still fairly slow, but really not that bad for "only a few ingots".

I can understand that you want some way to get the Aluminum out of the smeltery, and I am okay with being able to use the a nugget mold to get Aluminum nuggets. Though understand you would still have to macerate the nuggets into dust, which still takes 10 seconds per nugget in the MV macerator.

If you use the Electrolyzer you don't need to go mining for ores. Most of the recipes for making Aluminium dust in the Electrolyzer do not use ore dusts at all (that's what the Centrifuge is for). You can even make Aluminium dust out of something as simple as Red Granite Dust, in far less time than ore-berries.

**Comment by Exo594** [comment]
The MV Macerator is locked behind the implosion compressor.

**Comment by Bryfer** [comment]
You can use steam or LV macerator to turn oreberries into tiny piles of dust. But there are alot of better ways to collect aluminium as bigbass mentioned. (you still need an EBF to make ingots tho.)

When you place aluminium into the smeltery it turns into aluminum, which after that point can only be used for Tinkers' construct tools, and molds. It's not meant to use the smeltery to process aluminium.

Aluminum is useless as ingot/blocks/nuggets, and allowing creating of aluminum nuggets/ingots/blocks inside the smeltery would confuse alot of players, since its so similar to Aluminium.

If you want a way to empty the aluminum out of the smeltery, you can put it into tanks as liquid. You can later pump this liquid back into the smeltery once its needed.
You can NOT hovever turn it into Aluminium
![image](https://cloud.githubusercontent.com/assets/22825059/23957459/b80b143c-099f-11e7-9fee-52388fea9ca9.png)
![image](https://cloud.githubusercontent.com/assets/22825059/23957492/cd1d2806-099f-11e7-9f99-1f8943d70127.png)

An possible way to solve this would be to create an new item, or use the Raw Aluminum 5899:12 (This item is not used for anything according to NEI, so using this would not confuse players with the similar nugget/ingot/block name)
which then could be smelted into aluminum inside the smeltery of macerated into aluminium dust inside the macerator

However, it would be alot easier if you were to macerate the oreberries instead of putting them into the smeltery in the first place.

**Comment by bigbass1997** [comment]
I personally do not see any issues with adding a recipe so that the Aluminum from the smeltery can be poured back into Aluminum nuggets, so that all of that Aluminum is not wasted. @Dream-Master 

In the future I suggest double checking recipes using NEI before committing a lot of resources towards something. NEI does accurately show that Alumin(i)um processed into the smeltery can't be turned back into an item.

**Comment by Dream-Master** [comment]
@Exo594 @bigbass1997 so what i need to do here? for me it isnt a issue here. I can reenable the Aluminum Block From tinkers maybe to collect Alu.

**Comment by Dream-Master** [comment]
Ok alu blocks i cant do will add a ne item.

**Comment by Dream-Master** [comment]
I i using the Thinkers Raw aluminium item instead of making a new one. 9216 mb = 64 alu dust.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/24074161/89be527c-0c03-11e7-88a4-09b3930bcf96.png)
![image](https://cloud.githubusercontent.com/assets/2970688/24074162/8e2bb9e4-0c03-11e7-8dce-901b2745a024.png)
![image](https://cloud.githubusercontent.com/assets/2970688/24074163/94bbd23a-0c03-11e7-98ec-05d9437a18fa.png)

**Comment by bigbass1997** [comment]
@Dream-Master This wont help anyone. Original poster, and other new players who have accidentally put Alumin(i)um into the smeltery, are not going to be able to dump 9,216mB into the smeltery. With these recipes anyone who dropped even a couple ingots worth into the smeltery would still be screwed. Make the Raw Aluminum 144mB, and macerate into 1 dust.

**Comment by Dream-Master** [comment]
sure
