### ISSUE TITLE
[Suggestion] OV scanner range

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/NewHorizons#1211]
After crafting the OV scanner and trying it in action I found out the info about it is just wrong.

Its range is 25x25 centered on the player (not 9x9) and ONLY 12 blocks down. That makes it pretty much useless as you still have to dig down to ~15 height to be sure you don't miss any vein.

If you can change it or create your own scanner, I suggest making one scanning 9x9 area with 90 height. That gives you the same amount of blocks as 25x25x12 while being useful as you don't have to dig down every 48 blocks (and be smart and techy).

**Comment by kris449** [comment]
There is a seismic prospector that scans down to bedrock, though it's more complex to use.

**Comment by Fapiko** [comment]
I don't think the seismic prospector is a very good solution to scanning ore. By the time you can craft it and the supporting machines/supplies to use it frequently enough to do a large grid you probably already have access to a jetpack which makes digging straight down a pretty safe way to identify ores (and much faster than the whole seismic prospector loop, IMO). I mostly just use it for oil prospecting.

I agree that a portable scanner which can scan all the way to bedrock for finding ores is something I would love to see though I'm not sure if the GregTech one's range could be easily modified or a new one would need to be implemented. I imagine that it would be far enough along in the progression that you probably already have a jetpack so identifying veins without it wouldn't be very difficult anyways, just a very time grindy task which a scanner would make less-so.

**Comment by kokochicken** [comment]
tbh the recipe would have to be changed quite a bit,,,, the OV scanner does 25x25x12 because it goes out 12 blocks in each direction from the player. which is a 25x25x25 cube. If it could scan all the way to bedrock recipe would have to be much higher for balance reasons, and by then you will have enderquarry and a fast mining tool. Prospecting for ores only takes 5-10 seconds per 3rd chunk anyways by the time you have OV scanner, shouldnt be too bad :P

**Comment by Methes** [comment]
So, if at certain stage of the game you can dig down super fast with your pick and fly out with a jetpack, that's completely fine. But having a scanning tool doing that more cleverly is suddenly way off balance and should be nerfed to the point when you don't even need it anymore. I fail to see your gameplay logic at all.
My point is to buff otherwise useless item to enhance gameplay and player's quality of life in a balanced way that immersively makes more sense than making holes and flying out, while not adding any serious advantage, if any at all.

**Comment by Fapiko** [comment]
I think what kokochicken was suggesting is that the whole cube size would have to scale out, to get 90 blocks down you'd be looking at a radius of almost three chunks which would let you scan 4 ore veins at once. I haven't looked at the GT scanner code to know how it is implemented, but I think the better change would be to just unlock the Y range and have it scan from your current Y level all the way down to bedrock rather than increase the overall scan radius, similar to how the seismic prospector works but without having to go through all the work of scanning the data chip etc. Then the seismic prospector's main use would be for prospecting oil.

**Comment by kris449** [comment]
Well the fact is, as per [gamepedia](http://ftb.gamepedia.com/OV_Scanner) , the scanner IS supposed to 9x9 down to bedrock.  So at some point it was tweaked.  And I agree, having it scan a wider area at the expense of depth is near useless; and with the prospector, you can dig to the bedrock and pillar back up by the time all the processing is done.

**Comment by Dream-Master** [comment]
@Technus 
Are you able to code a better Scanner then the OD and OV Scanner?

**Comment by Dream-Master** [comment]
Mod added.
