### ISSUE TITLE
Lumberaxe is overpowered

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/NewHorizons#1232]
We have had a discussion on discord and most people agreed that giant trees + lumberaxe are way better than the wood farms you can build.
Sure the lumberaxe is first available after the EBF but the question is: Should wood farms be pretty much useless once you unlock that overpowered axe of doom?

The arguments are pretty clear, a lumberaxe is...
1. cheaper
2. faster
3. easier to keep running (no energy/fuel cost, no need to repair once you got moss which is very likely)
4. simpler to use
5. easier to set up
...than all the wood farms.
Yeah sure it's not automated but who cares if you chop max 10 seconds on a giant tree that drops 64^2 wooden logs?

So I got a few ideas what we could (if possible) do:
1. The axe itself is really cheap so if it could just have the same effect as the hammer or excavator (3x3x1 harvesting range) it would be perfect imo. This would also make the Thaumcraft "Axe of the Stream" usefull again and in general fit for the ressources you pay.
2. Remove moss as a possible modifier and change the durability to 20-25% of the current so you have to at least pay more materials for having this overpowered tool. While I think that this wouldn't really fix the issue it's not that much "for free" anymore. In addition when you hold it you should gain some effect that increases the time it takes to chop down big trees by 300%. Kind of an ugly solution but if suggestion 1 doesn't work it would be better than nothing.
3. Make it really really late game close to the level of the staff of power, at that point you don't need wood farms anyways. Also a weird change but hey I know that Dreammaster doesn't want to disable the tool which would be the easiest way to deal with its overpowered nature.

**Comment by VermillionX** [comment]
Most of those methods probably wouldn't work, or would require huge amounts of recoding TiC.
It would probably be easier to simply disable the Broad Axe Head's usable materials except for EV tier metals and above (meteoric iron, meteoric steel, titanium, palladium, iridium, osmium, etc...), which would keep it at EV+ and expensive.

**Comment by bigbass1997** [comment]
I think we should ask this question instead: How big is the demand of wood after LV tier? Sure, I will not denigh that using a Lumber Axe combined with the Sacred Oak tree, it is quite easy to get a large quantity of wood. However, what use does that wood actually have? By MV tier the player should have moved onto Biogas and/or Oil products for power production, MV being the tier where its easily possible to make the Lumber Axe. (Only other way is to scavenge together some Aluminium Ingots from loot chests). Before MV, and so before the Lumber Axe is readily available, wood is mainly used for creosote and steam. If the player chooses to do so, Forestry Multiblock farms can cheaply be made at LV tier, which is a very good, renewable source of wood.

While you may see the Lumber Axe as overpowered, what use does it even have at the point where you can actually make one? The only real use for very large quantities of wood after that point is maybe to create Oil using the Pyrolyse Oven, but that would need a constant supply of large quantities of wood, which is where a farm would likely be used instead of having to cut down and somehow store that much wood, only to have to do it again the next day (if not sooner).
If there is no major use for the large quantities of wood that the Lumber Axe could provide, then the Axe is simply not overpowered, even if it is "cheap" or easy to use.

> We have had a discussion on discord and most people agreed that giant trees + lumberaxe are way better than the wood farms you can build.

Who exactly agreed that the Lumber Axe should someway be nerfed? As far as I can tell only four people were involved in the discussion, one of which was you, another was Dream who didn't offer any opinions. The third person said they have never even tried the automatic farms before and so have no basis for an accurate opinion.

Vermillion's suggestion is something I was going to bring up but he posted while I was typing. If a nerf of some kind is going to happen, then if possible I would rather try to increase the required tier to make the Lumber Axe, say to HV or EV tier.

**Comment by WarlordWossman** [comment]
> While you may see the Lumber Axe as overpowered, what use does it even have at the point where you can actually make one? The only real use for very large quantities of wood after that point is maybe to create Oil using the Pyrolyse Oven, but that would need a constant supply of large quantities of wood, which is where a farm would likely be used instead of having to cut down and somehow store that much wood, only to have to do it again the next day (if not sooner).
If there is no major use for the large quantities of wood that the Lumber Axe could provide, then the Axe is simply not overpowered, even if it is "cheap" or easy to use.

I guess with that argument the tool is not needed at all then and could simply be disabled. Why have a tool to get wood at MV tier if you don't need any?

And my point was more that this pack has a focus on technic things since it is based on GregTech (sure there is magic stuff but that doesn't change it being a technic pack mainly). And in a technic pack things should be more complicated imo. Why is the recipe for a door that expensive? Not because doors are overpowered I guess, you can loot them everywhere... It's more of a style thing if you ask me. And I think if you ever need a lot of wood once you unlock the lumberaxe it would fit the pack way more to go for a wood farm than a tool that is extremly braindead.

**Comment by bigbass1997** [comment]
> I guess with that argument the tool is not needed at all then and could simply be disabled.

Just because something does not have a required need, does not mean it should be completely removed. How about for not quite as large trees? Lumber Axe still has some use there, but certainly not overpowered still, due to not as much wood at once. Or maybe someone just prefers hand tools over automated farms. Take Railcraft for an example, besides the Water and Fluid Tanks, the tracks and rail system is seldom ever used, but once in a while someone does want to use them, even if its not required to accomplish a task. We don't disable it just because it does not have much use. Another example may be Barrels vs Drawers. Practically identical mods, except that Storage Drawers adds to Drawer Controller, which gives it a large advantage over Barrels. But we don't disable barrels, because someone may prefer to use Barrels instead.

The reason I make that argument is to argue that the Lumber Axe is not overpowered; not to argue that it should be completely removed from the modpack.

> And in a technic pack things should be more complicated imo.

> And I think if you ever need a lot of wood once you unlock the lumberaxe it would fit the pack way more to go for a wood farm than a tool that is extremly braindead.

So how is the Lumber Axe "extremly braindead", but a farm that does everything for you is not braindead? Both options require some form of crafting and assembling, neither being all that complicated.
The Lumber Axe requires you to go out and actually plant the saplings, bonemeal if you have some or otherwise wait around, then cut down the tree, and pickup all the drops and manually put everything into storage. An automated farm is just that, automated. It will plant all the saplings for you, it will cut the trees for you, it will pickup everything for you and easily output into storage automatically.

**Comment by Methes** [comment]
The most valuable resource in this pack is player time. While the Lumberaxe gives you a significant boost over regular axe, automated farm is ultimately better. Yes the time investment is larger at first but in the end it pays off.

Punching trees is essential part of MC, while being a bit tedious. Normally you do it slowly even with enchanted diamond axe and wait ages for leaves to despawn. Is FasterLeafDecay overpowered? It takes away the benefit of Axe of the Stream too.

The way I see it it's perfectly balanced how it is now. You can either have lower initial cost but higher maintenance cost over time (time AND material cost of repairs) or just create a farm and be done with that.

Also better wood farming is important part of modded MC and now it is gated already behind MV age for Lumberaxe (3 weeks of intense playing) and LV for farms.

**Comment by Bryfer** [comment]
I see no reason to "extend" the gameplay of the modpack with some useless/boring tree chopping. I got plenty to mine underground already. I think the modpack is quite long already.

You need wood/charcoal mainly in Steam, LV and beginnind of MV before you advance into more advanced methods of creating energy.
If the Lumberaxe were to be movied into higher tiers it would become useless since you would most likely have an tree farm set up at that time anyway.

Do you guys remember how happy you was when you was able to craft your first two aluminium screws to make the Tool Forge?- **Don't ruin this feeling for new players!**

**Comment by WarlordWossman** [comment]
It's funny how you guys tell me since I was involved in the thought process of these nerfes back than. If I remember correctly Dreammaster and I had the idea to gate the tool forge after the EBF back than.

> The most valuable resource in this pack is player time.

Keep in mind that not everybody is playing on a server.

**Comment by Methes** [comment]
> It's funny how you guys tell me since I was involved in the thought process of these nerfes back than. If I remember correctly Dreammaster and I had the idea to gate the tool forge after the EBF back then.

And it was and is perfectly fine, good idea. I'm just saying I don't see the real need to move the Axe even further away, that's all :).

> Keep in mind that not everybody is playing on a server.

What do you mean? I play on a private server with just one friend so we do have to go through all of the things on our own. Is that what you're hinting?

**Comment by WarlordWossman** [comment]
I mean people seem to be fine with it and I can see why but it's not ideal imo and I would still like to see it changed.

>What do you mean? I play on a private server with just one friend so we do have to go through all of the things on our own. Is that what you're hinting?

Playing on my client I can't chunkload farms for hours without being afk ingame.

**Comment by Dream-Master** [comment]
Ok after all this Text i come to the decission to close this now and let the Lumber Axe like it is. There are more important Stuff we have to deal with. Thank you
