### ISSUE TITLE
Galacticcraft suits

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#1239]
This is not an issue, actually, but.

Thermal padding and oxygen gear looks awful. it flicks out of the most of armors, have a bloodeye crying color, have animation, urgh... and don't allow invicibility via armor disguise(Gadomancy).

Please, make this shit invisible in player models. Maybe with some kind of thaumcraft infusion.

**Comment by Dream-Master** [comment]
@Cinobi ask @BlesseNtuble about it. Mot sure if this is fixed in 1.1.4

**Comment by Cinobi** [comment]
What can i ask u? "please, remove ur suits models couse my thaum look bad with them"?)

**Comment by Dream-Master** [comment]
Do you think I can? I am a mod pack maker not a java coder sorry.

**Comment by Cinobi** [comment]
Well, u can make a correct english issue, atlest :D

**Comment by BlesseNtumble** [comment]
screen?

**Comment by Cinobi** [comment]
here u go:
https://imgur.com/a/Fed0O

**Comment by Bryfer** [comment]
It would be nice if we had an mod which could override the equipped armor and let you choose how you wish to look like without actually wearing it, like equipping ghost items instead of real gear.
This would allow vampires to actually "wear" the vampire armor even tho they are really using quantum armor etc

Just wanted to share my opinion i have no idea if this is possible at all

**Comment by DietmarKracht** [comment]
i tried to do the gadomancy stuff with both termal padding and oxygen mask but neither worked. and it looks very bad - espacially the oxygen mask

**Comment by Dream-Master** [comment]
@BlesseNtumble we using version 1.1.3 in the actual pack.  Will update to 1.14 soon.

**Comment by Dream-Master** [comment]
The mod dev break so much in never version i guess we never update this mod again.
