### ISSUE TITLE
Quests do not work on a server with onlinemode false

### ISSUE THREAD

**Issue by ValeroHD** [GTNewHorizons/NewHorizons#1275]
Hello!

I had problems to install this modpack on a server with online mode on false.

I saw that the problem is because BetterQuesting mod had this bug:
https://github.com/Funwayguy/BetterQuesting/issues/60

This was solved on its last version. 

Could you update it to the last version?

Thank you!

**Comment by bigbass1997** [comment]
Its not a bug that is causing this. Stop using illegal versions of the game!

BetterQuesting uses UUID's to track players instead of their names. UUID's are given through authentication from the Mojang servers, so illegal games/accounts will not work with BetterQuesting. And we will NOT support people who do not own legal copies.

If by some small chance you are using a legal copy of Minecraft, then there is no reason not to be using online mode.
