### ISSUE TITLE
Stargate caller Monitor

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#1284]
The monitor for calling the stargate in Atlantis is acting up again, cant call tier 1 and 2 plannets

**Comment by Ghengis88** [comment]
dream is there a way for us players to fix it if it happens or must a Admin fix it?

**Comment by Dream-Master** [comment]
Admin fix is needed. But i never played much with the mod.
@Drobac @Technus can you help?

**Comment by Technus** [comment]
update opencomputers/sgmod done for 1.5?

**Comment by bigbass1997** [comment]
@Ghengis88 Can you be a bit more specific about the problem? Are you able to dial any other gates? What exactly happens when you try dialing the Moon for example?

**Comment by Dream-Master** [comment]
@Technus so far ik we have the lastest sg craft mod version adn the lastest oc verion in the pack.

**Comment by bigbass1997** [comment]
Ok, I am ingame right now. I see nothing wrong with this computer. It dials to early and late tier planets without any issues.

@Ghengis88 Unless you can provide some additional information about what you experienced, I suggest this issue be closed.

And for everyone reading this, if you experience problems with the dialing computer, please just contact me on Discord instead of opening an issue.

**Comment by Ghengis88** [comment]
@bigbass1997 I think someone in the staff fixed it elrlier, so yea close the topic. 
what happend was there were just red text where  tier 1 and 2 plannets were suposed to be, there was the same problem a few weeks ago, if it happens again i will take a screenshot
