### ISSUE TITLE
Agricraft

### ISSUE THREAD

**Issue by KshitijSharmaIsCoding** [GTNewHorizons/NewHorizons#1309]
### I have a mod suggestion

# Agricraft

This mod can add a new dynamic to early game food production. By allowing to level up pam's crops.

The Link To The Mod :- https://minecraft.curseforge.com/projects/agricraft

 ---

#### If We Need To Remove a Mod. 

I Suggest AquaCreeper As It Adds Nothing Important.

#### If Needed I Am Ready To Make The Scripts As Well As The Mutations And Nerfs.

**Comment by Adz-Scott** [comment]
There is (or was last time I used it) a bug with agricraft where the client would crash if the block underneath a crop was destroyed. Something that's worth considering.

Agricraft would be a nice addition though.

**Comment by bigbass1997** [comment]
The way I see it, you are actually trying to remove the "dynamic" of food production. Pam's Harvestcraft provides us with 30+ plants, most of which can be made into tons of different foods. Those plants can be collected using the many kinds of gardens that generate throughout the world in different biomes. Pam's plants/crops are really not that hard to find and produce a lot of, even in early game.

There is no need to level up the crops. Only reason I see is so that players can be more lazy about farming. Build a tiny 9x9 and be done with food entirely. Or actually spend some time building a much larger farm with many different plants and harvesting them from time to time in bulk. Figuring out what combinations of different plants are best and how much of those plants are needed to make better foods. That sounds like a way better "dynamic" than Agricraft.

This modpack is supposed to be HARD, like really hard, but not impossible. Farming is hard, but far from impossible. If you want plants to grow faster, simply plant more of those plants.

**Comment by Jayjayx5x1** [comment]
also to add we already have a mod similar to this... IC2 crops :D

**Comment by KshitijSharmaIsCoding** [comment]
But IC2 Crops doesn't function for food. This is mainly for food.

**Comment by Dream-Master** [comment]
I let this suggestion open. Idk if this Mod really fits in the pack?

**Comment by hhheeexxx** [comment]
Agricraft for modpack with easy game. It's produce any resources (metals and so on). 10 x 10 x 10 level crop produce loot very fast. And with thaumcraft or bloodmagic farm automation it's produce unlimited resources fo free and very very very fast. It's not for HARD modpack.

**Comment by Dream-Master** [comment]
Yes i think we close this for now. This mod not realy fits.

**Comment by bigbass1997** [comment]
@Dream-Master Why did you reopen this?

**Comment by Dream-Master** [comment]
because we get this mod with all scripts an configs included (allready balanced and fit in this pack) from a  German YouTube playing the pack and knows well about the recipe style and tiering system.

**Comment by Dream-Master** [comment]
Long time ago this mod was suggest but no one doing the tweaks an recipes that why we close this issue (not exactly  this issue)
