### ISSUE TITLE
PLutonium 244

### ISSUE THREAD

**Issue by Dreminon** [GTNewHorizons/NewHorizons#1313]
why remove PLutonium244 from normal spawn?
only place you guys have it spawning is deep dark. by the time we get there we are so far beyond needing it
heck you even have plutonium 241 (the more refined verision) spawning at the T6 rocket
you can get uraniuam 238 which can be refined into plutoniuam 244 on T2. so you would think the plutonium 244 should be like t3-4.

**Comment by bigbass1997** [comment]
Looks like you need to do some more research..

If you would have performed a very simple search in the Github issues for Plutonium, you would have found issue #1144 where Plutonium 244 was added to Tier 3 and higher planets.

Since you obviously looked at the spreadsheet, you should have also seen row 152 for Ore Mix 87, that has Plutonium generating on Tier 3 and higher planets.

Plutonium generation used to be on the pack before I opened the issue, but it was accidentally removed when migrating some files over from bloodasp's version of GT5U at some point in time. Which is why it was readded in version 1.4.0.0.

**Comment by Dreminon** [comment]
first off I was asking a simple question since I had missed it on the spreadsheet you you guys had added it to the bottom after the deep dark stuff and i am sorry, but you did not have to be rude about it simply stating please refer to row 152 on the spreadsheet  would have sufficed. I have been nothing but thrilled with what you guys have created. and this right here is why i always cringe when i try to ask dreammaster a question and he tells me to post to the github.

**Comment by bigbass1997** [comment]
Well I am sorry if I seemed rude, however your initial post sounded accusatory to me, instead of a simple question. But I don't know why Dream would tell you to post this, since he is the person who made the change. In the future, maybe best to ask on our Discord, instead of Dream directly, he is often very busy to handle all the small questions.

Many people who use Discord for issue tracking, ask people to please search for their issue before making a new one. There are many duplicate issues for different things on this repo alone.

**Comment by Dream-Master** [comment]
@Dreminon yes we changed the Oremix some time before because Blood Asp removed it from his fork and the mix was no longer active in the game only in cfg file. I can add a ore mix PU244 to T3/t4 Planets sure.

**Comment by bigbass1997** [comment]
@Dream-Master Read my posts here... You already added a mix like that to Tier 3 and 4 planets #1144. I'm closing this issue before anyone else gets confused.

**Comment by Dream-Master** [comment]
@bigbass1997 Yes i seen this allready. Totaly forgot it.
