### ISSUE TITLE
Void dimension got overlapped with space station.

### ISSUE THREAD

**Issue by noobyaran9** [GTNewHorizons/NewHorizons#1314]
![2017-04-20_23 24 03](https://cloud.githubusercontent.com/assets/13598309/25276074/fd36554c-26ca-11e7-9a30-99116f59d229.png)
![2017-04-20_23 24 05](https://cloud.githubusercontent.com/assets/13598309/25276075/fd36c4c8-26ca-11e7-8667-d4b6c01f34b1.png)
![2017-04-20_23 24 27](https://cloud.githubusercontent.com/assets/13598309/25276073/fd3406b6-26ca-11e7-8a68-f988cb59900a.png)

My team void dimension got overlapped with the space station dimension.

**Comment by Namikon** [comment]
In order to fix this, a fork of UtilityWorlds or a "re-invention" of void dimensions by us is required.
Until that has happened, the usage of new void-portals is to be considered banned on both EU Servers. Will update the banned block list and Enjin page later

**Comment by Ghengis88** [comment]
Will this affect already existing void dimensions?

**Comment by Methes** [comment]
Since it has been 4 months and I'm still waiting for a fix in order to start building my proper base, has any progress been made with this?
Unless you want each player to have his own dimension, there are other ways around this (share one void dimension).

**Comment by Dream-Master** [comment]
@Bullwulf any news here?

**Comment by Methes** [comment]
If it's not possible for everyone to have their own dimension but you still want easier management in case something goes wrong, you could make it so that people share the same dimension but everyone is in his own region file.

**Comment by SirAzazel** [comment]
@Methes i have suggested that some time ago, but ill repeat (roughly) response i got:

Point is that if everyone share same dim it will give constant high load on server because someone is there

If everyone has separate dims - if needed they can be purged completely and they can be unloaded automatically when noone is on.

**Comment by Methes** [comment]
Fair point.

It's possible to use other mods such as RFTools or Mystcraft to give everyone their own void dimension, although it's more work than place and click.
If a fix for Utility Worlds is not available, resorting to upper mods would be alternative.
There's no words about how far GTNH 2.0 is from being released so I'd of course like to see a fix for 1.4.1.2 so that I can start playing properly, but that's just my wish.

**Comment by SirAzazel** [comment]
Technically i believe changing id of space station would work too (since space stations are unusable anyway.

**Comment by Methes** [comment]
Galacticraft has available github repository and can be forked.
What way of fixing are you trying to go?

**Comment by Dream-Master** [comment]
Seems to be fixed need to be tested.

**Comment by Dream-Master** [comment]
Thanks to @LOKKO12
