### ISSUE TITLE
Forestry core Block Quest

### ISSUE THREAD

**Issue by Jayjayx5x1** [GTNewHorizons/NewHorizons#1383]
requires steel screws when it has an assembling machine recipe and the quest is only unlocked after the assembling machine quest is completed. also change the crafting requirement to retrieval as the machine doesn't count as crafting (made that mistake myself)

**Comment by bigbass1997** [comment]
Okay so I had to have Bryfer explain this to mean, since just going by this post, I am extremely confused what all you are asking for.

Correct me if this is wrong:

This Forestry Quest (questID 577) you are talking about, is unlocked after the player completes the Assembling Machine Quest (questID 97). The Forestry quest's tasks currently require the player to manually craft everything for the quest, even though there is an assembling machine recipe for the same item that is required for the Forestry quest.

Because the Forestry quest is unlocked after the player has crafted the Assembling Machine, you want the Forestry quest tasks to be changed to retrieval instead of crafting? And so this would also mean that the quest would no longer require the player to make the steel screws, as those are not required in the assembling machine recipe?

If this is what you mean, then I see no issue with changing the tasks to retrieval instead of crafting. The other alternative is making the Forestry quest available before making the assembling machine; but then players still might make the mistake of using machines.

**Comment by Dream-Master** [comment]
I will see if i enable Forestry a bit before LV so people can decide when they make the first Tree farm or/and change it to retreival task.

**Comment by Jayjayx5x1** [comment]
I am fine with that. and yeah you got the idea of what i was saying. although with enabling it earlier, a player can't make the machine required as it needs a bookshelf which can only be gotten through making in an assembly machine or silk touch on an axe.
