### ISSUE TITLE
Chunkloader coins

### ISSUE THREAD

**Issue by Fozar** [GTNewHorizons/NewHorizons#1391]
I have a question. How to get points at the late game? Really need to spend huge amount of time in order to earn chunkloader coins? Because by that time I'll have the miners and the farm. And dig the ore will be very tedious. Absolutely not would be little time for other things. I think you need to improve the system. PS. I play on Epsilon.

**Comment by bigbass1997** [comment]
I too have encountered this. I never understood how some people were able to stock up literally hundreds of thousands of job points through their time playing. I personally setup a system that allowed me to exchange time in order to grind out points, but even then, that still took quite a while.

The points are important, as they function to prevent players from keeping too many world anchors running for too long without actually playing the game. However, as you mention, there are very limited ways to acquire these points, especially in mid-late game when many of the ways are now automated for the players.

So there needs to be a balance. So that the original function of these coins can still be effective, but also not overbearing for players.

Also note, @Namikon is the person who makes these modifications, as he is the main person who runs/manages the Delta and Epsilon servers.
