### ISSUE TITLE
Fluid extracting annealed copper ingot gives molten copper

### ISSUE THREAD

**Issue by Fapiko** [GTNewHorizons/NewHorizons#1425]
Seems like it should give molten annealed copper rather than molten copper, as there are fluid solidifier recipes for annealed copper.

**Comment by bigbass1997** [comment]
By definition, an annealed metal is a metal that has been heated to a certain point (usually glowing hot) and then cooled in a specific way (usually allowing it to cool slowly), in order to make the metal more malleable.

So it makes sense to me that if that metal is turned back into a liquid and then solidified, that it would have to be annealed again in order to make it an annealed metal.

Unless you can find some documentation that explains that once a metal is annealed, it will always be that way, even if remelted and solidified again.

**Comment by Technus** [comment]
Code wise - Recipes are autogenerated. Even if the the material is unobtainable.

**Comment by Fapiko** [comment]
@bigbass1997 Fair enough, I just found it odd that there were fluid solidifer recipes using molten annealed copper but I couldn't find a way to create it. Figured this might be a bug but feel free to close it out if it's intended.
