### ISSUE TITLE
Heavy Oil out of Wood log

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#1427]
Heavy Oil out of Wood log disable
Pyroluse Oven

**Comment by bigbass1997** [comment]
Is this being replaced by something else?

**Comment by Dream-Master** [comment]
I never heard you can get heavy oil out of Wood logs. In the feature you can get Wood Gas, Wood Vinegear and Wood Tar.

**Comment by bigbass1997** [comment]
The recipe has been in the modpack for many versions of the modpack. What is Wood Gas/Vinegear/Tar and what can they be used for?

**Comment by Dream-Master** [comment]
I let you know when i can look into it. Working with the Petro chemy update dev now on a working version for GTNH.

**Comment by Jayjayx5x1** [comment]
well oil does come from carbon based life (plants living things etc) when buried and pressurised for ages. although you can get oil from wood irl, it is called pyrolysis oil (probably where the name of the oven came from) also known as biocrude oil, it is a synthetic oil (cause it didn't occur naturally). here is the wiki page for it https://en.wikipedia.org/wiki/Pyrolysis_oil . imo since wood can be made into oil over time or be made into pyrolysis oil, stands to reason that in the modpack heavy oil is the best choice. but that is just my opinion and i thought you might like this bit of info about wood -> oil without waiting for thousands of years :)

**Comment by Dream-Master** [comment]
I can let it ingame. Looks for me do wrong in the first place.

**Comment by Jayjayx5x1** [comment]
I think heavy oil might just be a place holder tbh but i don't really know.

**Comment by Technus** [comment]
Most likely placeholder.

**Comment by Dream-Master** [comment]
So remove it or put another fluid in?

**Comment by Dream-Master** [comment]
i let it in so far no one complaint
