### ISSUE TITLE
Superconductor Wires have to be lossless

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#1437]
Better 1 eu loss per 10 Blocks the per 1.

**Comment by Bryfer** [comment]
Personally I have never really had any issues with the current EU loss in GT Cables.
Its alot euloss in LV tier, but you will not have alot of machines that are outspread in this tier anyway, and if you do you should consider changing your power distribution tactics.
in MV tier you can use longer MV cables, which will make the loss 4x less.
HV tier allows you to do this even better. which will make the loss 16x less.

I personally dont see the loss issue with 1 euVolt/block, since when has this became an problem in an "Gregified modpack" ?

an 16x Red Alloy cable is not too expensive. but it can transfer MV power lossless. *
an 4x Red Alloy cable can transfer LV power lossless. *
*You will need to transform the power to ULV and back to your power tier, this will cause some loss.

More information about GT Energy; Cables and euLoss here
http://ftb.gamepedia.com/GregTech_5/Electricity#Cables_and_Loss

**Comment by bigbass1997** [comment]
I am not really sure how this would actually balance cables more?? @Dream-Master What made you come up with this idea?

As Bryfer said above, the EU loss is not bad at all. I see no reason to change it.

**Comment by Dream-Master** [comment]
@bigbass1997 The first change i will make is make the Super Conductor Wire Lossless. I like the idea to add a Glasfiber cable in the EV/IV Tier and add a 3 lossless wire.
Redalloy wire is lossless at 8 EU/t

**Comment by bigbass1997** [comment]
I know you use Github for reminders to do things, however, changing the EU loss of all cables is not needed at all. Unless you experienced some difficulty while playing the game where the loss was the cause, I see no reason to lower the loss of all cables.

Superconductor Wires are so high tier that the loss is practically nothing already, however, because of that, I see no problem with making that lossless, and that very few people ever get to high enough tier to use it anyways.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/26320868/d2bf4360-3f24-11e7-93d6-8fc22cc2b304.png)

**Comment by Dream-Master** [comment]
Changing Superconductor Wires to Loss 0. Thas it for now.
