### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#1457]
I had a thought that i would be fun to have sort of a leaderboard for progress where you could see what on what quest everyone else is, is this something anyone else would want? Maby not so relevant on Delta but for epsilon i think it would be fun.

**Comment by Dream-Master** [comment]
Any suggestions how to display such thing @Ghengis88

**Comment by Ghengis88** [comment]
like a tab in the questbook on just a menue you could accsess anywhere, i know there is some form of leaderboard in atlantis but if memory servs that only dislplays like top 10 or somesutch and those 10 are not likely to change anytime soon and for new players they are quite irellevant. so something showing all players or players online the last month or so.

**Comment by Dream-Master** [comment]
@Ghengis88 i am not a programmer so suggest it directly to Better Questing Mod Author.
https://github.com/Funwayguy/BetterQuesting/issues
Thanks

**Comment by bigbass1997** [comment]
I can see one way this could be done, by making a mod that reads from the quest progress JSON file, but it would likely have to be both client and server sided in order to actually render the stats.

However, the main issue I see in this suggestion, is how to show progress. Like how would you define who is higher on that leaderboard compared to other people? The quest book has many branches that can be completed at any time, and many quests that never have to be completed.

> on what quest everyone else is

People could be "on" many quests at once, and there is no way to see what people are working on at any specific time. If the quest book was perfectly linear, with just a single quest line that everyone had to follow in the same order, this suggestion would be a lot easier to do, however, we don't have such a quest book, for good reason, so I don't see any way to "rank" people in the way you are suggesting.

**Comment by Methes** [comment]
Random thought:
How about giving the Coins another purpose then? Track how many coins the player recieved and calculate his progress that way. Just add all the coin values together.

**Comment by Dream-Master** [comment]
Doing a list and rebalancing coins right now. This need much longer then i thaought so the Coins wont be done in 1.5.0.0 fully.

**Comment by richardhendricks** [comment]
Just track the last Xxx completed quests, and display that information on the board (a special sign crafted using a sign and the questbook).  It wouldn't be a leaderboard in the sense of progression, but would tell you who has been active lately. It would be nice to have a crafting option that just tracks your personal quests too.
