### ISSUE TITLE
[SUGGESTION]Ore Deposites

### ISSUE THREAD

**Issue by Raccoon2709** [GTNewHorizons/NewHorizons#1459]
Ore Deposites

You dont like to quarry worlds of minecraft, just for some ore? 
Reducing laggs + bring minecarts back!

New Ore's like Iron Deposite with a pseudo random amount of ore (2-8 Stacks or w/e) which can only mined with a specialised miner. Every Minute you get 5 (Or w/e) Ore out of the Deposite and can use it for you stuff.

Because this stuff is realy rare, you have to build big minecart roads to get the stuff to your base. 
No time wasting quarry's which destory the whole world.

Woud be awesome if you can do something like that.

**Comment by bigbass1997** [comment]
What in the current ore generation system do you think causes lag? How do you figure minecarts running around everywhere, loading chunks, as less lag than what we have now??

Beyond the lag issue, this just will not work with this modpack. I feel like you don't understand how GregTech ore generation actually works. In some cases, you already can build a minecart rail through your mine just because it extends so far. If you want to learn about the GT ore generation system, go read this wiki http://ftb.gamepedia.com/GregTech_5/Mining_and_Processing#Ores (ignore the "Default Ore Mixes" chart, this is heavy changed in our modpack).

Also, this modpack requires a lot more than just 2-8 stacks of iron.. lol. There are currently around 20 different vein types in the overworld alone, not to mention the some 50+ others spread across other dimensions. Your idea would cause worlds to have to be absolutely massive just to support a few players. Not to mention most people would probably quit the modpack entirely because mining would take entirely too long.

I would just like to note, actual Quarry blocks, aka the Ender Quarry, are not available to player until mid-high tier, and seldom are ever placed in the Overworld, mainly because by the point you get a quarry, there is very little need to be mining in the Overworld. So your opening, rhetorical question, about "...quarry worlds...just for some ore", is invalid.

**Comment by Raccoon2709** [comment]
The Lag Issue was for the Quarry's and so one. But it was mainly a joke. I know the amount of Veins Types no worries. What do you mean by "have to be absolutely massiv"? When you add this 1 block/multiblock to hold more Iron in 1 Block. Which can simply be mined with a miner. This was more a example with the 8 stacks of iron. Stop the hate wtf. Im also at HV and im already about 2 chests of iron. This Suggestion is based on the Ore System from Fortresscraft Evolved(SteamGame). 

Back to Topic, i think you didnt understood what i meant.

Example

Iron Deposite
1 Single Block
Holds up to 20 - 100 Stacks of Iron (IF YOU WANT TO)
Can be mined with a electric miner, which mines 2 - 10 ores per second (IF YOU WANT TO)

I woud suggest you watch 1 episode of FortresscraftEvo when you realy want to understand what i mean.

**Comment by bigbass1997** [comment]
Okay, I understand more of what you mean, however I am not sure how that relates to minecarts..

Whatever the case, programming something like this still seems a waste of time. And you have yet to supply any valid reason for this sort of addition/replacement of the current ore system.

Also please note, saying this in your post,

> Stop the hate wtf.

is not a good way to get your suggestion added.

**Comment by noobyaran9** [comment]
> Because this stuff is realy rare, you have to build big minecart roads to get the stuff to your base.

So you're willing to spend time looking for these rare 'ore deposites' and building big minecart roads to transport the ores to your base and not go out and look for actual ore veins?

> No time wasting quarry's which destory the whole world.

I don't see how quarry is time wasting and how building big minecart roads will not destroy the looks of the world. And if you're not using the world hole upgrade, it won't leave huge holes behind.

**Comment by Raccoon2709** [comment]
Okay, we had a bad start. Once Again.

Its more an addition for our actually ore system. I just want to get rid of our actually "go 24/7 farm" get 2 chests full of ores and processes it to plates and stuff. I'm missing the Factory feeling, i woud like to have a "limited" source of ores which comes every 10 minutes with a cart and sort them into your factory. While not using Quarry's which drag 20 kinds of ores into your base. I'm missing the realism here.

When programming those deposits be a thing. We can build other factories with other aspects. A new look, a new "mining" in Minecraft. Maybe even a new way for the progression. 

> So you're willing to spend time looking for these rare 'ore deposites' and building big minecart roads to transport the ores to your base and not go out and look for actual ore veins?

The ore deposits shoud work as a goodie which you find and build a "mining facility" on this place. 

> I don't see how quarry is time wasting and how building big minecart roads will not destroy the looks of the world. And if you're not using the world hole upgrade, it won't leave huge holes behind.

I know the feature with the upgrade and by "time wasting" i mean the digging trough stone and dirt. I think the look of big train stations is better than 3 quarries next to each other. 

Sadly, i cant program java but in c# this "block" is simple. The only problem woud be the miner, which you have to place next to the deposit and have to count the "random" number down till zero(thats when the ore depletes) and "spawn" ore with the data's from the deposit block.

**Comment by bigbass1997** [comment]
Programming this is not "simple". You would need to program in a new miner (compatible with the GT energy system), the ore block itself, and a world generator (this includes how the ores are spread out and what type of ore is chosen). As well as you would need to integrate the possible ores with the ores in GT.

> I think the look of big train stations is better than 3 quarries next to each other.

I already tried to explain, but I guess I'll try to again. You are trying to compare your idea with something that is not related. Quarries in this modpack are seldom used in the overworld. By the time a player makes a Quarry, most often than not the player will setup some sort of teleportation of the items which relays the mined ores back to their base for processing, while also filtering out unwanted blocks. Since quarries are so often used in other dimensions, including planets, a rail system or anything "realistic" is not going to work.

> I just want to get rid of our actually "go 24/7 farm" get 2 chests full of ores and processes it to plates and stuff. I'm missing the Factory feeling, i woud like to have a "limited" source of ores which comes every 10 minutes with a cart and sort them into your factory.

I'm not sure what the difference is. Either way you would have the same setup for sorting and processing the ores. Just that one way comes in from a chest cart, and the other way comes in from say an EnderChest or equivalent.

**Comment by Raccoon2709** [comment]
Okay. Solved
