### ISSUE TITLE
Loss in % of the single block steam turbines

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#146]

**Comment by Dream-Master** [comment]
Make LV120% (from 66)  MV 115 % (from 50%) and HV 110 % (from 40%) 
(Blood Asps suggestion)

**Comment by Namikon** [comment]
Just to let you know what i've been testing and to provide a bit of background information on what you all should test yourself in a singleplayer world:

- Full sized RailCraft HP boiler, with a fully charged "FireStone" (5000 Buckets of lava)
- The heatup-phase takes about 1300 buckets of lava to reach 1000 °C
- The steam produced by this monster is enough to supply 5 _32 EU_ SteamTurbines

I think I don't have to explain why this is ridiculous. Of couse you can spam the world with 40 coke ovens and 2 large sized tree-farms to get enough charcoal, but
- It makes the world around f-ugly
- Large Railcraft boilers are meant to be used with CoalCoke (Coal found in vanilla worlds is about 50x the amount that GT spawns, so coke is not an option for us. You can't even get enough to heat one boiler to max)
- If you use charcoal, it is meant that you can smelt wood to charcoal in a furnace, or even with max-upgrade smeltery one wood per tick to charcoal, and not use CokeOvens to take 90 seconds for one single charcoal

So small sized RC boilers are fine, but the way this pack is meant to work, the only way to power them is a FireStone, which will, depending on the number of players, will dry out the nether very fast (As one stone sucks up 5000 blocks of lava). This might sound OP, but the stone is doing nothing more than holding that amount. It does speed up the boiler heatup time by 5x, but it doesn't save you lava. It is just used up a lot quicker (About 4-6 buckets *per second* on a full size HP boiler)

Increasing the amount of steam the turbines do convert, this might be a useable solution for 128, and maybe 512 eu/t. 32 eu/t works fine for small setups at the moment


Regarding the GT boilers: They all 4 eat the same amount of coal/charcoal per second (about 1-2), but produce different amounts of steam. On my own server, have the following setup to power my EBF (It's just an EBF with the first heating coils, i'll explain why later)

- GregTech Steel-boiler
- 8x 32EU steam turbines, which yield about 200 eu/t (after all conversion/cable loss/etc)

This works 24/7, but it requires a decent tree-farm and, on our server, a huge coke-oven farm.
My steve's carts "infinite woodcutter" is *not* fast enough to provide enough charcoal, so i have to let it run chunkloaded in order to stock up on charcoal. Other ways to get wood may be better.

About the reason why a higher-tier EBF is not working:
As soon as you plug in a higher-tier input hatch for energy, the EBF begins to draw more EU / t, which means if you plug in a 512EU hatch, it will draw 512 eu/t. If you can't provide it, it stops.
And that's the reason why I had a 8-slot HV battery box on my top-tier EBF, as the setup downstairs does only ~200 eu/t.

**Comment by Dream-Master** [comment]
Next update have the new Boiler from Blood asp and the new single block configs. I think if we use the rail craft boiler we have to use the single tank 1*2 and max 2*2. The others are useless charcoal dumpers.

**Comment by Dream-Master** [comment]
@Namikon We have to let this issue open or not.

**Comment by Namikon** [comment]
Will build my testsetup this weekend

**Comment by Dream-Master** [comment]
ok

**Comment by PaladinOne** [comment]
Railcraft boilers fuel efficiency increases substantially as their size increases. I've never liked the 36HP because of its massive inefficiency during heating, but I'm fine with a 36LP (360 Steam/tick output). Granted, by GregTech standards this is a little low, but it's workable.

As for GregTech Large Boilers, all of them consume fuel at the same rate, but have different output rates. 800, 1200, 1600, 2000 Steam/tick, Bronze, Steel, Titanium, Tungstensteel. However, even the Large Tungstensteel Boiler is less fuel-efficient than the GregTech (single-block) High Pressure Coal Boiler. (I did the math on this several months ago. http://ftb.gamepedia.com/Large_Boiler#Fuel_Efficiency )

**Comment by Namikon** [comment]
Ok, so this is the deal:
- Railcraft boilers are useable to a single 32 eu turbine, a 2x2x3 HP boiler is still not enough to power 2 32eu turbines
- A large bronze boiler is enough to power 5 32eu turbines, but only one 128eu
- The first tier of the large steam turbine from gregtech (small turbine) with an 128 eu dynamo hatch works fine with the large bronze boiler. However: The turbine and the boiler are rather expensive, and you need 128 eu machines to craft the turbine.

It's much better now, but power production is still a pain compared to the naquadah generators.

**Comment by Namikon** [comment]
Update: I've build a new setup which seems pretty functional to me. It seems that the new values are enough for one particular (and tbh the most important) case; Powering the EBF. I'll post the results later, as I want it to run at least one hour to see how the steam/water values are changing, or if it explodes / stops after looking away

**Comment by Namikon** [comment]
Result: Explosion of the bronze boiler due water shortage after 104 Aluminium Ingots.
Setup:
- 3 Railcraft Watertanks, filled up to 400 buckets each in creative, Large wood pipe is fast enough, attached MV pump to each tank. Probably not required (Lv should do the trick, or even without pump)
- Infinite Charcoal Barrel (Used up ~9000 Charcoal for all ingots; 104*85+HeatUp phase)
- Large Bronze boiler with 4 fireboxes, duct-taped for 100% efficiency
- Tier 1 EBF, duct-taped for 100% efficiency
- 3x LV Energy hatch
- 5x 32 EU Steam Turbine
- One 9x LV Battery Buffer as.. Buffer
- Connection between Boiler and turbines: Large Steel pipes with shutters

So at least for the LV tier I can say: The new values are good. They provide a stable power supply. The Charcoal is the only problem here, as it used up about 140 Stacks of 64 Charcoal each, for 104 Aluminium Ingots, which is enough for .. 5 maybe 6 MV machines. So you need a tree farm, and at least 15 maybe 20 coke oven to produce enough charcoal while you are in your base in order to not have another big waiting game. Positive thing is, you get a ton of creosote, which you can use in diesel generators to power your machines. It's not *the best* solution, but it works, and is worth the time and effort to build.

I guess the higher tiers with Boilers and steam turbines are comparable, but I will test them aswell, the same way I tested the LV tier

**Comment by Drobac** [comment]
Implemented with the new GT
