### ISSUE TITLE
Insufficient coins to complete quest

### ISSUE THREAD

**Issue by finkledoodle** [GTNewHorizons/NewHorizons#1469]
In order to complete the Technology: Evolved quest at the end of the "Kill all the Things" quest tab, you are required to have 1000 technician, dark wizard, explorer, and survivor coins. Not only can a player get plenty of dark wizard and technician coins from completing other quests, but you can also obtain them by repeatedly completing the other mob-grinding quests.

However, I don't see how it is possible for a player on his own to obtain the necessary explorer and survivor coins, as there is no way to get to 1000, even by completing all quests that provide them. This has forced me to trade with other players for the coins, and they are reluctant to give up their coins as that would just make their own job of completing this quest harder.

I would suggest either:
1) Adding as more common quest rewards throughout the quest book
2) Making it possible to repeatedly complete grinding quests to unlock them repeatedly, as it is with the technician and dark  wizard coins.
3) Alternatively, this could be solved simply by removing the requirement of the explorer/survivor coins for completing the Technology: Evolved quest.

**Comment by MineAnPlay** [comment]
Just remove the coins please, it just adds unnecessary grind. If you do really want the coins atleast make it so that if you complete all optional quests you will have enough coins for the coin requirements.

**Comment by bigbass1997** [comment]
I already discussed this in a similar way back in issue #1202 

Yet again, I don't understand why coins are still being used to restrict progression. Check my comment in the linked issue.

**Comment by Dream-Master** [comment]
In the new version coins are only used for the legendary quest line so two chapters are locked. Ok you can buy seeds with some coins or go find some pams seeds.

**Comment by Dream-Master** [comment]
Explorer and survivor coins amount i will look into it but with the new space quests you got a lot more of them (upcoming version 1.5.0.0)

**Comment by Dream-Master** [comment]
In the technology evolved quest I will look into it too.

**Comment by Dream-Master** [comment]
@MineAnPlay @finkledoodle @bigbass1997 
To complain about some stuff (Coins/Coin system) is very easy and remove it too, but developping on some future planmake the coins sytem better and user friendly is difficult. Maybe some helpfull suggestions or/and help/work on it are welcome.

**Comment by finkledoodle** [comment]
I tried to offer a few solutions in my first message. Fixing the entire coin system will be very difficult, but perhaps as a short-term solution you could:

1) Add additional quests that can be repeated for the explorer and survivor coins like there are for the technician and dark wizard coins that you get from killing 10 of each mob
2) Replace the coin reward for some of the existing repeat mob killing quests, such as for killing endermen and pigman quests with explorer/survivor coins instead.

In addition to being used to unlock legendary quests, coins could be made more useful by adding repeatable quests that allow them to be exchanged for loot bags of various types.

**Comment by bigbass1997** [comment]
@Dream-Master If you want to blame us for "complaining" then I guess I should explain why we are telling you about this problem.

If you want this coin system so badly, then you should actually pay attention to how you implement it. We are still reporting issues with the coin system because they don't work, and even with the suggestions that have been made, nothing has been done to remedy the issues (besides removing the coin requirements from each tier in 73e0cb6a85c6849b4123710297a11187a03e8e8e).

When I say "they don't work", I mean that you add these various coin requirements without putting seemingly any effort into whether or not those requirements can even be fulfilled given the number of coins generated by quests up to that point.

Also if repeatable quests are to be added in order to generate coins for these requirements, you have to make them repeatable over shorter periods of time. While this has since been removed, back in #1202 Bryfer figured that even if he finished all the repeatable quests every day, it would take around 200 real life days to generate enough coins.. This is what I am talking about, obviously there was some sort of mistake or not even care given to verify that enough coins existed in order to fulfill requirements.

> but developping on some future planmake the coins sytem better and user friendly is difficult. Maybe some helpfull suggestions or/and help/work on it are welcome.

Yeah it certainly is difficult, especially when no one knows what the goal of the coin system even is. And even then, plenty of people have given you suggestions already.

**Comment by Dream-Master** [comment]
Fixed for now. In 1.6.0.0 i will add Quests for using Coins better.
