### ISSUE TITLE
remove ingots from the furnace

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#1492]
remove ingots from the vanilla furnace.

**Comment by WarlordWossman** [comment]
Sounds like a bad idea to me. Would you have to use the smeltery for all the ingots? That would be a pain if you have no good lava spot nearby.

**Comment by Drobac** [comment]
A very bad idea

**Comment by Dream-Master** [comment]
sure if you see only this sentences yes. I need to work on a concept this was just notes to remind my self thing about a better solution @WarlordWossman @Drobac

**Comment by WarlordWossman** [comment]
Alright. Kinda hard to get with that one line you wrote and a "suggestion" tag rather than a "reminder".

**Comment by R60D** [comment]
I like this idea. Plus you're going to need a smeltery regardless so i don't see the problem.

**Comment by Dream-Master** [comment]
This issue was original only a note for me think about some solution. So Ideas under this post please.

**Comment by Bryfer** [comment]
If the idea is to use vanilla furnace to make tico smeltery to make GT multi smelter then I think this is an bad idea.
It will lead to even more confusion about alumin(I)um for example. It's also really annoying to use the smeltery when making ingots since it will create alot of alloys you didn't mean to make.

As I understand the current smeltery it's not meant to be used to make metal ingots/blocks. Its only meant for tico tools, molds and glass? (1.4.1.1)

But yes making ingots inside an oven(furnace) is not realistic. But I don't think the tico smeltery is better since it will make ingots almost impossible to get pre tico smeltery.

To make this idea possible an new machine would need to be created which will be really similar to an furnace. And it must be craftable pre-steam tier.

I don't think this change is nessessry unless someone has an good idea to solve this without making it too confusing.

**Comment by R60D** [comment]
he said "remove ingots from the vanilla furnace."

**Comment by R60D** [comment]
I think all coal powered furnaces shouldn't be able to smelt metals into ingots. The higher tier steam and electric furnaces for metal bar smelting would be much better, considering how the iron furnace and nether furnace are much better at this job even though they  are very cheap to make. This would nerf those furnaces and lead the player towards the tier path.

**Comment by Bryfer** [comment]
@R60D
How would you make the steam furnace (bronze) without furnace?

The best-bad solution I can think of is allowing the furnace to make nuggets only. These nuggets then needs to go into the alloy smelter with an ingot mold? 

Or does 1.5 come with an furnace with ingot mold? 
However. I still think it's an bad idea to change this.
