### ISSUE TITLE
King Slime loottable

### ISSUE THREAD

**Issue by leglerm** [GTNewHorizons/NewHorizons#1519]
Just posted on discord from a new player who made a easy slime farm with just a few buckets that is able to spawn the king slime which himself is able to drop excavators/hammers/lumber axes all possible at steam age. 

![](https://cdn.discordapp.com/attachments/181078474394566657/325763174353731585/2017-06-17_16.54.42.png)

**Comment by Bryfer** [comment]
If you are intressted in finding this conversation, search for **from: Crusher_X83#4318 in: #lobby has: image My drops** in discord
more pics available there.

I agree that an easy setup like this really breaks the difficulty of the game

**Comment by Dream-Master** [comment]
@Bryfer ok but any idea how to fix? Forbid to place slime buckets in the overworld?

**Comment by Dream-Master** [comment]
Yes slimebuckets needs to forbid in placing in the overworld and Nether.

**Comment by CrusherX83** [comment]
I'm not sure if you all want me posting a detailed workaround on here so I'll keep it vague unless asked but this doesn't solve the issue. Bringing the slime to my base and placing via bucket certainly, makes it convenient but I could simply move my setup to a slime islands and get the same result.

**Comment by Dream-Master** [comment]
@CrusherX83 thats true so if somone one to use it they can but i make it a bit harder to cheat. Or did you have an idea how to fix that better?

**Comment by EvgenijM86** [comment]
This is not much a cheat, because you can already find 2 aluminium ingots in chests and craft Tool Forge in Steam Age. IMO - if someone bothered to make an automatic farm at this point he might as well get the extra reward.

**Comment by Dream-Master** [comment]
So maybe i need to change Aluminium to another metal for the crafting table

**Comment by CrusherX83** [comment]
I don't see this as a cheat but I understand why it needs to be changed. I set up farms for everything that can be farmed whether it be cactus, crops, mob tower spawners, or slime.  Evgenij86 is correct on the aluminum though. Between village blacksmith chest, dungeon loot, the chest inside those witchery stone circles, and especially the chest in the center of Thaumcraft totem circles you are going to get all types of ingots and even tech you would not have otherwise had access too.  I'm not sure what is possible as I am not a dev but my recommendation would be to disable pink slime tools to solve the problem with king slime dropping them as you don't even need a farm to get him regularly...just build near an island and you will see him a few times a day. As for the tool forge could you change it so that it requires the use of a machine or some other tech from the appropriate teir?

**Comment by CrusherX83** [comment]
Thaumcraft

**Comment by CrusherX83** [comment]
http://thaumcraft-3.wikia.com/wiki/Structures

**Comment by Dream-Master** [comment]
Maybe i need to add Blacksteel or Stainless steel to the Forge from Tinkers to gate it behind.

**Comment by CrusherX83** [comment]
Not sure about Blacksteel but I have also found stainless steel in those chest

**Comment by Dream-Master** [comment]
so i need to add an material not spawn in this chests and gated at MV

**Comment by CrusherX83** [comment]
unless you could look at the loot table for various dungeon chest to see what is not allowed to spawn in them. A custom material would be a good choice.

**Comment by CrusherX83** [comment]
what about the folder config/TooMuchLoot 
I just looked at those XML files and can see aluminum in the loot table of the different chest

**Comment by CrusherX83** [comment]
![loot](https://user-images.githubusercontent.com/29513029/27487022-1b432048-57f8-11e7-910c-9a5084c86b47.PNG)

**Comment by Dream-Master** [comment]
Yes I add it very rare.

**Comment by CrusherX83** [comment]
as far as the king slime goes...why not just disable him from spawning. he serves no real purpose except to drop some hearts and those tools. Would disabling him in the openblocks.cfg work?

**Comment by CrusherX83** [comment]
https://forum.feed-the-beast.com/threads/dw20-disabling-certain-mobs.54749/

**Comment by Dream-Master** [comment]
I dont like to disable mobs from spawning. I dont like people go farming this Boss with Slime Pools. Maybe someone need to change Tinkers Sourcecode.

**Comment by EvgenijM86** [comment]
Steel ingots in chests are ok IMO, because it allows you to craft bags early in the game and bags allow you to explore for longer periods of time. If you disable steel ingots in chest then exploration will become a lot less useful.

As for aluminum ingots - it usually requires 4+ hours on a horse to find 1 aluminum ingot. You need 2 of them for Tool Forge, so expect to waste a day for exploration (unless you get very lucky). The question is - should players find something very useful for doing a lot exploration? Tool Forge is very useful.

I think stainless steel is even rarer than aluminum. Stainless steel allows you to craft 50 vis wand before building EBF (assuming that you can kill Lich boss). Not sure what kind of advantage you can get from 50 Vis wand in LV tier.

**Comment by CrusherX83** [comment]
I agree. Those treasures make exploring fun. Same with Loot Games. Both give access to things you might not otherwise have access to at that point in progression,  but that is their allure.

**Comment by CrusherX83** [comment]
The biggest issue was not the aluminum I don't think. It was the fact the King Slimes nearly make the tool forge obsolete as he drops every single big tool/weapon. The only way to fix that is to disable him from spawning or change the source code to remove pink slime tools from his loot table.  Either way I want to thank you @Dream-Master and in fact the entire team for this amazing pack. It has brought me back to playing after a long break.

**Comment by Dream-Master** [comment]
@CrusherX83 :)
