### ISSUE TITLE
Mod Suggestion: Better Achievents (Client only mod)

### ISSUE THREAD

**Issue by Ethryan** [GTNewHorizons/NewHorizons#1528]
A great little mod that gives the achievent system tabs instead of a single button.

(The vanilla achievment system drives me nuts.)

mod [Licence](https://github.com/way2muchnoise/BetterAchievements/blob/master/LICENSE.md)

Link to mod [Homepage](https://minecraft.curseforge.com/projects/betterachievements)

**Comment by Bryfer** [comment]
This mod only requires to be installed on the client, no serverside needed for it to work.

I've been using it for a good while aswell and its really something you need to have if you are intressted in unlocking achievements.
Since its an clientside mod I added it to the forums
http://www.gtnewhorizons.com/forum/m/36844562/viewthread/30450270-better-achievements-mod

![image](https://user-images.githubusercontent.com/22825059/27267779-302c353a-54ab-11e7-90df-e597f7ed637f.png)

**Comment by Dream-Master** [comment]
Ok added
