### ISSUE TITLE
Open Computers Robot does not Yield Wither skulls when equipped with a cleaver

### ISSUE THREAD

**Issue by flashsugar** [GTNewHorizons/NewHorizons#1537]
The Opencomputers robot doesn't yield wither skeleton skulls when wither skeletons are killed.

**Comment by Dream-Master** [comment]
@bigbass1997 any idea about that ? I never use much Open Computers.

**Comment by flashsugar** [comment]
@Dream-Master 

this is the only option apparently, supposedly dynamism tablets were fixed but they still crash our server

**Comment by Saereth** [comment]
just to past reference the current issue with the dynamism tablet; https://github.com/GTNewHorizons/NewHorizons/issues/941#issuecomment-309494378

**Comment by Diresheep** [comment]
Saw this in another pack.
/config/IguanaTinkerTweaks/Modules.cfg line 13 and 14

`    # Adds additional MobHeads and control over MobHead drops.
    B:MobHeads=true
`

**Comment by Dream-Master** [comment]
@Diresheep not sure if this brak anything?

**Comment by Diresheep** [comment]
shouldnt break anything, just gets rid of things like the TiCon Enderman head. blaze head, and pigman head, and allows fake players to harvest heads as usual

**Comment by Methes** [comment]
Turning it off will also fix that Thaumcraft Addon War-Axe which is supposed to drop heads when mobs are killed but doesn't work because of Iguana.

**Comment by Dream-Master** [comment]
I want to know when if i change this now the good and the bad things are in the majority?

**Comment by Methes** [comment]
Won't be at PC for the weekend but my thoughts:
1) AFAIK heads are used for Thaumcraft infusion and EnderIO. Both are balanced around vanilla drop rates so no problem there.
2) Proper ways of getting mob heads will finally function (beheading, artificial players, axe).
3) Additional heads (pigmen, enderman, blaze, some more?) added by Iguana might get deleted. This could cause Infusion stability issues if someone uses them as stabilizers (but then again I don't know if they even work that way) and as simple decoration they might vanish.
Don't know if those specific heads are used in any recipe. Might be worth trying first if the existing heads actually vanish after turning it off. Otherwise I don't see any issue.

**Comment by flashsugar** [comment]
@Dream-Master  There should be no problems  with turning it off as said before by @merthes , Ender io heads are able to be obtained without a cleaver setup and iguana tweaks heads aren't used for anything. I also believe they arn't counted as stabilizers for thaumcraft.

**Comment by flashsugar** [comment]
any updates on this issue? @Dream-Master

**Comment by Dream-Master** [comment]
Will be in 1.5.0.4
