### ISSUE TITLE
Ammonia recipe is imbalanced

### ISSUE THREAD

**Issue by dutsky** [GTNewHorizons/NewHorizons#1567]
If you want to craft ammonia you need: 1 nitrogen + 3 hydrogen and you will get 1 ammonia
But you can take 4 ammonia and you'll get 1 nitrogen + 3 hydrogen.

The more logical way is 1 nitrogen + 3 hydrogen = 4 ammonia.

Thanks!

**Comment by Dream-Master** [comment]
Will look into it

**Comment by JohannesGaessler** [comment]
The Electrolyzer recipes are currently not stocheometrically correct.
Ore processing would become very unbalanced if it was working like the new chemicals are (think 1 Bauxite Dust -> 2  Rutile Dust + 16 Aluminium Dust + 11000L Oxygen + 10000L Hydrogen)
Long-term I want to fix this but currently GT5U doesn't have necessary infrastructure.
I'm hesitant to fix it now because I want to also change ore processing at some point in the future and I don't want to put much work into a temporary solution.

**Comment by Dream-Master** [comment]
Ok ich change it back @dutsky

**Comment by dutsky** [comment]
Oh :'(
