### ISSUE TITLE
Ye Gamol Chattels mod

### ISSUE THREAD

**Issue by Radst0ne** [GTNewHorizons/NewHorizons#1578]
I found an amazingly great mod which is called Ye Gamol Chattels.
https://mods.curse.com/mc-mods/minecraft/224600-ye-gamol-chattels#t1:description
On github:
https://github.com/Ivorforce/YeGamolChattels

It adds some very lovely made furniture and decorative stuff but also you can carve blocks into microblocks  like chisel and bits!!
Ive tested this mod and so far there are only a few, but I think modpack related, bugs/issues.
1. The grindstone has to be nerved or banned it repairs weapons and tools but its to easy to craft
2. to get bits you have to break a block with the club hammer, but blocks just break instead of giving the bits (softer blocks like dirt are working, workaround would be to chisel out a bit and then break it with the hammer)

**Comment by Radst0ne** [comment]
Some quick pixelart to demonstrate
![2017-06-30_15 37 58](https://user-images.githubusercontent.com/27621272/27737912-2c637596-5daa-11e7-9d01-aa48a3ae16f7.png)

**Comment by Dream-Master** [comment]
I vote for no. We have allready many mods added in the pack.
Let the other make a decission too.

**Comment by bigbass1997** [comment]
Sure its a nice looking mod, but some parts of it already exist in the modpack, such as weapon racks and item shelves. There is an alternative to the "micro"blocks that you mention, by using the 3D Printer from OpenComputers, you can make literally ANYTHING.

On top of that, there are a few reports of various crashes on the Github repo for the mod, but the author has seemingly abandoned the project as those issues have not been responded to and there has not been a commit since September of last year.

So while yes I do appreciate mods that add creativity like this one, for the time being I would say not to add it to this modpack.
