### ISSUE TITLE
Light fuel produces to much energy

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/NewHorizons#1634]
You can get light fuel very early and with only two mechines and small amounts of energy, but does produces 320k eu per cell, i would nerf the output to 200k eu, so you are forced to procuce diesel, at the moment you need 3 more machines and get only 80k more eu. Would like to see a nerf, just that diesel gets more popular

**Comment by Dream-Master** [comment]
@Drobac @Technus @MineAnPlay any suggestions here

**Comment by Bluebine** [comment]
Diesel only requires 1 more machine, the mixer, than light fuel does. But it requires heavy fuel to make, which costs more than 3x the oil that light fuel does. From what I've seen, it's more annoying to make diesel (since you have to distill oil separately into heavy and light fuel, instead of just making a bunch of light fuel), but it's actually LESS efficient to do so, since it takes 8 1/3 oil cells to make 6 cells of diesel, but light fuel can be made 1:1.
The only time making diesel is worth it is if you find a bunch of heavy oil, which makes tons of heavy fuel but not much light fuel.
So definitely either diesel should be worth more or light fuel should be worth less.
