### ISSUE TITLE
[1.5.0.2] Extremely large number of products required in a quest. Split Bio Diesel Quests from Platic Quests

### ISSUE THREAD

**Issue by AntidermisMC** [GTNewHorizons/NewHorizons#1640]
In the whole biomass production questline (MV tier, quest IDs 731-736) the amounts of plantballs/plantmass/biochaff/biomass cells/fermented biomass cells are very high, with the highest number being 3067 plantballs which is actually too much to fit in the player's inventory (almost 48 stacks compared to 36 slots in the player's inventory) thus making the quest impossible to complete.

**Comment by Namikon** [comment]
Something weird happened in this commit:
https://github.com/GTNewHorizons/NewHorizons/commit/1d06da6217f82f7168657748e1d221e09bd840bf

@Dream-Master  you may want to verify your changes there, and all the following ones. Another quest requires 15k Wheat instead of 512

**Comment by Dream-Master** [comment]
I change it back to 3k. Using submit station can handle a big amount of items that not fit in the Inventory

**Comment by Bryfer** [comment]
Do I need to say anything more than this?
@dreammaster
Screenshot_20170709-041842.png

**Comment by bigbass1997** [comment]
3k won't fix the problem, and it is a non-consumption quest anyways. Don't make it consume the items, that would be even more stupid.

A player's inventory can contain a max of 2,304 items (4 * 9 * 64), and even that is still insane. If the player is able to make 64 plantballs, they obviously know how to make a billion plantballs, therefore there is NO REASON to force them to craft thousands, or even hundreds of plantballs. Unless of course you are trying to annoy players.

What is the purpose of most quests? To walk the player through the process of doing something or making something. Telling the player to make a stack of plantballs fulfills that purpose. Telling the player to make thousands of plantballs still fulfills that purpose, but is extremely annoying an a waste of time. When would a player ever actually need to carry around that many??? They wouldn't, they would have the process automated.

**Comment by Methes** [comment]
The quest demands should be equivalent to the reward you're getting.
Do you get something valuable in return? Sure, go ahead and make it more difficult to complete. Think of Healing Axe for example, that quest is certainly difficult compared to other quests you complete at that Tier. But you get the reward.
If it's a high end quest, you get better rewards just for the higher Tier lootbag, but it's still equivalent to your Tier (so steam lootbag is useless for you).
Having a quest require hours of work for a reward of a 10 seconds quest (and there are plenty of those) doesn't make sense. Even if it's optional.

**Comment by Dream-Master** [comment]
I will review this Quest line and see what i can chnge( reduce) here.

**Comment by Dream-Master** [comment]
All Quest using now not more then 64 items.

**Comment by Lainiel** [comment]
Okay I have several problems with this questline.

First:
"Way one: IC 2 Fluid canner" and "Way two: Brewery" quests that are 2 quests later require 1150 Biomass cells.

Second:
This questline is not at all optional even when it should be. You can't get into Tier 4 without having "Molten plasic" completed which requires you to do all the biomass quests. There is no reason for this. You can make ethylene quite easily from oil by steam cracking some light fuel or naphtha. The same with acetic acid that you use to produce cetane boosted diesel. This just forces players to go with biofuels when they could be using oil that is much easier to use and process.

Third:
Producing plantballs fast enough that it would keep the processing line running is just hard. The quest "Bio Fuels" tells you to use either Forestry managed farm, IC2 cropsticks or Steve's carts farms. When you build the managed farm multiblock from forestry and set it to wheat, you might get a stack of wheat in maybe more than an hour. Also you can't change the whole farm to produce wheat, because you can't make good enough circuit boards to switch it. You can leave it as an Arboretum producing trees and using the saplings for plantballs, but that is still really slow. IC2 cropsticks can't be automated, because the Crop harvester requires HV for some reason. I haven't tested the Steve's carts farm, because I've never used that mod and I don't really want to build another farm when I already have the Forestry multiblock and a ton of oil around my base.


My suggestion:
Don't lock the nitro fuel quests, ethylene-plastic quests and rocket fuel quests behind the bio fuels questline and make the bio fuels optional.

**Comment by Dream-Master** [comment]
@Lainiel I will considering your suggestions and will see what i can do here.
