### ISSUE TITLE
Noble gases 

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#1666]
Noble gases only ecists in cell form, you can not store them in a tank, you can only use it in a centrifuge tho  so no need to have it as a liquid except for storage

**Comment by Dream-Master** [comment]
Yes Noble Gases not have much use atm. Maybe @JohannesGaessler have a nice idea for a use?

**Comment by JohannesGaessler** [comment]
I added the Noble Gases Fluid because I had written code to automatically generate Fluids for Materials.
I think the process of separating Air into its components needs to be overhauled.
What I imagine is compressing Air into a liquid, then simply distilling it.
The Noble Gases Fluid/Cells would then be completely removed from the process.

**Comment by Dream-Master** [comment]
@JohannesGaessler ok thanks for info. Will add the commit when you will add it in the future.

**Comment by draknyte1** [comment]
How about for a change like that, you PR it to GTNH and not main?
It's just more grind factor. /2cents

**Comment by Dream-Master** [comment]
@JohannesGaessler see they want better you working fork us then for the main branch 😁😁

**Comment by JohannesGaessler** [comment]
Current Setup:
Compressor -> Vacuum Freezer -> Centrifuge

Proposed Setup:
(Compressor ->) Compressor -> Distillation

**Comment by Dream-Master** [comment]
@JohannesGaessler did you planing toadd there in the near future?

**Comment by JohannesGaessler** [comment]
No. I currently don't have much interest in playing GT or doing GT development.

**Comment by Dream-Master** [comment]
ok
