### ISSUE TITLE
Mod suggestion : RFTools

### ISSUE THREAD

**Issue by noobyaran9** [GTNewHorizons/NewHorizons#1667]
1) Solves void world issue on servers

Set this to true if you want to make sure RFTools can only create void dimensions
    B:voidOnly=false

With this config, it will only generates void world.

2) Better beacons (Environmental Controller)
It have alot of different buffs (a lot more than the vanilla beacon can offers) which can be targeted on a specific type of entity with a adjustable range.

3) Another way of moving around
Matter tranmitter and matter receiver.

4)Builder block (Can be used as a quarry)
The quarry is faster than the Ender quarry but only have a limited range and can be modified in the configs.. (Default 512x512x256) And to make it able to mine up GT ores (B:quarrySkipTileEntities=false) must be enabled.

5) Useful stuff
- 8 recipe crafter and its really fast
- Sheild Projector. You can make shield that can do damage / block stuff from passing.
- Wireless redstone transmitter / receiver 
- Screens. You can do some redstone / storage monitoring with it. (A lot more function but I've haven't played with it enough)
- Some storage mangement block. (Modular storage, remote storage) Can be used as early game AE with wireless item requesting.

**Comment by damug** [comment]
RF tools is pretty rad, as long as you disable the dimlets for ores and molten ores it shouldn't mess with progression and will provide a decent rf sink for late game (I'm assuming it'll be gated behind late game (ZPM or UV) machine hulls if its included.

**Comment by noobyaran9** [comment]
>disable the dimlets for ores and molten ores

once u enabled the void only option, basically nthing can be spawn except a void world with customizable sky and time.

>it'll be gated behind late game

Some of them maybe. Because aside from the dimension creation, most of the stuff is early game stuff.

**Comment by Dream-Master** [comment]
So not a mod we realy need in the pack?

**Comment by leglerm** [comment]
Dont see a point.

Void world: dont we have utility worlds which adds the same thing? Same for last millenium. All this needs would be a change how to obtain these two things if actually needed.
Beacons: might be interesting but i would assume this would be a late game thing then and potentially not needed anymore.
Teleport: We allready have mods in the pack (enhanced portals, stargate) again all this needs would be a change of recipes to enable those.
Crafter: EIO, AE have those. Usually this thing is used somewhere away from your system because its cheap (like EIO treefarm) but then you can use EIO.
Shield Projector: Interesting for mob farm but power costs are actually quite high in the base mod. And we have Grinder and Killer joe
Storage: Its nice but rebalancing would propably make it unattractive. Would be between EIO/ProjectRed and AE. 

Only valueable things are really the redstone components (wireless redstone from WR-CBE i recall can be buggy sometimes) and the screens because they are actually quite awesome. Though we have nuclear control the RFTools screens are very versatile but not sure about GT compatibility.

**Comment by noobyaran9** [comment]
>Void world: dont we have utility worlds which adds the same thing? Same for last millenium. All this needs would be a change how to obtain these two things if actually needed.

We're having issue on the official server where the dimension ID is used up for utilities world. Thus, no more void world for any other player other than those who already have them. For last millenium, the whole server shares the dimension.

>Beacons: might be interesting but i would assume this would be a late game thing then and potentially not needed anymore.

Its a good power sink for late game. And there are some quite interesting effect, especially the peaceful effect. Magnum torches / the monster repeller is not working at all so im not sure if the peaceful effect would work.

>Teleport: We allready have mods in the pack (enhanced portals, stargate) again all this needs would be a change of recipes to enable those.

None of those have recipes at all.

>Crafter: EIO, AE have those. Usually this thing is used somewhere away from your system because its cheap (like EIO treefarm) but then you can use EIO.

EIO is slow AF and can only handle 1 recipe. Each molecular assembler from AE can only handle 1 recipe if u don't set it up with the interface, which mean same issue with EIO.

>Shield Projector: Interesting for mob farm but power costs are actually quite high in the base mod. And we have Grinder and Killer joe

The power cost depends on what you're using it for. As it could be made as a door for a base.

>Storage: Its nice but rebalancing would propably make it unattractive. Would be between EIO/ProjectRed and AE.

The modular storage could be around LV/MV, 100~300 stack of storage space at early game is not that OP anyway. Remote storage could probably be pre-AE. ProjectRed is very confusing to use and sometimes it doesn't even work.

**Comment by Dream-Master** [comment]
no more mods for 1.7.10
