### ISSUE TITLE
Bricked Blast Furnace not using all slots

### ISSUE THREAD

**Issue by eXoShini** [GTNewHorizons/NewHorizons#1702]
Blast furnace stops processing when it hits stack of tiny pile of ashes even though there is 1 free output slot left.
![image](https://user-images.githubusercontent.com/14859263/28492167-28df0f1a-6efe-11e7-8feb-a39d970ab0cb.png)

**Comment by eXoShini** [comment]
I'll add that I earlier used stack of iron ingots and two stacks of coal coke but same result when it hit stack of ashes.

**Comment by Dream-Master** [comment]
Will ask @JohannesGaessler about it.

**Comment by JohannesGaessler** [comment]
This is less of an issue with this specific machine, but rather with GT itself.
You will find that any (GUI-based) machine will behave in the exact same way:
Any machine will only look for empty slots at the exact position it's supposed to put its output;
It will ignore empty slots that are at the wrong location.
Unless I rewrote GT at a fundamental level, this cannot be easily changed.

Also, the purpose of the increase in slots was not to store more coal but, because at some point in the future I want to add a recipe that has 3 inputs/outputs.

**Comment by Dream-Master** [comment]
ok thanks @JohannesGaessler for info. 
@eXoShini so you need to take off your dusts from time to time or make a full automated EBF.
