### ISSUE TITLE
Custom oregen

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#173]
We need to disable Biome o plenty ores and the new tainted magic ores.

Biome o Plenty ores you can remove with custom ore gen but for Tainted Magic we need to make a own xml file.

**Comment by Dream-Master** [comment]
Not working with our configs :-1:

**Comment by Namikon** [comment]
Ahm... Really?
Removed everything but GT Ores with CoFH: http://i.imgur.com/tb7xSWx.png
Removed everything *including* GT Ores with CoFH: http://i.imgur.com/35I6BCk.png
This seems pretty functional to me..?

**Comment by Dream-Master** [comment]
How. With custom oregen or COFH?

**Comment by Namikon** [comment]
I just used CoFH to remove blocks, not for ores. The oregen is done by gregtech, that's why there are small ores and veins. CustomOreGen is configured to block oregen from every mod, and he even managed to block emeralds (In the Overworld)

I think the tricky part is the section for Gregtech ores; As you can just enable CustomOreGen to generate GregTech ores (which will disable GT's oregen) or disable it. (That's when GT takes over, and spawns his own ores in the world)

However, I haven't looked into more detail about that. Like, if the oregen is affected in other dimensions or not, or if the ores generated from GT are correct, according to the config file.

By the way: CustomOreGen can't generate Ores in GalactiCraft planets. It's blocked by Micdoodle.

**Comment by Dream-Master** [comment]
Custom ore gen is only for the overworld. I am not sure if our custom mixes spawns from Gt. Bop Thaumcraft, AE2, IC2 and Forestry ores can be disabled but the new Ores from Tainted magic we have to remove with a own xml file we have to create first. I check it later wenn i be back home.

**Comment by Dream-Master** [comment]
I remove many of the gt ore in the overworld but cant remove all. Tungsten still exist and galena too. So i think no option.

**Comment by Dream-Master** [comment]
I think for only remove Bop Ores on the Overworld we dont need COG. If it it whitelisted in galacticraft maybe this mod is an mod we need.

**Comment by Dream-Master** [comment]
Emeralds spawns to often in the overworld. So we can disable it with Custom oregen or we have a nother way?

**Comment by Namikon** [comment]
I could try to hook into the oregen bus and prevent emeralds from spawning, but i'm not sure if that works. I read somewhere that emeralds do generate in a different way.
And tbh, there are much easier ways to get emeralds than finding them in the ground, so if you want to stop people from having emeralds before / without TF, you'd have to disable villager trading

**Comment by Dream-Master** [comment]
Ok than we let the Emeralds in the Overworld.
