### ISSUE TITLE
this change gameplay

### ISSUE THREAD

**Issue by NNM42** [GTNewHorizons/NewHorizons#1730]
may be need disable:
1. Naturas clouds (natura.cfg change to false).
2. BOP ash block in Nether.
3. Blood fluid in Nether.

aka cheats.
IMHO

**Comment by Dream-Master** [comment]
I can change the recipe for the clauds not need to disable.
Ash blocks gives ash ok but not a big deal in my Eyes.
Yes the blood make fluid paceable in the nether to get Obsidian. Anything else?
@NNM42

**Comment by noobyaran9** [comment]
>Naturas clouds (natura.cfg change to false)

Useless

>BOP ash block in Nether.

Trust me you will love it when u wanna make the QED.

>Blood fluid in Nether.

Yea this is OP and very annoying.

**Comment by Dream-Master** [comment]
"Yea this is OP and very annoying."

What is op ? @noobyaran9

**Comment by Bryfer** [comment]
Ash and blood I have no problems with, they add something extra to the already boring nether mining in my opinion, 
Obsidian isn't hard to make anyway so it's not op to use blood, just waste of time, just make an GT cobblestone generator and add some redstone to it, and you got yourself obsidian.

The clouds can be annoying when launching rockets/returning
Since the rocket can get stuck in the clouds when launching 
And your chest can get stuck upon returning

But overall I think these should stay since they add decorations to the world

**Comment by Dream-Master** [comment]
ok not an issue i guess

**Comment by NNM42** [comment]
ok. thx.

2017-07-26 4:30 GMT+07:00 Martin Robertz <notifications@github.com>:

**Comment by NNM42** [comment]
if using ash, than may don't use a charcoal on "steam age" from pileignitor, that generate some pollusion.

**Comment by Dream-Master** [comment]
Yes but you need to explore the dangerous nether for it so I can live with it

**Comment by NNM42** [comment]
thx for dialog. ^_^

2017-07-26 14:52 GMT+07:00 Martin Robertz <notifications@github.com>:

**Comment by Dream-Master** [comment]
Np feel free to post everything you think this is an issue and we can discussed it here.

**Comment by NNM42** [comment]
deal.
Q: why you choise RWG? Cos not RTG?

2017-07-26 15:52 GMT+07:00 Martin Robertz <notifications@github.com>:

**Comment by Dream-Master** [comment]
rwg looks more nice in my eyes but we run one server with rtg too.
