### ISSUE TITLE
Advanced Backpack Crash

### ISSUE THREAD

**Issue by DragScorpion** [GTNewHorizons/NewHorizons#1761]
1.5.0.5

Als ich versucht habe Lava aus bzw Wasser in meinen Tank vom Backpack zu packen stürzte Minecraft ab.

hier die Fehlermeldung:
https://pastebin.com/UZfb01Km

**Comment by Dream-Master** [comment]
@Ugachaga any  idea baut thus Crash? Happens when put Lava out the backpack and water in.

**Comment by Ugachaga** [comment]
Can you reproduce it on well-configured server, like official gtnh?

**Comment by Dream-Master** [comment]
We are using 1.5.0.7 on the official test server but I can test it later.

**Comment by Ugachaga** [comment]
This code has been here since the beginning of time. I've already seen such crash twice and both times it was small private or test server. Until you able to reproduce it on stable GTNH server I refuse to believe that this is Adventure Backpack problem. 

It seems something wrong with FluidRegistry, perhaps some fluid has no registered name.

**Comment by Dream-Master** [comment]
Could be . I report what happend on zeta.

**Comment by Dream-Master** [comment]
guess this can be closed
