### ISSUE TITLE
Block of Coal Coke not usable in Bricked Blast Furnace

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#1785]
Bricked Blast Furnace only support charcoal and coal coke, not the block of coal coke.  I didn't realize and turned 99 coal coke into blocks I can't burn.  I can't disassemble them either since I am still at steam.  I turned them into blocks because 1 coke lasts 3200, but a block lasts 32000, so you get a small burn time extension with the block form.

If the block will not work with the blast furnace, should a tooltip be added or the block recipe removed?

**Comment by Dream-Master** [comment]
Yes it's hardcoded maybe I need to add those blocks to gt code.

**Comment by MineAnPlay** [comment]
The only way this could work is if you use Iron Blocks with either 4 Charcoal Blocks or 2 Coal Coke Blocks. But the issue here is that it makes it so that you lose that bonus. So I think it would only be fair if the total time taken when you use a block should be not 9x longer then using plain ingots but 8x longer so atleast you get a boost.

**Comment by Dream-Master** [comment]
@JohannesGaessler make a fix for us.

**Comment by JohannesGaessler** [comment]
Im assuming you meant to say 'makes a fix for us' because without the s it sounds like a command.
Anyways, I added Block recipes to Blood Asp's repository.
1 Block is worth 10 regular items, processing speed is unchanged.
Because of Stack sizes you can't combine Iron Blocks with fuel Blocks.

**Comment by Dream-Master** [comment]
@JohannesGaessler my english isnt the best so it wasnt a command :)

**Comment by richardhendricks** [comment]
Thanks Johannes, much appreciated.
