### ISSUE TITLE
Circuits and Ebf Problem

### ISSUE THREAD

**Issue by Radst0ne** [GTNewHorizons/NewHorizons#1838]
#### Which modpack version are you using?
1.5.10

You cant smelt energetic alloy (gregtech) in the ebf.

Also I notice that circuits cannot be crafted with different compononents. You can either use smd or normal components. Like the integrated processor its only craftable with smd or without which makes no sense because you can craft smd resistors way earlier than some other smd components.

Little offtopic:
I noticed that crafting lower tier circuits for some items is sometimes painfull if you are in a higher tier.
My Idea would be to have a ability to "downgrade "better" circuits to lower tier ones like its done in RL with microchips, maybe a recipe in the ebf so that you "disable some features of the higher tier chips with heat"

**Comment by Bluebine** [comment]
You can actually smelt energetic alloy, it just needs kanthal or better coil blocks due to its temperature requirement. Make sure to check that your coils get hot enough before you try to smelt.

For the SMD parts, I'd imagine there'd be problems with trying to integrate them as the same item, since the late-game circuits are supposed to only be craftable with SMD parts. Not entirely sure but I'd imagine this being a problem.

SoC and ASoC wafers will be your friend for these last ones. Once you've got an EV circuit assembler, you can make circuits using just these and a few pieces of wire very easily. Or before that, microprocessors for basic circuits and integrated processors for good circuits can be made with just a CPU chip and a few other componets. Not to mention, making circuits of a certain tier usually requires two circuits of a lower tier, so downgrading them would just be a massive waste of your resources.

**Comment by Radst0ne** [comment]
Damn it forgot about the temeprature lol
A workaround for the smd part would be to lower the requirements or only allow normal components until atleast the integrated processor (or maybe the workstation), I think, since everything above isnt a problem anymore
Yes its right its a waste of ressources but not every single circuits needs two lower tier circuits, Im always mass crafting these so I have some of them and often a shortage of the lower tier

**Comment by Dream-Master** [comment]
@Radst0ne I need a more clear issue what need to be changed.
The smd components are the more advanced one. You dont need it in low circuits so want to know what is the issue here?

**Comment by Radst0ne** [comment]
@dream-master I was crafting the integrated processor had everything together execpt that I had smd resistors instead of normal resistors and that didnt worked, so I had to cheat in normal resistors

**Comment by Dream-Master** [comment]
Sure i can make that they using smd too if this helps. (low tiers) @Radst0ne

**Comment by Lainiel** [comment]
I agree that it would be nice if we could combine normal and smd components when crafting the circuits.

**Comment by Dream-Master** [comment]
Sure i am on it.

**Comment by Dream-Master** [comment]
done
