### ISSUE TITLE
Macerating glass into glass dust 

### ISSUE THREAD

**Issue by noobyaran9** [GTNewHorizons/NewHorizons#1849]
#### Which modpack version are you using?
1.5.1.0

#### What did you try to do, and what did you expect to happen?
Macerating glass only takes 1 seconds.

#### What happend instead? (Attach screenshots if needed)
![2017-08-17_20 13 31](https://user-images.githubusercontent.com/13598309/29411729-ab1c9454-8388-11e7-8cb1-086ec193f42f.png)

It takes more than 1s to macerate using the HP macerator.

**Comment by AmishInvader** [comment]
I think those numbers are for the LV machines, HP steam macerator would be slower.

**Comment by Bluebine** [comment]
For some reason, the steam macerator seems to take the same amount of time and steam to process anything, no matter how much it's supposed to. Stuff like macerating stained clay and the like takes way longer than it should, while a HP steam macerator can process certain stuff a lot faster than it should be able to. Pretty much anything neutronium (neutronium fluid pipes, blocks, etc.) should take many hours or days to process and use millions of liters of steam, but instead take like 20 seconds and a few thousand liters.
I don't know if this is intentional or not, but it's very odd.

**Comment by Dream-Master** [comment]
@JohannesGaessler any idea here?

**Comment by Dream-Master** [comment]
I mean about the last comment from @Bluebine

**Comment by noobyaran9** [comment]
@AmishInvader HP machine should have the same speed as LV machine but only able to handle upto 16eu/t recipe.
