### ISSUE TITLE
Large Chemical Reactor Missing Recpies

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#1856]
#### Which modpack version are you using?
1.5.1.1

The large chemical reactor does not have all the recipes from the single block chemical reactors
![2017-08-19_13 00 05](https://user-images.githubusercontent.com/20565115/29489109-97781714-84de-11e7-8b58-b5a023b81fcf.png)
![2017-08-19_13 00 45](https://user-images.githubusercontent.com/20565115/29489113-a4952c16-84de-11e7-9f1f-eb0eda09c7c5.png)

**Comment by Dream-Master** [comment]
Its not possible because of the fluid combination. Combination can be used only one time.

**Comment by JohannesGaessler** [comment]
This is not a bug, but the intended behavior.
Consider the following example:
Distilled Water can be made in either of the following ways:

* 1 Oxygen Cell + 2000 Hydrogen -> 1000 Distilled water + 1 Empty Cell
* 1000 Oxygen + 2 Hydrogen Cells -> 1000 Distilled Water + 2 Empty Cells

Because the Large Chemical Reactor replaces all Cells with Fluids these two recipes are condensed into a single recipe for the Large Chemical Reactor.
There are other examples where Recipes are condensed by a factor of four.
