### ISSUE TITLE
[Quest & Recipe] Change "Empty Circuit Board" to use Fluid Extractor/Assembler instead of Thermionic Fabricator

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#1885]
#### Which modpack version are you using?
1.5.1.1

Current diode quest expects players to use Thermionic Fabricator to make diodes, however that is buried deep in Forestry and Farms.  Diodes can also be made in Assembler.

However, assembler recipe uses Copper/Annealed copper instead of tin. 

Should the quest be changed to target Assembler and recipe updated to use Fine Tin Wire?

**Comment by Bluebine** [comment]
I'd also like to add this quest should probably get a title change to something like "Diodes". There's another quest called "empty circuit board" which is where you craft actual circuit boards, and I'm guessing someone accidentally put that title for the diodes quest by mistake.

**Comment by Dream-Master** [comment]
Will check this.

**Comment by OneEyeMaker** [comment]
@Dream-Master 
Don't remove recipe from Thermionic Fabricator (it'll break balance and compatibility between different mods). 
If you will add recipes for circuit parts to Assembler, let they produce **_much less_** components then Thermionic Fabricator does (for example: manually I can craft components by 1 per craft, in Thermionic Fabricator - by 8-16 per craft; let Assembler produce 2 components per craft). Otherwise, this will be too cheap (as cheat) and it'll break logic of modpack.

**Comment by Dream-Master** [comment]
I add a cheaper recipe because I want people using forestry too. Only this two recipes need identical ingredients. I change assembler recipe and forgot forestry ones.
