### ISSUE TITLE
Methane

### ISSUE THREAD

**Issue by Radst0ne** [GTNewHorizons/NewHorizons#1910]
#### Which modpack version are you using?
1.5.1.2

Methane has a higher burn value than Biogas.
Not sure if it is intended

**Comment by Dream-Master** [comment]
@JohannesGaessler

**Comment by Dream-Master** [comment]
Methane have 104.000 eu per cell and biogas 40.000 eu per cell.

**Comment by Radst0ne** [comment]
I mean it does not make sense to create Biogas out of Methane since build one more centrifuge (food to gas) instead of a Distillery so you get more Methane
You get a 3x output of Biogas from Methane but it isnt really worth

**Comment by JohannesGaessler** [comment]
The intent behind the recipe that lets you generate Biogas from Methane is not to increase the energy yield.
In GT5U where I added the recipe you get 32000 EU per Biogas cell so the energy yield actually decreases when you convert Methane into Biogas.
The reason I added the recipe is because there are some IC2 items like the Jetpack that have hardcoded fuels (like Biogas) and I wanted to add a way that lets you use Methane for that.

**Comment by Dream-Master** [comment]
@Radst0ne can we close this ?

**Comment by Radst0ne** [comment]
Im not sure im tryin to get some math on but it seems that methane is slightly op
You get for each melon slice 9mb of Methane and a total time of 200s for one bucket (mv)
build some more more and you will get alot
comparing it to other power generation it looks a bit easy to me
