### ISSUE TITLE
[1.4.1.1] Cadmium LV Quests

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/NewHorizons#1917]
In LV tier there are 2 quests that require Cadmium.
1)"A big meteorite"
2)Reusable battery "Cadmium"
The only way at this tier to get Cadmium is to Macerate Sky stone indo dust, then make Rare earth, then make Cadmium.

Sky stone dust -> Small pile of rare earth 20% chance. So to get 1 full Rare earth you need 5 * 4 = 20 Sky stone.
Rare earth -> Small pile of Cadmium 25%. So to get 1 full Cadmium you need 4 * 4 = 16 Rare earth.

So to get 1 Cadmium of Sky Stone you need 20 * 16 = 320 Sky stone dust = 160 Sky stone in Macerator.

So 3 full stacks of Sky stone to get a Single Cadmium! This is a really huge number. No other quest requires so much.

**Comment by Dream-Master** [comment]
Any better idea or suggetion? @nikitinalexx

**Comment by noobyaran9** [comment]
I believe you can process sphalerite for cadmium. Look up cadmium dust in the ore byproduct page.

**Comment by Dream-Master** [comment]
Maybe i only announced that you can use Sky stone also because much more common.

**Comment by SirAzazel** [comment]
you could buff earth to 60% drop or idk

**Comment by SirAzazel** [comment]
so its around stack of skystone for one cadmium

**Comment by Dream-Master** [comment]
@SirAzazel No sure if this break balance?!

**Comment by SirAzazel** [comment]
idk what other byproducts are

**Comment by noobyaran9** [comment]
Maybe you should mention in the quest book to use NEI more.

**Comment by basdxz** [comment]
Sky stone is quite common and LV macerators only take 2 eu/t to run (Not counting transfer losses).
160 sky stone at a rate of 1 per 400 ticks in seconds would be 160*400/20=3200 seconds with a single macerator. Which is a little under an hour of maceration with a single macerator that uses barley any power. 
This balances out the fact instead of looking for ore (Sphalerite or Chalcopyrite) and making the machines to extract the byproducts, you use some freely available sky stone that the entire map is littered with. This is compliant with other stone like materials that can be macerated and centrifuged into useful byproducts.
Plus, all the quests you mentioned are side quests not necessary for progression. Rather they are designed to show you your options.

**Comment by Dream-Master** [comment]
So only a small additional info would be enough?

**Comment by AlphaApotheosis** [comment]
Also could mention you get some rare earths as a 2nd byproduct of redstone processing (centrifuging purified crushed ores/dusts). I suggest just mention redstone and sphalerite in the quest.
