### ISSUE TITLE
Bug-cheating nuclear reactor

### ISSUE THREAD

**Issue by Proha5** [GTNewHorizons/NewHorizons#1974]
Nuclear reactor provide full EU to each sides.
Example. Reactor generate 192.000. If put second transformator to nuclear - total generation eu = 384.000. My battery  buffer charging 2 times faster.
![default](https://user-images.githubusercontent.com/29812448/30509960-1e50de70-9aff-11e7-9ae8-6f1a75588ab9.png)
![default](https://user-images.githubusercontent.com/29812448/30509988-61017720-9aff-11e7-9414-b4b850800403.png)
![default](https://user-images.githubusercontent.com/29812448/30509971-32578400-9aff-11e7-8346-7d51049ddb1f.png)

**Comment by nwmqpa** [comment]
Duplicated with #1937 ?

**Comment by Dream-Master** [comment]
No it's a bit different

**Comment by boubou19** [comment]
no it's totally the same. I just have a better way to "use" it.

**Comment by Dream-Master** [comment]
@Aroma1997 any idea about it?

**Comment by Aroma1997** [comment]
What MC version are you using? Are you using uncomplication or vanilla IC2 enet?

**Comment by Dream-Master** [comment]
Mc Version 1.7.10 ic2 latest build forge 1614 latest for 1.7.10

**Comment by Dream-Master** [comment]
So far I know we not change anything in the enet.  Not sure if gt does @Technus

**Comment by Technus** [comment]
GT has it own network, 
we use industrialcraft-2-2.2.828a-experimental

**Comment by Dream-Master** [comment]
@Aroma1997 
industrialcraft-2-2.2.828a-experimental means only that i change the ic2 lang file rename Refined iron to steel.

**Comment by Dream-Master** [comment]
@Technus are we able to fix this or is this a bug between different mods?

**Comment by Dream-Master** [comment]
@Technus guess we cant fix that.

**Comment by Teirdalin** [comment]
So this seems a pretty big exploit that still exists, and seems like it should be an easy enough fix.  Why not just have a new block that goes up against a reactor part that outputs the power to transformers;  and then have that block not be able to be placed within a certain distance from more of the same blocks to disallow people from using multiples of it on the same reactor.

And have transformers unable to draw directly from reactor parts.

**Comment by draknyte1** [comment]
Curious if this happens after The cable changes. 

If so, it’s an ic2 bug and there’s nothing you can do anyway.

**Comment by Dream-Master** [comment]
reopen?

**Comment by mitchej123** [comment]
Will take a look, no promises. First need to reproduce this.

**Comment by richardhendricks** [comment]
Bug still exists in 2.0.7.0.  Can pull multiple amps from each reactor chamber vessel.

**Comment by BucketPro** [comment]
Here's my idea: Accept this extra amp thing as a "feature" of IC2 Reactors and just remove the 10x Output boost. A nuclear reactor with 6 chambers has 18 places you can place a wire or transformer. Remove one for a lever and you can get 17 Amps from the Reactor (more if you use Transvector Interfaces). Removing the output multiplier results in 1.7x Total Power Output, which is significant, but not as bad as a 17x Power Output. It would also further incentivize building a larger reactor.

**Comment by Dream-Master** [comment]
we need the power because ae2 use 10x power too. Maybe the recipe for components or the cambers can be more costy.

**Comment by boubou19** [comment]
in my opinion the issue are transvector interfaces because no matter how expensive the reactor will be, you can reach easily uv/uhv power with it with this "feature". But ban transvector interfaces just because of this is non sense because transvector interfaces can be used in various things like in AE2 automation for exemple. So i suggest to tweak, if possible, the transvector interface to have a tile entity blacklist so it will limit the "feature" and if another exploit like that is found we simply need to add the tile entity to the blacklist.

**Comment by richardhendricks** [comment]
thaumic tinkerer is GPL so we could add a blacklist for the transvector.  I had proposed this idea week or two ago on discord, we had a long discussion there if you want to go over the good/bad points.  Most center around
1. Transvectors
2. This would make fluid reactors completely garbage since you could go from EU passive to vac freezer.
3. A two chamber Thorium reactor makes 800 EU/t (assuming current multiplers). With 5 extractions, that 4k EU/t, almost two full EV amps. a full reactor making 1920 EU/t you could get 24 faces and still have 2 left for on/off and temperature measuring, or 46K eu/t, rivaling the current vac freezer nukes.

 I think lowering the multiplier from 10x to 4x makes a lot of sense if we go down this path. That makes the 2 chamber reactor 320 EU/t or 1600 EU/t - not quite a full EV amp, so players would need to buffer etc their output. A full 1920 EU/t reactor would get 18k EU/t, or almost 9 full amps of EV.

If we went this path, I think tiering the nuclear components would help keep the reactor from being so OP. Maybe just the dual/quad rods, or all the heat management components.

Adding a new blacklist would be significant work, so probably a 6mo-1yr timeframe.

**Comment by draknyte1** [comment]
I can always try fix it for 2.8.

Adding a blacklist is probably minimal work. 
Just gotta inject a for loop and point that at a static list. Ez

**Comment by DoomSquirter** [comment]
fixing the problem is great.  win / win.

but blacklisting TVI's for ppl that either are paranoid about explosions and don't trust ppl saying oh you can make bends or what not, or ppl that have already built their setups and made the tvi's and don't want to redo them...   you're imposing something on everyone for the actions that only 0.1% of the population does.    

hyperbole yes, but it's essentially the gun control debate.  outlaw something cause a potential use of it can be disastrous.  it's backwards thinking.  

anyone doing anything exploity like this is ruining the fun for themselves.  who cares.  really?  who cares.  someone makes this on an official and brags about their nukes.  go and see the nuke yourself.  oh look you have multiple cables going, oh look you're using TVI's.  OH LOOK WE HAVE A CHEATER, let's shame this person.  

if they're doing it in ssp.  who.... fucking.... cares.....  

on that same footing, one could cheat in an infinite cube of energy at any tier power strength and use that.  well shit, let's get rid of NEI cause that allows you to cheat as well.  

even worse, not BL'ing TVI's and instead punishing every person that has an ic2 nuke by changing the ratios and power outputs based on the thought that everyone's going to now go and abuse this system?  I mean c'mon.  

This is silly nerf creep thinking, plain and simple.  This should only go so far as to beg someone to fix the underlying problem.  if not, welp, guess there's nothing to do here then.

**Comment by NoriSilverrage** [comment]
You can't change the nuke mechanics because of a bug/expoit. This is a poor decision making process and sets a horrid precedence.  If I hadn't read about that bug in the ticket I never would have found it or tried it. So just leave it be and don't talk about it. You don't need to reduce their effectiveness or else you now force everyone to use these exploits

And as far as blacklisting TVIs. No! Those make so many setups work nice and compact and allow nukes to be in a aesthetically pleasing cage with nothing but a nuke inside.

I hope Alk can fix it so this ridiculous discussion can be put to rest, but if not.. Just leave them be!

**Comment by richardhendricks** [comment]
We'll wait for Alk's fix.

**Comment by 0lafe** [comment]
If you can, just limit the TVI to only work on the middle nuke not the chambers. Then divide the current multiplier by the amount of free sides max. That way you can still use TVIs as you should in nukes, but the side dupe doesn't boost to UHV+, it's just required to reach current values.

**Comment by mitchej123** [comment]
Should be fixed with https://github.com/GTNewHorizons/GT5-Unofficial/pull/195

**Comment by 0lafe** [comment]
You're a saint

**Comment by mitchej123** [comment]
> You're a saint

I wouldn't go that far.

**Comment by draknyte1** [comment]
nOw We DoNt HaVe To BaLaNcE aRoUnD bRoKeN tHiNgS.
