### ISSUE TITLE
Why HV harder than EV ?

### ISSUE THREAD

**Issue by Proha5** [GTNewHorizons/NewHorizons#1977]
Why HV motors and circuits plates need lot of silver and gold?
EV motors and circuits plates need lot of copper.
Speed of 32EV = 64HV. Result: 1 copper = 2 silver&gold.

**Comment by Dream-Master** [comment]
@Proha5 any better suggestions of using Materials?

**Comment by MineAnPlay** [comment]
Keep it as is. EV is gated via moon so this is OK

**Comment by Proha5** [comment]
MineAnPlay, Current balance created for non moded GT. Where titan is hard. You may create titan only from rutile. But this modpack contain many titans from ores and from planets stones. After moon age, HV harder than EV.
May be reduce gold-silver in motor?
motor:
 2x2x silver cable --> 2x**1**x silver cable
 4x4x electrum wire --> 4x**2**x electrum wire

Probably, reduce gold and electrum foil in "Advanced circuit board", but no sure.
Current balance:
"Advanced circuit board" requere 8 electrum+8electrum foil (total: 3 gold+3silver)
"More advanced circuit board" requere 12+1 copper foil. (total: 3 copper)

**Comment by Dream-Master** [comment]
@Proha5 What is your exact suggestion? Reduce gold-silver mean increase another material

**Comment by Proha5** [comment]
i don't know
probably, reducing will broken balance. i don't know. Current balance created by bloodAsp? if yes, then this question for bloodAsp.

**Comment by Dream-Master** [comment]
will check .

**Comment by Dream-Master** [comment]
Maybe Titanium is in to high quantities available? @MineAnPlay What you think ?

**Comment by Dream-Master** [comment]
Bauxite is on the Moon and i will remove Ttanium Pure ore from Moon and put it on the Mars.
So on Moon Level you have to get Titanium out of Bauxite-Rutile_Titanium

**Comment by bigbass1997** [comment]
Whoa whoa whoa, I just heard about this issue through Discord. No Dream, your change is just plain dumb. What tier do you call Moon now? some fake tier between HV and EV?? The moon is the start of EV tier, because that is where you are supposed to get Titanium from; and I don't mean the piddly amount that you can process out of Bauxite. You need many STACKS of Titanium to progress through EV tier, which you will certainly not get from crappy Bauxite.

Putting Titanium on Mars makes absolutely no sense at all! Mars is for IV tier, not EV; you'll have to make another higher tier rocket just to get there. If anything, Titanium was already too rare on the Moon, but now totally removing it is just plain dumb. I don't mean to insult but that is the fact.

The original post wasn't even talking about Titanium at all... It compared the resource requirements of copper at EV tier, to silver and gold at HV tier. Removing Titanium from the moon, besides being a horrible design decision doesn't even fix the original problem!

**Comment by bigbass1997** [comment]
To quote KorGgenT from Discord:

> that 10 stacks of bauxite is 64 titanium

10 stacks of Bauxite ORE that he had just finished mining, will only make 64 Titanium Ingots.

**Comment by Dream-Master** [comment]
So what is your suggestion add it back as it was or change something? @bigbass1997

**Comment by Dream-Master** [comment]
@K1ngMX would to like your suggestions here too.

**Comment by K1ngMX** [comment]
I can see how there is "too much" titanium in a vein on the moon. I can only speak for my last world (which was singleplayer), and there was way enough titanium (i did not have any trouble finding multiple veins). However, as stated by bigbass (in discord) that may be different when playing on a server, because you have to share the veins with other players, so it may take time to find a vein.

But: i would advise against going the rutile way of getting titanium, because that is really annoying. I did the rutile route in another modpack (a much easier one) and it is still annoying, to a point were its really not fun. The "normal" way to get titanium in IC2 is meant to be endgame, so its okay if it really stresses you, but here it is different. It is hard enough to get the rocket (which gates titanium), so i dont see a point in making it more difficult (and it is really a spike in annoyance). 

If you want to give players less titanium, i would make it a third byproduct of something that is really common. That way, you need to wash and thermal centrifuge that ore, and get 2 tiny piles per ore block, which is still a small amount. 

But even then, i dont see that much of a point in reducing the titanium amount you can get. Its okay if you easily get enough on the moon, because getting there is the hard part.

If i would get to choose: leave the titanium ores simply there as they were before. 

At least dont go the rutile way, i can only heavily advice against it. 

I also dont really see how HV is that much of a hassle: when using a magnetite vein you can get lots of gold as direct byproducts, as ores and when using the magnetic separator. Silver is anyway not an issue, you are easily swimming in it after visiting TF. Also you can get lots of gold by trading with pechs (they can give you golden apples = lots and lots of gold)

**Comment by bigbass1997** [comment]
> So what is your suggestion add it back as it was or change something?

I don't have any suggestion for the original issue, but I made it quite clear already that Titanium must be readded to the Moon, exactly as it was before. I don't have to have any additional suggestion to make this statement.

**Comment by Dream-Master** [comment]
Ok ores are re added an be in the next release.
