### ISSUE TITLE
Balance ideas for circuit components

### ISSUE THREAD

**Issue by AlphaApotheosis** [GTNewHorizons/NewHorizons#1978]
So I have identified a few issues with the balance of circuit component recipes. Mostly that the Thermionic Fabricator recipes are much better than other recipes for Vacuum Tubes, Diodes, and Resistors. In addition, SMD versions of circuit components should be cheaper than the non SMD versions because they can only be made in MV, but this is not always the case.

Vacuum tubes: 3 ways to make them:
Manual - Expensive as it should be
Assember - 2x cheaper than manual - This is an LV assembler recipe but requires molten red alloy, which requires an MV fluid extractor. 
Thermionic Fabricator - 8x cheaper than manual and avoids dealing with the Glass Tube sub-component so is much better.

Diodes: The thermionic fabricator recipes are about 2x better than the assembler recipes.

SMD diodes: Gallium is very rare compared to other resources, and SMD diodes require 1 gallium for 1 stack. But regular diodes cost 0.0625 gallium per stack - not even close.

Resistors: Thermionic fabricator recipe are somewhat better than the assembler recipe, SMD resistors seem ok balanced.

Suggestion is to make the thermionic fabricator recipes less efficient than the assembler recipes, or make assembler recipes better. 

Changes suggested:

**Vacuum Tube recipe for Thermionic Fabricator: produce 4 instead of 16**
**Vacuum Tube recipe for assembler: produce 2 instead of 1 because this is technically an MV recipe (MV required for molten red alloy)**

**Diodes: Halve production of thermionic fabricator recipes, or disable thermionic fabricator recipe**

**Double production of all resistor and SMD recipes in assembler, or disable thermionic fabricator recipe for resistors**

**SMD diodes: change assembler recipe input from a full gallium arsenide dust to a wafer**

**Comment by OneEyeMaker** [comment]
@AlphaApotheosis 
Search in issues - there was discussion already. In summary of this discussion: Thermionic Fabricator **should** output the maximum amount of components (because this machine is obtained by player later then assembler).
Nerfing Thermionic Fabricator (i. e. removing circuit parts recipes from it) break mod compat.

Maybe amount of output should be (little bit) tweaked.
Also, it would good idea to add/move SMD components recipe to Thermionic Fabricator (and decrease assembler output for them).

**Comment by MineAnPlay** [comment]
How does it break mod compat? Firstly the Thermionic Fabricator recipes should be removed. Making the main GT components via a non GT machine isn't the best idea. Not only that, it is instant and requires almost no power to run. So it is harder to balance (and is way too OP right now). Secondly we could do two things about the resistor, diode etc. We could double all of the recipes outputs or halve all the resistor, diode etc needed in circuit crafting. The latter is better because the pure amount is way too much (not saying that as its too expensive but you require so much of not really "dense" materials). Thirdly SMD components should get a boost/recipe change but need to think of recipes that are balanced and not OP.

**Comment by AlphaApotheosis** [comment]
Even if you say the thermionic fabricator should be the optimal option for recipe parts, I think the problem is it is just too much better. 2x better is ok, 4x or 8x better (as for vacuum tube) is a little ridiculous

Still a problem is Vacuum Tubes - the assembler recipe is not really an LV recipe because it requires molten red alloy. The thermionic fabricator should not be 4x better than an MV recipe.

And shouldn't SMD diodes be cheaper than diodes? Right now they are much more expensive.

There is another problem with the component thermionic fabricator that I think cannot be fixed. If there is more than one recipe for a single output (i.e. diodes) and you start with one recipe for diodes, but then change the inputs to a second (cheaper) recipe, you will continue to get the output for the expensive recipe, but it will only consume from last recipe you set up.

**Comment by MineAnPlay** [comment]
SMD stuff aren't supposed to be "cheaper" (they require less total resources but rarer/more processed materials). But again the Thermionic Fabricator recipes should be removed entirely (this won't break mod compat in ANY way, you still need it to make Electron Tubes and other recipes). Adding recipes to the Thermionic Fabricator isn't wrong but making GT core components with other mods is IMO a bad decision.

**Comment by OneEyeMaker** [comment]
@MineAnPlay 
I see that you have some ideas, but I can't fully understand your vision. 
Can you modify recipes and make screensots to show, how **you** want to change circuits and its recipes.
These screenshots will be idea/reference/base for recipe refactoring.

And by 'mod compat' I mean idea of integration different mods for getting new game experience. Making everything one way is boring and tedious. That's why I *suggest* to don't remove Thermionic Fabricator (or replace it with something more configurable, like Carpenter or so). Make *everything* through GT (and only GT way) is boring.

**Comment by bigbass1997** [comment]
@OneEyeMaker You need to remember this modpack is centered around GregTech. Using a single machine from a different mod which is difficult to balance and uses very little power is not making a new game experience and doesn't really fit this modpack's theme.

Also, I don't see what is so hard to understand about MineAnPlay's idea. Remove the Thermionic Fabricator recipes. `We could double all of the recipes outputs or halve all the resistor, diode etc needed in circuit crafting.` Halving the number of each component would really help out in many ways including making crafting of circuits far less cumbersome and it would help with the time it takes to make circuits. Crafting time is NOT a factor of difficulty/laziness; making circuits take forever to craft will actually cause more boredom, something you seem to want to get away from @OneEyeMaker. Look here for some stats https://github.com/GTNewHorizons/NewHorizons/issues/1976. I don't think anyone wants to sit around doing nothing for 16+ hours..

I would also like to say something: Anyone who has not tried to actually play the game in survival, through to LV but preferably higher tiers, will not fully understand the feelings generated by the current recipes. Sure you can try to analyze them, but until you have to make them in order to progress, you won't fully understand.

**Comment by OneEyeMaker** [comment]
@bigbass1997 
What's hard to understand about idea of halving recipe inputs ore doubling recipe outputs? *Nothing*.
But I asked not about **this little idea**. MineAnPlay has many suggestions (in many places), such as removing previous tier of circuits from circuit crafting, reduce times of circuit crafting, etc.
And I understand how these suggestions can be completed - but it is *guess*.
That's because I want MineAnPlay to show his ideas *in practice*. (We said *too much words* about how it may be/should be. But where's result?)

@MineAnPlay (and anyone interested)
The proposal is still in force; so if you can realize your ideas (via scripts, for example) and publish (like pull request or suggestion) - this will greatly help in development.

**Comment by MineAnPlay** [comment]
I don't have as much time as I had so can't really do much anymore but I didn't say that the previous circuit should be removed (just lowered to require 1 but recipes must be changed appropriately). As seen in the screenshot in #1976 you require a lot of items that aren't "dense" which can be annoying. I'll try to post/suggest ideas as I have time to do it.

**Comment by Dream-Master** [comment]
ok

**Comment by basdxz** [comment]
Large quantity item management does make sense as you do need large quantities of these components, but while it's somewhat of a challenge it can be worked around. I agree that component crafting times need to be lowered and that whilst maybe it could be feasible to setup the thermionic fabricator for low end crafts SMT components should be more effective as in the real world they present a cheaper alternative to the same component.

**Comment by SirAzazel** [comment]
using thermionic for components is stupid in 90% of times, only resistors are completely fine with being heated to somewhat high temperatures (600 C for sodium glass [aka window glass])

**Comment by Palesteak** [comment]
The main thing bothering me is, that you have to start from LV circuits when you need one of a higher tier. Why was the system designed this way? It makes no sense at all. Who would make faster processor from an old one if the logical (and more realistic) approach is to craft it from scratch inside its technological level. 
To do that, the higher circuits should require a material that matches the respective tier. One example could be a tier-specific wafer created with silicon (at higher tiers maybe additional polyethylene or polytetraflourene etc.) instead of the lower tier circuit, that also requires the metal of the respective tier (e.g. aluminium/stainless steel/titanium a.s.o.). 
This would still keep the crafting of the circuits tedious enough but it would not be necessary to start from LV to craft something in hv for example.

**Comment by AlphaApotheosis** [comment]
@Palesteak This already exists - Your first HV circuits will be the advanced circuits made through LV Integrated Logic Circuits, but once you have an HV circuit assembler you can make Nanoprocessors in HV, which do not require earlier tier circuits. The way it's set up, if you want to make circuits for the current tier you need to have a full suite of machines for that tier first, otherwise your must assemble from previous tiers.

**Comment by SirAzazel** [comment]
i thought about that too, but i was told that further you go easier craft actually becomes, so you dont really require that much LV circuits to say make UV circuit. i calculated it would be 512:1, but Bass and Mine said it would actually be <1:1

**Comment by AlphaApotheosis** [comment]
LV circuits will never be needed to make anything more complex than the advanced circuit. See https://gtnh.miraheze.org/wiki/GT_Circuits

**Comment by Palesteak** [comment]
I guess I overlooked that somehow and it bothered me a lot ^^ I'll look into it again.

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/1996
