### ISSUE TITLE
Empty seared tank Ghost Damage

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#198]
Empty seared tank currently give the holder what appears to be *ghost damage*.
This occurs regardless of seared tank's liquid contents.

The knockback given by this TConstruct tank is frustrating to say the least.

**Comment by PaladinOne** [comment]
By 'ghost damage', do you mean, it seems to be dealing damage to you as if it had Lava in it? (The way a Bucket of Lava deals damage) Or is it dealing periodic hits of 0 damage?

**Comment by Namikon** [comment]
I verified the function of the module in my local test environment, and the coremod is working as expected. (I could fix a few things and made the commands available for the server console, but nothing of that had to do with the way damage is dealt to the player)

My guess here is:
- 0.5 hearts damage is not enough to "damage" the player, means the regeneration might be too high, or some mod is affecting this somehow
- The tinker's tank is added directly as item and therefor it will cause damage. Instead of adding the item itself, it would be better to add "fluid.tile.lava" with "exactmatch = true" to the config
- Damagetype "lava" will cause a death-message of "xx tried to swim in lava". Better use "onFire", then the message would be "xx burned to crisp" or somthing like that.

If someone wants to help setting up a proper config, go in singleplayer/creative and type /hazit help.
Most stuff can be configured ingame.

**Comment by Dream-Master** [comment]
I planing a small update this evening to update all mods.
@Namikon you are in TS this evening?

**Comment by Namikon** [comment]
Yes i'll be there

**Comment by Dream-Master** [comment]
I think i fix it.
