### ISSUE TITLE
Circuit Re-desing 2.x

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#1996]
After so much complains about the recipes in 2.0 I will open up this issue to have more specific recipes suggestions.

I don't want to read walls of text here just simple recipes changes/buffs please. (This is not a discussion thread)

**Comment by AlphaApotheosis** [comment]
Vacuum Tube Recipe in assembler: increase production to 4, replace molten red alloy with red alloy bolt

SMD Diode recipe in assembler: replace gallium arsenide dust with 2 wafer

**Comment by Scionoftruth** [comment]
Make all the circuits interchangeable within a tier.
Or make it possible to put in crafting table to switch between certain circuits in a tier like LV does.
The good electronic circuit is stuck at MV, when you are forced to make a completely separate circuit (the good integrated circuit) for making the next tier. But both do the same thing.

**Comment by AlphaApotheosis** [comment]
@Scionoftruth That is the point - this is because while the good electronic circuit can be made without machines or only LV machines, you need to invest in MV machines to make the next tier. The Integrated Logic Circuit is actually cheaper in terms of raw resources than the basic circuit, but requires more and higher level infrastructure.

**Comment by tranceplanet** [comment]
I'm a post-steam, mid LV player at the moment.

1) Iron Tank in Assembler now needs molten glass.  A simple request but can glass dust be an LV (28EU/t) recipe in the Fluid Extractor for Molten Glass.  The only recipe I can use at my level currently is Quartzite, very restrictive.

2) Simplify the (Basic) Integrated Circuit [crafting table] process as this is really crippling new people to the point I'm bored of making new machines.  I don't have experience beyond LV so I don't have any suggestions.  The previous recipe worked for me - the new recipe is just a grind fest on top of an already complicated modpack...  It's definitely taken the fun away for newer players.

**Comment by Scionoftruth** [comment]
@AlphaApotheosis DM doesn't want this to be a discussion thread, but I'm at EV lvl, so its not that big of a deal, but you only get the MV electronic circuit from bags. So in a group, you usually get a bunch that sit around at higher tiers, but just saying that basically you are forced to use that at the MV lvl. Not a big issue just annoying. I do understand what DM was going for with the 2 types

**Comment by Lainiel** [comment]
If you're gonna remove the Thermoinic Fabricator recipes for diodes and vacuum tubes, make the assembler recipes for them cheaper.

**Comment by kris449** [comment]
Or put the same recipes that the Fabricator used in the assembler at a higher tier.

**Comment by AlphaApotheosis** [comment]
Cut chemical reactor recipe time for plastic circuit boards (and all higher level circuit boards) in half or more.

**Comment by kris449** [comment]
(Reposting MineAnPlay's suggestion because he's lazy, alternate to my idea)

Double all of the recipes outputs or halve all the resistor, diode etc needed in circuit crafting. The latter is better because the pure amount is way too much (not saying that as its too expensive but you require so much of not really "dense" materials). Also the time taken to craft these should be decreased by a little.

**Comment by Radst0ne** [comment]
What about this:
Lv circuits stay analog
Mv circuit crafted with 2 lv
Hv circuit with 2 mv, but mv circuits will be easier to craft using a hv soc

**Comment by GMous** [comment]
I think 2^tier for circuits cost it's too expensive. It's boring and most of players on Epsilon (for example) AFK as world anchor for very long time.
I suggest such options:
Do not touch low tier recipes for each tier circuits. But for high tier recipes do 1 to 1 previous tier circuits requirement. Or even two tier-2 circuits (for example: 1 HV require 2 LV, not MV. MV can be either 1 to 1 or 2 to 2).
This will significantly reduce the boring part of the high tier circuits craft and keep the complexity of the craft chains.

Thermionic Fabricator recipes must be saved. If you want to remove recipes from it, it's better to simply transfer them to assembler and change Fine Copper wire to Fine Annealed Copper wire in Vacuum tube recipe.

**Comment by Dream-Master** [comment]
Any news here ?

**Comment by Palesteak** [comment]
The main issue is still the amount of time/resources circuit crafting itself is taking during gameplay. The most simple (and most likely fastest) way to do something about it would be to reduce production times and to either increase the yield of the recipes (more circuits/parts per production) or reduce the number of parts required per circuit. 

In the long run, especially on the lower tiers, the crafting itself should be less tedious and time consuming, it scares players off the server.. maybe reduce the amount of different parts that are needed for circuits on lv and mv level and reduce the raw material costs on hv and up by buffing the recipes a bit.

**Comment by AlphaApotheosis** [comment]
I want to reiterate that the thermal fabricator recipes should be removed entirely or at least moved to the LV assembler. The thermionic fabricator bleeds energy when not in use, is instant, and energy costs are not possible to balance. I believe it should really only be used for forestry machines, maybe the vacuum tube for thematic reasons. Not diodes/resistors etc, other circuit parts. 

GT circuit components should be made only in GT machines, where they can be balanced if necessary (some balancing is definitely necessary).

**Comment by Dream-Master** [comment]
i removed it allready.

**Comment by tranceplanet** [comment]
Is this still being looked at?  The pack is amazing and we appreciate all the work but c'mon please do something about this.  I really hope this hasn't just been left by the side and assumed 'all is well'.  For new players the circuits are sucking the life out of this pack.  I have just started to get out of LV and into MV only the learn that all the stockpile of circuits I've made are useless for later tiers as getting Advanced Circuits requires 'different' basic circuits.  Can you standardise the circuits or make a way to convert/upgrade them from one to another (Electronic Circuit -> Integrated Logic Circuit).  I don't understand why this part of the game has to be so tedious.  Older players aren't as bothered because they can automate a lot of this I understand that.  I personally think this part of the game is over-complicated, particularly early game.  The only good thing for me right now is the fact that components can be done in the Thermionic Fabricator on our version.  Apologies for my frustrated post but I have realised how little progress I do on this pack now due to the circuit changes...  I don't play this like it's my full time job, and for the time I'm on I like to focus on 1 thing at a time.  Several sessions with just a couple of circuits to show for it feels like no progress.   I will say I do enjoy this pack though and it creates a great community.  Thanks for your efforts.

**Comment by Dream-Master** [comment]
@tranceplanet I take this issue on hold because I not get new explicit suggestion how to change things. I can change an existing recipe but would it be better after the change? The more details and suggestions I get the better I can do the circuit changes. My problem is all people complain about it but no one make a clear and strait suggestion how it have to be in the future.

**Comment by tranceplanet** [comment]
The challenge for me to make a suggestion is that I don't know enough about this recipe going beyond MV.  But I find it daunting currently at my level to progress.

One immediate suggestion that may help to reduce the severe complexity of circuits that is currently hindering players is the ability to upgrade circuits from lower tiers to something useful.  I personally find it frustrating that there is numerous types of each circuit

(difficulty based on level that needs it...  E.g Steam player needs basic circuit)

Basic Circuit - LV
Electronic Circuit
Integrated Logic Circuit
Microprocessor

Good Circuit = MV
Good Electronic Circuit (requires Electronic Circuit)
Good Integrated Circuit (requires Integrated Logic Circuit)
Integrated Processor (requires Microprocessor)

Advanced Circuit = HV
Advanced Circuit (requires Good Integrated Circuit)
Processor Assembly (requires Integrated Processor)
Nanoprocessor (new circuit, no preq)

Already the circuit process is huge and complicated.  But MV recipe can use any circuit...??

Going to HV the process becomes very time consuming because you have to start making new circuits and upgrading them.  (Good Integrated Circuit -> Advanced Circuit)

I suggest only 1 circuit per tier.  Each circuit has a unique recipe (does not use previous circuit).

**Basic Circuit = LV**
Electronic Circuit [craftable/circuit assembly LV]
Recipe (crafting window) = stay as is
Recipe (circuit assembler LV) = stay as is
Circuit Board (basic) = double the current output on all recipes.

Good Circuit = MV
Good Electronic Circuit [craftable/circuit assembly LV]
Recipe (crafting window) = **3 aluminium item casing**, 2 copper wire, 1 steel item casing, 1 good circuit board, 2 diode
Recipe (circuit assembler LV) = **2 aluminium foil**, 1 good circuit board, 2 diode/smd diode, 1 copper wire, smoldering/tin/lead
Good Circuit Board = double the current output on all recipes

Advanced Circuit = HV
Recipe (circuit assembler LV) = 2 stainless steel foil, 2 integrated logic circuit (6028:32037), 2 Random Access Memory Chip, 4 Transister, 8 Fine Electrum Wire, 8 Annealed Copper Bolt

This can continue up beyond HV I guess.  But the idea is basically to strip the need to make a million different circuits and focus on 1 circuit type per tier on the main GT machines.  Also just 1 recipe for a circuit - not to have circuits -> circuits -> circuits.

Hope this makes sense as a suggestion?

**Comment by Dream-Master** [comment]
Thanks will look into it.

**Comment by tranceplanet** [comment]
Edits finished.  Just wanted to make sure the suggestion was as clear as possible.  Thanks

**Comment by Dream-Master** [comment]
Soon i be on vocation but back in December then i can take care things.

**Comment by tranceplanet** [comment]
I'm sure I'll still by MV by then 😆

**Comment by Dream-Master** [comment]
Thanks
