### ISSUE TITLE
[Quest] Molten Polyethylene

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/NewHorizons#2009]
#
#### If in multiplayer; On which server does this happen? 
Epsilon

Quest in it's final stage requires "Universal fluid cell". I think it should be usual Gregtech cell.

**Comment by Dream-Master** [comment]
There are no gt cells if you search in nei. Maybe I Can Try to add some.

**Comment by Bryfer** [comment]
Feels like this issue needs to be brought up again
#1089

**Comment by Dream-Master** [comment]
Molten cells are not added yet to gt cells.
 @Technus are you able to add molten gt cells for all molten fluids?

**Comment by Technus** [comment]
**Molten stuff has no cells:**
- it is not meant to be put into cells 
- this would conflict in some cases with dust cells 
(like the ones used some time ago in naquadah reactors). 

Fixing that would break compatibility and other shit. 

**Explicitly added Fluid materials:**
- should have fluid filled cells. (since they have no dust form)

**The way to handle molten fluids:** 
- use fluid solidifiers/ fluid extractors and store the molten stuff as ingots/nuggets etc.
- that is even more convienient since the amount of stuff you get from inots is not going to be easly dividable by 1000.

**Comment by Technus** [comment]
Reopen of the only liquid materials have no cells.

**Comment by Technus** [comment]
@Dream-Master as for quests - use GT cells when applicable or just give out ingots... if no cells exist
