### ISSUE TITLE
Integrate nerfed Recipes in java.

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#201]
(no minetweaker and modtweaker code any more )

**Comment by Namikon** [comment]
I don't see a good way to do this without running into trouble. The reason is simple; Minetweaker kicks in as soon as you login, which means that all mods finished loading their items blocks and recipes. The idea was to reduce login-lag, but I'd have to place that recipe loading somewhere within the login process, which renders the whole idea useless.
