### ISSUE TITLE
Distilling Water is not efficient.

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/NewHorizons#2019]
Here are the current recipes.

Basic Distillery 160 seconds = 1000 Distilled Water + 32000 EU
Basic Electrolyzer + Basic Chemical Reactor 160 seconds (Electrolyzed Water to Oxygen + Hydrogen and then both into Distilled Water) = 2176 Distilled Water + 96300 EU

So noone would care for those extra 60k EU if he can get more than twice Distilled Water. And Distillery should be like the most efficient for Distillation, because it is the only purpose of this machine - to distill things.

**Comment by Bryfer** [comment]
If you want distilled water then why are you not using an large turbine from gregtech? It actually gives you energy

**Comment by nikitinalexx** [comment]
Are you talking about MV Distillation tower? I can't find large turbine in NEI. And still i think Basic Distillery in terms of Distilled water output should be increased

**Comment by Bryfer** [comment]
Large turbine is an mid game energy source
See this for more information
https://ftb.gamepedia.com/Large_Turbine

**Comment by Methes** [comment]
Honestly there's no mention anywhere the Turbine produces Distilled Water, or how much. I didn't know that either.

**Comment by Dream-Master** [comment]
New for me too :-)

**Comment by Bryfer** [comment]
had to double check the wiki aswell, no mentions of water at all there yey for wikis!
as you know 1mb water = 150mb steam
with the steam and HP turbines it requires you to make an output hatch aswell. This output will output distilled water, I assume this ratio is 150mb steam -> 1mb distilled water since I've managed to make an lossless system that was running for multiple weeks without losing (distilled) water.

The Distilled water can also be used in the Large GT Boilers instead of normal water. as far as I know this water is also 1Distilled water -> 150 steam

Depending on your setup you might need to have an tank to store distilled water inside since there may be overflows of distilled water when you turn the boiler off and change all steam into (disilled) water.

The Large Turbine will void distilled water inside the output hatch if the output hatch is full. so pipe it out from there before it gets full to make it lossless, also keep in mind that slushing may also clog your water pipe and make the output hatch full that way.

Since this information is apperently missing from the common knowledge places, maybe its worth adding it to the large GT boiler /turbine quests as a mention there?

**Comment by Dream-Master** [comment]
Yes I can add it

**Comment by Dream-Master** [comment]
@Bryfer can you add a text for me here  i will add under the quest text. Thanks

**Comment by Bryfer** [comment]
Quest 784 "Bronze Boiler"
As soon as you have the ability to store energy in large quantities, it would be necessary to have a way to generate energy in large quantities. You need a large bronze boiler. But in order to make this boiler, you will need a mountain of bronze. This boiler produces 800 liters of steam per tick. _**The large boiler can run of both water and distilled water. Water is comsumed at a rate of 1l of water per 150l of steam.**_

Quest 783 "Large Turbine"
All your little turbines take up too much space? _**Are you running out of water?**_ It is time to solve these problems. This large turbine can help you produce a tremendous amount of energy. _**It will also distill water for you, so you can use the same water again inside your large boiler.**_  Don\u0027t forget to make a rotor for the turbine. At the initial stage the most suitable materials for the rotor are: vanadium steel (it has a very high durability, but slowly produces energy), cobalt (good combination of durability and performance) and ultimet (has higher efficiency, durability and performance)
