### ISSUE TITLE
Suggestions Mass Production #Shorter Production 

### ISSUE THREAD

**Issue by Raccoon2709** [GTNewHorizons/NewHorizons#2024]
#### Which modpack version are you using?
Latest
#
#### What do you suggest instead/what changes do you propose?

Im at mobile and dont know the current values. 

I woud like to have a new recipe for the bbf, exactly for the steelbars.

I dont want shorter production time directly instead i woud like to have a recipe for more steel in the same time.

Example 1

1 Iron and 4 Coal = 1 Steelbar

12 Iron and 5 Blocks of Coal = 10 Steelbars

Productiontime stay the same.

Further Recipe woud be for the EBF

12 Iron + Circuit board + 8 Coaldust = 10 Steel

Same time as normal Steel and same energy value (time==energy)

Im asking for another Example if you dont like mine, but like the idea.

**Comment by Dream-Master** [comment]
I am at work right now and cant check recipes.

I remeber there are recipes with gives you 9 ingots and using coal block but the production time is longer. 
The problem with recipes is i cant add similar recipes to the BBF like this: 
1. one iron and one coal block gives one steel (only example)
2. 5 coal block and 9 iron gives 9 steel (only example)

On EBF it is possible because i can chenge the meta id of the circuit.

**Comment by Raccoon2709** [comment]
Thanks, because bbf uses fuel and not items what's about a second inputslot for the bbf. I know its much more effort and a bit much changes for such an idea.

Example

12 Iron + 24 Coaldust and the Fuelcosts.

But as i said, its to much effort maybe.

**Comment by Bryfer** [comment]
Isn't this why there is a quest to make like 10 bbf?
Also currently you can already use coal which reduces time or blocks which allows you to put more fuel inside the bbf to make it run for longer

**Comment by Raccoon2709** [comment]
My problem isnt it to produce enough coal or run longer, i cant waste 10 hours babysitting my bbfs

**Comment by Dream-Master** [comment]
Make a ebf and automate it.

**Comment by Raccoon2709** [comment]
I have a ebf im at ev lol

**Comment by Raccoon2709** [comment]
Whatever when you dont think its a issue close the thread.

**Comment by Dream-Master** [comment]
Not sure how and what i can change.  We can add high tier recipes with a higher voltages.

**Comment by Bryfer** [comment]
no need to add any more/other steel ingot recipes, once you reach a higher tier you can craft steel almost instantly.
and at LV-MV you can also make steel using oxygen which is super quick aswell.

no need to sit and stare at the actual bbf for 10hours, but iron and coal inside all your bff and then build something else inside your base, or get an chunk loader so you can mine while waiting for your material to process.
There is alot you need do to all the time. and you'll run into this problem again at every tier you enter.
When you reach a new tier, you'll have trouble creating the materials needed to progress. and once you are past the tier its alot easier to make the materials since you most likely (semi)automated the process to make it.

You'll miss how easy it is to make steel in the future :)
