### ISSUE TITLE
Weird Pipe behaviours

### ISSUE THREAD

**Issue by Radst0ne** [GTNewHorizons/NewHorizons#2027]
1: There is a "rule" that only items are moving into a machine if they have a recipe for it, but somehow some items wont move even if they have a recipe. E.g. water cell into chemical reactor (recipe sulfuric acid)

2:If you extract something out of a chest into a pipe, only the first machines gets items, and the items gets stuck in the first pipe waiting to be processed in the first machine. However the second machines gets nothing, you need much more oversized pipe to fix that or need one conveyor on each pipe to extract into the next pipe.

3: More gretech related: why doesnt the conveyor fill up the stack which is in the pipe, it waits until the pipe gets empty and the fill it up again?. Why does always the first pipe holds items instead of extracting the amount of items needed.

This three points make automation with gt pipes unecessary complicated.

Possible solution:
Make other pipe systems a little bit cheaper

**Comment by Methes** [comment]
Ad 1
Haven't had that problem yet.

Ad 2
Haven't experienced that either, it works fine for me. If I understand your problem correctly though. You might consider adding screenshots of your setup.

Ad 3
If there are items in any block of the whole pipe line, whole pipe line gets locked until that item is removed. That's just how the pipes work.

**Comment by Radst0ne** [comment]
Check the recipe

![2017-09-28_20 58 27](https://user-images.githubusercontent.com/27621272/30987968-13d06bfc-a499-11e7-8cd4-dfef96fa59ec.png)

you can see the "waiting" items. they will stay forever because the pipe is reffiling the machine each time one item is used up, which doesnt make much sense.

Im saying why not only extract the amount is needed, dont fill every pipe

**Comment by Bryfer** [comment]
Those items are stuck because they have nowhere to go. 
If you want slot of different items inside the same pipe then GT pipes are not really what you are looking for.
Also keep in mind that different GT pipes has different items/t that they can move and some of them can even transfer two different items at a time. I assume you should be using those instead, or EnderIO conduits

**Comment by Radst0ne** [comment]
@bryfer both machines are fluid extractors it is stuck because the pipe is busy keeping the first one filled and thats a odd behaviour

**Comment by Bryfer** [comment]
Check the tooltip for your pipe. It says it can transfer one xxitems each xxticks. You need a better pipe.
If your pipe is trying to put xxitems inside the first machine each xxticks it will not try the 2nd machine at all since it has already done it's task this operation

Upgrade your pipes or go for EnderIO

**Comment by bigbass1997** [comment]
GregTech pipes are not "smart" by design, and fit with the tiering of all of the transportation systems throughout the modpack. If you want smarter item transport, then you will have to upgrade to other systems, such as EnderIO.

The costs for such other systems fit with their abilities and which tiers they are designed to be available from. GT pipes are cheap because they don't have a whole ton of features. EnderIO Conduits are more expensive (but not too much) as they are much MUCH more advanced and have tons of complex features.

The way GT pipes work is that only one item can be inside of a single pipe at a time, which makes quite a lot of sense as the item physically moves through the pipe; larger pipes can transfer more of that item over the same period of time. EnderIO for comparison moves items instantly, and even they only transfer one type of item at a time.

To address your first "issue", be sure you are using a GT cell, not a universal cell. Otherwise try putting the other required inputs into the machine first.

**Comment by Radst0ne** [comment]
![2017-09-30_15 35 39](https://user-images.githubusercontent.com/27621272/31046208-111ae830-a5f5-11e7-8d0d-45e3171b7261.png)

You can see the cell is stuck in the pipe (its a fluid canner) and it wont move to the chemical reactor, it works if the cell is already in the chemical reactor (gt cell no universal etc.).
Also I tried with bigger pipes 1stack each 40ticks (recipe takes 64t so its fast enough) but it doesnt split the item.
I tried another world with the same exact setup and there it works flawlessy.
So it could be either some directional bug or something interfere with something, I cant tell
