### ISSUE TITLE
GT++ Fish Catcher/BioDiesel

### ISSUE THREAD

**Issue by braeven** [GTNewHorizons/NewHorizons#2051]
Currently the GT++ Fish Catcher only needs 8 Iron Bars and 1 Wrough Iron Casing(=3 Iron and 2 Wrough Iron) to make, but they make nonstop Fish, Slimeballs, Diamonds, Emeralds, Sand and some other stuff without needing anything.

Currently one of the best Energy-Options for LV/MV and even HV is making fish with tons of Fish-Catchers, make Fish Oil out of it and mix it to Bio-Diesel or even Cetan-Diesel.

6B Bio-Diesel bring you 1.500.000 EU
Producing 6B Bio-Diesel using fish catchers needs only ~216.000EU
> (9.600EU making Fish Oil
> 18.000EU Mixing Bio-Diesel
> 320EU Making Sodium Hydroxidemaking
> One Bucket of Ethanol/Methanol out of fermented Biomass 84.000EU
> 7B Fermented Biomass 21.000EU
> 7B Biomass 5.120EU
> 10 Bio Chaff 12.000EU
> 10 Plant Mass 60.000EU
> 20 Plant Ball 6.000EU)

So you get ~1.300.000 EU out of one Production

And we nerfed Biogas/Methan to only bring 62,4k EU while Producing needs ~46,4k EU. This seems pretty Unbalanced since you only need LV-machines for both ways.

So I would suggest to make producing Bio-Diesel out of Fish Oil need more EU and make Fish Catcher more expensive to craft.

And The Fish-Catchers also produce slime-balls which can be used to make a pretty easy Rubber-farm and bring you other stuff like iron nuggets, gold nuggets, diamonds, emeralds

**Comment by Dream-Master** [comment]
Making fish catcher more expensive would solve the problem

**Comment by MineAnPlay** [comment]
Don't make it too expensive (make it LV/MV tier). A crop farm will produce other products too unlike fish which would produce only oil and some other stuff that aren't really that important(there are a LOT better ways to get those items).

**Comment by Methes** [comment]
Make it LV.
Even with it being cheap like it is it's easier to get 2000EU/t with steam now than with any other source, meaning Bio-Diesel, Biogas, Methanol and Oil are dead to me now. (talking about self-sustainable energy production).

**Comment by Dream-Master** [comment]
Maybe i can make it use alu and steel to be mid lv after ebf.

**Comment by MineAnPlay** [comment]
Make it require steel. It's nice but like Methes said you require a lot of it to even get a large EU per tick.

**Comment by Dream-Master** [comment]
ok but steel is mid bronze age

**Comment by MineAnPlay** [comment]
And? Fish Oil has no use till you have machines. This will make it so it's not just some pieces of iron.

**Comment by braeven** [comment]
I don't think just making the traps more expensive is the way to go, I think the recipes making fish oil should be more expensive. Currently you need 150 vanilla fish to make 6B of Bio-Diesel and to Produce 6B of Fish Oil you only need 9600EU, 64EU/40mB Oil, Maybe also Pump up this number to something like 900EU/40mB Oil, so you don't get an enormous amount of Energy compared to other LV-Energy Options like Biogas/methan

**Comment by Dream-Master** [comment]
ok fish trap get steel and production cost will be use a bit more eu. @braeven @MineAnPlay  ok?

**Comment by braeven** [comment]
okay with me

**Comment by Methes** [comment]
Yes, BioDiesel is enormous in comparison to Biogas/methan, but that's because BioDiesel (and cetane) are more like MV suited and also because Biogas and Methane suck, a lot.
I don't have the exact numbers ahead of me now but using seed oil requires the same amount of energy of processing. Is that an issue? No.
Don't change the energy demands and worsen yet another energy source by that.
Steel is fine. It's basically automatic crop producer so think of it as an automation of flint hoe, dirt and seeds. Nerfing it even more means it loses it's place as an interesting alternative to plants.

**Comment by Bryfer** [comment]
So now that there is an OPaf fishing machine available thru GT++, will the Pam's harvest fish trap which I recall is more expensive to craft than the GT++ one, and also requires bait be disabled? 
No need to have multiple things that has the same function when one is far more superior than the other one..

**Comment by Dream-Master** [comment]
So disable gt++ fish trap and let pams inside ?

**Comment by MineAnPlay** [comment]
You can produce a LOT more seed oil then fish oil. Because of this I don't think that the fish oil/fish catcher should be nerfed(other then it requiring steel). Yes the fish catcher is more OP then the Pam's Fish Trap but that is WAY too slow to make it worth it for power production. So overall yes it's a bit OP but shouldn't be gated too much nor nerfed heavily.

**Comment by braeven** [comment]
I don't think disabling the Fish Trap is the way to go, the Pam Fishtrap needs bait for working. making it more expensive is a good choice.

Currently Making Seed Oil using Vanilla-Seeds only gives 10mb per seed(most pam seeds give only 3mb) and need 64 EU for Vanilla Seeds, Pam-seeds need 800EU, so there is allready some kind of nerf in place.
since you need to build a farm and maintain it to get seed oil, there is way more work required to make seed oil than make fish oil currently

**Comment by MineAnPlay** [comment]
The Pam's Seed will most likely be changed to be inline with Vanilla but a farm that makes seed can make TONS of seeds. Even a non upgraded farming station will make a LOT more seeds then a fish farm making fish and it only requires 40 rf/t (11 ish eu/t). Don't forget that there is also the option to breed IC2 Crops to get Rape which will give 50L and with max stats you will get more seed oil then you can use. There is also Forestry Trees as well. As you can see there is more options for Seed Oil and all of them both produce it faster and more efficiently. The Fish Catcher doesn't require power but it takes time and because of this even with a large amount of them you won't really generate as much fuel per tick compared to seed oil. So other then changing it to require steel I don't think any other nerf should be done.

**Comment by Methes** [comment]
Pam's Fishtrap is a joke anyway.
Getting enough seed/fish oil for around 4500EU/t requires 170mB per second.
Good luck making 600 fish catchers instead of large and efficient seed farm.

**Comment by braeven** [comment]
Farming Station is late MV tier and requires a lot of machines to even make one
Steves Cart Farm is LV and requires a big load of steel and coal for running
forestry Multifarm is LV and requires a big load of resources, machines, needs energy, fertilizer, dirt and water to run

And we are not talking about energy needs of 4500EU/t, we are talking about LV age and compare it to LV-Energy Options, like biogas/methan, currently with the gt++ fish catcher, it's way to OP compared to biogas/methan and even seed-oil, it's just to strong for this tier

**Comment by Methes** [comment]
Lets put it this way. In LV Biogas is useless, methane too. Steam is the way to go or use large infrastructure to produce biomas (brewing stand anyone? MV Thaumcraft thing or being smart?) with fish oil.
Go to MV, Biogas with methane are still just farts, steam is still king with fish oil loosing its edge and slowly being replaced with seed oil.
HV, seed oil is superior to fish oil, steam is similar to oil.
The way I see it it's fine as it is, I'm just sad Biogas and Methane are useless.

**Comment by Dream-Master** [comment]
ok so i willl only change recipe from fish trap. 
@Methes How Biogas and Methane need to be chnage that it is wrose to make some setup ?

**Comment by richardhendricks** [comment]
I disagree, the steves farm is much less intensive than a fishfarm.  Every fisher block will require pipes and some sort of output like a hopper or conveyor or transfer node. I am OK with increasing the resource requirement for a single fish farm, but realize it already is way higher than a steve's cart farm because of the other incidentals required like pipes and conveyors.  Rails are really really cheap once you have an assembler, and can be found throughout the overworld.  Steve's carts can use wooden rails, which are practically free.

I think it is good to offer two alternatives:

fish farm requires a larger investment and automation to handle the garbage collection and conversion to standard fish. doubling the output requires doubling pipes, doubling catchers, doubling extractors, planning for water, etc.  Limits are quickly reached that will require more intensive work like splitting the pipes.  However ongoing costs are low (self-crafting to fish, or small eu for autocrafting to fish.)

stevescarts requires a smaller investement and much less automation (only 1 location, only has to be done once). Doubling the output just requires adding some more rails, no additional planning or design work really required. Ongoing costs are still pretty low, just some coal.

Timewise, for 16 fish catchers, you can make ~16 buckets of biodiesel per hour, so 1 biodiesel/hr/catcher.  I haven't used a stevecarts farm for seed oil.

biogas/methane is a different discussion.

**Comment by KorGgenT** [comment]
Waaaait a minute guys, you forget a very important thing: In order to get fish traps to work, you need some sort of automation. Pipes. Hoppers. Workbenches. Dedicated machines. For crops to get seed oil, you aren't going to need nearly as many pipes. I am find with making the fish catcher take steel bars, but i reaaaally think that if you mess with the cost of the recipes of fish, it will force people to never use it again. You also need to remember that you need to make very large farms to get enough fish: yeah, it only takes a few ingots to make 1 fish catcher, but to get any sort of useful amount of fish oil out of it, you're gonna need a hundred.

**Comment by Radst0ne** [comment]
Dont make the trap more expensive, since like @korGgenT said you need a shit ton of them, and it doesnt scale with tiers, if possible just change the drop chance for fish diamonds, etc

**Comment by Ethryan** [comment]
How about making the GT++ Fish Trap be an upgrade of the Harvestcraft fishtrap and include it in the recipe?

**Comment by braeven** [comment]
Remember guys/girls, we are talking about LV-Age, not EV Energy-Needs

@KorGgenT you really don't need much infastructure to currently get a good fish farm running
You only need one Transfer node and one World interaction upgrade to make pams fish into vanilla fish(after the update you won't need this step)

Automating the Fish-Farm can be done with some jabba-barrels(collecting unwanted stuff) some Hoppers and One Conveyour and some GT-Pipes or if you are a little more advanced, some eio item pipes

Hoppers are basically only a big amount of iron , not really that expensive

to make a steves Cart farm you need to make: CargoManger, Cart Assembler and the Cart itself, which needs Circuits, a lot of Steel and a lot of crafting

@richardhendricks extracting the oil from fish only takes 0.8 seconds with LV, so one Fluid extrator could process more than 3600 fish in one hour or 144 Buckets of Fish Oil which means you can get more than 512 EU/t  with one extractor

@Ethryan Pam's farm is made with some wood and strings, using it to craft a gt++ one doesn't really do anything


A Fish Catcher will catch something around every 2 Minutes, so one Fish Catcher will give 30 Items/h
let's go with 20 fish/h, since not every catch can be used:
a simple farm with 20 catchers and 30 Hoppers will produce around 400 fish/h or 16Buckets of Oil or 4 Million EU or ~57EU/t
And only 20 usefull fish is calculated pretty low

to double the Amount of EU in this example, you only need 270 Iron for the Hoppers and currently 60 Iron and 40 Wrough Iron for the fish catchers

**Comment by Dream-Master** [comment]
Ok i make the trap more expensive (LV) and we will test it then.

**Comment by richardhendricks** [comment]
Don't forget to process the fishoil into biodiesel you need sodium hydroxide and methanol/ethanol.

**Comment by richardhendricks** [comment]
Hoppers only transfer one item at a time, so they will quickly saturate an item pipe if you keep expanding the number of catchers. 

A stevescarts assembler can be used for many things, so its cost isn't really 100% for this scheme.

The cargo manager is expensive but to autocraft the pam's fish into normal fish would require some sort of automatic crafting setup.   I am unfamiliar with the requirements on the transfer node/world interaction upgrade.  Is that available in LV?
