### ISSUE TITLE
Mercury and bathing with it is extremely slow

### ISSUE THREAD

**Issue by Gemlord** [GTNewHorizons/NewHorizons#2060]
Mercury is used to bathe crushed ores to get silver, platinum and gold, and etc, but it uses a full bucket to do this and all recipes for getting mercury are incredibly slow, as opposed to sodium persulphate which is used in a similar manned for less valuable materials but gives 5x more and far more quickly, so i suggest either the recipes for centrifuging mercury are made faster or that it uses than a full bucket per chemical bath recipe, although not as low as the Sulphate as the mercury byproducts are more valuable.

**Comment by MineAnPlay** [comment]
I don't really think this is needed. Redstone can easily be obtained in very large amounts and there are ways to generate it so over time you will make infinite Mercury. You won't always be using it so it won't be too bad. The reason Sodium Persulfate requires less is because the recipe changed and it's harder to obtain. Though not directly about this but why was the processing times of the Ore Washer and Thermal Centrifuge change to 25s from 20s?

**Comment by Dream-Master** [comment]
Idk not do a change there.

**Comment by Dream-Master** [comment]
So close the issue ?
