### ISSUE TITLE
Drawer + Hopper will lose items

### ISSUE THREAD

**Issue by Gateswong** [GTNewHorizons/NewHorizons#2073]
Version 2.0, on private server.

Items in drawer will be take out until 1 stack remaining while a hopper below in some conditions.

Step to Represent:

- Place a hopper and a drawer on top of it.
- In hopper, make 5 slots "64 cobble stones" "64 cobble stones" "63 cobble stones" "64 cobble stones" "64 cobble stones". (In other words, **doesn't satisfy "all slots are full stack of items"**)
- Put 100 stones into drawer. Then the amount of drawer item will reduce quickly to 64 which is one stack.

Here is a demo video:

https://youtu.be/KnQxg1nkpX8

**Comment by SirAzazel** [comment]
1.7.10 storage drawers have a lot of bugs that will most likely never be fixed due to jaquadro moving to newest versions of MCF.

> There's just a lot that could got wrong in 1.7.10-land.

**Comment by tranceplanet** [comment]
I lost a healing axe and a TiCo shovel to this bug while using the storage drawer -> hopper combination.

However, I managed to do this with vanilla chest + hopper.  Same steps but using a non-stackable item.

Steps to recreate, though fiddly and not guaranteed each time:

1) Setup - Chest -> Hopper -> GT working machine
2) Fill hopper with 4* 64 items that are being used by machine
3) Insert non-stack item into chest and let it drop through hopper
4) Remove non-stack item and place 64 items into hopper
5) Place non-stack item in chest.

Though the item appeared to stay in the chest and I could remove it, it then disappeared from my inventory.  I feel the bug is hopper related.

Interestingly I've had many situations where I've put exact ingredients on to cook using a hopper and later when I check the output I've got what I thought was leftover ingots.  Probably the result of lost input...
