### ISSUE TITLE
Claim Bug

### ISSUE THREAD

**Issue by EmirShen** [GTNewHorizons/NewHorizons#2103]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
nope
#
#### What did you try to do, and what did you expect to happen?
I try claim but nothing happen
#
#### What happend instead? (Attach screenshots if needed)

#

**Comment by Toperoco** [comment]
You'll have to be a bit more specific, how is anyone supposed to help you off of that little info?

**Comment by Bryfer** [comment]
You might need to execute /bq_admin default load.
This should be done after each update.
Since you are playing nope you just need to enable cheats first to be able to execute it in chat.

**Comment by SirAzazel** [comment]
Suggest renaming this to Better Questing Claim Bug
==
@EmirShen make sure you are running bought online minecraft, if you play cracked or offline mode - BQ quests cannot be claimed due to difference in way UUIDs work on online/offline mode.

As Bryfer already said - if you just updated you need to run `/bq_admin default load` to load new quests.

**Comment by Dream-Master** [comment]
@EmirShen When you write issue i need more infos. Did you mean claim rewards or land or anything else?

**Comment by Dream-Master** [comment]
I close this now.
