### ISSUE TITLE
mod: RFtool

### ISSUE THREAD

**Issue by bengenie** [GTNewHorizons/NewHorizons#2110]
I like to have RFtool  that lets anyone make an dimensions that lets anyone control the ore in gregtech. 
It make it easier at end-game tech.

I have not tested this mod.

mod link: https://minecraft.curseforge.com/projects/rftools

also an requires mcjtylib: https://mods.curse.com/mc-mods/minecraft/233105-mcjtylib#t1:other-downloads

**Comment by Bryfer** [comment]
We already have the Deep Dark dimension which seems pretty similar to what you are describing.
its an dimension which has _almost_ all ores available and perfect for quarrys

its available in late/end game of the modpack

**Comment by braeven** [comment]
RFtools offers a lot of interresting items, but we need to break it down in more than just the dimensions:

The Dimensions are only one part of the mod, they need energy to be created, maintained, you need to find the parts to create the dimension. But they would bring in an option to get EVERY ore in huge masses, even ores that are normally not created. Also you can make Dimensions full of EnderDragons or other mobs. This would require a lot of configuring and nerving this Part of the mod. You could even make Dimension made out of titanium-blocks with orbs out of awakened draconium.

RFtools would add an interesting teleport-system, which could be used to make teleports to every Dimension and place, which could be an interresting addition. It even adds personal Teleporters.

It adds it's own auto-crafters,  an elevator-system(with moving platforms), some machines to read machine data and to give out redstone-signals.

it adds a shield-system, which can be used to build mob-traps/protect your base.

it adds it's own version of a mob spawner which requires a mob-syringe, some energy and some matter(actually 2 types, one food-like matter and one mob-specific matter)

There are Builder-Blocks(which can be used as quarry), Exchange-tools and much more


adding this mod to the pack would require a lot of work. You also would add duplicates to allready existing mod-features, that would not be late game, would be really difficult to add this mod to the pack

**Comment by Ethryan** [comment]
Maybe, if dimension building was disabled, if i remember correctly RFTools blacklists all gregtech ores since it's oregen doesn't work with the dimlet system. If you enabled the gregech ores the dimension would spawn a lot of empty ores when you used a gregtech ore dimlet and then laggs the crap out of the server and dies, it's a really nasty world corruption issue with cascading worldgen in the dimlet world (the worldgen continues until the server dies), I had a RFTools dimension thet had a size of 2.6 GB before the server crashed and i was forced to delete that dimension.

I would say to much work to be added and to many exploitable shortcuts without really close fine tuning.

**Comment by Dream-Master** [comment]
I think we not need more mods.
