### ISSUE TITLE
Cetane-Boosted Diesel from Diesel not profit

### ISSUE THREAD

**Issue by Usernm0** [GTNewHorizons/NewHorizons#2136]
#### Which modpack version are you using?
2.0.1.3

We can craft 500 mb Cetane-Boosted Diesel from 1000 mb Diesel in mixer. But if we count, 500 mb Cetane-Boosted Diesel give us 360000 eu, but 1000 mb Diesel give us 400000 eu. 

I suggest to change Cetane-Boosted Diesel output to 1000 mb.

**Comment by braeven** [comment]
It feels more like all Cetan-Variants and their sources need to be looked at:

Currently normal Diesel gives to much EU, compared to Bio-Diesel which only gives 256k EU, normal Diesel gives 480k EU. And compared to Light Fuel which gives 320k EU.

Making Cetan-Diesel out of Bio Diesel currently gives 750mB for 1000mB
Making Cetan-Diesel out of normal Diesel currently gives 500mB for 1000mB
Making Cetan-Diese out of light Fuel currently gives 1000mB for 1000mB

I would suggest to also re-arrange the EU-numbers of normal Diesel/Bio Diesel.

My Suggestion:
Normal Diesel: 400k EU/B(-80k EU)
Bio-Diesel: 300k EU(+44k EU)
Light Fuel: 320k EU(no change)

1B Bio Diesel to 0,85B Cetan Diesel using 17mB Tetranitromethane (around 2,04 more Energy by making it Cetan, down from 2.4 with new Energy-Value for Bio Diesel)
1B Diesel to 1,10B Cetan Diesel using 22mB Tetranitromethane (around 1,98 more Energy by making it Cetan, up from 1.11 with new Energy-Value for Diesel)
1B Light Fuel to 0,85B Cetan Diesel using 17mB Tetranitromethane(around 2.04 more Energy by making it Cetan, down from 2.25)

So you would still get a lot more Energy out of your Fuel by Adding Tetranitromethane which doesn't really need much EU to be made compared to the amounts needed

But we need to remember:
6B Diesel are made out of 5B light Fuel + 1B Heavy, by just using a mixer you make 1,84M EU into 2,4M EU(with new Values), so making Diesel before Cetan is again better than using light Fuel directly(Currently the best way to make Cetan is to use light fuel directly and not to make diesel, since this way you get more energy)

**Comment by Dream-Master** [comment]
Normal Diesel: 400k EU/B(-80k EU)
Bio-Diesel: 300k EU(+44k EU)
Light Fuel: 320k EU(no change)
@braeven so only this change is enough for balancing it well?

**Comment by nikitinalexx** [comment]
Please also count.
I think if we start with the same amount of Oil, it is much more profitable to make Light Fuel and burn it, than make Heavy+Light and then Diesel. So why would anyone make Diesel in this case if he can get more Energy from the same amount of Oil by only making Light Fuel (which also reduces the amount of machines needed).

**Comment by Dream-Master** [comment]
So what you suggest @nikitinalexx  ?

**Comment by Logicus123** [comment]
I think Diesel and all it's variants are well enough balanced already. Every effort of making it even "better balanced" doesn't make much sense, because we have to keep in mind that the current system is very very good balanced and nobody whatsoever has an advantage/disadvantage out of it. Adjusting numbers in this case could even mess with peoples energy setups, because they probably calculated with those numbers. (As we saw in the update where a few machines went from LV->MV or LV->HV (ammonia) so it totally messed with peoples setups)

Suggestion: Don't change the values

What do the others think about it?

**Comment by AlphaApotheosis** [comment]
Don't change the fuel values, this could have unanticipated effects. No reason for that.

However, the recipe for cetane-fueled diesel from diesel should be changed so it produces 1000mB cetene-fueled diesel from 1000 diesel, just like light fuel. This should be the only change required, and would fix the issue.

**Comment by braeven** [comment]
Are you guys kinda blind? I didn't only suggest to change the Burn-Values for these 3, I suggested to also change the amounts of the cetan-diesel you get. And currently they are NOT balanced. But I can see why lowering the Burn-Value of Diesel doesn't work against Light Fuel.

## 1. Currently it's like this:
Bio -> Cetan gives you 211% Energy (256k -> 540k EU)
Diesel -> Cetan gives you 75% Energy (480k -> 360k EU)
Light -> Cetan gives you 225% Energy (320k -> 720k EU)

## 2. Bio compared to regular Diesel
Bio-Diesel is far to weak compared to normal Diesel, remember it's supposed to be a replacement for normal Diesel. But only 256k EU/B compared to 480k EU/B isn't really a replacement. That's why I suggested to pump up Bio-Diesel.

## 3. Making it 1B to 1B
Just making it a 1B -> 1B recipe isn't enough, it would give diesel only 150% Energy(480k -> 720k)
There would still be no reason to make Cetan-Diesel out of normal Diesel when you can just use Light Fuel:

### 3.1 Based on processing Oil without a Distillation-tower:
Oil needed for 6B Diesel: 8.33B (5B light -> 5B Oil, 1B Heavy -> 3.33B Oil)
using these 6B Diesel as Cetan(with 1B to 1B) would give you **4.32kk EU**

Using these 8.33B Oil for only light Fuel -> 8.33B Light
using these 8.33B Light as Cetan would give you **5,997kk EU**


### 3.2 Based on processing raw Oil without a Distillation-tower:
raw Oil needed for 6B Diesel: 16,66B (5B light -> 10B raw Oil, 1B Heavy -> 6.66B raw Oil)

using these 6B Diesel as Cetan(with 1B to 1B) would give you **4.32kk EU**

Using these 16.66B raw Oil for only light Fuel -> 8.33B Light
using these 8.33B Light as Cetan would give you **5.997kk EU**


### 3.3 Based on processing light Oil without a Distillation-tower:
light Oil needed for 6B Diesel: 52,5B (5B light -> 37,5B light Oil, 1B Heavy -> 15B light Oil)

using these 6B Diesel as Cetan(with 1B to 1B) would give you **4.32kk EU**

Using these 52,5B light Oil for only light Fuel -> 7B Light
using these 7B Light as Cetan would give you **5.040kk EU**


### 3.4 Based on processing Heavy Oil without a Distillation-tower:
heavy Oil needed for 6B Diesel: 11,51B (5B light -> 11.11B heavy Oil, 1B Heavy -> 0,4B heavy Oil)

using these 6B Diesel as Cetan(with 1B to 1B) would give you **4.32kk EU**

Using these 11.51B heavy Oil for only light Fuel -> 5.18B Light
using these 5.18B Light as Cetan would give you **3.729kk EU**


## 4. Summary about producing Diesel instead of just using light Fuel for Cetan Diesel
So the only case where making Diesel out of Oil for cetan-diesel instead of light fuel would be the better choice is heavy fuel, but normally you would not process the heavy-oil to light fuel directly, you would process it to heavy fuel and then into light fuel:

### 4.1 Breaking Heavy OIL to Light Fuel Using Toluene & 3 Distillerys
1B Heavy Oil -> 2,5B Heavy Fuel -> 1B Toluene -> 1B Light Fuel
compared to:
2.22B Heavy -> 1B Light Fuel

And to be realistic: You would not process Heavy Oil into Heavy Fuel using a distillery, you would build an Distillation-Tower rather quick to break the Heavy Fuel down further, cause you are waisting a lot of ressources you would get out of it.

And Heavy-Oil is the Oil-Variant you can only get after reaching HV, you normally use oilsand or oil-springs for your first Oil.

So just using light Fuel is the way to go in most cases currently.

## 5. So why change the Fuel Variables and the amount of Cetan you get
After my suggested changes, all 3 Variants of making Cetan-Diesel give you around the same boost for Energy total(every option gives around x2 more Energy Total). Making Diesel instead of light fuel into Cetan gives you more Energy total, like it should be. 

### 5.1 About leaving the Burn-Value for Diesel the same
Maybe we can leave the amount of Energy you get from Diesel the same, but we would need to adjust the amounts of Cetan-Diesel you get and pump up Bio-Diesel even more, to balance it. So we would end up with something like this:

## 6. New, but not good looking Suggestion
new Bio-Diesel: 350k EU/B instead of 256k EU/B
1B Bio Diesel to 1B Cetan Diesel using 15mB Tetranitromethane (around 2,06 more Energy by making it Cetan)(new: 350k EU into 720k EU, currently: 256k EU into 540k EU)
1B Diesel to 1,4B Cetan Diesel using 30mB Tetranitromethane (around 2,1 more Energy by making it Cetan)(new: 480k EU into 1008k EU, currently: 480k EU into 360k EU)
1B Light Fuel to 0,85B Cetan Diesel using 15mB Tetranitromethane(around 1,91 more Energy by making it Cetan)(new: 320k EU into 612k EU, currently: 320k EU into 720k EU))

And I really don't like adding a little amount of Tetranitromethane into 1B Diesel to get 1.4B Cetan, but that is the only way to make using Diesel better than using Light Fuel(like I explained further up).

**Comment by Logicus123** [comment]
Diesel is basically 5 buckets light fuel + 1 bucket heavy fuel => 6 buckets diesel
So in your new calculation:
6 buckets diesel -> 8,4 buckets cetane-boosted
Which is basically 5 light fuel + 1 heavy fuel => 8,4 buckets cetane-boosted

But if you convert 6 light fuel into cetane-boosted:
6 buckets light fuel => 5,1 buckets cetane-boosted

Now compare these numbers:
8,4 buckets cetane VS 5,1 buckets cetane JUST BY replacing 1 bucket of light fuel with 1 bucket of heavy fuel.

And that doesn't make sense, because why should you get 3,1 buckets more cetane-boosted just by replacing 1 bucket of light fuel with 1 bucket of heavy fuel

So your changes would make diesel 37% stronger (if you are smart enough to use a mixer to mix 5light + 1 heavy)

To really make sense diesel should only be around 5-10% stronger because mixer + 1 bucket heavy fuel is really easy to make

**Comment by timothy1601** [comment]
Well if you use heavy fuel for the diesel you lose a big chunk of other materials like ethylene or propene so you should at least get more energy out of diesel to cetan than lightfuel. Plus you need HV to get a big amount of heavy fuel so is should be rewarded to power a distillation tower with HV than with MV. So the diesel way for cetan should give atleast 7 buckets. If not than the diesel way is useless and no one will go the step for it, because you waste a big amount of energy in it.

**Comment by braeven** [comment]
@Logicus123 if you had read my explanation, you would understand, WHY I buffed Diesel -> Cetan this much:

Replacing One Bucket of Light Fuel with Heavy Fuel, does make a big change:
Like I showed on 3.1 - 3.3, you need way more Oil to make ONE bucket of Heavy Fuel than to make One Bucket of Light Fuel.

But to repeat myself:
To make 6B Diesel ouf of Oil you need 8,33B Oil
6B Diesel gives you(with 1B to 1B) 4.33kk EU

using these 8.33B Oil to only make Light Oil and this into Cetan would give you currently 5,997kk EU

With my new Values for making Cetan:
6B Diesel -> 8,4B Cetan-> 6.048kk EU
8.33B Light Fuel -> 7,1B Cetan -> 5.112kk EU

which would be 18% more Energy

**Comment by Logicus123** [comment]
Quote:
"heavy Oil needed for 6B Diesel: 11,51B (5B light -> 11.11B heavy Oil, 1B Heavy -> 0,4B heavy Oil)"

But you didn't take into account that you also could make light fuel out of normal oil
Plus the 1B Heavy fuel out of 0,4B Heavy oil

So that means:
To make 6B Diesel out of oil you need 5B Oil + 0,4B heavy oil

That means: 5,4B oil (5 oil, 0,4 heavy) VS 8.333 Buckets oil

So you would get: 8,333B Oil divided by 5,4B Oil  = 54% More Energy Just my Mixing Diesel
(Even more dramatic then my old calculated 37%, because you can get more heavy fuel out of heavy oil)
(Of course it depends how you want to evaluate the worth of 0,4B heavy oil; still: if you make 0,4B heavy oil equivalent to 1B normal oil [which is insane btw] you would still get 37% more energy)

So: By making 5,4B oil VS 8,33B Oil an equivalent only by mixing diesel is just imbalanced

Keep in mind that the energy ratio between cetane and non-cetane-source must not be equally between all three; (This is because the burn value of diesel is very high; in this case 480k; and light fuel very low; in this case 320k). Balancing it would mean to look at ressource input(oil) VS energy ouput PLUS a little bit of 5-7% extra energy for a more complicated energy setup (invest 1 time; benefit 5-7% whole game)

Most of your attempt to balance it, is to look at the ratio cetane : non-cetane-source; But it mostly relies heavely on resource input(oil) and energy output PLUS little bit extra because of a more complicated energy setup (like 5-7% extra for diesel in this case)

Suggestion:
1,1B Cetane for 1B Diesel (10% extra energy for more complicated setup)
1B Cetane for 1B Light Fuel (Same)
1B Cetane for 1B Bio-Diesel (Seems legit, didn't calculate it though)

**Comment by braeven** [comment]
> But you didn't take into account that you also could make light fuel out of normal oil
Plus the 1B Heavy fuel out of 0,4B Heavy oil

If you have multiple different Oil-Sources you could do it this way, but normally you only have one type of Oil-Source and and we are talking about even more machinery, pipes and even more luck needed to do it this way. I think this is more of a way, that most players won't even try to do, cause the effort is way bigger than just progressing with the stuff you have and use them even better(like building a Distillation-Tower instead of prospecting 40 more chunk and building a 5-20 Chunks long pipeline/transport system to get another oil source into your base). It's like skipping Mars, it's possible, but it would take way more Effort than just doing it the normal way.

> So: By making 5,4B oil VS 8,33B Oil an equivalent only by mixing diesel is just imbalanced

It depends on the method/way you use to make the Heavy-Fuel for the Diesel. If you look at it from a perspective like I did before(6B Diesel(out of 8.33B Oil) vs. 8.33B Light Fuel(out of the same oil)) it's just the wrong way to make diesel first and not just use Light Fuel directly. Making Diesel would mean you are loosing a lot of possible energy you could make out of the same input-ressources.

> Keep in mind that the energy ratio between cetane and non-cetane-source must not be equally between all three;

I didn't try to make them all equally, I tried to get Diesel fitting in by still keeping the old ratios(for bio & light Fuel) in mind, but this would have resulted in something like: 2B Cetan out of 1B Diesel. Without nerfing light fuel, it just get's absurd looking at the amounts

> Most of your attempt to balance it, is to look at the ratio cetane : non-cetane-source; But it mostly relies heavely on resource input(oil) and energy output PLUS little bit extra because of a more complicated energy setup (like 5-7% extra for diesel in this case)

it's the only way to balance it, but since there are multiple ways to make light/heavy fuel it's still takes a lot of effort thinking about all possible ways to get it working for every way, It is nearly impossible to get every way fitting with each other, we just have to find the way where most of us can say: it's okay with me

## New Suggestion/Idea
Why is there even a recipe for making Cetan-Diesel out of light Fuel? Why not remove it and force the players to build a Diesel/Bio-Diesel Setup.

This way we don't need to try to Balance Light Fuel and Diesel, we just have to find new working Values for Diesel -> Cetan, Bio-Diesel -> Cetan and a new Value for Bio-Diesel(since only 256K EU vs 480k EU just looks wrong)

So my new Suggestion would be:

> remove the Light-Fuel > Cetan-Diesel recipe
> Pump up Bio-Diesel from 256k EU/B to 350k EU/B(since Bio-Diesel should be stronger compared to Diesel, since it is a replacement)
> 1B Diesel for 1.2B Cetan-Diesel(480K -> 864K, + 80%)
> 1B Bio-Diesel for 1B Cetan-Diesel(350k EU -> 720k EU, +105%)
> both would require 15mB TetraNitroMethane

**Comment by Logicus123** [comment]
The Problem with your suggestion is that it even more messes with peoples energy setups. Imagine we removed lightfuel into cetane recipe. People on servers would scream why the hell would you do something and who is responsibile for such an idea.
If it's a completly new modpack and people had to start a new world it might be a differt story.

See, you think you have to balance "Diesel", because you think people _must_ use it in order to progress. But why? {[We could instead just came up with something like "bio-diesel" -> cetane is not the proper way. Lets make bio-diesel -> mix it with a little bit heavy fuel -> bio-heavy-diesel. AND now we can make that bio-heavy-diesel into cetane. Doesn't make sense right?]}

So the solution isn't removing light fuel into cetane recipe but rather removing Diesel. Which is of course a  bad idea aswell, because it would also mess with peoples energy setups.

If at all: My Suggestion is the same:
1,1B Cetane for 1B Diesel (small buff)
1B Cetane for 1B Light Fuel (same)

**Comment by braeven** [comment]
EVERY Update changes the Modpack, 2.0.0 -> 2.0.x changed the sulfuric-acid recipe, but most people just accepted the change, and reworked their setups to adapt to the change

1.4 to 1.5/2.0 completely changed the whole modpack(Destillation-tower 12 heigh? new cracked recipes?, new circuit recipes?), but the people still adapted

2.0.0 to 2.0.x removed most recipes from the thermic fabricator and moved them into the assembler, but people just adapted.

Your whole argumentation is based on people who are to lazy to look into changes and adapt to them. This isn't an easy Modpack, this Modpack is supposed to be hard and take a lot of effort and time. If you want to build something that doesn't get changed or doesn't need Maintenance for 100 years, you better play Vanilla like Modpacks.

Your Solution is just bad, nobody would still make Diesel if they can just use Light Fuel to get even more Energy(In most setups/cases), Like I showed you more than one time. 

And we don't fuck up their energy systems with my solution, after they rebuilded a small part of their system, they get even get a buff on their energy system.

Removing the Light Fuel into Cetan-Diesel recipe would even make sense, cause it's called Cetan-DIESEL, not Cetan-Light Fuel.

**Comment by Logicus123** [comment]
It's not about lazyness, it's also about fun;
A hard-modpack can be fun, but it's being destroyed if you always have to reconstruct your early game setups and can't go on to new projects.
So tell me why do you want to remove now light fuel into cetane completly (changed your mind in the first post) Something tells me, that you aren't that sure after all whats balanced and what's not, because if you would be, then you would'nt change your balance suggestions 2 times.

**Comment by braeven** [comment]
I changed my Balance-Suggestion cause I found out by looking deeper into it, that there is no easy fix, cause there are way to many ways to get light fuel/diesel and it's just near impossible trying to balance something with that many input and resulting outcomes, when everybody starts crying, cause their way get's nerved while other ways get boosted. 

> A hard-modpack can be fun, but it's being destroyed if you always have to reconstruct your early game setups and can't go on to new projects.

Maybe we should also revert the Biogas-Changes, cause the 1.4 setups have given WAY more Energy, new Biogas just sucks. And maybe revert back to old Nitro-Diesel, it was way easier to make. And maybe we can make charcoal and all metal-ingots in a furnace again. And give us 4 wood plank and 4 sticks again by crafting manually. If you start playing GT with this Attitude, it's just the wrong pack for you.

> Something tells me, that you aren't that sure after all whats balanced and what's not, because if you would be, then you would'nt change your balance suggestions 2 times.

So you're telling me, discussion and taking other peoples opinions into account is a bad thing? So you're telling me, that finding a solution together is the worng way to do things here? Maybe I should get back to my First Suggestion and be a rock hard wall until I get it MY WAY. Ooops but I'm a human able to adapt and take other opinions into account.

And Gregtech is about Rebuilding your setups from time after time, or do you still have your steam machines in use? Do you still use a refinery-setup without a distillation-tower? do you just burn wood and don't make charcoal out of it? Do you still make your circuits in a crafting table?

**Fact is:** if you keep the Light-Fuel recipe, there are just to many Situations, where Diesel isn't anywhere near the way to go, if you can just use Light-Fuel directly(Like I showed multiple times). You just can't find a balance between light Fuel and Diesel with this many ways to get both of them, where one Way isn't OP compared to another way. It doesn't really matter if you buff the diesel or the nerf the light fuel recipe as long as they are basically made with the same raw-materials, you just can't find the point where one way is definitely better than the other way as long as there are 20 other ways to get it done.

**Comment by Logicus123** [comment]
> I changed my Balance-Suggestion cause I found out by looking deeper into it, that there is no easy fix

Fix for what? There is no balancing problem. And that there exists some item/fuel which nobody uses has nothing to do with it. This is because it's often the case that there exists some kind of item which nobody uses. For example there exists so many tinker construct materials which are just outright bad.
Or who uses the pickaxe of the core from thaumcraft if there exists tinkers tools?
Or who uses the ichorium sword?
Who will ever use Epic Ore Washing Machine IV (UMV Voltage)
Or for example: Duranium/Tritanium Turbines if you could use oriharukon (or even vibrant alloy)

So there are many examples that there exists something which isn't used much or never (like diesel) and doesn't affect the gameplay in any way

**Comment by Dream-Master** [comment]
There are recipes in the chemical reactor  with glyceryl trinitrate.

**Comment by richardhendricks** [comment]
It's not a balance problem, but a progression problem. Right now most players who do the math or spend 30 minutes on the discord know that LF is the way to go, and skip making HF and diesel straight to cetane. 

I suggest:
- Remove the LF-> cetane recipe. 
- Make desulfuring HF require MV. 
- swapping the LF/HF production ratios, so LF is more "expensive" with oil than HF. Lower HF to 200k. So swapping to HF production gives 600k vs LF 320K.
- Make mixing diesel MV.  Adjust output vs input ratio so 480K is a very nice boost again in output per unit of starting oil.
- TNM production can stay at MV. A player who doesn't want to deal with it still gets nice EU per oil bucket, but investing in the infrastructure gives a great boost.
- I think biodiesel can stay as-is, or maybe a small boost. It does require significant infrastructure, but once completed is pretty much automated. (I use cetane-boosted biodiesel from fish right now, but will probably add seedoil as well).

This gives new players nice stages to follow
LF -> HF -> diesel -> cetane

vs today which is just
LF -> biodiesel(maybe) -> cetane

**Comment by richardhendricks** [comment]
I also suggest reworking the gas turbine quest so that players know it is not really efficient as a primary power source, and should only be used when you have a byproduct gas to burn (ie, methane during rubber wood centrifuging, multiblock still byproducts, etc).

**Comment by repo-alt** [comment]
As I understand 'diesel' is purely for other mods compatibility, why people are so heated about it. Nobody used it before chemistry update, and nobody I know uses it now, except for rockets, which is just fine.

**Comment by Dream-Master** [comment]
I am working on it

**Comment by Dream-Master** [comment]
I take the idea from @richardhendricks 
![image](https://user-images.githubusercontent.com/2970688/34602668-f326b572-f200-11e7-9b7b-dfdb79e1a57f.png)

**Comment by Dream-Master** [comment]
Cetan = HV

![image](https://user-images.githubusercontent.com/2970688/34602934-141b8fa4-f202-11e7-88cf-092b7c817604.png)
![image](https://user-images.githubusercontent.com/2970688/34602937-19b4804c-f202-11e7-8662-8091a1d50c9f.png)
![image](https://user-images.githubusercontent.com/2970688/34602944-22f7407c-f202-11e7-8417-b905f9a6e5e2.png)
![image](https://user-images.githubusercontent.com/2970688/34602949-2742cf84-f202-11e7-8814-76d9a37b9472.png)
