### ISSUE TITLE
Journeymap version is fairplay

### ISSUE THREAD

**Issue by Ethryan** [GTNewHorizons/NewHorizons#2148]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
My own
#
#### What did you try to do, and what did you expect to happen?
I changed the settings in the config file Journeymap server, and expected the client version to follow what i had put in, instead the only thing that worked was the map, cave mapping that i tried to enable didn't work.
#
#### What happend instead? (Attach screenshots if needed)
Absolutely nothing happened no matter what i set the config to.
#
#### What do you suggest instead/what changes do you propose?
Exchange the fairplay version that is downloaded with the modpack to the unlimited version, witch follows the settings from the server config file.

Link to [Journeymap Editions](http://journeymap.info/Editions).
Link to [Journeymap Download](https://minecraft.curseforge.com/projects/journeymap/files/2367915) page.

**Comment by Bryfer** [comment]
the modpack is supposed to come with the fairplay version

**Comment by Dream-Master** [comment]
If you play sp replace it by your own. If you play on the server cave mapping is disabled anyway.

**Comment by bombcar** [comment]
The default server install of GTNH comes with Journeymap-Fairplay meaning you can't see caves and the nether map is nearly useless. Arguably this is because it's too easy to find lootgames when you can see caves.

However, against a server the client can just modify their jar file ... (not that anyone would EVER do that) and restore the functionality of full edition.

Most servers just install the modpack as is and I suggest the default should be the non-fairplay version.

If this makes early game too easy for some because they go loot game hunting, well those become relatively useless around HV or so.

And if server admins feel strongly they can just swap out and use the other jar. Many who are running their own server won't want it or even know of the option to have a useful minimap in caves/nether.

**Comment by Dream-Master** [comment]
I am against it and even if you ask me I like no map at all. ok maybe a map you need to craft ins use it in high tier maybe a electronic nap like journeymap

**Comment by bombcar** [comment]
Being able to have journeyman features be crafted in at different tiers (get main map and waypoints in steam, MiniMap in LV, and cave-view in HV) would be awesome and real progressive.

Could even have "view mobs/view players" gated to Thaumcraft.

However, such my require negotiating with the Journeymap dev.
