### ISSUE TITLE
Basic Crafting: Motors does not complete

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#216]
Please recheck the condition for *Electric Motor (LV): 0/2* as it does not appear to trigger on crafting the two motors.

**Comment by Namikon** [comment]
Should've worked, but i guess the same happend as for the monitors; Some additional NBT data is stored when you craft those. I switched to NBT independant detection. Please report back if that works, as I can't test quests myself. (Limitation of the edit-mode)

**Comment by Dream-Master** [comment]
@Namikon  is this fixed?

**Comment by Namikon** [comment]
As I wrote, I can't test it myself. Teteros needs to report back if the new settings work as expected

**Comment by Dream-Master** [comment]
I will add lastest hqm file to the Server (next Update) and hope someone can test it.

**Comment by Teteros** [comment]
Tested, but quest does not complete so far.

**Comment by Dream-Master** [comment]
@Namikon 
Is this hard to fix?

**Comment by Namikon** [comment]
No, but since a lot has changed already in the lower tiers, I have to redo most of the quest, that's why I did not fix the motors yet. I will eventually redo the whole book, and just give a quick introduction to the modpack instead of taking the player by hand. Everytime a recipe in the existing tiers (0-3) changes, the quests need to be updated, keep that in mind

**Comment by Dream-Master** [comment]
I like the Quests how they are now. Would be sad if there are missing. It wasn't a urgent call only a question.

**Comment by Namikon** [comment]
New quest-system incoming. The old book is "gone", and peoples quest progression will be reset soon. Therefore: Closed
