### ISSUE TITLE
longer day and night cycle

### ISSUE THREAD

**Issue by Blinzer** [GTNewHorizons/NewHorizons#2161]
#### Which modpack version are you using?

latest

#
#### If in multiplayer; On which server does this happen? 

all servers

#
#### What did you try to do, and what did you expect to happen?

many, many new players tried to play the pack expecting to be able to play the game.

#
#### What happend instead? (Attach screenshots if needed)

new players have a RIDICULOUS time starting off. most of the time they rely on other players to sleep at night, and the day cycle barely gives a new player any time to get a setup because hunger at the start is such a death sentence in the pack. most new players end up digging holes and sitting in them, wasting a whole bunch of time. it's discouraging to new players, makes a lot of them quit, and is not fun. the original day and night cycle was designed in the original minecraft under the assumption you could still see at night and could sprint: if you're going to change the core mechanics, then you have to change the surrounding aspects to be more suitable for your pack as well. there's nothing "hardcore" about sitting a hole and wasting 12 minutes of your life doing nothing, it's just garbage. on top of it, people who aren't new are never affected by this anyways, so it's just a kick in the balls to whoever wants to actually try out the pack and play.

#
#### What do you suggest instead/what changes do you propose?

extend the day and night cycle to be at least 20 minutes each(ideally 30), as opposed to the current 12 minutes. this will give new players a lot more leeway in finding the resources they need to actually survive the first night.

**Comment by Dream-Master** [comment]
@Blinzer 
is there a mod who do it or how we can chnage day/night time length?

**Comment by WarlordWossman** [comment]
Even if I am not effected by the issues new players might have, I agree that a longer day cycle would be nice to have. I guess it will make solar a bit easier to handle since you only have to sleep every 20 minutes then, but not like it was hard to carry a bed around anyways.

In general I just think a longer day cycle would fit the pack well.

**Comment by Methes** [comment]
Just a note:
- 20 or 30 minutes won't make a real difference in letting the new players survive the next night. They need at least armor from infernals to survive running around at night (because of infernals). Even then with just a torch in your hand you can't do much in unknown terrain, not even dodge the dangerous mobs.
- 20 or 30 minutes means they will have to spend EVEN MORE time waiting in the ditch if not enough players sleep the night, so it's actually counter productive.
- almost every night is skipped unless there's too many players. If that's the case, the server starts lagging seriously, often bringing the average TPS to 10, meaning everything timed gets doubled (all your machines get downgraded one tier, fun stuff), so the nights will take not 20 minutes like now, but 40 to 60. Yeah, I wouldn't mess with that.

The only scenario where making the day longer would be beneficial is in singleplayer at the very beginning, where the player doesn't have bed yet so he has to spend those 2 to 3 nights waiting, until he can craft one. Later on you usually play other games while waiting for something to craft/produce/whatever so it's a bit like an introduction to the pack's mechanincs.

I personally think the Hardcore Darkness is dumb and makes the game very ugly (ugly shadows or ugly night vision). Nights outside with sky and artificial light is the visually nicest part of the game and Darkness takes that away. I don't play the pack with it, but that's a different topic.

**Comment by Blinzer** [comment]
dreammmaster, i'm not sure if there's a mod. surely there has to be one though, i'll do some research later or something.

warlord does bring up a point that it is a slight buff to solar panels in that you don't have to actively sleep to reactivate them as frequently, but that's just a nuissance mechanic more than anything.

now for the last guy, let me address in order:

1. 20 or 30 minutes gives a player enough time to find flint, get enough food to survive a night and do basic necessities. unless you're a speedrunner, there is no way you can get food, get flint AND get enough wool to make a bed in time in the current cycle. this is mostly due to not being able to sprint.
2. statistically, players do sleep. the problem is that with more frequent threats of night, a new player is discouraged to travel far out because he's relying on other players to sleep, which means if they need to go out and kill sheep or get a resource but there are none close to them, they can't get to them in time. with an extended cycle, that problem is solved.
3. again, the nights being skipped is not the point. it's the frequency of the nights that becomes annoying when you're trying to get something done outside.

yeah, i suggested this for new players and that's the very thing i said, and it is valid for both single player and multiplayer. for anyone who has a house, it makes little to no difference how long the night is if the day cycle is equally as long. as i said, this is to boost new players without affecting old players, and you're kind of agreeing that this is the case.

i don't like hardcore darkness either, and yeah it's pretty ugly. but i can deal with it, it's mostly just ugly.

**Comment by Blinzer** [comment]
https://mods.curse.com/mc-mods/minecraft/222463-toomuchtime

There is a concern in the bottom, you should probably test it first to make sure it doesn't mess with gregtech ore generation. The guy even sounds like he used it for new horizons, lol.

**Comment by KaneHart** [comment]
Just keep in mind that you will need to test it as well with other planets, and things like orbit / moon phases, etc.

For example:
https://wiki.micdoodle8.com/images/2/23/Moon_Day-Night_Cycle.png

A mod/plugin could have an effect on all of this.

That being said if it is tested well and works out I would personally consider just adding it to my server alone without it even in the pack.

I think it's great on servers. Having to sleep every 12 minutes is kind of annoying as is even for Single Player. It's such an annoying Micro management feature that extending it to say maybe 36 day and 24 Night would be more interesting concept.

**Comment by KaneHart** [comment]
Sadly the Client also Requires the mod:
https://i.imgur.com/U7wkigx.png

**Comment by Blinzer** [comment]
that's a good point kane, i don't know much about outside planets so i don't really know how the day and night cycle of earth could influence them. do you know what kind of importance the cycles have on other planets?

**Comment by Dream-Master** [comment]
Ok i close this now.
