### ISSUE TITLE
coins are completely busted

### ISSUE THREAD

**Issue by Blinzer** [GTNewHorizons/NewHorizons#2163]
#### Which modpack version are you using?

latest

#
#### If in multiplayer; On which server does this happen? 

all servers

#
#### What did you try to do, and what did you expect to happen?

i expected to play the game and have to craft my own LV components

#
#### What happend instead? (Attach screenshots if needed)

i used my 2000000 easy-to-get technician coins to get enough robotic arms to feed africa

#
#### What do you suggest instead/what changes do you propose?

coins as a whole need a rebalance. they are given somewhat randomly and are a renewable resource(due to monster hunting which is suspectible to spawners). either make them a non-renewable resource(aka no repeatable quests to get more coins), or nerf what you can purchase with them.

**Comment by Dream-Master** [comment]
@Blinzer 
make some more explecite suggestions about coins.

**Comment by Bluebine** [comment]
@Dream-Master I'd personally suggest that you can't purchase LV parts until you've reached MV, MV parts at HV, and so on. Since I was at HV when these quests were added, they didn't seem unbalanced to me, but as an LV player I can see how they'd be.

I'd also suggest making every machine crafting part (pumps, pistons, etc. but not the circuit stuff) except for motors cost twice as much, as is it's pretty much not worth buying motors since everything else, which all take motors to craft, are barely any more expensive.

**Comment by Blinzer** [comment]
@Dream-Master There are two approaches that can be made: renewable, and non renewable.

For non-renewable, I don't see a problem with the way it is now. You are granted a specific amount of each coin by completing quests and can cash them in at any point in time to give you a jump start during your progression in the pack, but without making it so the bonus. It simply does not make sense that killing something easy like zombies and skeletons can give you robotic arm/piston/etc, something you need machinery to get the components for. I've unfortunately not gotten past LV in the new version, but once I see later tiers I'll be able to tell you for sure what changes are optimal.

If you want to go down the path of coins being a renewable resource through hunting and other means, I'd say instead of giving materials for LV directly, I'd like to bring in concrete as an example of a resource which can be useful in a different way. Concrete allows you to create roads you walk quickly on, which can be useful to expand your base in a more diverse way than simply handing over machine components. It can also help to create more blast furnaces which produce the steel that the components that are currently offered are made of. Coins should be seen as something that can enhance the player, not carry it.

This is a pretty rushed answer, I'll have to think about it some more. I do think that regardless of which way you choose to go, there is a solution.

**Comment by Ethryan** [comment]
Is there any way we can add gregtech fluids to forestry capsules, and give those instead of ic2 cells?
Right now i am paying for a stack of lubricant just to get the empty cells to use for other fluids.

the forestry capsules are single use, that would be a better thing for something you can buy with coins.
