### ISSUE TITLE
Mars generation

### ISSUE THREAD

**Issue by ko5h** [GTNewHorizons/NewHorizons#2180]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
priv serv

#### What happend instead? (Attach screenshots if needed)

~80% ore on Mars have mix (arsenic.antimony,bismuth)
https://imgur.com/h0KnXmV https://imgur.com/sFuhaaG
confirm in sp

**Comment by richardhendricks** [comment]
Is this a fresh world, ie generated with 2.0.1.3?

**Comment by richardhendricks** [comment]
I don't see any reason why it would happen like that, based on my look at the ore vein definitions.  I'll try a SP world to see what I can find out.  If you could, enable debugOrevein in your gregtech.cfg file, fly to new chunks, and take a look in the gregtech.log file.

**Comment by ko5h** [comment]
@richardhendricks yes..i create new world in sp... /dimensiontp to mars

**Comment by Dr4cos** [comment]
Which modpack version are you using?

2.0.1.3

If in multiplayer; On which server does this happen?

MyFTB

What happend instead? (Attach screenshots if needed)

Have exactly the same problem, most of mars are arsenic antimony and bismuth

**Comment by richardhendricks** [comment]
Okay, I'll try taking a look tonight. Very weird.

**Comment by richardhendricks** [comment]
OK, here's what I can tell.  

It's not using the overworld/nether/twilight forest oregen code, it must be using something separate. 

It does look like the ores are spawning, it's just that bismuth/etc are really really common and are also overlaid or something.  See shot of Electronic Prospector.
![2017-11-08_23 33 37](https://user-images.githubusercontent.com/1214811/32589990-85364794-c4dd-11e7-9df3-a4267fed3636.png)
I will investigate, see if I can determine what's going on.

**Comment by richardhendricks** [comment]
OK it looks like GalacticGreg is responsible for oregen on other planets.

Right now I am looking at worldgen lag on overworld/tf/, this issue will be later.

Ideas

@moronwmachinegun Maybe load up v1.4.1.1 and load into a Mars dimension, see what the ore gen looks like then.
November 9, 2017
moronwmachinegun - Today at 12:00 AM
I think it might be more interesting to remove the bismuth vein, see if the new last vein overspawns.  Or include the veins before and after bismuth, see if it's because it is past 89 oremixes.
Umm think either GT or something has a debug item that will provide that information @moronwmachinegun
just search "debug" in NEI

**Comment by KaneHart** [comment]
Has anyone done any more testing on this issue? We have people going to mars and it's sadly very broken and is making me really sad. One of our users is even going to take a break because of this issue from planets till it works. I fear more and more are going to hit mars soon without any kind of temp fix.

![xztbv5n](https://user-images.githubusercontent.com/425853/32698072-2d77729e-c76c-11e7-92bd-3244c7f6c5f9.png)

and just to confirm it's this bad:
![yb8u36p](https://user-images.githubusercontent.com/425853/32698084-755d3f8a-c76c-11e7-904c-d1a38fdb5fe2.png)

I just checked the next planet Probos same issue:
![x4cb1by](https://user-images.githubusercontent.com/425853/32698116-4110c1ce-c76d-11e7-96ea-a865d847c567.png)

**Comment by Dream-Master** [comment]
@richardhendricks let me know when your fix/change orgen code is done.

**Comment by richardhendricks** [comment]
I have root caused issue in GalacticGreg oregen.  Looking at fixes.

**Comment by richardhendricks** [comment]
Example of current oregen
![2017-11-24_14 22 32](https://user-images.githubusercontent.com/1214811/33223202-07ef3104-d123-11e7-9a1b-4022e56ab0ec.png)

**Comment by richardhendricks** [comment]
Example with fix:
![2017-11-24_14 33 45](https://user-images.githubusercontent.com/1214811/33223384-80dd96e0-d124-11e7-93f3-f5815ce2b0d0.png)

**Comment by richardhendricks** [comment]
Please note I am not chunkifying mars generation, chunks seem to be fast enough.

**Comment by richardhendricks** [comment]
Pull request filed.

**Comment by richardhendricks** [comment]
For those desperate for a fix before the PR is approved and published.

[GalacticGreg-1.7.10-0.9.6.zip](https://github.com/GTNewHorizons/NewHorizons/files/1502546/GalacticGreg-1.7.10-0.9.6.zip)

Standard disclaimers apply.

**Comment by repo-alt** [comment]
@richardhendricks 
I can't say I understand the oregen code well enough, but what was the reason for the arsenic/bismuth abundance? Looks like Generate_OreVeins did not change for at least 2 years (when the sources were published), and in the previous modpack version (1.4.*) Mars oregen looked normal, so, obviuously something has changed.

**Comment by richardhendricks** [comment]
Basically, all oreveins are mixed together into one giant list.  Let's say we have 5 oreveins, that look like this.

O1
O2
M3
O4
O5

In this case, there is only one valid Mars vein, and 4 valid Overworld veins. The way orevein selection works, it  picks a totally random orevein.  So, let's say it picks O2 while on Mars.  Because of this bug, when it could not place a vein, it tries the next one in the list.  so M3 would actually get placed. If it chose O4, it would fall off the end of the list, and try another round of the RNG. 

What was happening was something like this.

Old

O1
O2
M3
O4
O5
O6
O7
O8

New
O1
O2
M3
O4
O5
O6
O7
O8
M9

So with this, in the old setup, any RNG of O5-O8 would fall off the list and try again.

With the new setup, any RNG of O5-M9 would end up at M9, skewing the oreveins heavily to M9. 

With my proposed fix, it will immediately re-roll the RNG if it does not find a dimension-appropriate orevein.

**Comment by richardhendricks** [comment]
It's a little more complex than this because oreveins are actually weighted, but that is the general picture.

One side effect of the bug is that each orevein's weight is actually the "sum" of all the incorrect dimensional weights above it.  Using the new example above, with example weights:

New
O1  - 160
O2 - 40
M3 - 80
O4 - 80
O5 - 80
O6 - 120
O7 - 40
O8 - 20
M9 - 20

So, M3 is supposed to be twice as frequent at M9, 40 vs 20.  But because of the bug, in reality it was 160+40+80 = 280 vs 80+80+120+40+20+20 = 360.

And if a new orevein, M10 @ 120 is added, then it gets really skewed, with 280 vs 360 vs 120.

**Comment by repo-alt** [comment]
Oh, I see, I didn't realize the vein list is global, thanks for the explanation.

**Comment by Dream-Master** [comment]
@richardhendricks fixed ?

**Comment by KaneHart** [comment]
Pretty sure it's fixed but im not a 100% sure. I think he figured out what was causing at least for this one.

**Comment by richardhendricks** [comment]
Yes, this should fix the issue with incorrect oregen.  Recommend regenerating any planets.  Ratios of all ores will be correct now.
