### ISSUE TITLE
Gunpowder

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#220]
As far as i've seen, there are 3 ways at the moment to get Gunpowder, which you need a ton of for all the GalactiCraft rockets:
- Creeper-Farm
- Bees
- Mixing Saltpeter/Sulfur/Coal

Creeper farm can be a problem, due the terrain damage they do. And if they're infernal, hooray..

Bees, a neat way if you manage to breed them, but very time consuming and really not for everyone. (At least not before you reach gendustry)

Mixing Saltpeter/Sulfur/Coal
Probably the best way, however, we don't have saltpeter spawn in the world. Railcraft saltpeter is disabled, and we don't have a gregtech vein for it, only small ores. 

So it sums up to only 2 possible ways to get Gunpowder: Creeper farm and Bees.
I need 32 industrial TNT at the moment for something easy to craft, and I somehow have problems getting it. Maybe we should look into that..?

**Comment by Dream-Master** [comment]
Maybe have to add some salpeter inside a vein

**Comment by UltraPeeks** [comment]
You can make Salpeter from Potassium, Nitrogen and Oxygen. There is a broad range of sources like Enderpearls and Rocksalt for Potassium and you can get the rest literally from thin air.
2 Rocksalt ores make 2 Potassium dusts which is enough for 10 Salpeter to make 15 Gunpowder

**Comment by Namikon** [comment]
Well, I only listed possible "good" sources of saltpeter, the distillery requires 8 seconds to produce 21mb Oxygen, and to get air in your machine, you have to use the compressor/fluid canning machine. If you forget about the time and energy to compress empty cells to compressed air cells to get "air" in the distillery, you have to spent:

- 131.282 EU (32 EU/t) and 205 seconds for 2 Nitrogen cells (from air) 
- 1.950.476 EU (128EU/t) and 761 seconds for 2 Oxygen cells (from air)

So in total, 5 saltpeter require about 2 Million EU, just for the distillery. I don't think this is something anybody would build before he has some really really good power source and no idea where to put all the power.

You could, however, use sand (SiO2) for Oxygen, which would lower the power cost damatically. But I still think that this is a setup for mid/lategame when you have automation going (and chunkloaders!).

**Comment by Dream-Master** [comment]
The Salpeter Recipes I disable because unrealistic.

**Comment by UltraPeeks** [comment]
I heard Drobac talking about an Enderpearl farm. I hope this wasn't his main intention...

**Comment by Dream-Master** [comment]
I will add some Machine recipes back. Any Ideas?

**Comment by Drobac** [comment]
i got bees for gunpowdet :)

**Comment by UltraPeeks** [comment]
I have some ideas for a mid-/lategame recipes for the chemical reactor. I did some research so the recipes are kinda realistic. It's rather complicated but would reduce energy and time costs.

We would need 3 new materials: 
* [Potassium Hydroxide](https://en.wikipedia.org/wiki/Potassium_nitrate) (KOH) a white dust
* [Nitric Acid](https://en.wikipedia.org/wiki/Nitric_acid) (HNO3) light yellow liquid
* [Ammonia](https://en.wikipedia.org/wiki/Ammonia) (NH3) colorless gas (optional)

Recipes:
* Chemical Reactor: 2 Rock Salt (KCl) + 3 H2O -> 3 KOH + 1 H + 1 Cl (20s 92EU/t -> 36800 EU)

This is the realistic recipe but is hard to implement because the Electrolyzer has no second input and the Chemical Reactor has only two output slots. Maybe there is a way to add it to a different machine?
* Alternative: 1 K + 3 H2O -> 3 KOH + 1 H (If both recipes are possible this should use more energy)
* Chemical Reactor: 6 NO2 + 3 H2O + 1 O -> 10 HNO3 (10s 24EU/t -> 4800 EU)
* Chemical Reactor: 3 KOH + 5 HNO3 -> 5 KNO3 + 3 H2O (2s 8EU/t -> 320 EU)

The last reaction is very exothermic. We could maybe give some energy back in the form of steam or H instead of water.

Then I think we need another way to get Nitrogen from air. I used the [Haber Process](https://en.wikipedia.org/wiki/Haber_process) as inspiration:

* Chemical Reactor: 1 Compressed Air + 3 H -> 4 NH3 (10s 24EU/t -> 4800 EU)
* Chemical Reactor: 8 NH3 + 7 O -> 6 NO2 + 9 H2O (10s 8EU/t -> 1600 EU)
* Chemical Reactor: 8 NH3 + 3 Compressed Air -> 2 N + 9 H2O (5s 8EU/t -> 800 EU)

Energy and time values are just estimates. I'll do some math next.

**Comment by Dream-Master** [comment]
I be back home soon maybe we can talk about a solution.

**Comment by Dream-Master** [comment]
Added Potassium Hydroxide Dust and Nitric Acid as Fluid in the Core Mod

**Comment by Dream-Master** [comment]
added Recipes in the next update
