### ISSUE TITLE
Suggestion: Add water generation for MV/HV

### ISSUE THREAD

**Issue by Bluebine** [GTNewHorizons/NewHorizons#2210]
So once you get to the steam age you can build a water tank, and once you hit EV and get titanium you can  get infinite water, but until then there's not really any better renewable sources of water. If possible, I'd suggest a machine that uses small amounts of power (maybe 5-10k EU per bucket, since a bucket of water makes ~60k EU when made into steam and put into a turbine) to make water, but makes it rapidly enough to easily power a large boiler or two, or maybe a large multiblock, like the water tank but bigger and more expensive, that generates water passively but faster than the water tank.
If you don't want to add any new machines for water generation, making the Remote IO water reservoir craftable at either MV or HV would help with the water gen.

**Comment by Bryfer** [comment]
Did you know that the Large turbine outputs distilled water which can then be re-used in the large boiler?- however this does not solve this issue since it available around HV-EV tier 

There is already some alternatives early game to get renewable water. the easiest one is to make multiple railcraft water tanks, as OP mentioned. but here is a few more easy alternatives
Snow
![image](https://user-images.githubusercontent.com/22825059/33192000-58a0a858-d0bf-11e7-83df-e8a22cc9cbe3.png)
Cacti
![image](https://user-images.githubusercontent.com/22825059/33192007-636d935e-d0bf-11e7-86dc-d82daac48048.png)

**Comment by Radst0ne** [comment]
Im pretty sure the reservoir (enderio) is hv

**Comment by Methes** [comment]
Also to get a nice speed (1B/sec) even for 5k EU means 250EU/t, no thanks. Reservoir at HV is plenty usually.

**Comment by Bluebine** [comment]
Oh, didn't even realize the enderIO reservoir existed until you mentioned it.
A quest telling you to craft it to help with water issues would be nice, just put it right after the quest for making stainless steel.

**Comment by AlphaApotheosis** [comment]
Possible to make the Thaumcraft Thirsty Tank at MV, this will provide infinite water as well, though less than the reservoir.

**Comment by Dream-Master** [comment]
It is HV
![image](https://user-images.githubusercontent.com/2970688/33426083-f6cd7f32-d5c0-11e7-907a-ef83ffbc75a6.png)
