### ISSUE TITLE
[suggestion] Bronze age GT ore finder tool

### ISSUE THREAD

**Issue by EnnekPL** [GTNewHorizons/NewHorizons#2226]
Hi! All i want to say about suggestion is in video
[Video](https://www.youtube.com/watch?v=U2LsttUgYO0)
and sorry for may English,it's first time when i record in english.

**Comment by richardhendricks** [comment]
I like the idea, but I think some tweaks are needed.

- Make it use dusts instead of ores. 
- Only work for copper/tin/iron/redstone/lapis dusts
- Increase copper/tin small ores in the mountains. Y heights are OK, but increase amounts to 128 or so, enough that it is reasonable to find with a flint pickaxe or just by walking up and down the mountainside.
- The dust will find any of the ores that contain it.  Specifically, tin -> tin ore, cassiterite, cassiterite gravel. copper -> copper ore, malachite ore, chalcopyrite ore. redstone -> redstone ore. lapis -> lapis ore. Iron -> Magnetite, mineral sands, pyrite.

Players will still have to search for other overworld veins, but by that time they will have better tools that can mine faster than flint. 

Looking at other Overworld veins:
Vanadium/Gold - Super common, found with iron
Salts - Must be searched, but fairly shallow heights, 50-70
Soapstone - Uncommon. Must be searched. Pentadalite is a source of nickel, but can be found separately in the TF. Low usage
Diamond -  Uncommon. Must be searched. Could be dug out horizontally if a fast pickaxe is available. Alternative sources available such as small ores, fish catchers, or bees.
Apatite - Fairly uncommon. Must be searched. Not necessary until higher tiers.
Oilsands - Who cares?
Mineral Sands - Common. Found with iron
Manganese - Rare. Manganese needed later on, easily can be searched by digging horizontal shafts at high speed.
Mica - Rare. Not needed until later on, easily can be searched by digging horizontal shafts at high speed.
Dolomite - ???

**Comment by richardhendricks** [comment]
Also, be sure to read <https://gtnh.miraheze.org/wiki/Ore_Generation> especially the Efficient Mining section.

With the new oregen, there will be many less empty oreveins. Even so, I estimate 1% of players will need to search at least 56 centers to find casseterite sands for tin, so this tool will still be very useful for them.

**Comment by richardhendricks** [comment]
Flying around some mountains, I could find a few small Copper ores here and there.  I couldn't see any Tin ores, probably because they are really hard to see?

I think this tool could be very useful for players.  Recommend adding some in village smithy and dungeon chests if it is added.

**Comment by Dream-Master** [comment]
Mod is ready and i test it rn.

**Comment by richardhendricks** [comment]
Can PM me a copy? I'd like to check it out. Are you going to use it as-is, where people have to find the ores first, or my suggestion that dusts gathered with small ores work as well?

**Comment by Dream-Master** [comment]
Yes I can link it

**Comment by EnnekPL** [comment]
i will try with dusts suggestion

**Comment by Dream-Master** [comment]
Cool

**Comment by Dream-Master** [comment]
[IFU-0.8.zip](https://github.com/GTNewHorizons/NewHorizons/files/1521284/IFU-0.8.zip)

**Comment by richardhendricks** [comment]
Will test this week.

**Comment by richardhendricks** [comment]
Okay, here are my comments after testing.

- Add a sound effect.  Maybe take a stick and wobble it rapidly to make a sound recording.  Too easy to pay attention to walking/running and not the stick.
- I am not sure on the tools/ring requirements. Hammer requires 6 iron to make, and can't be made with copper, so you have to find iron.  Although it will be pretty common now!  Along with copper too, since it is in a couple of frequent veins. So maybe not a big deal anyways.
- Change requirements from bronze to just plain copper.  Small tin is really really hard to see.  I had to spawn some in to actually see what it looks like, and tin and small iron ores are basically invisible on the BoP mountains that are a mix of stone and cobble.
- Don't worry about making it break.
- Dusts definitely need to find the primary ores.
- Also, it doesn't work with cassiterite sand.

**Comment by Dream-Master** [comment]
[IFU-0.9.zip](https://github.com/GTNewHorizons/NewHorizons/files/1540149/IFU-0.9.zip)

**Comment by Dream-Master** [comment]
dust suggestion is working
woble sound is added

**Comment by richardhendricks** [comment]
@EnnekPL What will the license terms for the mod be? Will it be open source?

**Comment by richardhendricks** [comment]
Wobble sound is perfect, nice and subtle, can be heard even when raining.

I could not get dusts to work, which did you try?

I was over brown limonite, tried brown limonite dust and iron dust.

Over cassiterite sand, tried cassiterite dust, cassiterite sand dust, tin dust.

Could only detect with actual ores.

Also, one other problem - tool does not detect GT ores until after they become blocks.  By default they are tile entities and only turn into blocks when the object next to them updates.  To demonstrate, place ore item into detector, then delete blocks using COFH commands (COFH clearblocks command does not do block update)

/cofh clearblocks <playername> 150 200 150 gravel *sand *dirt *stone *fluid *plant sandstone clay

wait for blocks to delete then fly around with electronic prospector and compare against effect.

Cassiterite Sand vein
![2017-12-09_22 27 40](https://user-images.githubusercontent.com/1214811/33801923-407058a0-dd30-11e7-8437-1e5529ce97d9.png)

Visually:
![2017-12-09_22 28 35](https://user-images.githubusercontent.com/1214811/33801926-4e400fc0-dd30-11e7-9f01-e0297516fcfb.png)

After placing torch to force block update:
![2017-12-09_22 29 30](https://user-images.githubusercontent.com/1214811/33801929-79a179f6-dd30-11e7-9315-5a39bc3fbdfb.png)

**Comment by richardhendricks** [comment]
Also, I assume this is a client-side mod? So should not affect server TPS when in use?

**Comment by EnnekPL** [comment]
Yes it will be open source mod so anybody can change anything.
[How dust work](https://www.youtube.com/watch?v=FNhEBHeHK3E)

**Comment by EnnekPL** [comment]
for now I figure out what's hapen because once work correct other time as you present

**Comment by richardhendricks** [comment]
Thank you for your contribution.  We will be updating the mod to meet our needs.

**Comment by richardhendricks** [comment]
Orefinder has been updated to work server-side to detect unexposed GT ores.
