### ISSUE TITLE
Wood fence\wood slab issues

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#2259]
#### Which modpack version are you using?
Delta one
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
i'm trying to craft wood fence from jungle wood, to use it in craftings recipes further(for piston, if u interested). As NEI says, the recipy is this: 
![2017-12-13_15 45 37](https://user-images.githubusercontent.com/25028786/33939643-03279b76-e01d-11e7-9114-8527533d484d.png)
but instead of normal fence crafting result is this:
![2017-12-13_15 45 43](https://user-images.githubusercontent.com/25028786/33939667-11ad4a42-e01d-11e7-96b7-cbbe498c6ea9.png)
This item can't be used in any crafts involved fence, except of some tinker constuct recipe.

Suggestion: remove this slabs from game, or add them as fences in dictionary, or don't allow them to work with vanilla trees.

**Comment by WarlordWossman** [comment]
Yeah this has been an issue for a while now. Almost every youtuber runs into this issue when crafting the fences for either the bed or the piston.
I can see how it's a bit weird with the differnent wood types, but maybe we should just make all these recipes give you vanilla fences and you can chisel them after. Would def remove some clutter and result in less confused people since we the pack normally gives you options to use equal materials like sand vs red sand for example!

**Comment by Anarack** [comment]
Or have a recipe to convert them into standard fences from whatever they are registered as.

**Comment by LOKKO12** [comment]
@Cinobi try to put them in name remover....

**Comment by codewarrior0** [comment]
It looks like the recipes for Birch, Spruce, Jungle, Acacia, Dark Oak fences are straight up wrong.

**Comment by Dream-Master** [comment]
we closing it when the release is done.
