### ISSUE TITLE
Power Station Control Node (Added by: Alkalus - [GT++]) currently not working in MP

### ISSUE THREAD

**Issue by Dacer1** [GTNewHorizons/NewHorizons#2268]
Which modpack version are you using?

2.0.1.3

If in multiplayer; On which server does this happen? 

MyFTB-Network
Server 1

What did you try to do, and what did you expect to happen?

Building a Power Station Control Node (1949:812)
Expecting it to form a Multiblock automatically just like in singleplayer.

What happend instead? (Attach screenshots if needed)

1.The Multiblock didn't form although every needed block was placed (Exactly the same way like in singleplayer where it actually worked)

2.Also after placing the multiblock controller the sprite on the block changed to the "active" one although the Multiblock wasn't even finished.

3.Another issue is some sort of bugged inventory after right clicking on a placed controller. Shortly after doing that blocks cannot be broken properly or placed.

What do you suggest instead/what changes do you propose?

I actually have no idea.

**Comment by Dream-Master** [comment]
@Dacer1 wait for version 2.0.2.0 and test if it work there.

**Comment by Lithorn** [comment]
Helpful update. In 2.0.1.3 this works fine. The station misses listing that it needs a muffler on top center. Thats why it will not form. No clue why it needs busses. 

The real bug is that no matter how fast power comes in, power is only output per 1 dynamo at 1 pulse of power every 6 seconds or so. I fed mine with 8 IV solars, and stuck 1 EV Dynamo and it was feeding power soooo slow.

**Comment by Dream-Master** [comment]
@Dacer1 did you report it on Gt++ side ?
