### ISSUE TITLE
Add Properties to Fluids 

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#227]
Adding Properties to Fluids
Like the can' t be placed in the world
Are Gases
Have special effects like poisons or other potion effects
have different temperatures (like the Plasma 10000 K)

**Comment by Namikon** [comment]
Not placeable: Easy to do
Special effects: Not as trivial as the first one, but possible

Gases and Temperature is a problem; as there are no "Gases", only liquids. You can register new fluids in Gregtech, but as you can't add a new material, it will automatically be used in machines.
For example: I registered a new gas, with temperature 1500k and material "Oxygen", and it automatically got registered in the Arc Furnace as valid "oxygen".

Temperature is a Gregtech thing, which will be difficult/impossible to set if the fluid is not registered by GT, at least from what i've seen so far

**Comment by Dream-Master** [comment]
Ok with the gas I mean that is is in the title like Greg did it. We don't need gases in the world placeable. Only the option that you can place it or not. Properties like effects would be nice.

**Comment by Namikon** [comment]
There is a forge-setting for "gaseous" and temperature, but it seems that it does nothing at all, and is not picked up by gregtech in any way. See the latest commit to the CoreMod for some "more advanced" example of fluid registration. At least buckets can be disabled, and your fluid can glow (yay..)

In order to just register fluids (Without blocks), I have to find a new way, and will probably be added as a new Fluid enum. This will take some time to do.

About the effects for fluid pools; maybe this weekend

**Comment by Namikon** [comment]
See commit
GTNewHorizons/NewHorizonsCoreMod@97ad081ef4aeed61d66b3027db20ec19e36c37a8
Things left: Register fluids without the ability to place it in the world and temperature/gas-settings.
Latter is depending on Gregtech (as discussed on teamspeak), and the first one can be done, but needs more time, as I probably have to add a new class and a new registration way just for that.

But as I have other projects open with work to do, I'll probably not do anything for the remaining two features in the near future, as it won't break anything if you can place a fluid in the world. I need to finish GalacticGreg so that we can go public with that

**Comment by Dream-Master** [comment]
So far it  works. if we need more advanced Fluids we have to open an new Issue.
