### ISSUE TITLE
Tinkers Lumber Axe issue with Forestry Trees

### ISSUE THREAD

**Issue by Gateswong** [GTNewHorizons/NewHorizons#2276]
Version 2.0.1.3

If a forestry trees grows it's own wood, cutting down it with lumber axe will only drop 1 wood.

If grows vanilla woods (oak, brich etc.), it works normally.

**Comment by Gateswong** [comment]
Found this issue with Larch and Lime wood.

**Comment by Dream-Master** [comment]
Not sure what i can do here. Forestry allready not dveloping any 1.7.10 version i guess.
if we dont do a fix  who elese?
@richardhendricks @mitchej123 is this fixable ?

**Comment by richardhendricks** [comment]
Code for TC seems fairly straightforward
https://github.com/GTNewHorizons/TinkersConstruct/blob/1.7.10/src/main/java/tconstruct/items/tools/LumberAxe.java

onBlockStartBreak could be a problem if the forestry wood is not detected as wood, but it should be OK since they are oredicted?

detectTree looks a little hinky.  Need to look at forestry tree to see how it generates the trees. It may be that detectTree is not properly seeing the forestry leaf blocks, might need to oredict forestry leaf blocks to allow matching.

**Comment by Dream-Master** [comment]
@richardhendricks did you need i pull Forestry to GTNH ?

**Comment by richardhendricks** [comment]
Not yet, lets take a look at their leaf blocks first, maybe we can do it
with just an oredict.

**Comment by mitchej123** [comment]
I can't tell if the bug was in TCon, or Forestry; but I backported the lumberaxe code from master on TCon and got it working, so ¯\_(ツ)_/¯
