### ISSUE TITLE
Molten Plastic

### ISSUE THREAD

**Issue by Radst0ne** [GTNewHorizons/NewHorizons#2311]
#### Which modpack version are you using?
2.0.2.5
#

#### What did you try to do, and what did you expect to happen?
Tried to pick up molten plastic (polyethylene) out of a tank with a normal cell
#
#### What happend instead? (Attach screenshots if needed)
Cell didnt fill up
#
Edit: you also cant empty universal cells that are not 100% filled

**Comment by Dream-Master** [comment]
This issue is very old. All molten materials act like that sadly.
@Technus we need a fix here.

**Comment by Dream-Master** [comment]
[Quest] Molten Polyethylene #2009

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/1891

**Comment by Radst0ne** [comment]
wait what? im pretty sure it worked before

**Comment by Technus** [comment]
**Molten stuff has no cells:**
- it is not meant to be put into cells 
- this would conflict in some cases with dust cells 
(like the ones used some time ago in naquadah reactors). 

Fixing that would break compatibility and other shit. 

**Explicitly added Fluid materials:**
- should have fluid filled cells. (since they have no dust form)

**The way to handle molten fluids:** 
- use fluid solidifiers/ fluid extractors and store the molten stuff as ingots/nuggets etc.
- that is even more convienient since the amount of stuff you get from inots is not going to be easly dividable by 1000.

**Comment by Technus** [comment]
Reopen of the only liquid materials have no cells.

**Comment by Technus** [comment]
@Dream-Master as for quests - use GT cells when applicable or just give out ingots... if no cells exist

**Comment by Technus** [comment]
Edit: you also cant empty universal cells that are not 100% filled - intended

you can empty them tho in non GT machines like rc tanks/ bc tanks?/EnderIO tanks

**Comment by Technus** [comment]
@Radst0ne ^

**Comment by Radst0ne** [comment]
Thats what Inmeant, you cant empty then in a bc tank at least filled with Polyethylen
