### ISSUE TITLE
Buildcraft Items and Blocks

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#232]
Are there Blocks and Items in Buildcraft we need ? like the Robots .....

I will not enable the Item and the fluid pipes we have Gt for that. Only the Kinesis Pipes recipes i will change a bit.

**Comment by Namikon** [comment]
Open computers has a very complex robot system, and by "very complex" I mean that not only the crafting is difficult, you have to write lua code in order to tell the robots what to do. But if you manage to do that, these robots can do almost anything a player could do. (or more, it really depends on your coding skills) 

From what I've seen, Buildcraft robots could be a beginners mod for robots. However, they are designed to work with  pipe gates, and fluid / item pipes from BC, so it has to be tested first if you can get them to work at all, or if a major part of functionality would be missing.

**Comment by Dream-Master** [comment]
Ok maybe we let out the Robot section because of the Pipes but there other Things we could need. Atm we can use only the Tank, Kinesis Pipes, Auto Working Bench and some Pipes with a special function (Void Pipes). Any Suggestion?
