### ISSUE TITLE
Issue with some GT items name

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#2325]
#### Which modpack version are you using?
2.0.2.5
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I scanned item for getting the wetware mainframe recipe and I also used electric prospector's scanner (zpm)  
#
#### What happend instead? (Attach screenshots if needed)
Instead of having real name of items i got %material
![2017-12-29_17 19 31](https://user-images.githubusercontent.com/12850933/34441604-23a9b508-ecbd-11e7-8334-6da80fec0125.png)
![2017-12-29_17 19 43](https://user-images.githubusercontent.com/12850933/34441610-2a077430-ecbd-11e7-8108-0fb8148d9684.png)
![2017-12-29_17 19 48](https://user-images.githubusercontent.com/12850933/34441612-2b6f2dfe-ecbd-11e7-9c24-9067232b6aad.png)
![2017-12-29_17 19 50](https://user-images.githubusercontent.com/12850933/34441613-2cc8386c-ecbd-11e7-9a79-07068f4bd7a0.png)

**Comment by Dream-Master** [comment]
@boubou19  Please test with new relase 2.0.2.6 when it is out. Thanks

**Comment by Dream-Master** [comment]
Not worked in 2.0.2.6
@Ethryan any idea?

**Comment by Ethryan** [comment]
No, i went through the code and looked at where it gets the ore name, it imports it from [GT_LanguageManager.java](https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/util/GT_LanguageManager.java), honestly it looks more like something is wrong with GT5-Unofficial since it seems to affect the gregtech scanner and not just the Prospector's Scanner.

**Comment by Dream-Master** [comment]
Aniflux make a change.
