### ISSUE TITLE
Changing the new storage component recipe back to pre 1.5/2.0 recipe.

### ISSUE THREAD

**Issue by jiamingc0824** [GTNewHorizons/NewHorizons#2333]
#### Which modpack version are you using?
2.0.2.5
#### If in multiplayer; On which server does this happen? 
-
#### What did you try to do, and what did you expect to happen?
-
#### What happend instead? (Attach screenshots if needed)
The current recipe for storage component (both liquid and item) takes
1k -> LV
4k -> MV
16k ->HV
64k ->EV
256k -> IV
1024k -> LuV
4096k -> UV
16384k -> MAX
#### What do you suggest instead/what changes do you propose?
Change the AE storage component (both liquid and item) to the old circuits recipe.
1k -> ULV (Maybe Vacuum tube)
4k -> LV
16k -> MV
64k -> HV
256k -> EV
1024k -> LuV
4096k -> UV
16384k -> MAX

Considering how expensive cirucit is now, the storage component is way more expensive than it should be after the circuit overhaul and even worse, changing the 1k component to take LV circuit, 4k component to take MV circuit and so on. Each higher tier storage component also takes 4 of the lower tier. For example, 1 16384k storage compoent would take 16384 1ks to craft and that takes 65536 LV circuit, 16384 MV circuit and so on which a little bit ridiculous when u need 10 of the 16384k to craft 1 infinity chest.  So, I suggest that changing the circuit to as above would be more reasonable.

**Comment by benstuwie** [comment]
Or just lower the infinity chest to only take 1 of them. That's reasonable to craft, hell even 5 is fine. If my math was right and the 10 16384ks cost 2.5M copper, then I think it's just fine overall :/
Excluding the infinity chest, I feel like the storage components are balanced. Even maybe the infinity chest, if it takes  2.5M copper

**Comment by jiamingc0824** [comment]
I think infinity chest recipe is fine as it is, its just the circuit being expensive and causes the storage component to be unreasonably expensive as you go higher tier and changing it to use LV circuit on 1k storage compoent made it even more unreasonably expensive than it should be.

**Comment by benstuwie** [comment]
I mean I think the components are fine as they are, even when it comes to the infinity chest. They aren't too expensive, but they're still reasonable

**Comment by jiamingc0824** [comment]
>I mean I think the components are fine as they are, even when it comes to the infinity chest. They aren't too expensive, but they're still reasonable 

Have you played pre 1.5/2.0?? The recipe currently is not simply just increase the amount of circuit or resources consumed by 4x compared to pre 1.5/2.0 because of the change of 1k component to take LV circuit.

**Comment by benstuwie** [comment]
Yea, I've been playing since 1.2. It was a little annoying to make the in pre 2.0, but I made 30 4ks the first time I made any. Making the 1ks harder would have probably made me make 1ks instead

**Comment by jiamingc0824** [comment]
>Yea, I've been playing since 1.2. It was a little annoying to make the in pre 2.0, but I made 30 4ks the first time I made any. Making the 1ks harder would have probably made me make 1ks instead

If you've played since 1.2, you should know how much more expensive it have been after the changes in circuit and changing 1k to use LV instead of NAND chips / any ULV equivalent circuit. Futhermore, asking for 10 16384k for 1 infinity chest is fine but asking for 2.5M copper just for the 10 storage component is not reasonable which leads me to think that instead of changing the recipe infinity chest, the storage component of lower tiers one (1k ~ 64k) should be changed to the old recipe circuit types (ULV -> LV -> MV -> HV).

**Comment by benstuwie** [comment]
The infinity chest is extremely over powered though. I'd gladly dump 2.5M copper into it. I know the recipe got more expencive, but I kind of like that.

**Comment by Dream-Master** [comment]
Ok i will look about the storage upgrade recipes. Infinity chest stay like it is.

**Comment by benstuwie** [comment]
If you change the recipe for the component, you change the recipe for the infinity chest. Lowering it to vacuum tubes for 1k components will cut the total cost of some materials by 4. Instead of ~2.5M copper it'll be like 625k. Anyway, vacuum tubes are a useless thing to make for anyone in the tier of making an infinity chest, or even AE components. Especially needing 65k of them. LV circuits are always useful, no matter what tier. It'd be like making it require wrought iron, or those sticky resign bords. Infinity chest is meant to be a really late game item, and right now it is. It's doable to make, just hard. I've made about 50 64ks since 2.0 and they really aren't a problem. The only issue I have with them is how 64ks only take a single circuit, instead of any of that tier. It's only work stations which seems weird

**Comment by Dream-Master** [comment]
So the changes is bad i made before ?

**Comment by benstuwie** [comment]
The way they are in 2.0-2.0.1.3 is fine for the 1k components in my opinion. I'm not sure what they are like in 2.0.2.5. The 64ks had issues in 2.0-2.0.1.3 where they only took one circuit of a tier, instead any of the circuits in that tier. It was only workstations instead of any of the elite circuits (I think it was elite)

**Comment by Dream-Master** [comment]
@benstuwie i changed it now all one Tier of circuits down.

**Comment by Proha5** [comment]
Best balance is original AE2 balance -> each next tier requere **__3__** previous components (instead 4) + 4 current tier circuits.
Like as there: http://ae-mod.info/16k-ME-Storage-Component/

I reach end game, deep dark. But i can't create infinite chest - its EXTRA MEGA hard. Not profitable.
Harder comonents is 18 x "quantum chest V" and 10 x 16M cells.
Quantum chest requere 108 UV motors(28K superconductors) + 2304 Wetware processors == 37K stemcells(!) == 550K eggs.

10 x 16Mcells stores **630** types x 1.000.000 capacity for each. (or 128 mil for 1 type)
Inf chest stores **253** types x [infinity capacity]. 
But 1Mil - is enought for store any items and ores.
Total result: 10x16M cells better than 1 inf. chest.  Because stores more types, and not requere 18 "quantum chest V"

**Comment by Dream-Master** [comment]
Then don't craft it

**Comment by jiamingc0824** [comment]
Changing the circuit one tier down is the best method to rebalance the storage component recipe as this recipe have been alway around since pre 1.5. This is a good change/revert.

**Comment by codewarrior0** [comment]
This one kind of caught me by surprise since some time after the circuit overhaul, a cheap recipe for LV circuits (Microprocessor) was added. But there's a really cheap assembler recipe for vacuum tubes too, so that's fine.

**Comment by Dream-Master** [comment]
Yes why not can change it

**Comment by Dream-Master** [comment]
No we have the nand circuit back in ulv so use this instead of a vacuum tube.
