### ISSUE TITLE
Server crash - stack overflow - 2.0.1.3 Forestry Worktable

### ISSUE THREAD

**Issue by ProsperCraft** [GTNewHorizons/NewHorizons#2444]
#### Which modpack version are you using?
2.0.1.3

#
#### If in multiplayer; On which server does this happen? 
ProsperCraft
#
#### What did you try to do, and what did you expect to happen?
From the player - "there is also probably issue associated with using the same item in the recipe over and over like pam's harvestcraft pots/pans etc and evidently the ztone ofanix as well now"

![2018-01-16-154937_345x340_scrot](https://user-images.githubusercontent.com/4427684/35011984-57f58ef2-fac5-11e7-8dd0-2ac73857abcf.png)

#
#### What happend instead? (Attach screenshots if needed)
https://gist.github.com/ProsperCraft/7b40ebc821e0f070714a9b1180ecfa62
Server crash.
#
#### What do you suggest instead/what changes do you propose?
Fix the stack overflow or disable the worktable?

**Comment by LOKKO12** [comment]
Ofanix is bugged AF. i realy recommend not using this item.

**Comment by ProsperCraft** [comment]
Its the table that caused the crash.

**Comment by Dream-Master** [comment]
I can remove the offanix . It is dropped by the lich (we add it)

**Comment by ProsperCraft** [comment]
Its the table, and the fact that the item has no durability......not the Ofanix.

**Comment by heatskr** [comment]
Hello Dream. This is a simple comment, not a issue. It is possible to fill your inventory with cobblestone. When you do that several people get disconnected from server. If we could stop bulk crafting actions with Ophanix... Via tweaks, if possible, or via programming in last case. Limit the max crafting amount to one item stack instead of craft until inventory is filled. I know that is delegated to Zstones. Between say thank you to GTNH team for all you made to us. 🥇
