### ISSUE TITLE
Steam/turbine convenience suggestions

### ISSUE THREAD

**Issue by Bluebine** [GTNewHorizons/NewHorizons#2446]
#### Which modpack version are you using?
2.0.2.7
#### What do you suggest instead/what changes do you propose?
So for steam, I've got 3 suggestions me and a few other people discussed.
1. Make everything produce and use half the amount of steam, so everything stays the same but steam is easier to transport around. 
2. Steam turbines shouldn't blow themselves up just because they can't output all their power. That's just stupid.
3. All the turbines should only use as much steam/plasma/gas as they need to produce energy, and stop once their buffer is full, like the small generators. This might be OP, so to balance this you could make them use a bit of steam/gas/plasma while idling, make starting/stopping damage the turbine, or make them generate less EU for 30 seconds or so when they're turned on, as the turbine gets up to speed.

**Comment by richardhendricks** [comment]
1.  Like it, since 1 steam at 100% efficiency == 1 EU that way. Also makes pipes using steam easier to deal with, since boilers at a tier right now require huge pipes to move steam. And sloshing effects etc matter less when smaller % of the pipe is used.
2. Fucking +1 to this.
3. My suggestion is that steam turbines use 10% of their rated optimal steam flow for "idling" at speed, with 1% the damage rate. So they can resume operations immediately, but bleed off a little steam, and get slightly injured, but not too much.  The only wrinkle are setups that disable the boiler when the battery buffers are full.  An idling turbine would drain all the steam over time.

**Comment by LOKKO12** [comment]
4. Maybe add a Decay Time to Steam, like it would cool down?

**Comment by Bluebine** [comment]
That would be interesting and fine IMHO, but I can't imagine how annoying that'd be to program.

**Comment by Prewf** [comment]
I love #1, I had to make large enderium pipes to transport my steam. I shouldn't be doing that :(

I feel like #2 is just Gregtech being gregtech and not necessary. Outputting EV tier power into an HV tier dynamo hatch makes sense that it would explode (it's GT electricity 101, you overvolt = explosion). Just use the proper size and/or lower tier material for your rotors. And make sure you don't have an input hatch full of steam before inserting your rotor into it. It's analogous to making sure you don't give water to an empty, heated steam boiler.

#3 I feel like maybe only gas/plasma should do this, but I'd be ok with this too. Steam was always a "have it on hand at all times" resource vs liquid "use just enough that you need." I'm only thinking this way for consistency.

**Comment by benstuwie** [comment]
For 1, I disagree. I think steam is fine as it is for power. I wouldn't ever want to use it for MV-HV, but I think that's fine. It kind of works at EV, but by then you'll have better pipes that can move it in the quantities you need.
2. If this is added, it should probably apply to all turbines. However, I think turbines should just have better tooltips that accurately tell you how much power you'll be making, and explain that if you overpower a dynamo it'll explode. I think exploding is a good way to get people to not use the large turbines for HV, but instead wait until EV.
3. I disagree. I think they should work like any other multiblock. You can set them up in ways in which you wont be wasting any power, so it should't really matter.

**Comment by richardhendricks** [comment]
But with 2, would you always make less than the full output of the dynamo.  At high tiers it doesn't matter but at low tiers I expect if I make an HV dynamo I can output at minimum 1A of HV.

**Comment by LOKKO12** [comment]
I see another problem with 1: Now 1 Steam = 1 EU BUT then 0,5Steam = 1 EU. This is no problem if you directly consume the Steam, but with 1, the Railcraft Tank becomes a 41,472,000EU Storage. (You would double the EU Capacity of the tank)...

**Comment by Prewf** [comment]
@richardhendricks I expect to generate **however much my math indicates I'll generate** with that rotor. In your case, a normal sized vibrant alloy rotor with optimal flow 36k and eff 1.15 expects to make 1035 EU/t if fed 36k of steam, which in your case it did exactly that and exploded (because you had an HV input hatch full of steam before you put in your rotor). 

It's actually technically possible to generate proper HV voltage with this rotor if you had used an EV fluid regulator to downstep your steam per second to ~17808L/s. But like you said, you can't make an EV fluid regulator because of a lack of titanium, so instead you should've just used a rotor with a lower optimal flow. And if that tier turbine doesn't generate enough EU to make 512 EU/t, then you simply make another large turbine that is fed your excess steam from the first turbine and feed the output from both large turbines into a battery buffer or something. Voila, multiple amps of HV tier voltage.

Btw, the dynamo hatch description even says it outputs 1A of whatever tier it is. You can't expect it to conveniently output your 1035 EU/t into 3 amps of 512 EU/t . It essentially tried to cram 1035 EU into a 512 bottleneck according to that tooltip, so it exploded.

Gregtech has a frustrating lack of documentation about these things, but rightly so because fitting all the math into a tiny tooltip is infeasible. But that's why we have wiki's (and the amazing people over on the discord) to light our way :P

**Comment by Prewf** [comment]
To further explain what happened in your scenario, even if you had an EV fluid regulator downstepping steam to 17808L/s, your large turbine still would've exploded because you put in your rotor *after* you had an HV input hatch full of steam. Fluid regulator or not, you unknowingly had a bomb on your hands the second your input hatch contained over 17808L of steam (because it wouldve generated over 512 EU at that point).

**Comment by Dream-Master** [comment]
Make steam less volume by 50% is unrealistic. Steam need much much more space then water and this us ok and realistic. Think steam turbines can be effiencenter at some tier.

**Comment by Dream-Master** [comment]
And yes explosion is stupid. Turbines need to switch off or let steam out

**Comment by Prewf** [comment]
But the explosion happened because of overvoltage. Like I said on the other discussion thread, that's GT electricity 101, not a problem with the large turbine itself. The explosion could've happened in similar circumstances with a large gas turbine or a plasma turbine. I view the large turbines as an "X EU/t output machine" Unlike all the single block steam turbines, the multiblock version is a variable amount of EU output, so you need to make sure you're setting it up properly.

I do agree that explosions in GT *in general* are stupid. It's an extremely harsh punishment for making a mistake on building something that's basically poorly documented (the spirit of gregtech amirite!). That could be a separate discussion on its own tbh.

**Comment by richardhendricks** [comment]
A generator that includes *circuits* in it should be smart enough not blow it self up.  If you want to penalize players by having any steam above optimal bleed off, that's fine with me.  Having to tune the blades to precisely the EU/t of the output dynamo is not fair, esp. since the player is not warned this can happen, and doesn't happen with any of the single block turbines.

*At a minimum*, the tooltip needs to be updated with proper information reflecting this dumb rule, and how to calculate it and properly throttle the steam delivery speed. Fluid regulators/pumps should be appropriately sized for the tier/flow rate of the blades.

@Prewf, I already know what happened and why it exploded now. I never assumed I would get extra amps beyond 1 from the large turbine, I just assumed that I could give the turbine all my steam, and any extra beyond what is needed to generate the 1A would either not be used or be vented out.

The tooltip says "Optimal steam flow"  not "EU/t, throttle steam flow to match dynamo".

I've since rebuilt it with the fluid regulator and LV input hatch and it doesn't explode.  But even there, I have my doubts the large turbine blades are really putting out 512 EU/t because I have it attached to a 16x HV battery bank, and it the tricorder does not show the output dynamo nor the wires at 512 EU constant load.

**Comment by richardhendricks** [comment]
Further discussion on on 2 on https://github.com/GTNewHorizons/NewHorizons/issues/2449

**Comment by Anarack** [comment]
Why are you using a turbine that is that far above what you can handle? Wouldn't the efficiency penalty for being that far below optimal kill any gains in power you would get?

While turbine behavior could be better defined in game, I would hesitate to make any major mechanical changes from the main branch of the mod due to said documentation problems, as well as the issue of it invalidating previous experience with said systems.

1. Please do not change the fuel value for steam, there is enough major math changes specific to this pack, we don't need more, and its intended to be annoying to move around and to make it a terrible fuel to move.

2. Thats just standard GT behavior, not sure why anyone that can make a turbine would expect over voltage not to cause problems.

3. Would be extremely annoying due to turbine spin up/down time, and can be dangerous for coolant feedback loops or other systems that rely on the output material of the turbine.

**Comment by richardhendricks** [comment]
Because I was trying to provide 1HV A for a MV EBF, and the small turbine rotors would require multiple LBTs to do so and still not get 1HV A.  So I upgraded to a normal vibrant alloy to use as much steam as possible, but there was no warning about potential explosions.

Yes, I know now from https://ftb.gamepedia.com/Large_Turbine about the loss due to not hitting the optimal flow rate, so it's probably irrelevant anyways.

**Comment by CalterOK** [comment]
Multi-block turbines are an excellent source of energy, but to use it you must fully understand how it works. As for me there is no need to change something in them, even if the game lacks information on the calculation of turbines, it is on the wiki. Since there is a quest for a multi-block turbine in its description, you can add some formulas for calculation and advice that is not necessary

**Comment by richardhendricks** [comment]
Tooltip and quest will be updated with information on turbine dangers and equations for calculations.

I think that integrating as much information as possible into the questbook/tooltips is a better answer than reading the wiki IMO.
