### ISSUE TITLE
Make Fluid Filters cheaper

### ISSUE THREAD

**Issue by Kortako** [GTNewHorizons/NewHorizons#2448]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
SP and MP
#
#### What did you try to do, and what did you expect to happen?
Use a fluid filter with a nonuple pipe.
#
#### What happend instead? (Attach screenshots if needed)
Looked at the recipe and said "screw that".  Fluid filters cost too much for their functionality.  They are the "intended" way to use nonuple and quadruple pipes, but each one costs 2 HV circuits, making the use of a nonuple pipe significantly more expensive than just running 9 pipelines (which I'm sure is much more laggy).  You can also just attach a Ender Fluid conduit to the end of a nonuple to extract what you want, and those are significantly cheaper to make for that purpose.
#
#### What do you suggest instead/what changes do you propose?
Considering that an Ender Fluid Conduit can achieve the same result, I don't think Fluid Filter covers should be so expensive.  If the intention is to gate them behind HV, then make them require some cheaper HV material.  Maybe make them require a shutter and a vibrant alloy plate, which then brings it in line with the Ender Fluid Conduit's costs (especially since they can only be used on GT pipes).

**Comment by TwentyOneZ** [comment]
There should actually be an incentive for people to use that kind of filter, since it reduces lag in servers.
If this really is supposed to be gated after HV, the materials should be cheap as a Shutter Module Cover and a Stainless Steel Plate. But in my opinion, this recipe should be simple as a Shutter Module Cover and a Fluid Detector Cover, maybe some molten polyethylene to make it gated after MV.

**Comment by Dream-Master** [comment]
Ok will change it for next release.
