### ISSUE TITLE
[Suggestion] New early quest Main/2nd

### ISSUE THREAD

**Issue by Bryfer** [GTNewHorizons/NewHorizons#2497]
There is alot of confusion around about the questbook.
Most players do not know that there is Main Quests and Secondary Quests

I would suggest adding a quest at this location (See picture below) since this is the first time you'll see a secondary quest.
![image](https://user-images.githubusercontent.com/22825059/35255727-be169b6a-fff0-11e7-875b-2ac06ec76cc4.png)

This quest should be one of those "Press X to continue" quests.

I'm not sure what the text of this quest should be, if you have any suggestions please write them ;)

One way to explain it would be this

> Now that you have made it this far you'll notice that you now have two quests available to you. Pay attention to how these two quests look different. One of them is a Main Quest. You need to complete Main Quests to progress to new tiers. The other quest is a secondary quest, It dosn't have to be completed but they will show you useful stuff that you unlock thru the modpack.

**Comment by richardhendricks** [comment]
I think "side quest" sounds better than secondary.
Also

"Main quests are connected with a thick line. Side/Secondary quests have a smaller line. 

Because of space reasons, not all required quests have a connecting line. If a quest is not seen, try completing some of the other main quests available."

**Comment by Dream-Master** [comment]
Yea good idea to explain it. Will add this quest.

**Comment by damug** [comment]
How about this small edit?

> Now that you have made it this far you'll notice that you now have two quests available to you. Pay attention to how these two quests look different. The quest that looks like a crown a Main Quest and it is linked to other main quests by a thick line. You must to complete the Main Quests to unlock the next tier in your quest book.  The other quest is an optional quest and you do not have have to be complete it to progress through the tiers of quest book.  However, be mindful that optional quests often introduce you to useful items or processes that will greatly benefit you as you progress.

**Comment by Dream-Master** [comment]
Yes sounds good to me but let's ask a native speaker @richardhendricks 
@damug are nativ speaker too?

**Comment by damug** [comment]
I don't speak the Queen's English.  However,  I have spoken American
English my entire life if that counts.

**Comment by Dream-Master** [comment]
So I will add the quest asap. Thanks for help

**Comment by damug** [comment]
Made some small grammar fixes. Should have proofed better earlier. My apologies.

**Comment by richardhendricks** [comment]
I dunno, the new wording sounds fine to a native English speaker, but what about someone who is ESL? Does the average German or Russian player understand the paragraphs?

**Comment by bartimaeusnek** [comment]
@richardhendricks there is no average player, it really depends on the age and the intrests of the Player. Thats why we need a russian, german, french, chinese, japanese and spanish translation. 😜

**Comment by richardhendricks** [comment]
Now that you have made it this far notice the two new quests. See how these two quests look different? The quest with a crown is a main quest and is linked to other main quests by a thick line. You must complete the main quests to unlock the next tier. The other quest is an optional quest is not needed to unlock new tiers. However, optional quests often introduce you to useful items or processes.

Not all main quests have a connecting line to guide you through your adventure because of book size. If there is not an obvious linked main quest at any point, try completing some of the other main quests available to you to progress.

How does that sound?
