### ISSUE TITLE
Rock-Breaker LV and MV not craftable due to IndustrialDiamond requirement

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#2544]
The LV and MV RockBreaker can't be crafted at LV and MV ages, as it requires an Industrial Diamond, which is tiered HV+ as you need an Implosion Compressor to make one.
Suggestion would be to either:

1 - Change the DiamondGrindingHead to accept normal and industrial Diamonds
or
2 - Replace the Grinding-Head for LV and MV RockGrinder with just a Diamond; Just like the early Macerators do

I'd personally prefer variant 2, but as for resource cost, 1 would be the better solution.
As far as I've checked, this doesn't influence tiering in any way. All machines that use these Grinding Heads are HV+ anyways.

**Comment by Ugachaga** [comment]
Keep in mind that Rock Breaker gives you access to unlimited and cheap Obsidian (block per Redstone dust).

**Comment by richardhendricks** [comment]
Well, just because the machine is labelled LV doesn't mean it should be craftable immediately at LV.  I think it's OK to require the higher end cutting blades since the machine provides such a benefit.  Lower tier versions are useful for power efficiency and for bill-of-materials.

Otherwise, obsidian dust can be obtained from the buckets of XP primitive UU.

**Comment by Namikon** [comment]
I do agree with the endless Obsidian thing; However, when you're able to craft that machine, you already have access to Steel, thus to Steel tools, and you do have access to "endless" Obsidian by taking a bucket of water and search for lava pools underground. On top of that, the recipe for Obsidian could be tweaked to require 120 or 480 EU/t, gating it at those respective Voltage tiers.

As for "just because the machine is labeled LV doesn't mean it should be craftable immediately at LV" thing is an interesting thought. At least I didn't had that in mind when adding the WorldAccelerators, or others when adding things like AutoMiners to LV.
But I somehow do like that idea. The WorldAccelerator is a machine that should be LuV/ZPM+, auto-miner at LV Age is debatable but IMHO a Quarry, regardless how slow it is, also doesn't really fit in Low-end tiers.

**Comment by Namikon** [comment]
It's not a question if you *need* that machine; It's a question about that the recipe isn't possible until you reach HV. And my suggestion was to alter it so it can be crafted. There are a few auto-setups at MV that require a cobblegen. Not only for generating blocks to build your base; Also for Oxygen and silicon.

The alternative is the TransferNode and a WorldInteraction upgrade. Which works without power, and is easily doable in late LV/early MV.

**Comment by richardhendricks** [comment]
Hmm...Good point.  It can be hard for me to defocus from my setup and realize other players have different needs at the same tiers.  For me, sand has never been an issue since my fish catchers gather so much for me, but I can see how a player far from the appropriate biomes might need a cobblegen to smash up cobble for gravel/flint/sand/other byproducts.  Same for silicon, I have tons from clay dust and other  electrolysis, but maybe someone else needs it.

@Namikon I also agree with the autominers at LV.  I made two but "retired" them for MV miners since the LVs are so poor at clearing out veins they just weren't worth the maintenance hassle.

Progression should be a 4 stage process, imo:
1. Don't need it.
2. Want it, but getting it is annoying
3. Getting it is less annoying
4.  Getting it is trivial

The rockbreaker is definitely a stage 4 machine IMO.  What tier are the block breakers? Those could be used in a stage 3 setup with in-world water and lava (granted no obsidian, but that should be a little harder to get).

For me in my game, I have a rockbreaker that I just throw in an MV battery whenever I feel like it, and it just stacks obsidian until the batt runs out.

**Comment by Dream-Master** [comment]
So put it from Hv to Mv are ok ?

**Comment by Namikon** [comment]
Sounds fair. If in doubt about Obsidian, then the recipe could be changed to require like MV or HV tier. This regards cobblestone only.

**Comment by CalterOK** [comment]
The compressor does not require a clean room, and it is available in LV
