### ISSUE TITLE
Electrolyzing distilled water takes shorter time than normal water makes no sense

### ISSUE THREAD

**Issue by noobyaran9** [GTNewHorizons/NewHorizons#2547]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?

#
#### What happend instead? (Attach screenshots if needed)
![2018-02-03_00 02 12](https://user-images.githubusercontent.com/13598309/35742562-c9a8c0e2-0875-11e8-865e-630b13657304.png)
![2018-02-03_00 02 15](https://user-images.githubusercontent.com/13598309/35742563-ca38c340-0875-11e8-9cae-8d7f200ae24d.png)

#
#### What do you suggest instead/what changes do you propose?
Distilled water can't be electrolyzed or at least it won't be faster than normal water. Remove electrolyzing distilled water recipe and revert the time taken to electrolyze water into hydrogen and oxygen back to 75s.

**Comment by codewarrior0** [comment]
In base GT5, both recipes take 100 seconds.

**Comment by Dream-Master** [comment]
why the recipe is wrong in your eyes @noobyaran9  ?

**Comment by noobyaran9** [comment]
"Electrolysis of pure water requires excess energy in the form of overpotential to overcome various activation barriers. Without the excess energy the electrolysis of pure water occurs very slowly or not at all."

https://en.wikipedia.org/wiki/Electrolysis_of_water

The recipe of electrolyzing distilled water should not be faster than normal water or just shouldn't exist at all.

**Comment by richardhendricks** [comment]
GT is not a physics course.  Otherwise we should also fix the exploit of electrolyzing water in cells vs fluids. I like having the recipe as a side-benefit to using the large steam turbines.

**Comment by noobyaran9** [comment]
>GT is not a physics course.

Isn't that what the circuit and petrochemistry update trying to do?

I don't mind the recipe existing but i don't like the idea of distilled water electrolyz faster than normal water.

**Comment by richardhendricks** [comment]
It's a gameplay and balance question, not a "this should reflect real world physics" thing.  But I can understand your viewpoint.  How about this proposal?

Water electrolysis direct from tanks and via cells stays the same

Remove salt water recipe using normal water, or reduce its output since it isn't "pure" water.

Create a recipe for salt water using distilled water and NaCl. 

Water electrolysis via salt water gets a boost, lower EU/t and/or faster, even when the mixing is taken into account.

Directly using distilled water is removed or slowed - change to 120 eu/t.

This way someone can still use water directly, but if they want to improve efficiency they can make a sodium chloride source and mix clean salt water for electrolysis.

In real life, most oxygen comes from air, and most hydrogen from natural gas.

https://en.wikipedia.org/wiki/Oxygen#Industrial_production
https://en.wikipedia.org/wiki/Hydrogen_production#Steam_reforming

How does that sound?

**Comment by codewarrior0** [comment]
> and most hydrogen from natural gas

On this note, prior to the petrochem update I would always get my hydrogen from methane, but now it seems like I'm better off burning the methane for power and using it to run electrolyzers.

**Comment by richardhendricks** [comment]
How fast is the CH4 -> H recipe?

**Comment by codewarrior0** [comment]
With the required MV Electrolyzer, produces 4 H from 5 CH4 over 4 sec, costing 4800 EU. Burning 5 CH4 in a gas turbine provides, let's say 500,000 EU after line losses, enough to produce just over 16 H via electrolysis.

**Comment by codewarrior0** [comment]
But if I paid more attention, I would have noticed a chemical reactor recipe that produces 8 H from 1 CH4  + 72kEU and some water... wow, I'll just do that from now on.

**Comment by richardhendricks** [comment]
I dunno, seems fair to me. I prefer to keep my setups compact vs massive arrays, so once i get the multiblock still I could easily see me swapping from water to methane electrolysis. Others are more focused on EU efficiency, and could follow your path.  Choices are good.

**Comment by Dream-Master** [comment]
So what i need to change now ?

**Comment by noobyaran9** [comment]
Either change electrolyzing distilled water to 100s and change normal water to 75s or just remove distilled water recipe.

**Comment by Dream-Master** [comment]
Or we change both to 100s like the origanl gt recipe.

**Comment by noobyaran9** [comment]
Sure
