### ISSUE TITLE
Tinkers' Construct Tools - Rebalancing (?)

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#2583]
Somewhat required, and somewhat a discussion issue.
We found that lots of people have really powerful tools at MV/HV Age. Mining speed ~40 and more is possible with a simple Steel Hammer. 
This ofc renders more valuable materials like HSS/Vanadium/etc.. pretty... uhm... "Useless". Steel is trivial to obtain after MV-Age.

It's of course not "game breaking", but it was not intended to have high-speed broad-mining tools in LV/MV. Probably a derp on our side, aka "misbalancing".

Iguaga's Tinker-Tweaks, as it is configured right now, applies up to 7 modifiers with 9 Level-ups (Extra Slots included). That is.. well.. a lot.

It's not that we want to make LV/MV even more grindy and boring as it is already, (Circuits.. Ciiiiircuits... And not to forget ChemicalReactors...), but we'd like to increase the value of better Materials and manual Upgrades. Currently, Moss and Durability is like auto-added with Level 4, Fortune is a random luck but you will have a "maxed" out Tool once you hit Level 8 or 10. No need to go the Thaumcraft way to add auto-repair to your tools. The only thing that is not auto-applied is SilkTouch, but even that is easy with a little bit of luck on Lootbags.

So post your comments on this, please. One possible way would be to completely remove the automatic modifiers and just give modifier slots. And maybe not on each second level, maybe on each 4th, or 5th.

**Comment by noobyaran9** [comment]
# Each modifier is equally likely on levelup. Disables useful bonuses. [default: false]
    B:CompletelyRandomBonuses=false

Fiddle-ing with this might be interesting.


toolleveling {
    # Adds a random bonus on these levelups if 'RandomBonuses' is enabled
    I:BonusesAtLevels <
        2
        3
        4
        5
        6
        8
        10
        13
        16
        19
        23
        27
        31
        36
        41
        47
        53
        59
        66
        74
        83
        93
        99
     >

Maybe not as frequent on the early levels. But the frequency at where u get increase by 1 every 20 lvls. 
Smth like 5,10,15,20,25,30,35,36,40,45,46,50,55,56,60,61,65,66,70,75,76,80....

# Adds an extra modifier on these levelups if 'ExtraModifiers' is enabled
    I:ModifiersAtLevels <
        5
        10
        15
        21
        28
        36
        45
        55
        66
        78
        91
        99
     >

Same as above.

# Removes the ability to add modifiers with Gold, Diamond, Netherstars etc. [default: false]
    B:disableBonusModifierModifiers=false

Maybe disable this so that people only get extra modifier from level-ing and the creative modifier.
      
How i wished we had 1.10+ tinkers right now.

**Comment by WarlordWossman** [comment]
I do agree with tools scaling a bit too fast.
And the mining speed is probably the most important value here. I would say that mining speed should be bound to the material only as 50 redstone is super cheap for what it does. I would also say that auto-repair should be thaumcraft only. (Things like the hammer and lumberaxe benefit too much from passively repairing for it to be a free modifier you can get imo)

Another thing I thought about is redoing mining levels since we have a ton of ores and the progression of "what am I able to mine" doesn't seem to be too thought through atm.

**Comment by richardhendricks** [comment]
I disagree.  I think the tools are fine as-is.  If we need to tweak something, make the higher tier planets' rock hardness harder so that the tools have to be upgraded to maintain a decent speed.  Even with that I have some issues because of how difficult it is to reliably get from A to B without hurting performance (at least in SP).  For example:

You leave for moon with a vanadiumsteel hammer.  It can mine moon rocks, but not super fast.  So you mine up mats from the moon (let's say titanium) that is now faster. Great. But processing that titanium requires a whole infrastructure back on the overworld. So you go back, upgrade your tools, and come back to the moon? I don't think people would be happy about that.

I don't think this really increases or improves gameplay.  What I would prefer is more reasons to stick around on a planet.  Unfortunately that would require really adding/modifying serious amounts of code, like adding roguelike dungeons to other planets (derelict crashed spaceship, abandoned mines, haunted outposts, etc). But that would be way more interesting then artificially forcing the most boring part of the game to last longer (getting good tools).

It would be Ok if the alternates worked better, ie the GT miners didn't miss ores when skipping through dimensions or require a chunk loader in every chunk to mine.

My proposal, if we really want tools to operate like this (I don't):
1. Find ways to make the planets more interesting overall. Don't know if we have the capability on staff to do this, esp. considering 1.7.10's abandoned status with most mods.  A translation of roguelikes to use a "spacey" tile set would help a lot, and might be do-able. 
2. Allow for stacking GT miners just like GT pumps to accelerate performance.
3. Have GT miners chunkload the location they are mining (except for their current chunk). The miner would require a chunkloader in its own chunk, but mining large areas would be possible. I would prefer this to be an option in the GUI - could even require putting a 2nd chunkloader in a GUI slot.
4. Sit down and intelligently create a spreadsheet of materials at each tier, their capabilities and designated uses. Setup so that each tech tier has 'fast mining', 'high durability', and 'high tool level' options, with a 'jack of all trades' available at the top of each tier, and maybe a few mixed-use alloys that support two of each option. This would need to be mixed in with ore distribution and EBF tiers. As a simple example (ignore the names, just for placeholders):
Tier 0 mats

| Alloy     | Durability |  Mining speed |  Tool level  | Notes
| Copper    |    low     |     Good      |      1       | Starter material, easy to find
| Tin       |    Good    |     slow      |      1       | Starter material, easy to find
| Bronze    |    Good    |     slow      |      2       | First alloy, allows mining iron ores
| Iron      |    Good    |     Good      |      2       | First jack of all trades material

etc

5. Update hardness information for dirt/rock/ores so that at higher tier dimensions, better mining speed tools are required to work in a reasonable amount of time. OW/Nether/TF would be left alone, but moon and above would need tweaking.

**Comment by WarlordWossman** [comment]
"artificially forcing the most boring part of the game to last longer"

I mean there is a reason that you can't instant mine with your bare hand, we are talking about adjustments like reducing the effect of redstone modifiers or using a higher value material to apply the modifier yourself (if that is even possible).

I like the idea of your material list and dif alloys could be tweaked so you need to make a decision on what combination of speed/durability/mining level you want. Maybe you carry 2 picks with one being slow but able to mine some ores you otherwise couldn't mine (?).

Anyways atm you can slab a million things on your tools (or get them for free by leveling) so I think restricting it a bit more or adding higher costs for something like speed upgrades would be a good idea.
The changes should not be made to make life more painfull but moreso to get a clear line of progression within tools as the current situation feels really random.

**Comment by richardhendricks** [comment]
well, it might be OK to slow down mining speed and add quests for the traveller's gear from TiCon.  Don't the gloves boost mining speeds?  Never got around to making them before I found mica.

**Comment by Prewf** [comment]
Regarding the original pos: you may be able to mine fast with a steel hammer, but also the durability is so low compared to high end metals that it kinda balances itself. I remember always keeping a stack of steel + a tool station in my inventory because I'd be repairing so often. If you want a mining tool that lasts a really really long time you still need a high end tool rod and plate on your tool.

Also, a lot of the ores in space seem to be artificially increased in mining requirements so again, you can't stick with low end metals like steel for too long. You HAVE to upgrade at some point.

The only problem I see with ticon is the sheer number of choices I have for making tool components. Like, 80% of them are useless tbh, but I have to filter through all that bs myself through NEI before I know which components are worth making. Like, who is going to be making a sword out of polyethylene?? Why is that even a thing?

**Comment by richardhendricks** [comment]
Those components are automatically created.  It would be useful to have a Cheat Sheet section in the questbook that lists information like this I suppose.  Players normally ask it anyways in Discord, so putting it up in the qeustbook isn't cheating (or at least no more than asking in the #help channel is).

**Comment by Prewf** [comment]
Cheat sheet would be useful. I also liked your suggestion #4 for tiering the different materials so that everything has its own purpose.

**Comment by Methes** [comment]
Unless you change the mechanics of upgrades (maximum amount of redstone upgrades for example), there's going to be no real change, it will all just take longer.
Take my example:
1) After acquiring netherrack (easy with iron bucket), I create several flint tools and level them up twice.
2) If I don't get 2 haste modifiers, I delete the pickaxe.
3) With 2 haste modifiers you have enough speed to instamine netherrack - I fire my AHK script that places/mines blocks, repairs the tool if broken, replenishes hunger, sleeps in more private worlds. I let that run for a few hours in total.
4) If you get luck, max it before getting the next random modifier to not get luck twice.
5) If you get redstone/reinforced, good for you. If you get anything else, meh.
6) Reinforced VIII is generally enough to have a long lasting pick with room for more random reinforced upgrade. Reinforced 3 from obsidian tool rod, 2 from gold+diamond additional modifiers means you need just 3 random reinforced modifiers, rest you can put in haste. Or just go all the way to unbreaking if you have enough speed already.
7) Just upgrade your pick as you get better materials. Done.

**Comment by WarlordWossman** [comment]
Yeah that's what I mean the stackability of the modifiers is so high that you can get a quite good tool.
Pair that with free modifiers and you can do what Methes wrote down, even if afk scripts will always make your life easier.

Def needs some major redoing to make the tools less wonky but not making mining too slow/boring at the same time.

**Comment by Dream-Master** [comment]
Thats why i nedd some suggestions not only in text. You lnow my pack better then me so i need values,  lists, config changes etc.

**Comment by Namikon** [comment]
Well, I think we all agree that a change in code, with Tinkers/Iguana, is not trivial. I wouldn't go this route 
 anyways. Let it be how it is, and tweak it with the config options we have. The only thing that could be changed would be to equalize the XP required to LevelUp between all Materials, to prevent a speed-level with like Netherrack. But I'm not sure if that's possible for us. Haven't checked if Iguana is OpenSource.

So what about removing the auto-level-up bonuses, and adding a new Slot not every 2nd, but every 3rd level-up? So even if you get a lot of slots on these level-ups, you still have to get the materials to apply them to the tool. Which, in return, is still rewarding and also giving the player the choice of what to do with his Tool. There is no need to set it to each 5 Level or more, **and** to remove Updates. I think all this should be balanced with a Level 10-15 Tool in mind. This is what you end up doing a "normal" playthrough until MV/HV age.

Let us do this in small steps, please. The tools are Ok. The System is ok. It's just a *bit* too much. No need to make massive changes now. Change one thing, observe new players and check how they're doing, then tweak again if required.

**Comment by WarlordWossman** [comment]
The things I like about that idea is that you can choose yourself and that you have to apply the modifier.
So already a big improvement in my opinion.

However what comes to mind is that reinforced still is a thing and with the 15/3 levelup modifier slots + extra from the pick head + extra for other modifiers you can get with paper, thaumium etc it might be easy to get an unbreakable pickaxe. We should probably wait for @Methes to respond since he dealt more with pickaxes and modifiers it seems.

**Comment by noobyaran9** [comment]
Remove random bonuses and reduce the frequency that u get modifier. Seems like a good plan.

**Comment by Methes** [comment]
No randoms, max level 15, total 5 modifier slots unlocked.
Vanadium Steel Pickaxe (MV, kanthal coils)
 - Vanadium Steel Head
 - Obsidian Binding
 - Damascus Steel Tool Rod
 - Haste 5, Reinforced 2, Luck
 - Mining speed 48 (need 45 to instamine smooth stone, 60 for cobble), effective durability 14400, 
   mining level 05 Obsidian

That's the best pickaxe you can get I think. Not bad at all, later you can get even better pickaxe (if you're clever).

**Comment by UpstreamEDA** [comment]
Coming from a new player that has just entered MV, I love Iguana's Tinker Tweaks and the random modifiers on level up.  Getting lucky with your random modifiers makes your tool feel special, and I like having to choose between continuing to level my current pickaxe with its mediocre modifiers, hoping that my luck will turn and the next few will be exactly what I'm looking for, or deciding to start leveling a pickaxe from scratch is a nice form of RNG that lets the player make meaningful decisions.

If anything, my tools/weapons have leveled up too quickly and it's too easy to drop my old pickaxe and start leveling a new one.  This decision should carry more weight in my opinion, so the mods should definitely come fewer and far between.

**Comment by UpstreamEDA** [comment]
Coming from a new player that has just entered MV, I love Iguana's Tinker Tweaks and the random modifiers on level up.  Getting lucky with your random modifiers makes your tool feel special, and I like having to choose between continuing to level my current pickaxe with its mediocre modifiers, hoping that my luck will turn and the next few will be exactly what I'm looking for, or deciding to start leveling a pickaxe from scratch is a nice form of RNG that lets the player make meaningful decisions.

If anything, my tools/weapons have leveled up too quickly and it's too easy to drop my old pickaxe and start leveling a new one.  This decision should carry more weight in my opinion, so the mods should definitely come fewer and far between.

**Comment by WarlordWossman** [comment]
I would say testing the version Namikon suggested in his last comment would be an idea, def sounds better on paper than the current system.
