### ISSUE TITLE
Quest for the Combustion Engine Multiblock

### ISSUE THREAD

**Issue by mtesseracttech** [GTNewHorizons/NewHorizons#2598]
An idea would be to add the combustion engine multiblock as one of the multiblock quests. It can give decent EV/IV power bridge for what it's worth, since a lot of people don't really like IC2 reactors.

Just gate the quest behind the minimum requirements of the multiblock controller and have it be optional.

**Comment by Dream-Master** [comment]
Sure why not

**Comment by benstuwie** [comment]
Is that the multiblock version of the diesel engines?

**Comment by Dream-Master** [comment]
Guess so

**Comment by mtesseracttech** [comment]
@benstuwie Yes, correct. It's available at IV and it mostly requires a decent bit of Titanium. I don't think it's particularly fuel efficient, but at least it fills the gap for IV power gen if you dislike reactors and don't want to spam solars.
A nice comment would be that it would be best to implement it with state switches or manually. Since it does not stop automatically if its energy buffer is fully and it has an efficiency that slowly ramps up as it runs. Also, it requires some extras, on top of the fuel. It also requires lubricant and oxygen to run at max efficiency.

A state switch would be something like a battery buffer with 2 redstone outputs, one set to emit when over 80% and one when under 20% , and connect these to a project red latch. That way the thing starts up when under 20% and shuts off above 80%. Allowing it to reach top efficiency without waste. And running the output of that switch into a redstone controller on the multiblock.

**Comment by Dream-Master** [comment]
@mtesseracttech because i never had Combustion Engine Multiblock i need help with this.

**Comment by Wolozo7** [comment]
Required quests: "Tier 5" (you can build it once you've been to the moon, it gets easier once you were on mars because of the one tungstensteel cable)
------------
Name: Idk, someone else think of something funny
-------------
Description: Your old and trusty combustion engines don't quite cut it anymore. If you want to keep burning liquids. you need to build a better engine. This multiblock can produce 1A of EV voltage by default and 3A if you supply it with oxygen. However, this power doesn't come for free, you need to supply the machine with small amounts of lubricant constantly (and oxygen if you want to boost both its efficiency and output).

Hint: This multiblock will blow up if it produces more than the dynamo hatch can handle. Don't boost it with an EV dynamo!

Hint2: High Octane Gasoline is an excellent fuel source for this engine.
------------
Retrieval task: 
1x Combustion Engine
2x Titanium Gear Box Machine Casing
8x Engine Intake Casing
19x Stable Titanium Machine Casing
1x Maintenance Hatch
(Besides that, the multiblock requires 3 Input Hatches, a Muffler and a Dynamo Hatch, but their tier should be left open.)

**Comment by mtesseracttech** [comment]
hmm, that seems pretty decent. I don't think it blows up though (at least it would seem strange to me), I would also require the player to make 3 fluid hatches, since you need at least 2 and you can optionally add an oxygen hatch (And why would you not, at that point in the progression).

**Comment by Wolozo7** [comment]
Oh, it does indeed not blow up. Information was based on [this](https://youtu.be/mvJFCNSvhlg?t=94), but doesn't seem to apply anymore. I wouldn't require the input hatches as part of the quest, because you'd have to decide what tier of hatch the user is supposed to get. Maybe someone has an LV and two MV hatches sitting around, another one likes to use HV for everything. Of course it wouldn't be a lot of work for the user to make hatches if they are told to by the quest, but is it necessary? An alternative would be mentioning the remaining parts (fluid hatches, dynamo, muffler in the quest description.

**Comment by codewarrior0** [comment]
Or if the quest author wants to do a lot of work, he could use MT to add all of the hatches to `<ore:questGtInputHatch>`, `<ore:questGtOutputHatch>` and so on, in order to use those oredicts for quests...

**Comment by mtesseracttech** [comment]
@Wolozo7 Ah good point about the tiered hatches.
@codewarrior0  There are probably 12 or something, how much work would that be?
If you give me an example, I could even do it.

**Comment by Dream-Master** [comment]
its not that much work but did it maybe are exploitable. I mean what happend if i put hatches to jabba like we did with copper and annealed copper before and get another tier out. If all hatches have the same ore tag @mtesseracttech @codewarrior0

**Comment by mtesseracttech** [comment]
@Dream-Master Ah, I see the problem. I didn't quite realise that the effects would also be used by stuff like jabba.

**Comment by Dream-Master** [comment]
I not test it but I doubt it could make problems.

**Comment by mtesseracttech** [comment]
@Dream-Master is there any type of blacklisting for Jabba?

**Comment by codewarrior0** [comment]
The oredict conversion for both JABBA and StorageDrawers only works for a short list of prefixes - `ore dust ingot nugget` - and conversion is already disabled for both mods in your configs.

**Comment by mtesseracttech** [comment]
Sounds like it would be all fine for this situation then. Baffles me though how people who implement storage unification don't allow for blacklisting of items.

**Comment by codewarrior0** [comment]
Not sure about JABBA, but [StorageDrawers does have a blacklist](https://github.com/jaquadro/StorageDrawers/wiki/MineTweaker-API) accessible through MT. StorageDrawers for more recent Minecraft versions also exposes it through the config file.

**Comment by mtesseracttech** [comment]
Ah that is interesting and good to know. Sadly this pack has both so one can't exactly only blacklist them for one of them x)

**Comment by Dream-Master** [comment]
No they dont and we have issues with it i remeber. And we not get any update here.

**Comment by mtesseracttech** [comment]
I could try and check with someone who knows a decent bit about reflection and bytecode manipulation if he knows if these things are possible to implement with a patch.

**Comment by Dream-Master** [comment]
sure.

**Comment by mtesseracttech** [comment]
@ReikaKalseki Do you have any idea how doable this is? To implement a blacklist for Jabba in the form of a patch.

**Comment by richardhendricks** [comment]
A good quest name:
Burn and Turn

I think a good follow-on quest to this one would be:
Automated Activation for Fun and Profit

Now that you built a multiblock combustion generator, you realize it does have a drawback - it runs continuously!  You hate the idea of wasting energy leaving it on, and even worse, wasting time turning it on and off manually. Automate it!

(notes on how to setup automated machinery)

16x EV battery bank
16 ev batteries (or let the player choose?)
Energy cover
Machine controller
(stuff to turn it on at 20% batt level and off at 80% batt level)

**Comment by ReikaKalseki** [comment]
@mtesseracttech The bigger issue I see is in releasing a pack with ASM into another mod in it; without permission from that mod, you are potentially being very unfair to them, as who knows what the ASM might break if they change anything in the codebase.

But aside from the main FML-loaded mod class, basically any class in any mod can be ASM patched.

I do not know anything about the feature you are describing, nor have I looked into the relevant code inside JABBA, and as a result I cannot comment on the exact nature of a potential patch.

However, I can say this: The closer to the original behavior a patch is, the easier it is to implement. If you are simply adding a new entry to a list (which could be accomplished without ASM at all, and can be done with reflection), that is trivial. But if you also need to rewrite the parsing of entries in the list, for example, that is much more difficult.

**Comment by richardhendricks** [comment]
Please take the JABBA blacklist issue to a separate ticket, let's keep this one focused on the Combustion multiblock.  It will help with searches too if it is has its own topic.

**Comment by mtesseracttech** [comment]
@Dream-Master So after a short talk with Reika, he basically told me that if there is no native blacklist in there, it's very difficult to get the functionality in there, leaving aside the ethical component he mentioned.

**Comment by Ugachaga** [comment]
JABBA is open source under [CC BY-NC-SA 4.0 license](https://minecraft.curseforge.com/projects/jabba/license).

**Comment by Dream-Master** [comment]
We fork jabba and the issue is with storage drawer

**Comment by Dream-Master** [comment]
@Ugachaga @richardhendricks @mtesseracttech 
Jabba will be fine we need to look into storrage drawer and it us open source and forked too.

**Comment by MakinToge** [comment]
To go back to discussion on combustion engine, maybe an additional quest with machine cover with power lvl and how to set it up with a machine activator cover would be nice. There's one problem tho, which power storing solution to propose to player, it could be the quad HV battery thing or the small sunnarium one or even the power storing block from gt++ (forgot its name). quad HV is not bad since as @richardhendricks said, the generator is mainly used to bypass IC2 reactor and the sunnarium battery need the molecular machine which need EV sensor which need radeon which need to go to mars or other T2 planet. And that's also something ppl that avoid IC2 would avoid (At least that's the case for me)

**Comment by mtesseracttech** [comment]
oh damn, I didn't mean to close it...

**Comment by mtesseracttech** [comment]
So what my comment was going to be: At the point you have large amounts of titanium to make this generator, I think you definitely are able to make a ton of Lapotron Crystals for your 16x EV energy storage.

**Comment by richardhendricks** [comment]
![2018-08-21_00 27 44](https://user-images.githubusercontent.com/1214811/44382155-802b9b00-a4d9-11e8-8c8c-56fb22f286d9.png)

Followup quest
`Now that you have a GT boiler or LCE with a faster startup time, you can automate it to produce power on-demand. Use a machine controller cover on the controller (protip: You can put it on the bottom, or on the side next to a casing, casings will transmit redstone signal). 
With a machine controller cover, you can use redstone to turn the machine on and off. This is handy if you don't want to use a soft hammer to disable a machine.
 
The best way to do that is with an RS latch. One input will turn the machine on, and one input will turn the machine off.
Use a comparator attached to a valve to measure the steam level in your multiblock Iron or Steel Tank. Invert the signal to turn on your boiler when the steam level is low. When the steam level signal is high, turn your boiler off. Use a trail of redstone to lower the signal strength. Because of boiler/turbine warmup, try to set the ON strength to 30 percent of capacity and OFF strength to about 90 percent.

Red alloy wire will hold a redstone signal for a longer distance.

You can use a Energy Detector Cover in Normal Electrical Storage (including batteries) mode to monitor the power in a battery buffer and use it to enable/disable generators in a similar way. Change mode using a screwdriver.`
