### ISSUE TITLE
New EV quest lines

### ISSUE THREAD

**Issue by Wolozo7** [GTNewHorizons/NewHorizons#2599]
Suggestion for two new quest complexes. I'm mostly looking for opinions before actually writing the quests, regarding 

- are they relevant?

- is something obvious missing?

- are there other important things happening in EV that aren't covered by quests?

![image](https://user-images.githubusercontent.com/34921674/36116390-5a6cfd38-1036-11e8-9432-161851e87e90.png)

**Comment by Dream-Master** [comment]
Good idea will look what i can add.

**Comment by benstuwie** [comment]
+1
Looks like good EV stuff. I'd also suggest more solar stuff. I think you can make an EV one in EV

**Comment by mtesseracttech** [comment]
I can think of a few quests for EV and IV too I suppose.

**Comment by Dream-Master** [comment]
epoxy is added but yes silicon ruber and styrene rubber i could add.

**Comment by mtesseracttech** [comment]
I know a few other ones. Let me see if I can give some idea for arranging. I suppose BPA could be moved to HV

**Comment by mtesseracttech** [comment]
https://i.imgur.com/SNDHXbN.png could be a way to do AE2 quests

**Comment by Dream-Master** [comment]
I modifying today the file so be careful if you add new stuff but I like the idea others helping me with quests.

**Comment by richardhendricks** [comment]
Are we good on this? I think all these items have been added?

**Comment by Dream-Master** [comment]
maybe hi amp traffo missing

**Comment by richardhendricks** [comment]
I added the high amp and power transformer quests to HV since that feels like a better fit to me.
![image](https://user-images.githubusercontent.com/1214811/57198838-51593600-6f3d-11e9-838f-353a20800500.png)
![image](https://user-images.githubusercontent.com/1214811/57198841-55855380-6f3d-11e9-808a-d3d54cce162c.png)
![image](https://user-images.githubusercontent.com/1214811/57198842-59b17100-6f3d-11e9-985a-df307701fba3.png)

![image](https://user-images.githubusercontent.com/1214811/57198846-603fe880-6f3d-11e9-845f-2909514c33b0.png)

**Comment by DietmarKracht** [comment]
Keep in mind that the transformers do need to be in step up mode. So 16 A HV = 4 A EV etc.
