### ISSUE TITLE
Bee Frames

### ISSUE THREAD

**Issue by Zoko061602** [GTNewHorizons/NewHorizons#2621]
#### Which modpack version are you using?
2.0.2.7
#

#### What do you suggest instead/what changes do you propose?
Change the Thaumonomicon description of all Magic Bees Frames, since they are using the description from Thaumcraft 3 (I'm not quite sure about it, but I think TC 4 doesnt use differnt kinds of flux).

I think it would also make sense to add a shift tooltip to all frames, that shows what they do, because it is pretty annoying, to go though the Thaumonomicon, or the code of  some mods, to look the stats of a frame up.

**Comment by mtesseracttech** [comment]
I'd like to second this till some degree. While I am not entirely sure about the TC stuff (since I haven't played with magic bees yet), adding proper descriptions to the frames would be nice. Especially since some of the names of items don't seem to exactly match the tooltip at this moment. (Mutagenic frames being the main one that springs to mind). Since how would something wildly mutating really cause only the fittest to survive?

**Comment by Dream-Master** [comment]
@Zoko061602 can you write a new text for me i could add?

**Comment by MineAnPlay** [comment]
The stats of all the frames (for the shift preview):
https://docs.google.com/spreadsheets/d/18oEfhi5ttxPLilxUjkBmOWIwRiB-mtXb8jzW_H93ftM/edit#gid=0

**Comment by mtesseracttech** [comment]
@MineAnPlay I think the "Busy" frame is the "Working" frame.

**Comment by MineAnPlay** [comment]
Not made by me so... :P

**Comment by Zoko061602** [comment]
I made some Minetweaker Code:
https://pastebin.com/VkYVNLxN
It adds a ShiftTooltip to all Frames and shows the best stats (like TConstruct durability)

**Comment by Dream-Master** [comment]
@Zoko061602 do a pull request I can merge it into the pack

**Comment by mtesseracttech** [comment]
@Zoko061602 nice work!
