### ISSUE TITLE
[Suggestion] Add Cinnabar/Quicksilver to Sifter

### ISSUE THREAD

**Issue by Axiflare** [GTNewHorizons/NewHorizons#2641]
Just figured it'd be siftable after washing due to the fact it's a pearl, or gem-like object. If this results in too much mercury for your taste then maybe reduce the percentages of extra results.

**Comment by bartimaeusnek** [comment]
Well, HgS is commonly dissolved and then scooped from the surface of the dissolving fluid (see "Wirtschaftsgeologie der Erze" and "Froth flotation"). But yes, HgS should exist as a Gem aswell. But in our pack, we only have Hg as item (which is non-logical, due to its fluid state). All in all is mercurry easily obtainable by centrifuging redstone, so i don't see any reason why we shouldn't add it. If @Dream-Master is in agreement, i'll add this to the core mod.

**Comment by jiamingc0824** [comment]
Sifting for cinnabar is ok but definitely not for mercury.

**Comment by noobyaran9** [comment]
Sifting for cinnabar is ok but definitely not for mercury.

**Comment by Axiflare** [comment]
Yeah, a few rounds of 'cinnabar sifting' would probably leave you with a LOT of mercury. Add that, plus the large amount of magnetite veins, and you've probably got enough gold that it isn't rare anymore. Although it's _definitely_ faster than redstone centrifuging... cough...

**Comment by Dream-Master** [comment]
give the cinebar the gem suffix maybe aouto add it idk.

**Comment by bartimaeusnek** [comment]
> Although it's definitely faster than redstone centrifuging... cough...

 nope, added Cinabar 2 Mercury sifting with approx. 1/2 the speed as redstone centrifuging.

**Comment by Axiflare** [comment]
Still the same % for bonus outputs but takes twice as long as centrifuging redstone seems good. Glad I could suggest something!

**Comment by mtesseracttech** [comment]
To me this seems a bit strange, considering that quicksilver is literally liquid mercury that in TC likely just is this way because of practical reasons.
