### ISSUE TITLE
[Suggestion] Add a recipe for Damascus Steel

### ISSUE THREAD

**Issue by pgelinas** [GTNewHorizons/NewHorizons#2651]
#### Which modpack version are you using?
2.0.2.7

#
#### What do you suggest instead/what changes do you propose?
Add a recipe for obtaining Damascus Steel through processing instead of only through coins. Probably something in a "Thaumcraft" way, like the steel transmutation/alchemy recipe but more advanced. The InifiTech2 modpack is a nice example of this and I think it would fit nicely.

**Comment by Kortako** [comment]
Isn't there a recipe for making Damascus Steel dust?

**Comment by richardhendricks** [comment]
There is only a shapeless recipe, which is strange.  Maybe worthwhile to add mixer recipes?

![2018-02-27_23 04 28](https://user-images.githubusercontent.com/1214811/36770860-9188b9dc-1c12-11e8-81d2-3884ad9f0199.png)

**Comment by Dream-Master** [comment]
If it had more than 6 items I can't. Will check.

**Comment by eloquentJane** [comment]
There are seven different items in the first recipe (steel dust, small nickel dust x3, tiny manganese dust, tiny chrome dust, tiny coal dust, tiny silicon dust, and tiny molybdenum dust). The second recipe only has six different items though (steel dust, small manganese dust x2, small chrome dust x2, tiny silicon dust, tiny vanadium dust, tiny coal dust), so that one could theoretically be done in the mixer.

**Comment by pgelinas** [comment]
Wow, ok I completely missed that recipe. Maybe I'm not meant to have access to that yet anyways 😛

**Comment by bartimaeusnek** [comment]
@eloquentJane the first one can be done in mixer aswell if we any of these materials as molten.

**Comment by mtesseracttech** [comment]
@bartimaeusnek I think that would solve nothing really. It would be both counter intuitive (since you get a metal dust from something that is partially liquid).
The only idea I can come up with is to keep it as is, add the 6 item one to the mixer and add recipes to the GT++ alloying system if people really want it to be done in machines.

**Comment by bartimaeusnek** [comment]
Acutually, i dont think we need a mixer recipe for this. damascus steel is only used in LV/MV and only in small ammounts, if i remember it right...

**Comment by richardhendricks** [comment]
True, it's good for weapons and tools mostly for toughness.

**Comment by mtesseracttech** [comment]
Exactly, and if there really was a good incentive to do so (maybe SuperTiC could add some cool things to it) I think making some batches by hand is not the biggest of problems. Otherwise, GT++ could have the recipe if it really needs to be automated using machines.

**Comment by draknyte1** [comment]
No harm adding Dam. Steel to the Alloy Blast Smelter.
What's the shapeless recipe?

**Comment by Dream-Master** [comment]
I add a recipe where you can craft Damascus steel dust and put it in ebf. I am against put it in alloy smelter. If it fit into mixer  (6 slots) I am ok with it. If not I close this issue.

**Comment by eloquentJane** [comment]
The only particularly good uses I can think of for Damascus Steel are using it for crafting tools (for high durability) and using it for Tinker's Construct tool rods (for high durability multiplier). I really don't think it's super necessary for it to be automated.

**Comment by Dream-Master** [comment]
No i wont add it to the mixer because 7 inputs.

**Comment by DietmarKracht** [comment]
@draknyte1 where is the ABS recipe? I cant find it actually. There is only the general dust to fluid recipe but no other recipe

**Comment by draknyte1** [comment]
Probably wasn’t ever added. Make a ticket on my GitHub and I’ll get to it.
