### ISSUE TITLE
Quest 33 (Tinker-time) only detects part builders made of oak barricades

### ISSUE THREAD

**Issue by NauticalOx** [GTNewHorizons/NewHorizons#2656]
#### Which modpack version are you using?
2.0.2.7
#
#### What did you try to do, and what did you expect to happen?
Tried to complete Quest 33 using a part builder made from spruce barricades. Expected quest to detect non-oak part builders.
#
#### What happend instead? (Attach screenshots if needed)
It was not detected until I crafted an oak part builder instead.
#
#### What do you suggest instead/what changes do you propose?
Make the quest detect part builders made from the other woods.

**Comment by Bryfer** [comment]
Duplication of #2172 ?

**Comment by Dream-Master** [comment]
And not possible to fix. Quest can use oredict or item.

**Comment by richardhendricks** [comment]
Has a comment been added to the quest to

1 - Warn players only oak-based goods work
2 - That oak saplings are available from the coins tab

**Comment by Dream-Master** [comment]
so far i know there is a comment and a quest where you can buy saplings (oak)

**Comment by MineAnPlay** [comment]
There is a quest but it requires 5 forestry coins but to get that many you need to do quests that are later then the bed quest.

**Comment by Dream-Master** [comment]
Ok then i need to reduce it or change it.

**Comment by WarlordWossman** [comment]
Maybe the oak one you need for the quest can be made by all barricades (so you will craft the right thing all the time) and you can rotate through the other wood colors by putting it into the crafting table or using a chisel (if we really need dif color part builders, it's not super important imo)

For this example I think ignoring the fact that you will be able to make the oak one with any log will work because the item is not decorative anyways. The focus here should really be on the quest working smoothly so we should go with all barricade types making the oak one just to simplify it imo.

**Comment by Dream-Master** [comment]
Yea switching it to oak are possible I guess.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/37203878-6f07af42-238f-11e8-978d-aaeddd86aec8.png)
