### ISSUE TITLE
[Suggestion] Thaumcraft useful things quests

### ISSUE THREAD

**Issue by rekongstor** [GTNewHorizons/NewHorizons#2702]
#### Which modpack version are you using?
2.0.3.0
#

I suggest to add some recipes for handy items like Arcane Lamp (incredible amounts of light) and Runic shield items (helps much with mobs) especially with Amulet of Vis Storage and its upraded version - Collar of Pain.
Also there're a lot of handy Wand Focuses. Useful with Vis amulet and Thaumic Bases bracelets (they're still broken)
Explosion (small warp) is for early explosions before Mining Laser (e.g. helps with AE singularities). Also everybody loves explosions.
Blink is kinda useful in various situations.
Equal Trading is good for building especially with Builder's Wand. Can change block at incredible speed.
Portable Hole helps finding ores and helps in Twilight Forest with blocks with high hardness.
Warding is useful for Wither killing and base defending
Flux Scrubber helps with Flux and decreases normal and temporary Warp after augmentation
Mending helps much at early Blood Magic - instantly heals a lot of HP
Dislocation is handy Mob Spawner "dolly" with potantially infinite usage.
Illumination are Thaumcraft infinite torches.
And more, and more useful stuff.
Of course you should add Focal Manipulator quest after Vis Relays and first Wand Focus quest for enchanting these Focuses.

**Comment by ForTheHorde01** [comment]
All thaumcraft items have their recipes after you unlock them in thaumonomicon

**Comment by rekongstor** [comment]
@ForTheHorde01 at least I suggest to add more useful things to Quest Book. I know a lot of "gregged" people bad with magic skills. Combining tech and magic in most ways makes thing easier especially in GTNH

**Comment by Dream-Master** [comment]
Ok so new quests.

**Comment by ForTheHorde01** [comment]
we Don’t need more magic quests, rewards are shit anyway from bags thanks to whoever balanced them, also ppl are forced to do magic stuff if they want to get infinity armour for example which requires top tc/bm parts. Modpack is based on gregtech ofc and ppl who want magic they go for it, if they don’t want they don’t. Simple as that

**Comment by rekongstor** [comment]
@ForTheHorde01 I thought this modpack is more like more hardcore Greg and Gregged mods. And these mods surely have to balance some hardcore in modpack. These badass infrenal mobs as example become non-sense earlier due to Runic shielding cause Nano armor set can't absorb them properly. Early-game item and even player teleportation between dimensions comes with magic. There're many more examples of life-hacks with magic stuff.

**Comment by Wolozo7** [comment]
I disagree with your idea of what "we" need. The purpose of quests for me is not the rewards for said quests, but to guide the player, especially the ones who are not absolutely familiar with the used mods, through those mods. In that context, hinting the player towards those useful, but potentially not well known items (like certain foci, the hungry tank, runic shielding baubles, that magic redstone stuff) helps diversifying player progression paths and gives them new options to solve the games obstacles.

The need for quests becomes more apparent when looking at Witchery, because TC is rather well documented with the Thaumonomicon. Witchery adds a ton of moderately useful stuff as well, but since it doesn't have decent books or quests, players either know about the features or pass by them without a clue.

**Comment by ForTheHorde01** [comment]
I assure you there’s only like 5% only who never played with tc and magic stuff. Everyone else who found this modpack know tc better than the mod author i bet xd and also tc is ez enough to be understandable by newbie with tc as the current quests shows you how the basics works and thaumonomicon explains u all u need to know. Also there’s shit tons of vids on yt showing/explaining how any of tc multiblocks works. Not sure if u did notice there’s 3 or 4 tabs with thaumcraft quests too

**Comment by richardhendricks** [comment]
More quests is good.  I've played with TC before, and I don't know the usefulness of the various wand foci.  I think another quest tab focused on wand foci (hur hur) would be great.

**Comment by mtesseracttech** [comment]
Can't really say no to new quests, I can write a few.
I'd like some help though on guiding the players through the wand system, since it's very strange if you are not used to it (it looks like it's not possible to get from one tier to another, even though you can).
This could be tiered using the Twilight Forest boss quests.

**Comment by Dream-Master** [comment]
Wand Focus fro Thaumic Bases and Horizons following after i nerf these mods.
