### ISSUE TITLE
Excessive cooling of superconductors

### ISSUE THREAD

**Issue by CalterOK** [GTNewHorizons/NewHorizons#2735]
All recipes in a vacuum freezer pass at the same voltage (120 U / T) and for the most part take no more than 20 s. The added superconductors require 480 IU / t and are cooled from 450 s to 750 s, which in my opinion is too much. If you want to increase their cost for energy, it is better to use a blast furnace for this because they are more common or increased

**Comment by richardhendricks** [comment]
I don't really see why upgrading a single energy hatch would be a big deal? By the time you're doing that anyways, you should have plenty of higher power options.  I vote to leave it as-is.

**Comment by codewarrior0** [comment]
For comparison, cooling Hot Neutronium takes 120 EU/t for 312.5 seconds. The next one down is Hot Naquadah with 120 EU/t for 49.5 seconds.

**Comment by Dream-Master** [comment]
I could change it too.

**Comment by Dream-Master** [comment]
Maybe default recipes are not the best one.

**Comment by Prewf** [comment]
Glad this was brought up. It's just inconsistent..the 2.0.3.0 superconductors are the only vacuum freezer recipe that requires HV tier power and are on their own level in terms of processing time. It seems kinda arbitrary, because the wires themselves are already appropriately gated, why make the vacuum freezing step extra convoluted?

I mean I get it, they are superconductors, they're supposed to be difficult/painful to get, but it's just inconsistent in terms of recipe with what we're normally used to with vacuum freezer recipes. It's like how there are no MV or HV tier implosion compressor recipes (so far) that I've run into. My suggestion would be to keep it at 120 EU/t for consistency, but keeping a long processing time since they are high tier stuff after all.

**Comment by Dream-Master** [comment]
No i will put more materials to higher voltage like ebf recipes.

**Comment by Prewf** [comment]
I guess that works too

**Comment by CalterOK** [comment]
In my opinion, it would be logical that the cooling time depended on the temperature at which the ingot was created.

**Comment by Takafate** [comment]
450 s or 750 s are really excessive. If they stay like this, that world only drive me to build more freezer other than upgrading them. I already have 7 freezer at EV, they are enough for 9 EBF at ZPM and 2 at LuV. But they are far less then enough when i deal with superconductor base material. Freezers are really cheap, they don't take much room or produce pollution. Building an extra EV freezer save me 4096 EU/t and do the same thing as an IV one can do. Putting more materials to higher voltage is fine, but please reduce cooling time at the same time.

**Comment by codewarrior0** [comment]
For all the base GregTech hot ingots, it computes the vacuum freezer time from the material's mass and creates the freezer recipes automatically. I wonder if it wasn't creating recipes for the new alloys, and that's why they had to be hardcoded?

**Comment by Dream-Master** [comment]
Yes it creates recipes but very short time at 120 eu/t

**Comment by bartimaeusnek** [comment]
@codewarri0r for balancing reasons :p
