### ISSUE TITLE
GT++ Alloy blast smelter needs balancing

### ISSUE THREAD

**Issue by K1ngMX** [GTNewHorizons/NewHorizons#2750]
#### Which modpack version are you using?

2.0.2.7
#### What did you try to do, and what did you expect to happen?

The alloy blast smelter is just not balanced 
#### What happend instead? (Attach screenshots if needed)

Here is an example: Tungstensteel
![image](https://user-images.githubusercontent.com/5102870/37870110-bd42b19c-2fc5-11e8-87b7-d43faee452cb.png)

here is stainless steel:
(removed, since this will be fixed in the next version)

this are only two examples, there are seriously a lot of recipes which are just wrong. This includes a lot of "you may optionally add this fluid in the EBF"-recipes
#### What do you suggest instead/what changes do you propose?

All the recipes for the alloy blast smelter need to be balanced.
I get the idea of "have this machine, it saves you a couple of percent of power", but:
1) the alloy blast smelter does not need coils
2) it doesnt respect power requirements
3) it gives you direct fluid 
4) it skips vacuum freezer steps

After talking with Dream, i think it is not possible to just change a config as far as i understand, so it always requires a code change in the gt++ code (which is "all rights reserved", im not sure about licensing things, but this doesnt sound that good).

ALL the recipes for the ABF need to be fitting for ALL the gtnh recipes. If it only saves you 20% power: ok. But like it is now you can skip big parts of progression.

**Comment by Dream-Master** [comment]
@draknyte1 still not fixed in dev (2.0.3.1)

**Comment by K1ngMX** [comment]
Here another example: desh ingots
![image](https://user-images.githubusercontent.com/5102870/37870196-eb5ae0e8-2fc7-11e8-8b5d-e8d74f22ee68.png)

**Comment by K1ngMX** [comment]
Manyullyn
![image](https://user-images.githubusercontent.com/5102870/37870237-799b86dc-2fc8-11e8-95ef-38a55816d30c.png)

**Comment by K1ngMX** [comment]
Nichrome:
![image](https://user-images.githubusercontent.com/5102870/37870241-99a907ba-2fc8-11e8-9ce3-3fd508dfb281.png)

**Comment by K1ngMX** [comment]
Tungstencarbide:
![image](https://user-images.githubusercontent.com/5102870/37870249-d0c98530-2fc8-11e8-811b-5b7a5fdab12c.png)

**Comment by K1ngMX** [comment]
Trinium:
![image](https://user-images.githubusercontent.com/5102870/37870270-84491cd8-2fc9-11e8-951d-f2259f76dd22.png)

**Comment by K1ngMX** [comment]
Redstone alloy:
![image](https://user-images.githubusercontent.com/5102870/37870289-19383324-2fca-11e8-8d3f-504b2d66d5ca.png)

**Comment by K1ngMX** [comment]
(i think you see what i mean)

**Comment by draknyte1** [comment]
You know, testing against 2.0.2.7 isn't valid at all for GT++ issues.
I will not accept them, nor try fix them.

Tungsten Steel and Stainless Steel in the ABS have already been fixed.
Refer to: https://github.com/draknyte1/GTplusplus/commit/077d55642ea436b2338dd1f866bdbe95969f3aba

**Comment by Dream-Master** [comment]
I Test it against newest gt++ code and it not work for me also. @draknyte1 Is there a new config option I not see?

**Comment by codewarrior0** [comment]
It's probably the dynamic ABF recipe generation that's doing it. The dynamic recipe generation doesn't even *look* at the base EBF recipes and always uses 120 EU as the process cost.

**Comment by Dream-Master** [comment]
Yea we put those EBF recipes to the core mod and add Gas to the recipes and changinge the auto gen time.

**Comment by K1ngMX** [comment]
>I will not accept them, nor try fix them.

okay. I dont see a compiled version in your repo. Also, your commit shows that you are checking if gtnh core is in the pack at all, so i couldnt just throw a pack with only gt and gt++ in a mini pack to test it. Any recommemdation for me how to test it? No idea if gtnh core has other dependencies at all. I specifically made screenshots of the recipes that i have found so others (with more knowledge :) ) can check it quickly, but i can also test it. 

Point was just, i talked with dream, who told me that the recipes are still wrong in the current version.

**Comment by draknyte1** [comment]
> It's probably the dynamic ABF recipe generation that's doing it. The dynamic recipe generation doesn't even look at the base EBF recipes and always uses 120 EU as the process cost.

It's a direct rip of code from the .09 EBF generation.. With a modifier on the time.. That's it..
The issue stems from the fact GTNH doesn't use the vanilla GT generation and then tweaks things outside of that..

> your commit shows that you are checking if gtnh core is in the pack

Well, yeah, because these changes are ONLY for GTNH.. 
Because I am happy to add the mod-pack specific features.

> okay. I dont see a compiled version in your repo

The latest release on github is probably the latest release on Discord, which is probably the latest release on CurseForge. I don't ensure the code on Git is 100% compilable, it's simply a place where I store my code and at no given commit is there a guarantee on this. I suggest Forking it, rolling back to a release tag and then making the appropriate changes to the recipes class.

**Comment by K1ngMX** [comment]
I would suggest some kind of config, instead of hardcoding it like "!CORE.GTNH ? 120 : 480". If this would be the case, i could simply talk to dream and we can fix it without bothering you.
The latest release (found here: https://github.com/draknyte1/GTplusplus/releases) is 17 days old, so there would be no chance for me to test it.

**Comment by draknyte1** [comment]
As I've told you before, I won't add config options for everything. I do not feel this is worth one either.
I'll probably send Dream a compiled version tonight or tomorrow, depending upon what I get up to.

**Comment by K1ngMX** [comment]
>An easy fix to support for GTNH, but when you guys tweak core machine mechanics/code [...]
>Well, yeah, because these changes are ONLY for GTNH..
>As I've told you before, I won't add config options for everything. I do not feel this is worth one either.

see, that is the exact reason i think a config is necessary. Dream should be able to fix recipes for his pack, the mod shouldnt try to implement stuff for a modpack it is used in.

**Comment by Dream-Master** [comment]
Why not make all recipes use min 480 eu/t  or change it to ingots and hard parts not dusts ?

**Comment by Prewf** [comment]
Not disagreeing at all about how easy to ABS recipes are compared to the "normal" way. 

However, about the original post, you can't skip "progression" per say with just the ABS. At least, not *that* much, because the pack itself already has a gate behind these things.

Your examples have desh, TUNGSTENsteel, and TUNGSTENcarbide, which already require HV-tier machines (HV assembler for the t2 heavy alloy ingots for t2 rocket for Mars, where the relevant ores exist. Not to mention an EV assembler for the Mars suit).

Progression-wise, it would *seem* like you could skip kanthal and go straight to nichrome, but kanthal can't be skipped because the alloy smelter controller block itself needs titanium. You need kanthal in the first place to process titanium to get the alloy blast smelter, not to mention a trip to the moon. Once you have the ABS though, you can get nichrome without an HV-tier EBF. TBH, I don't see what anyone would gain by skipping an HV-tier EBF by the time they have visited the moon. There are ores that a fully upgraded EBF will need to process into order to progress to EV-tier, that an ABS cannot help you with.

I'm running 2.0.3.0 and trinium doesn't have an ABS recipe, only an EBF recipe. Maybe some recipes were already nerfed in this patch? In fact, I don't really see too many high tier ingots in the ABS recipes within NEI.

**Comment by Dream-Master** [comment]
We disable all recipes over 3300K so far i rember

**Comment by K1ngMX** [comment]
Just to add: with progression wise i do not mean "until you break to that point", but take desh for example: you need more and more the farther you are into rocket making. You need 4 desh plates for every rocket ingot starting with tier 3, and you are required to make a lot of them (look at rocket engines for example). So, i know it doesnt make the initial ones easier, but it is a massive discount later on.

**Comment by draknyte1** [comment]
Think this is well resolved since ABS recipes are all generated based on EBF recipes that already exist.
