### ISSUE TITLE
[RFC][Balance] Move food cans to HV

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2821]
Food cans are awesome.  I think they're actually better than the healing axe since you can eat them immediately instead of waiting around for food to fill.

I think though they are a little too much of a reward at LV, since they completely negate the Spice of Life food diversity.

I propose moving the food can extruder recipe to using stainless steel.  This would require either finding stainless in the world (not super hard) or getting to HV level.

This ticket is to start discussion on a balance change.

**Comment by WarlordWossman** [comment]
I don't think that's a good idea, the healing axe has other utility reasons like being an unbreakable axt I can put into one of those EnderIO farming stations and can be used to heal mobs.

Tin cans on the other hand require ressources in the making and have you refilling them with machines (besides batteries the only reason I would touch a canner since the gt++ tanks can cells for free).

If you wanted to give them a more industrial feel they could take longer to make (3 or 4 times even?) so you would want to get a higher tier canner up.

**Comment by 0lafe** [comment]
What about HV canner, using aluminum or steel? Would take longer and need HV, but you can still make them in bulk for the most part

**Comment by richardhendricks** [comment]
yeah but once you can go into the nether there isn't much stopping you from getting the first axe.  A second axe requires killing the wither.

**Comment by WarlordWossman** [comment]
@0lafe doesn't really sound like a good solution to me, as I said encouraging people to use machinery and automation is a main theme of the pack and harvesting/crafting food by hand is mostly just annoying imo.

@richardhendricks what is your point here? If the axe is easy to get tin cans should technically be less of a problem since the axe also gets rid of the spice of life part.

**Comment by richardhendricks** [comment]
OK @WarlordWossman and I talked for a bit, here's an idea:

Make the recipe for food + empty can => filled can have a 90-95% success rate.  Add an empty stainless steel can and filled stainless steel can.  food + empty stainless steel can => filled stainless steel can have 100% success rate.

Remove recipe to create cans using normal steel.

This way players at LV, if they have some extra tin, can use it to make cans. Once they get to HV, they can make permanent cans.

And if they want, they can chase the healing axe quest.

**Comment by richardhendricks** [comment]
After some discussion, propose making 2 tiers of cans, tin & aluminium.  Make tin cans craftable with the otherwise useless LV extruder.

**Comment by CalterOK** [comment]
But cans are another intermediate stage, the next step will be the creation of a talisman of satisfying hunger automatically.

**Comment by draknyte1** [comment]
> since the gt++ tanks can fill cells for free  

You mean, Since any GT Tank Entity will fill containers for free*
Hatches work the same, so do super and quantum tanks.
