### ISSUE TITLE
SMD Components Quest

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#2838]
2.0.3.0

Quest ID: 1030

This quest states that smd components are cheaper than normal components however this is not true as they, diodes and transistors require much more gallium than standard materials.

**Comment by bartimaeusnek** [comment]
@Dream-Master we could nerf the normal diodes and transistors here

**Comment by septemberWaves** [comment]
The most efficient way of making ordinary diodes produces 8 diodes per small gallium arsenide dust, or 32 per whole dust. SMD diodes take 1 gallium arsenide dust to produce 32 diodes, meaning they take exactly the same amount of gallium as ordinary diodes, while also taking less polyethylene (although they do require platinum instead of annealed copper).

Regular transistors don't take any gallium, but the amount of gallium foil used for making SMD transistors is so little compared to the transistor output that you can make a stack of SMD transistors from a single gallium ingot (with an identical polyethylene cost per transistor, but using annealed copper instead of silicon and tin).

Where the SMD diodes _do_ start to consume more gallium than ordinary diodes is when using wafers instead of gallium arsenide dust; in this case, one monocrystalline silicon boule produces a stack of diodes, and each monocrystalline silicon boule takes only a small pile of gallium arsenide dust, meaning that with the wafer method you produce 8 times as many diodes per gallium arsenide than any other method. It does however require a 450-second blast furnace recipe to produce each silicon boule.
