### ISSUE TITLE
Glowstone Doped Monocrystalline Silicon Quest

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#2839]
2.0.3.0
Quest ID: 1237
This quest has the wrong quest description.

**Comment by Dream-Master** [comment]
Maybe fixed in 2.0.3.1 ?
![image](https://user-images.githubusercontent.com/2970688/38907517-45d8dbac-42e6-11e8-8c67-a44aef8f7a16.png)
![image](https://user-images.githubusercontent.com/2970688/38907540-5f10ae7e-42e6-11e8-9da8-3bc9a97d5370.png)
![image](https://user-images.githubusercontent.com/2970688/38907554-6c1cf230-42e6-11e8-9d21-30741c12501c.png)
@Anarack 
can you check what is wrong here?

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/commit/fcbd4cc1d975181fb39fe144bc2824312d58e6a8

**Comment by Anarack** [comment]
It had the description of the previous tier of silicon boule quest in 2.0.3.0 but those screen shots are correct now.
