### ISSUE TITLE
Golden Bag

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#287]
@Drobac 
If you missing items I refund it to you.

**Comment by Teteros** [comment]
The angel ring needed some diamonds too, you know? ;)

**Comment by Dream-Master** [comment]
I know but no. We have enought way to fly. If you realy want it i can make it out of Dense Neutronium Plates ;-)

**Comment by Teteros** [comment]
Hehe, was just taking what little chance of refund I have,  for the items it needs to be crafted with.
I agree the forementioned items needed to go though.

Since I hijacked this issue anyways, thanks for only disabling the recipe for projectred bags rather than the items themselves. I had lots of valuables in those to save.

**Comment by Dream-Master** [comment]
The Normal Bags have 4 Row the big one 8 you can use 4 Bag that is enought space to go minig.

**Comment by Namikon** [comment]
BIg bagpacks still have only 4 rows. Maybe they only have 8 Slots after you re-craft them?

**Comment by Dream-Master** [comment]
We have to exchange all Bags because of the new Size.

**Comment by Dream-Master** [comment]
Done if not reopen it again.
