### ISSUE TITLE
[Suggestion]Chlorine for late/end game

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/NewHorizons#2878]
#### Which modpack version are you using?
2.0.3
#
#### What do you suggest instead/what changes do you propose?

With no more pams salt, and chlorine coming from ghast tiers, end game is going to have some issues. I personally use close to 16B of chlorine per second, but getting 16 ghast tiers a second has its problems. Large scale mobfarms kind of mess up with the teleporting and web placing mobs. 

My idea is a fusion recipe for chlorine would be Oxygen with Hydrogen. It sorta works out chemically. Both are pretty easy to get, but it would still make chlorine harder to get than it is right now. Maybe have it take some mk1 eu/t value, and maybe at 16000L hydrogen and Oxygen to make 32000L Chlorine and take 8 seconds. It would be pretty close to the cost of electrolyzing salt right now, but would need a fusion reactor, and a decent amount of power. Not to mention the cost of 16B of oxygen and hydrogen. It's still more work that what we have now, but it's better suited for LuV+ than ghast tears are. 

Maybe something like 8192eu/t for the recipe, and some starting EU that will put it in the MK1 category

PS

pretty sure @Cinobi has an issue with it too, and Pie might, couldnt really tell his opinion from earlier.

I use chlorine for silicone rubber, which I use for wetware circuits, and sometimes cables. I also use it for epoxy which I use for circuits as well as carbon mesh. I use it for titaniumtetrachloride, which I use for PTFE, polyethylene and glue, which I use for circuits, machines, and duct tape. I use it for HCl which I use for iron3chloride which I use for circuits. I use it for HCl which I use for one of the oil things, I think epoxy but it could be silicone. I don't craft chlorine as I need it, I have it constantly running to fill buffers that then get used in AE crafting, such as epoxy boards, carbon mesh, iron3chloride, and such. That way, I don't need to wait for thousands of epoxy to be crafted so I can make one of the 32 stacks of EV machines I need to fill a PA with.

I used to use an EV PA of LV machines to make chlorine, but it was always holding everything else up, so I tried an IV one, then had to change to an LuV one. It still struggles to make chlorine, but it can sometimes almost keep up, and more often than not, makes the slowest aspect, my oil production/refining into propene.

**Comment by richardhendricks** [comment]
Looking at a couple alternatives for salt production
https://github.com/GTNewHorizons/NewHorizons/issues/2854
https://github.com/GTNewHorizons/NewHorizons/issues/2842

**Comment by richardhendricks** [comment]
Salt ore in the pulverizer gives 4 crushed salt and 10% rock salt dust.
Rock salt ore in the pulverizer gives 4 crushed rock salt and 10% salt dust

**Comment by noobyaran9** [comment]
Suggestion:
Buff salt ore output to something like 12 or 20 crushed. Honestly, i dont think this number is wrong.
RL salt ore is way more denser than this.

https://en.wikipedia.org/wiki/Salt_mining

**Comment by richardhendricks** [comment]
![2018-04-29_03 22 54](https://user-images.githubusercontent.com/1214811/39404645-a8aaeb0c-4b5c-11e8-8e00-6799849c5bf8.png)
Fulled mined out salt vein using an HV single-block miner = ~22 stacks.  Would be ~88 stacks crushed with current numbers. Gives 88*1.1 = ~97 stacks of KCl or NaCL dusts, or about 3,104 buckets of chlorine

As a point of comparison, turning 8 stacks of Rutile (not that hard to get) into titaniumtetrachloride takes ~2048 buckets of chlorine.

Other mitigating factors - large ore drilling plant will give ~3x the amount of crushed ores.

**Comment by DarkShadow44** [comment]
> With no more pams salt

What do you mean? You can use a water bucket with pam's harvestcrafts pot to make salt, and that you can electrolyze. Did I miss something here?

**Comment by Anarack** [comment]
Its being removed or being made to only make salt that can be used for food.

**Comment by codewarrior0** [comment]
`As a point of comparison, turning 8 stacks of Rutile (not that hard to get) into titaniumtetrachloride takes ~2048 buckets of chlorine.`

512 buckets, unless you're voiding the magnesiumchloride?

**Comment by richardhendricks** [comment]
I was going to add the ratio for recovery when used for titanium next. But, it's not only for titanium, it can also be used for plastics production, in which you get none back.

**Comment by 0lafe** [comment]
Considering this is for endgame stuff, I guess I should add that I only use rutile for plastics and glue, never for titanium, and because of that never recover any chlorine. Also, we should probably be looking at ghast tier chlorine, as it's a higher tier method than salt ore, I think.

**Comment by codewarrior0** [comment]
But doesn't the tetrachloride used to process plastics like vinyl chloride actually represent a chlorine discount?

**Comment by 0lafe** [comment]
Don't think so. Does ptfe or polyethylene or refined glue use any chlorine? Anyway, it's barely used. If I make 630,000 plastic sheets, I will use as much chlorine as I make in 14min

**Comment by noobyaran9** [comment]
https://media.discordapp.net/attachments/440359501816659970/440359513158057994/unknown.png

>512 buckets, unless you're voiding the magnesiumchloride?

Magnesiumchloride? what are u talking about??

**Comment by 0lafe** [comment]
You get it when you process it for titanium instead of using it for extra output. After TiCl4 I think it turns into that

**Comment by noobyaran9** [comment]
>You get it when you process it for titanium instead of using it for extra output. After TiCl4 I think it turns into that 

Reprocessing magnesiumchloride into chlorine is out of the question then. People do use TiCl4 for making plastics and stuffs.

**Comment by repo-alt** [comment]
When extracting titanium from rutile you get insane amounts of TiCl4, but seriously, who uses rutile for titanium after getting to the Mars...

**Comment by richardhendricks** [comment]
I'm using it now because I am out of titanium ore from my Moon trip, I have tons of bauxite, and why not, it's a legitimate use for it.  I don't think "insane amounts" is correct, I think you only get 1B per rutile?

No kink-shaming, plz.

**Comment by 0lafe** [comment]
This issue isn't meant to Target people using TiCl4 for titanium. The problem is at UV+ you need a lot of Cl in a way ghast tears can't provide, nor salt ore. Fusion fixes it pretty easily, but a revamp for UU would work too I guess. Or some scaling recipe like silicon boules using glowstone/vibrant/naquadah. There could be a way to make chlorine from ghast tears that needs some gating material, like awakend draconium or infinity

**Comment by repo-alt** [comment]
Richard, I have a strange feeling that you are taking my words personally, please don't, perhaps my wording is incorrect, but I'm definitely not trying to teach anyone the "only right way" or anything. I also used rutile to get some titanium, but when you have pure titanium as an ore, getting it from rutile is just not efficient. (Now, when I played on a GT5 server where there were no titanium ore - everybody was quite content with rutile processing chain, but here titanium is required in massive amounts.) As for the the TiCl4 amount, yes, you get 1 bucket per dust, but when used as a catalyst it is used not by buckets but by 100L per recipe, hence my impression that you get a lot. Sorry for the offtopic anyway.

**Comment by richardhendricks** [comment]
No worries, it's not my primary source, as I said my stacks of titanium got used up (3 titanium boilers ftw) so I was starting on lower priority sources because I already mined out two veins on the moon and didn't want to have to search for more right now.

Anyways, sounds like plastic isn't a major use for it, and if we add alternate high tier ways to get large quantities that might work for everyone.

**Comment by 0lafe** [comment]
Get large quantities of what?

**Comment by Wolozo7** [comment]
I'm mildly confused by why there is a need for a both fast and infinite way to make Chlorine when none of its usages are indefinite. Maybe someone could calculate the materials required for whatever the common Lategameplayer regularly builds (a stack of EV machines was mentioned), to give a more imaginable idea of the need for Chlorine to those who haven't reached such a stage yet.

**Comment by codewarrior0** [comment]
`I use chlorine for silicone rubber, which I use for wetware circuits, and sometimes cables. I also use it for epoxy which I use for circuits as well as carbon mesh. I use it for titaniumtetrachloride, which I use for PTFE, polyethylene and glue, which I use for circuits, machines, and duct tape. I use it for HCl which I use for iron3chloride which I use for circuits. I use it for HCl which I use for one of the oil things, I think epoxy but it could be silicone. I don't craft chlorine as I need it, I have it constantly running to fill buffers that then get used in AE crafting, such as epoxy boards, carbon mesh, iron3chloride, and such. That way, I don't need to wait for thousands of epoxy to be crafted so I can make one of the 32 stacks of EV machines I need to fill a PA with.`

If chlorine were scarce, you'd use:

Vinyl chloride for cables instead of silicone
Polyethylene for carbon fiber
TiCl4 only for epoxy and vinyl chloride
Sodium perchlorate for circuits whenever possible
MV-line circuits (plastic board) for stacks of EV machines instead of HV-line (epoxid board) or EV-line (fiber-epoxid board)

**Comment by richardhendricks** [comment]
I don't think it's really relevant to the conversation.  We can play this game all week (How do you get Sodium Persulfate and Vinyl Chloride?), but I don't think it's offering solutions.

I think the best option is a mix:

 - Buff the pulverizer output from 4x to 12x for salt and rock salt ore. This is reasonable as salt is one of the most mined substances on Earth. This would work for low tiers
- Add salt water as fluid to planets.  Mars, etc as proposed in other ticket. Quantity would be 5x higher than current oil on some planets, with a good drilling plant should be plenty of salt/s.
- Add a distillation tower recipe for salt water - 2000L to 1 normal pile of salt every 2s at 120 EU/t.  This is equal output to the current distillation recipe recipe (500L to 1 small pile), but is much faster and can be accelerated with faster hatches (2s/MV, 1s/HV, .5s/EV, etc). 

If we still want to use the ghast tear solution, I think it should be a more magical solution rather than technical, since the tears come from a magical beast. Maybe an alchemical recipe that turns 1 tear into a quantity of salt (8? 32? Dunno what a good number is here) using terra, aqua, and ignis aspects? I think it could be automated simply enough for mid-tier players who don't want to mine salt anymore and don't need massive quantities yet.

**Comment by 0lafe** [comment]
And what about the endgame solution?

**Comment by richardhendricks** [comment]
salt water at 5x oil could give you easily 2000L/t, more with a higher tier drilling plant

With HV a distillation tower gives you 1 salt/s or 1 chlorine every 2s.  Since it's only 2 tall, it would be easy to have 2 or 4 to up rates.  So 2 chlorine/s should be easy with an HV setup.

Is that sufficient or do you think more is needed?

**Comment by 0lafe** [comment]
I don't like the use of the distillation tower because of how poorly it overclocks, nor do I like relying on something that needs chunkloading away from your base, and requires remote power transfer, as that doesn't really work at high tiers. It would need its own dedicated generator, which can't really be a fusion one. Needing to transfer power doesn't really work with fusion considering you can't really split power up very well with it. I don't see what's wrong with a fusion recipe for chlorine liquid from oxygen and hydrogen or something like that.

**Comment by 0lafe** [comment]
Chunkloading is normally controlled on servers. The one I played capped it at 60 chunks total. Wasting one on a drill just because it has to be far away from your base to work, seems dumb to me. If you can get UV+ levels of salt from HV or even IV power, then that's an issue itself.

The issues I mean are that it has to overclock like a singleblock machine, but is large enough you can't have too many of them because they will drop server performance if you have too many multiblocks. If it's an MV recipe, needing IV speeds from it is a huge waste of power. If lower levels can keep up, then again, that's also a problem. 

Fusion opens at the beginning of LuV I think. You need an assembly line, and possibly even wetware supercomputers if I'm remembering it right. I can't remember if those need zpm or not to make though. The problem with sulfur or phosphor is that you can't make those at the rates that would make the fusion recipe worthwhile. Using air products, or hydrogen works because of how you can make them in mass at higher tiers, but sulfur and phosphor don't work like that at all. In fact, phosphor is a huge pain to get at all, with sulfur being only slightly easier.

**Comment by noobyaran9** [comment]
>I don't understand the concern with power transfer. HV power could be easily provided with a single block turbine and supplied with the plentiful products, gas or fluid, available at tier. EV or IV power could be done with a large combustion or turbine, which should be more than enough on-site.

There exist a thing called ender tanks. 

>Chunkloading is a thing now, is it not? Why the reluctance to do it away from your base? Is the concern other players? Mobs? I just want to understand the issue.

More loaded chunk = more lag to the world. Which this whole thread is trying to increase by using more machines.

>I don't know enough about fusion, would that allow you the rates of chlorine you need? What tier does that open up? Chlorine from fusion should be from sulfur + hydrogen or phosphorus + helium.

I think I've seen chlorine plasma at some point.

**Comment by Anarack** [comment]
Not sure why you want a fusion recipe as if it follows the existing pattern even the fastest recipe L/t recipe you would need many many fusion reactors to keep up. At that point you might as well start replicating it.

**Comment by 0lafe** [comment]
>Not sure why you want a fusion recipe as if it follows the existing pattern even the fastest recipe L/t recipe you would need many many fusion reactors to keep up. At that point you might as well start replicating it.

The one I suggested uses times that would put an mk3 at the speed I was making chlorine before salt gets removed. So only one reactor, 2 if you're feeling particularly needy for chlorine. 

>There exist a thing called ender tanks.

moving the fluid isnt the problem, it's generating the power once it's there. Not too bad up to UV, you can just use a naq reactor without it being a huge problem. I just think it's dumb you need a whole new power generator just because this thing has to be far away.

**Comment by richardhendricks** [comment]
>More loaded chunk = more lag to the world. Which this whole thread is trying to increase by using more machines.

Please, be serious.

Considering the large bases I've seen at high tier, an extra 9 chunks loaded on a desolate planet with ~4 machines is hardly a cause of major server lag.  Ore drilling plants or ender quarries would be more lag since they would actually touch blocks in the chunk. Oil drilling plants don't touch blocks once they hit bedrock. 

How much lag do you think the automated setups spamming Pam's salt at ridiculous speed is creating? 

If there's an issue with remote chunk loading due to reliability or feeding coins, fine. But crying "lag" is just not productive.

**Comment by noobyaran9** [comment]
>How much lag do you think the automated setups spamming Pam's salt at ridiculous speed is creating?

Less than chunk loading a oil drilling rig. And adding setup to process salt water => salt => chlorine.

**Comment by 0lafe** [comment]
> an extra 9 chunks loaded 

yea that's way too much. I was complaining because I thought it was 1 lol

>Less than chunk loading a oil drilling rig. And adding setup to process salt water => salt => chlorine.

I'd agree, but the way I setup exu stuff was apparently using 40% of the server or something like that

**Comment by richardhendricks** [comment]
> The one I suggested uses times that would put an mk3 at the speed I was making chlorine before salt gets removed. So only one reactor, 2 if you're feeling particularly needy for chlorine.

I don't have a problem with this solution, it could be implemented as well.  I just don't think it offers much gameplay, with a box you just shovel in EU to get chlorine.  

So you're saying that you currently need about 16 chlorine/s.  With my suggestion I think an HV drill should give you plenty of salt water at a good spot, like ~100+B/s.  Maybe change the distillation tower recipe to 16000L salt water => 8 salt at 2s at Mv.  That should allow overclocking to get the quantities you need at EV. I'll update my proposal above.

>yea that's way too much. I was complaining because I thought it was 1 lol

Is there a single chunk chunkloader?  Anyways,  I don't think 3x3 chunks for drilling is that much of a server load, since it wouldn't have very many tile entities or block updates.

>I'd agree, but the way I setup exu stuff was apparently using 40% of the server or something like that

Yeah, exactly.

**Comment by 0lafe** [comment]
>So you're saying that you currently need about 16 chlorine/s. With my suggestion I think an HV drill should give you plenty of salt water at a good spot, like ~100+B/s. Maybe change the distillation tower recipe to 16000L salt water => 8 salt at 2s at Mv. That should allow overclocking to get the quantities you need at EV. I'll update my proposal above.

What I'm saying is that it shouldn't be possible at those tiers, but should have a way that it works at higher tiers by either requiring more machines (not necessarily placed in world, like the PA), or some other gated recipe or something

>I don't have a problem with this solution, it could be implemented as well. I just don't think it offers much gameplay, with a box you just shovel in EU to get chlorine.

You also have to supply it with a steady stream of fusion products. I don't see how it's different than your solution, it's just better suited for high tiers, and doesn't have the dumb quirk of needing a dedicated chunkloader and wireless power transfer

>Is there a single chunk chunkloader? Anyways, I don't think 3x3 chunks for drilling is that much of a server load, since it wouldn't have very many tile entities or block updates.

It's not as much of a server load problem as it is a limited chunks problem. On servers you will sometimes only be allowed to load X chunks, using any of those for something that clearly doesn't need it, doesn't seem like a good idea to me. Needing a dedicated chunkloader just because it's far away for no other reason than to be far away, I don't see the appeal.

**Comment by richardhendricks** [comment]
Ok, "limited chunks allowed to be loaded from servers" is a valid reason, but I disagree with the "just because it's far away" because that same logic applies to any remote machine like an ender quarry, ore drilling plant, implosion compressor, or oil pump now.

 I'll lower my distillation numbers back down a bit and add your suggestion too.

**Comment by 0lafe** [comment]
And the ender quarry should probably be switched out for some void ore miner, considering mining itself has huge server related issues. Ender quarries are so cheap, but you can't really have more than 1 per dimension because other people gotta mine there too. 
I have the same problems with the pump, and the ore drilling. That's why I make my oil from trees and mine with the exu quarry, because of the problems with things that are too far away. I have no idea what you mean about the implosion compressor though

**Comment by draknyte1** [comment]
I guess I could finish the bedrock miner in a hurry if it's really needed..

**Comment by noobyaran9** [comment]
>And the ender quarry should probably be switched out for some void ore miner, considering mining itself has huge server related issues. Ender quarries are so cheap, but you can't really have more than 1 per dimension because other people gotta mine there too.
I have the same problems with the pump, and the ore drilling. That's why I make my oil from trees and mine with the exu quarry, because of the problems with things that are too far away. I have no idea what you mean about the implosion compressor though

Keep ender quarry out of this topic please. Ender quarry is nowhere as fast as the any GT ore miner and it doesn't boost outputs. And it's not cheap considering it just caps around IV. 

Im fine at keeping things far away as long as it doesn't comes with a cost of server lag.

**Comment by 0lafe** [comment]
>Keep ender quarry out of this topic please. Ender quarry is nowhere as fast as the any GT ore miner and it doesn't boost outputs. And it's not cheap considering it just caps around IV.

Im fine at keeping things far away as long as it doesn't comes with a cost of server lag.

I just mean on a server, if I throw 4 quarries in each dimension at 0,0 people won't like that, but in single player its fine.

**Comment by noobyaran9** [comment]
>I just mean on a server, if I throw 4 quarries in each dimension at 0,0 people won't like that, but in single player its fine.

One quarry per person at one time should be a rule on the server.

**Comment by richardhendricks** [comment]
Server lag for the drill + tower is not a valid topic without legitimate numbers.

How many chunks are you limited to loading in the official or unofficial servers? How many players are reaching the tiers where they need this volume of chlorine?

**Comment by 0lafe** [comment]
The server I played did 60 chunks total

**Comment by codewarrior0** [comment]
>I don't think it's really relevant to the conversation. We can play this game all week (How do you get Sodium Persulfate and Vinyl Chloride?),

You missed my point entirely. He is spending literally a hundred times as much chlorine as is absolutely needed to craft a stack of EV machines.

**Comment by richardhendricks** [comment]
Sure, but the point of the game is **progression** not "how do I optimize my chlorine usage". If the correct player response to this is to require them to drop back to MV circuits and use other lower tier solutions, I think that's a serious issue with gameplay.

**Comment by codewarrior0** [comment]
Why do you say that? Hasn't there always been a tradeoff between using lower tier machines for power efficiency or material cost versus higher tiers for compactness or convenience?

**Comment by 0lafe** [comment]
Yea, but much like processing areays, you can't always use the most "efficiency" way. Circuits aren't really more efficient anyway, only that some use less chlorine. For my setup, it's faster, and I think cheaper, to make the highest tier possible. Except for the changing chlorine cost. 

Anyway, once you're in IV, crafting a stack of LV circuits isn't too bad. So why in UMV should it be so hard to make an EV circuit.

**Comment by richardhendricks** [comment]
Crafting LV machines to save power is a gameplay *choice* - you could choose to make LV machines  or use IV machines.  Not having enough chlorine to do high tier work is a gameplay *limitation*.  It doesn't open up new choices to make, but restricts them. And restricting them downwards is just poor tiering IMO.  It really ruins the sense of accomplishment of reaching tier X when you realize that you can't use tier X machines because of resource limitations and are stuck using tier X-3 * 8.

**Comment by codewarrior0** [comment]
Using a Replicator to print chlorine is also a gameplay *choice*. Has anyone figured out the tradeoffs for that?

**Comment by codewarrior0** [comment]
Chlorine's atomic mass is 36, which determines the UUM amount and duration of the replicator recipe. When supplied with UUA, a mass fabricator of any tier takes 25,720 EU to produce one UUM. An IV-tier fabricator consumes exactly 8192 EU/t; each tier below consumes half the EU as the one above (all tiers can input up to ten amps), and each tier above consumes only twice the EU as the one below.

The replicator takes 1024 ticks per atomic mass, consumes a full amp of its voltage tier, and uses standard overclocking, dividing the recipe time by two for each tier above LV.

The amplifabricator takes 5,760 EU over 180 ticks to produce one UUA. It also consumes a full amp and uses standard overclocking.

For each cell of chlorine, you need:
- 207,360 EU in the LV amplifabricator
- 925,920 EU in the mass fabricator
- 1,179,648 EU in the LV replicator
- ~30.1 LV-replicator-minutes
- ~5.4 LV-amplifabricator-minutes
- Plus whatever is needed to generate scrap

Total EU per cell is 2,312,928. Since the topic mentions 32 processing arrays each loaded with a stack of EV machines, it's relevant that one such processing array may consume 131,072 EU/t and would produce ~1.13 cells of chlorine per second if it could efficiently dedicate all of that EU to fabrication and replication.

The barrier to replication as a solution is that Replicator and Amplifabricator machines do not have free overclocking (which Mass Fabricators *do* have). To replicate at the above rate with maximum power efficiency, you would need around *two thousand* LV replicators and about six stacks of LV amplifabricators.

If the Replicator did have free overclocking, that throughput could be managed with a stack of EV replicators in an array, or a single ZPM replicator.

**Comment by codewarrior0** [comment]
Yeah, but since you're starting from salt and then using iron chloride instead of sodium persulfate for board etching, and then using silicone instead of vinyl chloride to make cables, I get the idea that your process lines aren't at all designed with chlorine efficiency in mind. I personally don't consider your base to be an example of what the end-game chlorine needs actually are.

**Comment by codewarrior0** [comment]
@bartimaeusnek The PA already supports amplifabs. While it is possible to support the others, you'd have to add in a lot of special case code because the PA works using standard recipe maps, which the Replicator and Fabricator do not use. @draknyte1 has already done this for his Industrial Mass Fabricator and the Replicator mode of his Multi-Machine.

**Comment by draknyte1** [comment]
I agree with @codewarrior0, that these choices shouldn't be based on 0lafes poor design choices. 

What's funny is, I've got semi completed solutions for all these things. Maybe Someone can ask Code nicely to do some touch up work while I'm in Japan, otherwise I'll focus on them prior to bedrock drilling when I return.

**Comment by noobyaran9** [comment]
>Yeah, but since you're starting from salt and then using iron chloride instead of sodium persulfate for board etching, and then using silicone instead of vinyl chloride to make cables, I get the idea that your process lines aren't at all designed with chlorine efficiency in mind. I personally don't consider your base to be an example of what the end-game chlorine needs actually are.

No matter what u use for board etching, u still need salt. Both sodium and chlorine are used quite alot in any plastic recipes.

>chlorine efficiency

i dont think this matter, if its chlorine efficient then, it must be sodium inefficient.

The point right now is how to generate salt, not chlorine nor sodium.

**Comment by richardhendricks** [comment]
Reading about the lava in Hawaii, they mentioned that lava flowing into the ocean makes a highly acidic steam full of HCl.  So, yet another proposal!

LCR only reaction
64 B H2O  + 32 B Lava => 32 B HCl + 32 NaOH + 32 Obsidian Dust, 16s 1920 EU/t
So at EV it is not super high speed (1B of Cl/s), but players could use other alternates (ores, fluids, ghast tears) at lower tiers or just wait/build a couple.

But it would allow scaling to very good speeds at high tiers (32B of Cl/s at UV).

**Comment by 0lafe** [comment]
it's quite a lot more than 32B/s at UV, but I guess I'm on board. I still think thaum lava generation should be buffed to accommodate for this, so you're not forced to pump the nether or something dumb like that

**Comment by richardhendricks** [comment]
Ah dammit, did the math wrong on that.  I was trying to back down from 32B of Cl/s at UV.  So that's 256x faster than EV, so EV needs to be .125 Cl/s, or .25 HCl/s.  So I think that's 128s at 1920 EU/t for the recipe:

**Comment by richardhendricks** [comment]
It would require 3,200 L/t of lava and 6,400 L/t of water at UV.  I think the Everful Urn can handle 9,999 L/t right?  How fast is the Everburn urn?

**Comment by 0lafe** [comment]
i remember it doing something really weird, like capping at 5B/s or something like that

**Comment by Anarack** [comment]
Blood magic can also generate lava, but idk what rate it can do per ritual.

**Comment by draknyte1** [comment]
Just enable underground lava pumping from the nether. (Since that lava already is full as hell with Lava, ba-dum tss)

Provides less lag and high flow of Lava, which can be run through a LHE to produce Pahoehoe (Hawaiian Lava), which can then be turned into the Steam @richardhendricks mentioned. The LHE steam could be used in the Nether to run the drilling rig setup, for a convenient closed loop power system.

Thoughts?

**Comment by 0lafe** [comment]
Really depends on rates, and how it scales. The problem I'm seeing is to make it doable for late tiers, it'll end up being buffed so hard, it will be the new meta for power. I like it again as a EVish tier solution, but I still think UV needs something that's actually aimed at that tier. LCR works great because it doesn't gate to UV, but it's just as useful in every tier you can use it. Drills don't overclock so well. If in UV I'm supposed to spend an amp of UV drilling lava to make chlorine, I could just spend that power to drill chlorine on any planet. It's not really a different solution for high tiers.

**Comment by richardhendricks** [comment]
Looks like the limitation is in the amount of ignis vis it can drain from around it.

https://github.com/GTNewHorizons/Thaumic_Exploration/blob/master/src/main/java/flaxbeard/thaumicexploration/tile/TileEntityEverburnUrn.java#L148

Every .5s it refills 1 vis if less than 16 vis.  Based on the conversion factor, it looks like the 2 vis per second is converted x250, so 500mB/s.  Not very much lava at all!

To make it work in this case would require significantly increasing the output, and testing to determine how big a node would be needed to meet the vis requirements and setting an appropriate conversion factor.

32-64 B of lava per second would be quite a lot of lava.  They are magical, so maybe that works.  With the current configuration that would require 128 ignis vis, which is probably reasonable with 4 nodes and empowering bees.

Looks like there was a lot of activity back and forth on the settings. @Dream-Master do you know why you settled on what you did?

**Comment by richardhendricks** [comment]
I captured all the options on this wiki page.  https://gtnh.miraheze.org/wiki/Salt_Nerf_Options

Please comment here if you think I am misrepresenting something.

I don't have a problem with choosing more than one option.  That allows players to innovate IMO.

**Comment by richardhendricks** [comment]
Added GT++ dehydrator recipe and salt bee option.  Need pros/cons for those.

**Comment by bartimaeusnek** [comment]
added a pro/con for GT++ dehydrator

**Comment by 0lafe** [comment]
Added some more info on tiers and such. So, is the idea to have a lot, or choose one or one per tier? Like one for early game (salt ore buff), mid game (ghast tears/drilling) and late game (lava/fusion)

**Comment by richardhendricks** [comment]
I'm ok with that.  I think certain ones are easy to do, some will take some effort.  so I am thinking holding off on the lava & liquids options is probably best for now, and implement the fusion and ore multiplier increase.

**Comment by Dream-Master** [comment]
We have Salty Bees now for Salt Thanks to @Zoko061602

**Comment by richardhendricks** [comment]
Fluids have been added to planets.
