### ISSUE TITLE
Forestry Circuit Board Assembler Recipes

### ISSUE THREAD

**Issue by septemberWaves** [GTNewHorizons/NewHorizons#2884]
#### Which modpack version are you using?
2.0.3.0
#
#### Issue description:
Circuit boards from Forestry all have a recipe in the carpenter, which is complex and fairly expensive. They _also_ each have a _vastly_ cheaper recipe in a low-voltage assembly machine. I am inclined to believe that the carpenter recipes are the intended way to craft the circuit boards, and presumably the assembler recipes are older recipes for the boards that are no longer the intended recipes and were simply not removed when the carpenter recipes were added. I would suggest removing the assembler recipes to force players to use the more Gregtech-balanced circuit board recipes.

**Comment by sthegreat** [comment]
Hmm, I'm in the same version and don't have those recipes

**Comment by WarlordWossman** [comment]
@sthegreat exactly what I thought about. I think something is messy with scripts and configs when you upgrade. I still got a recipe in 2.7 where you can fluid extract vibrant alloy from the dust that only works in singleplayer, but doesn't work on the official servers.
And yeah the details are offtopic but what I am trying to say is that some recipes seem to survive updates when they shouldn't.

Do you have the chance to get on a server with that version and test if it works there @septemberWaves ? Might not be that easy since most servers are 2.7 still but it would be fairly interesting to know if you ran into the same thing I did where old recipes still exist and somehow still work on your client.

**Comment by Dream-Master** [comment]
In 2.0.3.1 dev there are onle carpenter recipes but i can add them to circuit assembler.
