### ISSUE TITLE
[Suggestion] 2.0.4 bee nerf

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/NewHorizons#2931]
#### Which modpack version are you using?
2.0.4
#### What do you suggest instead/what changes do you propose?

Bees got a HUGE nerf it seems like, most of which is really not what it needed. Tons of bees needed a huge buff to make them worthwhile in any way. 

My first problem was blacklisting them for world accelerators. I can kind of see the problem, but world accelerators have a weird balancing to them. The LV-HV ones are pretty overpowered for high tiers, EV-LuV is fairly balanced, and ZPM/UV isn't usually worth it. With bees, even 2.0.3 and before, with the cost of industrial apiaries, you pretty much needed to accelerate them to make them worth it. I used 1.5A LuV per apiary, because making 64 times the apiaries I had, isn't reasonable. Even having the equivalent of 256 apiaries from 4, I was still getting drops slowly. Apart from a few unbalanced bee products, even at 256 apiaries, metal bees aren't worth it, and neither are most bees. I could mostly get by using my phosphor, egg and rubber bees, but they barely made enough materials to keep up with my slow HV LCR usage of phosphor for epoxy. 256 apiaries couldn't even keep up with a zpm disassembler for making stem cells. I've used a lot of bees, and needing to make the amount of apiaries I need isn't too reasonable. It would end up being huge walls of bees. 

Metal bees (copper, tin, gold, iron, etc...) were already almost useless past IV before this update. Considering a lot of those bees are materials aimed well past IV (naquadria, osmium, iridium, etc...) it doesn't make too much sense. The ender quarry out preforms them all, but not in a way that's overpowered. You need the amount of materials the ender quarry makes, and trying to use bees to reach a similar quantity before the bee nerf was already unreasonable. Now, it's much, much worse. 

There doesn't need to be an infinity bee. All parts of infinity can already be obtained in very reasonable ways. If anything, infinity needs a little bit of a nerf. While the initial catalyst from planet stone can seem like a huge grind, once the DD opens up, infinity is pretty easy to get. Some ways are almost the same as using a bee hive. While I don't mind the mutatron change too much, I think if the accelerator change was aimed to keep infinity bees fair, removing infinity bees could alloy the accelerator change to be reverted. 

Bees are an essential part of endgame nh. You need absurd amounts of eggs for lategame circuits. Chicken farms that size cause server problems, leaving you with ic2 crops or bees. Crops might need a bit of a buff, but bees work just fine for the materials you need. You can dump a few amps of LuV into an accelerator, and mostly get the amount of eggs you need. The same idea applies to other lategame things, such as meat for growth medium, ender pearls for lapotron crystals, certus for infinity chests, glowstone for solars, and a lot more. For the most part, these recipes were balanced, and you could get enough using industrial apiaries with accelerators. However, needing the amount of apiaries that equate to the accelerated ones, isn't very doable now that you need to have that amount of them.

**Comment by 0lafe** [comment]
That one isn't really about bees though, but yes my main point was that accelerators should work on apiaries. The amount you need without accelerators is insane

**Comment by Cinobi** [comment]
Totaly agreed, getting 1m+ glowstone and same amount of eggs without accelerating apiaries will kill the server for sure.

**Comment by noobyaran9** [comment]
Disabling world accelerator usage on apiary is one of the worst decision ever. What makes people think that using 64 apiary is better than using 1 apiary with world accelerator?(Server-wise at least)

Increasing the power tier to creating gendutry item is fine, but not reducing the time required is just stupid. (Basically 4x the current power usage making them way more expensive that they should've been)

Adding infinity bees and gating processing of their comb to UV (infinity catalyst) and UHV (infinity dust) is just pointless. I'll be straight right here, I don't need them, they're stupid. (Before you shoot me down on this reason, think of other ways of getting those item. They're easily obtainable at a reasonable speed and price which further proof that this addition is just stupid.) ~~ Another pointless QoL nerf after cross dimension TP and infinity armour nerf~~

> mutagen: I:gregtech:"gt.metaitem.01"@2394 => 5000 mb //Infinity Catalyst Dust
mutagen: I:gregtech:"gt.metaitem.01"@2397 => 1000 mb //Infinity Dust

Infinity catalyst dust is worth more than infinity dust? 

Nerfing the process needed to create mutagen by slowing them down 20x~(I didn't calculate the exact amount) and increasing the cost and power usage of creating them in favour of re-enabled mutagen producer which of course gated to UHV parts(??????). Another stupid and pointless decision. (Who even need resources from bess when you're already UHV? And every single way that u can name is much better than getting resources from bees.)

Changing advanced mutaton recipe to cost cosmic neutronium and UHV part(Correct me if im wrong on the UHV part). Is 100% mutation that OP that u need to gate them into the tier that bees is pointless (Except bee that produces egg)?

**Comment by Cinobi** [comment]
Btw, about suggestions. If u worried so much about accelerating infinity bee - just remove all accelerators after IV. They are not reasonable to use anyway.

**Comment by Teirdalin** [comment]
Honestly I think I-apiaries should be acceleratable.  They make bees actually kinda useful and isn't really overpowered considering all the work and power that goes in.

**Comment by BlackAce21** [comment]
Uhh...just to throw my $0.02 worth, I completely agree with the OP on this issue =\ disallowing world accelerators on Apiaries encourages bulk bee setups to keep up with item demands at later tiers and from a server standpoint, it makes sense to open the option for World Accelerators to be used in combination with them. The balancing should be done at the power requirement for the WA or some other form but again, removing it does nothing but encourage bulk bee setups which while grindy in the spirit of GregTech, is very laggy because they are constantly ticking Tile entities. I think we would all be better off if we encourage smaller setups with a lot less Tile-Ents.

**Comment by Dream-Master** [comment]
yes I made changes yesterday.

**Comment by richardhendricks** [comment]
Looking at https://github.com/richardhendricks/gendustry/blob/mc1710/resources/assets/gendustry/config/upgrades.cfg the stack limit and multiplier for production frames can be increased.  But talking in Discord, the problem is that once you hit the limit of 1 special item every 27.5s, you can't make the apiary produce any faster without world accelerators.

**Comment by richardhendricks** [comment]
The stack limit *and* the multiplier can be changed.  So we could change it so each frame is 2.0x, like in an alveary.  But it wouldn't get past getting more than 1 product every 27.5s, I want to test it out to see what happens though.

**Comment by Dream-Master** [comment]
Like all gt machines work. 4x power 2x speed

**Comment by Namikon** [comment]
> Like all gt machines work. 4x power 2x speed

Wrong. It's PowerTier x6 per Tick for TileEntities and PowerTier x3 per Tick for Non-TEs.
That is for Maximum Speed and Size selection. Power-usage is lower for smaller/slower settings.

**Comment by Dream-Master** [comment]
I take a closer look at the poll and we ned to change the important things:
All machines are blacklisted for acceleration except apiaries => remove Blalist Entry - [ ]

**Comment by Prewf** [comment]
does "41 Votes All machines are blacklisted for acceleration except apiaries" mean, all machines in this pack? or just gendustry machines?

**Comment by Dream-Master** [comment]
Only Gendustry ?

**Comment by 0lafe** [comment]
>Wrong. It's PowerTier x6 per Tick for TileEntities and PowerTier x3 per Tick for Non-TEs.

That's how the machine works, I was describing overclocking. 6A of the next tier of power, which is 4x power, for a 2x speed bonus. LV is 2x, MV is 4x, HV 8x, etc...

**Comment by noobyaran9** [comment]
Suggestion regarding the upcoming bee changes:

1) Remove infinity bee line
We don't need them. Even if we do, gating them to UV+ just makes them useless.

2) Change gendustry advanced mutatron back to UV tier instead of UHV. And remove cosmic neutronium from the recipe or replace it with black plutonium or bedrokium..
Nobody going to use bees at that tier to produce resources (except some weird resource like egg). Gating the machine at UV is perfectly fine. Not only UV, you also need to get Naquadah bee in order to get the parts needed for advanced mutation (You can change this to naquadria bees if u wished to). 

3) Removed alloy bees or bees that produce material that requires more than 1 base material to make.
Bees should only produce base product like crops and no point having them.

4) Fix this please
>mutagen: I:gregtech:"gt.metaitem.01" 2394 => 5000 mb //Infinity Catalyst Dust
mutagen: I:gregtech:"gt.metaitem.01" 2397 => 1000 mb //Infinity Dust

Infinity dust should produce more than infinity catalyst dust.

5) Reduce the amount of nerf onto the mutagen recipe using GT machines

6) Reduce the time taken to craft gendustry item like genetics labware and others by half. 
It used to be IV tier recipe, if u want to gate them higher tier, at least reduce the total amount of power used by a little.
