### ISSUE TITLE
Nether Portal Issues

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#2937]
#### Which modpack version are you using?
2.0.3.0
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Nether portals to link to each other.
#
#### What happend instead? (Attach screenshots if needed)
World created a new portal and sent me there.
#
#### What do you suggest instead/what changes do you propose?
I've been testing my private server with the following server-side mod: https://minecraft.curseforge.com/projects/netherportalfix I figured I'd simply submit this as a recommendation to be added to the server pack download. Obviously this isn't a GTNH issue but it is sort of annoying and this seems to fix it for me.

**Comment by WarlordWossman** [comment]
Just take a screenshot of your coordinates of the overworld portal and build one at 1/8 of the coordinates in the nether and they should link.
There is no randomness so no extra mod needed.

**Comment by Dream-Master** [comment]
This mod is 6 KB big and if it works as descibed obove i guess we can add it to the server.

**Comment by WarlordWossman** [comment]
I don't get why people need it, I am pretty sure it messes things up more than it fixes.
But I guess learning about game mechanics was never that big in modded since you can just change the game and be lazy.

**Comment by richardhendricks** [comment]
I would be very concerned that people have already setup portals to take advantage of the vanilla mechanics. 👎

**Comment by WarlordWossman** [comment]
I play technical vanilla and never had issues linking a nether portal, if you can't divide by 8 you might wanna install this tho.
My point is that nether portal mechanics are more complex than what this picture displays and I wouldn't want to change well known vanilla mechanics to something else that has no documentation.

**Comment by richardhendricks** [comment]
IE, what if I setup a portal to transfer items back to my base from 1000+ blocks away?  This mod would break that, right?

**Comment by noobyaran9** [comment]
I think the 8 block calculation would also lead to fast travelling. 
And with the 8 block calculation, you’re forced to build your base around nether portal which is annoying. And this would lead to less randomly generated nether portal in the world.

I’ve had time when i moved my overworld nether portal by less than 10blocks, going in and back from nether just spawn me like 100 blocks away from my base although i just move my overworld nether portal by less than 10 blocks.

**Comment by richardhendricks** [comment]
https://www.smbc-comics.com/comic/oops-2

**Comment by WarlordWossman** [comment]
>I think the 8 block calculation would also lead to fast travelling.
And with the 8 block calculation, you’re forced to build your base around nether portal which is annoying. And this would lead to less randomly generated nether portal in the world.
I’ve had time when i moved my overworld nether portal by less than 10blocks, going in and back from nether just spawn me like 100 blocks away from my base although i just move my overworld nether portal by less than 10 blocks.

If you move your overworld portal 10 blocks you only need to move the nether portal by 1 block if it was lined up before (which it probably wasn't anyways).
Just learn how to use the mechanics.
And I think we would agree that no base has multiple nether portals within an 8x8 cube while wanting them to target different nether portals.

**Comment by bartimaeusnek** [comment]
actually ive had issures with portals on delta (i always get ported into the base 6 chunks away which is annoying af), imo we should fork this and add it to the core mod, its easer than a lot of small files for every fix...

**Comment by Dream-Master** [comment]
I guess we can use this fix. Not hurting anyone.

**Comment by WarlordWossman** [comment]
>actually ive had issures with portals on delta (i always get ported into the base 6 chunks away which is annoying af), imo we should fork this and add it to the core mod, its easer than a lot of small files for every fix...

talked to him in dm and he didn't link them...

>I guess we can use this fix. Not hurting anyone.

how is it not hurting anyone? there is setups that rely on the old portal logic which are probably fucked because people can't divide by 8

**Comment by draknyte1** [comment]
Changing vanilla mechanics because people are idiots isn't a valid reason to add a mod. 

If you're aware how vanilla works, there is never any hassle. Take it from my 8+ years of playing since the portal was introduced. Literally google 'MC portal calculator' and you only need one set of X/Z coords. Does it get any easier?

**Comment by bartimaeusnek** [comment]
linking portals just sound like a lazy devs excuse to not have to fix a buggy mechanic...

**Comment by WarlordWossman** [comment]
You have never explained how the mechanic is buggy, it's consistent compared to this "fix" .
I wonder why every technical server I know has 0 problems with how portals work, I guess the 3 people that are for this fix have never tried actually linking portals which is funny.
"Let's change something because I can't be bothered reading about it"
With this logic we should also remove mechanics like overclocking that have no hints ingame but in the end make sense and add depth.

**Comment by noobyaran9** [comment]
>You have never explained how the mechanic is buggy, it's consistent compared to this "fix" .

Moving overworld portal by <10 block could lead of change in location of nether portal that leads back to hundred blocks away from the original portal.

**Comment by WarlordWossman** [comment]
>Moving overworld portal by <10 block could lead of change in location of nether portal that leads back to hundred blocks away from the original portal.

This is not buggy behavior at all. When you go through a portal in the nether it searches for the closest portal in the overworld starting from the nether portal coords x8, which means that those 10 blocks you moved the portal kicked it over the edge that your described OW portal is now the closest so it links to that one.

As I keep saying: It is an easy fix, just put your nether portal in a position where it always links to your OW portal, which means you can have your OW portal wherever you want. You just have to move the nether portal so it always leads back to said OW portal. IT IS NOT THAT HARD.

What I see happening with this "fix" is that if I have 2 portals in the nether linked to one OW portal and depending on which one I used last to get to the OW my OW portal now links to this one, which is inconsistent as vanilla portal logic would always decide for a single portal to link to, while this "fix" makes it unnecessarily complex and I technically have to remember which portal I used last to tell what my OW portal now links to (sounds stupid right? - yes, because it is)

**Comment by noobyaran9** [comment]
>What I see happening with this "fix" is that if I have 2 portals in the nether linked to one OW portal and depending on which one I used last to get to the OW my OW portal now links to this one, which is inconsistent as vanilla portal logic would always decide for a single portal to link to, while this "fix" makes it unnecessarily complex and I technically have to remember which portal I used last to tell what my OW portal now links to (sounds stupid right? - yes, because it is)

Nope.

**Comment by noobyaran9** [comment]
>linking portals just sound like a lazy devs excuse to not have to fix a buggy mechanic...

8 Block thing is okay, but its a buggy mechanic as bart says.
https://www.minecraftforum.net/forums/minecraft-java-edition/survival-mode/2354235-nether-portals-still-arent-fixed

![image](https://user-images.githubusercontent.com/13598309/40121428-213e7674-5954-11e8-865b-8bd04923609c.png)

This is how the mod works.
