### ISSUE TITLE
Super Buffer/Chest Buffer causing lag

### ISSUE THREAD

**Issue by finkledoodle** [GTNewHorizons/NewHorizons#3006]
#### Which modpack version are you using?
2.0.3.0
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
I used super buffers and chest buffers to handle sending my ore/dust throughout my ore auto-processing system, however when the system is in use they cause tremendous amounts of lag on the server.
#
#### What happend instead? (Attach screenshots if needed)
I had to remove the buffers to reduce lag
#
#### What do you suggest instead/what changes do you propose?
As it was explained to me, when the buffers have enough items to meet their requirement to push, they repeatedly attempt to push the items out into the destination inventory and tick high, whether or not that destination can accept them. It sounds like the code just continuously running the code to try and input them items, whether it can or not.

**Comment by Bryfer** [comment]
Similar to #2919

**Comment by repo-alt** [comment]
It is the same issue but here a probable cause is pointed out. I didn't look in the code but if the buffer indeed repeatedly tries to output every tick (and fails), perhaps inserting a delay counter in the output would help. (Also a delay counter may be exponential up to some limit, like 2, 4 , 8, 16 ticks)

**Comment by richardhendricks** [comment]
@finkledoodle please provide a detailed description of your setup, including pictures.  Are you only using the SBs for dust processing?  Do you have dust patterns in your autopackager?

**Comment by Cinobi** [comment]
![2018-05-27_22 25 57](https://user-images.githubusercontent.com/25028786/40590036-e30a901c-6200-11e8-9caa-84a3b10a5c0d.png)
![2018-05-27_22 54 46](https://user-images.githubusercontent.com/25028786/40590049-fe77fea2-6200-11e8-84c6-cf556b9db96e.png)
may i post some pics too? =D

**Comment by repo-alt** [comment]
I looked at the super buffer and related MTE code and from what I understand it works like that:
if it succeeded pushing some items into the target directory, it reset the success counter to 50 and next 50 ticks it will try to push more items.
Before and after pushing it does 256*256 comparisons, compacting inventory. That is 130k calls to  GT_Utility.areStacksEqual every tick (if at least every 2 seconds can push something to the target, which it usually does, when supply is sufficient).

**Comment by richardhendricks** [comment]
I think reducing that counter down to 2-5 should be sufficient.  No reason to keep pushing every tick for 2.5s. Esp. since a success restarts the counter.

That change would help with lower tier setups.  Higher tier setups would still keep whacking every tick.

Doing the resort every time after trying to push is not necessary.  It should only attempt a resort after a successful push.

Also, doing a resort before every push is probably too much as well.  I think we could recode that to do it every 5 or 10 ticks without significantly hurting behavior

The algorithm could do with some tweaking, but without detailed performance numbers we won't know where to attack.  The current way it is coded, it is compressing and bubbling null slots to the end of the list at the same time.  It would probably be best to do all the compressing and then separately pull the null slots directly to the end.  This would minimize the number of calls to  GT_Utility.moveStackFromSlotAToSlotB, which looks pretty expensive with the item stack copies. 
https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/util/GT_Utility.java#L462
It's also possible the comparisons themselves are expensive, need to look into https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/util/GT_Utility.java#L698
but it is hard to say without getting real numbers.

**Comment by richardhendricks** [comment]
ok, looking at the packager (most likely destination for the SB), it takes 100 ticks at LV to process small/tiny dusts.

It looks like the max packager tier is IV, which is ~6 ticks for each package. So a better algorithm would be to push and then hold off for 5 ticks instead keep trying every tick for 50 ticks - above MV that means it is trying basically every tick all the time. That will be fast enough to keep IV and below stocked with at least 1 batch of dust ready to go.

Need to also look at compressor, I guess this is also used as a filter on the compressor to make sure it is receiving the correct amount of stuff to compress into biomass.

**Comment by richardhendricks** [comment]
No changes, seeing ~.36 ms of load time with 91 items in the buffer.

Added a check after the insertion to only resort if the inventory was modified. Lowered it slightly,but not enough to matter.

Switched up algorithm to do compression first, then swap nulls to the end.  Probably won't do much, now that I think about it, since the load seems to be ~300us even with no output activity.

**Comment by richardhendricks** [comment]
Ok, I did a couple of changes, I think I got the average down by about 1/3.  
Before fixes
![2018-05-30_02 24 34](https://user-images.githubusercontent.com/1214811/40705568-d9cca344-63b0-11e8-8392-6cf26d540196.png)

After fixes
![2018-05-30_02 00 30](https://user-images.githubusercontent.com/1214811/40705552-c8891522-63b0-11e8-9bc0-39ddce496858.png)

I need some SSP testers for this.  These two versions have the added debug code, with the fixes in one but not the other.  Try both in a heavily filled superbuffer, with at least 100+ items.  Scan with the tricorder.

[gregtech-5.09.32.24-nofix.zip](https://github.com/GTNewHorizons/NewHorizons/files/2052809/gregtech-5.09.32.24-nofix.zip)
[gregtech-5.09.32.24-fix.zip](https://github.com/GTNewHorizons/NewHorizons/files/2052810/gregtech-5.09.32.24-fix.zip)

**Comment by richardhendricks** [comment]
It is only for testing right now.  I have some more changes I want to test out.

Replace N^2 comparison with 
insertion sort
compression
insertion sort

Make sure nulls are pushed to the end by the insertion sort.

Should optimize to about O(3n) in most cases since we can keep the inventory sorted,  instead of always N^2.

Based on the above data though, it looks like just the move attempts alone are ~100uS.  They are done by https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/util/GT_Utility.java#L527

I am hesitant to really muck with that since it is probably used by every machine.

**Comment by richardhendricks** [comment]
yeah there are some possible optimizations that could be to the utility function, but since it is O(n)-time, I am not going to worry about them right now. Best to focus on the N^2 problem.

**Comment by bartimaeusnek** [comment]
@richardhendricks how about [the Treesort?](https://en.wikipedia.org/wiki/Tree_sort) Worst case is n*log(n).

**Comment by richardhendricks** [comment]
There are lots of nlogn sorts, mergesort, quicksort etc.  But insertion sort has a really good best case of O(n) when the data is mostly or partially sorted. Which it should be in this case, so the number of comparisons should be way less.

**Comment by repo-alt** [comment]
I think the change that you already made (inv. change check), plus some delay before the next push attempt will already speed up this function like 10 times, even w/o sort optimization. (Not that I have anything against it)

**Comment by richardhendricks** [comment]
Yeah it does help alot but the worst case will still blow up if an item is inserted and something is pulled from the same tick.  

It also doesn't help when the # of items in the inventory grows, it could easily explode the processing time for the worst case.

I think the insertion sort/compression/insertion sort (really a bubbling up of the nulls) should vastly improve worst case performance.  The constant time spent trying to push items is a bit of a drag, not really sure what I could do there except not to do it every tick.  For packagers we could probably get away with every 4-5 ticks, but I need to check on sapling compression time for biomass and how it accelerates at the high end.

**Comment by repo-alt** [comment]
Biomass processing may use usual chest buffers just as well, because there are not many types of saplings/plants, so if SB in that case will become a bit slower, it's no big deal.

**Comment by richardhendricks** [comment]
yeah good point, a chestbuffer is only 27 max items vs superbuffer with 257.
Saplings take 15s at LV, so doing 1 in 3 ticks should be fine.

**Comment by richardhendricks** [comment]
Also, as a general comment, to minimize lag with these, output larger than the minimum size.  IE, output 40 instead of 4 small dusts.  It shouldn't matter that much with these changes in place though.

**Comment by richardhendricks** [comment]
And also, don't jam 1 thing every tick if you can do larger batches less frequently.  But even so, it should be about 1/2 the previous load even full of 256 items.

**Comment by richardhendricks** [comment]
streaming in items continuously 1 per tick
![2018-06-02_02 58 36](https://user-images.githubusercontent.com/1214811/40872264-fad20bf8-6610-11e8-8877-75ef92128c0c.png)
(would see higher load if items are also taken out every tick)

Load after outputting an item, full chest
![2018-06-02_02 50 37](https://user-images.githubusercontent.com/1214811/40872280-3d8abde6-6611-11e8-891a-d85a7f19c62d.png)
Note ticks at the bottom pushing every tick, then ticks at the top pushing every 5th tick.
