### ISSUE TITLE
Spice of life updated

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#302]
This sounds interesting:

``````````````````
Added config option use.time.for.food.history.length
If true, the food history will use time (in Minecraft days) instead of number of foods eaten for its maximum length. For example, a length of 12 will store all foods eaten in the last 12 Minecraft days.
Also added config option use.time.progress.time.while.logged.off to control how time progresses for players on a server
````````````````````````

http://minecraft.curseforge.com/mc-mods/220811-the-spice-of-life/files/2251265

**Comment by Dream-Master** [comment]
Maybe change this to 4-5 Mc Days. And switch on the log off that players not can skip this time.

**Comment by Dream-Master** [comment]
What do you think about the food History for Days?

**Comment by Namikon** [comment]
It's a pain already right now, as somehow since the last update you have to eat different foods to reduce the "eaten x times" counter, which means you need to carry around 10 types of food, at least.

And Martin, for god's sake, please keep the reduced stacksize for food OFF. This is getting ridiculous. People are actually meant to play and enjoy the game, without ways to bypass the food later on, it would be impossible because you'd had to spend 40% of your time playing in eating and taking care of crafting food. So no, I vote against that.

**Comment by Dream-Master** [comment]
Is the reduce Food stacksize now on ? I can't remember i switch that. So we let the Food history for Days off.

**Comment by Dream-Master** [comment]
We change the Stack size to 64 back and set the food stacksize to normal.
