### ISSUE TITLE
Speed machines adds TONS of lags

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#3030]
#### Which modpack version are you using?
Epsilon one
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
If GT machine process it's recipe too fast(less that some ticks or even less than 1 tick) it creates serveral client fps drop. U can check the effect if u setup LuV+ forge hammer, or EV+ singleblock water distiller.

**Comment by richardhendricks** [comment]
Will look in July, after I actually get a chance to play.

**Comment by richardhendricks** [comment]
could be that short recipes are causing sound to play/replay every tick.  Should be fairly easy to make it only replay sound every second or every other second.

https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java#L681

Probably needs a % 20 to go along with > 20.

**Comment by richardhendricks** [comment]
So, can you clarify what you mean by tons of lag?  I have 9 LuV machines hammering cobble, and my FPS goes from ~185 to ~175 fps.  They, and all their power, is in one chunk. I did notice when I had their power cables in another chunk that FPS dropped a little more. 

When the cables and machines were in two separate chunks, I noticed ~40 chunk updates per second.  When i moved them all into the same chunk, I only got ~20 chunk updates per second. 

I don't think we can get around a machine needing a chunk update every time it processes. But if your chunk already has a few mahcines, it probably is already getting updated frequently.

What is it outputting to?  An AE system?

I would try putting a storage on the output, like a chest or mini/babychest or whatever, and then use a HV-tier conveyor belt to pull out from the chest.  That way you can quickly output from the hammers into the chests every tick, and then every 1s pull a stack from the chest to input into AE.

**Comment by jiamingc0824** [comment]
Change how the sound and animation(fake) works? To something like 
if(machine working)
start animation();
else 
stop();

instead of using the old one which refresh everytime a recipe is started.

**Comment by richardhendricks** [comment]
NO, it doesn't refresh every time AFAICT.  It looks like it sends a packet once every 10 ticks.  But the chunk updates happen every tick if it is fast.

**Comment by richardhendricks** [comment]
Possible solution, increase recipe time and # of items processed.

So a .5s recipe would become a .05s recipe (1/tick) at EV.  This would also mean you don't get the EU discount for overclocking a 1/tick recipe.

Also, if a recipe was changed to say 32 items/16s (32/s at EV), then you could just increase the tier and get even more per second. IE, 32/.5s at IV, 32/.25s at LuV, etc.

**Comment by richardhendricks** [comment]
Cinobi pointed out that Processing Arrays don't seem to cause the same level of client lags.  And they have no animation or sound, so it is possible there is something to look at.

Check how often client packets are really received.  Code looked like it was every 10 ticks, but maybe starting/finishing a recipe makes that faster?

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java#L640

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java#L516

**Comment by richardhendricks** [comment]
There is definitely a difference between SSP fast machines and multiplayer fast machines.  Will continue investigations.

**Comment by richardhendricks** [comment]
OK, GT_MetaTileEntitiy_BasicMachine::onPostTick is what initiates the sound for a process.  It uses startProcess() to begin the sound.  It looks like there are separate per-machine ones for the bronze and HP steel machines.

GT_MetaTileEntity_BasicMachine_GT_Recipe::startProcess will start a sound loop using sendLoopStart() only if a valid sound name is assigned for that machine.

MetaTileEntity::sendLoopStart is what actually sends the block event to the clients to initiate the sound loop. Nearby are sendLoopEnd (never used as far as I can see) and sendSound (used for stuttering machines)

BaseMetaTileEntity::receiveClientEvent processes the event on the client side.  If it matches case 5, it calls startSoundLoop().

And now we end up back at GT_MetaTileEntity_BasicMachine_GT_Recipe::startSoundLoop(). This is what actually does the sound at the client end.

The sound list is at GregTech_API, line 227.

I am going to try and throttle the sound packet generation on the server side.  That seems to make the most sense for me, since it not only reduces the sound output at the client, but also the network traffic generated by the server when players stand next to a lot of fast machines.

**Comment by richardhendricks** [comment]
Hmm, with 8 IV forgehammers on a standalone server, not really seeing a lot of lags.  Maybe it's an issue with a more remote server? Lots of machines -> lots of packets.  Also animations, but I assume that really isn't the issue?

I'll keep investigating, see if I can measure how often the sound packets are sent to the client.  For short recipes the packets are sent every tick, but from what i can see the sound loop isn't replayed until the loop completes (bronze machines are slightly different since they do the steam output sound.)

If it is sending the sound packets every tick, I can still use the same idea I had before to try and reduce how many are sent.  That might help a little bit.  I am not sure though since a whole chunk update is sent any time the machine state changes, ie the process completes and updates inventory.  That is probably way more expensive than a block update.

**Comment by richardhendricks** [comment]
Do not use
[gregtech-5.09.32.28.zip](https://github.com/GTNewHorizons/NewHorizons/files/2113740/gregtech-5.09.32.28.zip)

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/pull/130

Needs testing.  I tested it locally and it *seems* to make the situation better. Make sure you wait at least 5-10 minutes after joining server for FPS to settle; I noticed a big jump after 5 minutes that was confusing me. With 0 ticks between sounds, I was getting around 310-320 fps with my testing setup of 8 IV forgehammers smashing cobble.  With 30 ticks between sounds, I was seeing 320-340 fps.

Increasing the ticks also seemed to drop the number of chunk updates, not really sure why though.

**Comment by richardhendricks** [comment]
[gregtech-5.09.32.28.zip](https://github.com/GTNewHorizons/NewHorizons/files/2114225/gregtech-5.09.32.28.zip)
Zipped version of the mod.

**Comment by richardhendricks** [comment]
A fix has been released to production, we will check the results on the next update. Everyone, **please** get a good feel for how your base sounds, and how much FPS you get there, and let me know how it feels with the next release.
