### ISSUE TITLE
Rocket Engines Efficiency

### ISSUE THREAD

**Issue by Krispion** [GTNewHorizons/NewHorizons#3048]
#### Which modpack version are you using?
2.0.4.2
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
Rocket Engines from GT++ appear to be too good for their cost. Their recipes are nearly the same as the LCE controller while requiring no secondary inputs, no multiblock structure and having nearly the same efficiency (136% at EV, slightly reduced in tiers thereafter). Their recipes were previously reduced in cost in #2568 with no hit to their performance.
#
#### What do you suggest instead/what changes do you propose?
Lower their efficiency to be more in line with previous tier's singleblock combustion generators. Every combustion gen from LV -> HV has its efficiency progressively reduced, it should continue this way and have the circuit in the recipe reduced to its output tier, or keep the circuit as is and leave it at HV efficiency (85%).

**Comment by 0lafe** [comment]
Easiest to just remove them probably. We can already use oil for about as long as it's good. If you want LuV with oils, just make 5 LCE's. It's not like that's out of the question by that tier. We already have gens for the tiers before that pretty much. Don't really see why we need them.

**Comment by Krispion** [comment]
I tend to agree, really. Singleblock power generation should be scarce past HV, especially for early game sources like combustion. There are no equivalent singleblock generators for gas/steam, nor should there be.

**Comment by Prewf** [comment]
There's an alternative solution, which is to make the efficiency consistent with the existing single block combustion engines. Since it's decreasing linearly, the GT++ blocks would need: 

80% fuel efficiency at EV with 320 pollution per second. 
75% fuel efficiency at IV with 640 pollution per second. 
70% fuel efficiency at LuV with 1080 pollution per second.

The fuel values of existing combustible fuels already acts as a sort of gating. Unless a player has ridiculous amounts of cetane generation (requires 72 L/s at EV, 304 L/s at IV, and 1301 L/s at LuV), they won't be able to keep using cetane past like EV simply because of how much fuel it requires to keep up that level of EU/t.

But if the intention is to deter players from using simple single block generators the higher up in tier you go, you could make the efficiency even worse than this. Maybe 60% down to 50%. That would encourage players to try the LCE or move onto nukes. I'd prefer that over simply removing blocks, since it keeps options open for players (i.e. let people inefficiently make energy, if they want).

**Comment by richardhendricks** [comment]
GT++ added new high complexity rocket fuels and massive pollution output from rocket generators.
