### ISSUE TITLE
[balance] small efficiency buff for single block steam turbines

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/NewHorizons#3124]
The single block steam turbines drop off quite a lot in efficiency when you go MV/HV.
Idea would be to buff the efficiency rate of them a little bit. Most people use fuels anyways so a small buff shouldn't hurt and if diesel and cetane might get another small buff ( #3115 ) it's actually not the worst idea since those are the fuel equivalents for MV and HV.

So yeah my suggestion would be to buff efficiency percentage like this (LV/MV/HV):
85/75/66,5 (current values) ---> 90/82,5/75 (suggested values)

As you can see not the biggest buff, but should make steam more of an option until you reach the multiblock turbines. Currently the ratios are really hard to handle anyways since most steam setups eat a lot of charcoal and need better wood farms once you tier up.

**Comment by richardhendricks** [comment]
Really need a rebalance across steam and fuel based generators.

I like the idea of the primary reason to upgrade to LBTs being efficiency, but at HV and below it is hard to get good rotors, and to match rotor flow with fluid regulator capacity.

For fuels, maybe we should change the pollution amounts for the SB gens higher, to encourage players to upgrade to the LCE.

**Comment by richardhendricks** [comment]
another option is to set fluid gens pollution amounts based on EU output.  So higher block turbines pollute more, with maybe HOG giving a .8 or .7 multiplier since it is cleaner-burning.

This would also tie in nicely with GT++ pollution detectors/scrubbers, but those need a look-see on balance too.

**Comment by draknyte1** [comment]
> This would also tie in nicely with GT++ pollution detectors/scrubbers, but those need a look-see on balance too.

They've been rebalanced several times up till now and won't be seeing any logic or efficiency changes.

**Comment by CalterOK** [comment]
Offering to increase the efficiency of turbines, you forget about 2 important points. First, it is necessary to take into account the losses in the transformation of energy (voltage increase). Secondly, the too high efficiency of single-blocks will lead to their greater use than multi-block turbines.

**Comment by WarlordWossman** [comment]
Not really the best point you made there, fuels are a lot easier anyways and the multiblock turbines only start to shine when you are EV+ anyways, the best "small turbine" (all other turbine sizes are EV+) is vibrant alloy which already costs more ressources than a turbo combustion generator, breaks over time and only makes 405 eu/t on optimal flow. (there is other small turbines but if they make more than 512 eu/t you obv need the EV dynamo which is ofc EV too)

So yeah buffing the single block turbines doesn't hurt the multiblock ones too much, they are still really good once you make your steam with nuclear reactors and suck before.
The whole idea is that steam is okay in LV, then drops off at MV and HV a lot and becomes okay again at EV - which just feels off.

**Comment by Lainiel** [comment]
Steam doesn't need just a small change it need a complete overwork in my opinion. Steam is only competitive in LV. Even in MV you won't be able to make a setup that doesn't cost more than 4 times as much materials as a light fuel setup. Large steam boilers are expensive and completely useless. You need another 2 multiblocks to supply enough fuel to run them (forestry farm and pyrolyse oven), produce a ton of polution together with pyrolyse oven and do not produce enough steam to be competitive. Large steam turbines are completely useless when not using nuclear reactor, because they are too expensive when you can just make single block steam turbine. GT++ boilers are effective but they are expensive and do not produce enough steam to be viable too. In total if you use steam past LV you are just hurting yourself or seeking a challenge.

**Comment by Lainiel** [comment]
First you say you don't need a tree farm and then you say that you run a golem tree farm. Golems are locked behind MV by the way. I have no idea how much charcoal do the GT++ boilers consume, but I know that you'de have to build like 20 coke ovens to run GT Large boiler to keep up, which is almost the same hassle as building that pyrolyse oven. It's okay that GT++ boilers are getting buffed, but honestly they shouldn't outshine the multiblock boilers in everything. I'm not a fan of single block machines being better than multiblocks that are a ton more expensive. (HV Turbo Steam turbine compared to Large Steam Turbine for example). Large GT Steam Boilers combined with Large Steam Turbine should be able to make about 3 amps of HV to be worth the price of setting them up.

**Comment by draknyte1** [comment]
You don't need a forestry multifarm for trees, no. 

Couldn't tell you where golems are, but I feel like they're not that late game. @DoomSquirter could comment on our availability, but 20 Coke ovens don't cost anything at all. (Considering there's a quest for 10 in bronze/early lv)

Not my fault all vanilla GT multis suck and still use vanilla GT rates for a modpack that expects more. Again, just buff multi boilers or use the Thermal boiler. Steam is viable because is scales cheaply and the fuel is infinite and free once set up, unlike oil. Buff it too much and it's OP to a point of oil being useless for power.

**Comment by richardhendricks** [comment]
I would be OK with buffing the large boilers so they produce more steam per tier.  Dunno if that should be 2A or 3A though. Each amp requires 1 LBT on its own, so that's 4 large machines to get 3A. The benefit would be more efficient use of fuel and also less pollution per amp. 

The big problems is that fluid regulators at that tier would not be able to effectively handle that amount of steam, and that the rotor selection right now sucks, esp. at MV.

**Comment by draknyte1** [comment]
People making large steam turbines before late HV are doing it wrong. (You can't regulate or make rotors that suit so, too bad) They're intended (based on th lack of changes to them in GTNH) to sit at late HV, early EV, so let's stop prenteding otherwise. Again, power creep for tier doesn't scale well if we buff it more than a minute amount.

**Comment by richardhendricks** [comment]
If that's the case, then we should change the requirements and questline to reflect HV not MV. Saying players are "doing it wrong" while there isn't anything in game to guide them isn't helpful.

Even at HV, they are damn inconvenient to use IMO.  I'll have to review my setup, but a steel boiler requires 2 large turbines because the fluid regulators aren't large enough and the rotor selection good enough.

At EV i use 3 titaniumsteel boilers and 3 small shadow rotors to make 2160 EU/t, pretty unimpressive for EV considering the LCE's ability to make 2048 EU/t and 6144 EU/t with a trivial upgrade.

**Comment by Lainiel** [comment]
Once again large turbines and boilers are COMPLETELY USELESS no matter what tier we are talking about. You are doing it wrong if you use them at all. The only exception is using the large turbine with nuclear reactor. It's nice that you're making 2048 EU/t with 6 damn expensive multiblocks but I can beat you with just 1 GT++ rocket engine burning light fuel.

I'm not saying people should use Large Steam Turbines at LV or MV, but that they should be at least viable to use in HV/EV. Just look at the material cost to build those damn things. And about the GT++ boilers: They shouldn't be simply better than the large GT boilers if you spam them.

How I imagine it should be: If you build a forestry tree farm, pyrolyse oven, Large GT boiler and a Steam turbine you should be making around 3-4 amps of HV depending on your boiler tier and turbine blades and you should produce quite a lot of polution. (from pyrolyse oven and boilers)

**Comment by richardhendricks** [comment]
I was agreeing with you, it is disappointing to use 6 large machines to make only 1 amp of power.

I need to look more at numbers, but we could look at doing ~3A of power per boiler but that would still require 3 large turbines.

I agree, more pollution would be good, esp. since pollution gets knocked down so much with muffler upgrades.

**Comment by richardhendricks** [comment]
If we do improve the large boiler -> large turbines, I say we keep the single block steam turbine efficiency like it is.  This gives a big incentive to going to the large blocks, 66% vs 90% is a big improvement.

**Comment by Lainiel** [comment]
I disagree 66% vs 90% isn't a good enough improvement to justify building the large steam turbine considering that you have to change the turbine blades, turbine has a spin up time and can waste steam. (singleblock turbine isn't using steam when batteries are full) I stand by my suggestion that a single steam trubine should make 3 to 4 amps of HV.

**Comment by Krispion** [comment]
Those Rocket Engines need to be nerfed, I made an issue awhile ago but it seems to have been forgotten. I would also be careful with buffing the GT++ Boilers too much since that's what broke the Rocket Engines to begin with. A 3x buff to them sounds a bit reckless. Single blocks should not be competitive with multiblocks from the same fuel source.

**Comment by richardhendricks** [comment]
Well for a single steam turbine to make 3 A, we would need to adjust the dynamo hatches to output more than 1 A, and rebalance rotors so there are available ones at HV.

**Comment by Lainiel** [comment]
I don't know how hard it is to make the dynamo output more than one amp, but rebalancing the rotors shouldn't be that hard.

**Comment by Prewf** [comment]
>Once again large turbines and boilers are COMPLETELY USELESS no matter what tier we are talking about. You are doing it wrong if you use them at all. The only exception is using the large turbine with nuclear reactor. It's nice that you're making 2048 EU/t with 6 damn expensive multiblocks but I can beat you with just 1 GT++ rocket engine burning light fuel.

But that assumes an incoming light fuel rate of 128L/s indefinitely. I mean, you're going through a cell of oil every 8 seconds. Yeah you get a lot of oil from wells, but compare that to the "expensive multiblocks" setup for steam through burning charcoal which is completely renewable and self-sustaining without user intervention, save for swapping out rotors (which isn't a big deal if you are redstone controlling your turbines. Rotors last a long time).

>I'm not saying people should use Large Steam Turbines at LV or MV, but that they should be at least viable to use in HV/EV. Just look at the material cost to build those damn things.

They ARE viable in EV. Just not through burning coal. The only problem really is the lack of effective coal-burning steam generation methods at HV. As it stands right now, the GT Large Boilers have no reason to exist because they are obsolete the moment you have access to them. That's something I can agree with. The easy solution would just be to boost their steam output appropriately, but not so much so that it goes into EV territory. EV and onwards is the job for fluid reactors.

IMO large turbines don't need to be touched. They're unwieldy at HV because they aren't MEANT to be used at HV, like Alkalus pointed out. By the way, the issue of having to split your steam intake into multiple turbines? That's something you have to do at all tiers, not just at HV, so I don't see what all the surprise/fuss is about. My initial fluid reactor setup at IV required 6 turbines and my upgraded LuV setup also needed 6 turbines, I'm not surprised when I read people need to make 6 turbines to generate "just an amp of HV". That's just the nature of Large Turbines and steam as a power source and it has always been this way. Part of the process is trying to fit together all the different rotors you need to use to efficiently use all the steam you feed it, **because steam as a power source is extremely power-sparse (compared to light fuel which is power-dense)**.

**Comment by Prewf** [comment]
@Krispion the thread is still up there https://github.com/draknyte1/GTplusplus/issues/311

**Comment by Lainiel** [comment]
@Prewf 

> They ARE viable in EV. Just not through burning coal.
That's what I said. Their only use right now is with the fluid reactor. Also you don't need 6 of them, that's why there's a loose fitting mode. You can run the fluid reactor with 1 HP steam turbine and 1 Steam turbine for about 20k EU/t. The fuss is about that they're completetly inferior to a single block HV Turbo Steam Turbine that costs much less, doesn't require a rotor, doesn't waste steam and outputs 512 EU/t with just a bit worse efficiency (66% compared to 90%). And by the way Oil might not be renewable but is really easy to make it self sufficient with just a few ProjectRed pipes that take care of desulfuring (you also get a load of sufuric acid as a bonus). The only thing you have to do is swap the pump when the oil runs out and lay the pipes.

> But that assumes an incoming light fuel rate of 128L/s indefinitely.
Not true at all. First GT++ rocket engine had 136% efficiency so you're burning 94 L/s not 128L/s. Second you're not burning that fuel all the time only when your demand is high. The engine shuts off perfectly when the batteries are full so you are not wasting anything. No warmup, no spinup, no voiding, no redstone circuitry required. It behaves exactly like a battery. Third I was using light fuel as how extremely low effort you can go and still make an amp of 2048 EU/t. With diesel you get down to 62 L/s and with cetane you're down to 42 L/s, both of which are not that hard (especially diesel).

> steam as a power source is extremely power-sparse (compared to light fuel which is power-dense)
Yes steam is a power-sparse but steam should be scalable into high EU/t. There's a reason why we use coal power plants in real life and not oil/diesel ones.

**Comment by WarlordWossman** [comment]
I mean it depends if we want to keep the large turbines for HV/EV which I could see but even then 1 turbo combustion generator can make 1 amp of HV while my large turbine with small vibrant alloy turbine (!) makes 405 eu/t on optimal flow and runs out of durability, so yeah totally useless and you even have to use some tricks like 2 fluid regulators.

I think it would make more sense if the regular size turbines wouldn't need titanium rods since the better ones of those need titanium anyways for an EV dynamo.
The whole dilema is that the dynamo hatches can output 1 amp at max and there is nothing that comes closer than 475 eu/t while still making sense with the other values. And that's a multiblock that runs out of durability and needs flow controll - while I could be sitting there with 1 turbo combustion generator (and yes oil is not as easily renewable).
If the turbines could for example output more amps that might be okay but currently I really see no reason to ever use those multiblocks if I am making steam without using nuclear power.

Even the options you get with TC ingots still suck compared to the fuel generators that never run low on durability...

**Comment by Prewf** [comment]
>Also you don't need 6 of them, that's why there's a loose fitting mode. You can run the fluid reactor with 1 HP steam turbine and 1 Steam turbine for about 20k EU/t.

I'm not going to forgo 10000 EU/t just so I can save space on 4 turbines, but that's just me. It's not that hard to set up additional turbines when you're already in the process of setting up 2. And running it in loose-mode only makes the durability problem worse, making it pretty annoying to work with. You'd basically be spreading the total durability damage among 2 rotors instead of 6.

>The fuss is about that they're completetly inferior to a single block HV Turbo Steam Turbine that costs much less, doesn't require a rotor, doesn't waste steam and outputs 512 EU/t with just a bit worse efficiency (66% compared to 90%).

All this says to me is that there isn't enough steam output at HV to make the Large Turbine worth setting up. It's not a problem with the Large Turbine itself (maybe rotor options are though?). I already said I agreed with this. On top of this, you seem to be placing a lot of value into the ability for a multiblock to regulate itself. Redstone logic using thresholds isn't that complicated to set up.

>Not true at all. First GT++ rocket engine had 136% efficiency so you're burning 94 L/s not 128L/s. Second you're not burning that fuel all the time only when your demand is high. The engine shuts off perfectly when the batteries are full so you are not wasting anything. No warmup, no spinup, no voiding, no redstone circuitry required. It behaves exactly like a battery. Third I was using light fuel as how extremely low effort you can go and still make an amp of 2048 EU/t. With diesel you get down to 62 L/s and with cetane you're down to 42 L/s, both of which are not that hard (especially diesel).

We're not talking about diesel or cetane and light fuel is up for a nerf so, things are about to change when we're making this comparison. Honestly this is more pedantic than anything. 128L/s down to 94L/s, that doesn't make it any more sustainable. Having to go out into the world and manually move pumps is not self-sustaining. Of course, if you effectively have infinite oil (which it seems you do based on #github-dicussion), then this comparison isn't even fair in the first place because you're comparing infinite amounts of a dense power source vs infinite amounts of a sparse power source.

>Yes steam is a power-sparse but steam should be scalable into high EU/t. There's a reason why we use coal power plants in real life and not oil/diesel ones.

We don't have to have 1:1 parallels to real life in this game. As a game mechanic, burning coal is the most mundane thing to do and it's an option available to you at the very beginning of any GT pack. In the sense of a game mechanic, it doesn't make sense to me that this "beginner" method of burning materials should scale into EV. Maybe HV at best.

>The whole dilema is that the dynamo hatches can output 1 amp at max and there is nothing that comes closer than 475 eu/t while still making sense with the other values.

Yeah it sounds like there needs to be more rotor options tbh. Something with decent durability and that can handle the amounts of steam generated by the revised boiler output levels.

So as a revised list of suggested changes, how about:
-increasing large boiler steam output such that it can, at best, generate 1 to 2 amps of HV worth of steam. This means high-tier large boilers need to output more than 13517 L/s to make them better than single block hv steam gens.
-revisiting rotor numbers for many of the small and normal rotors to make them viable for HV setups (and not just lock everyone to just using vibrant alloy, because that seems to be the case right now).

**Comment by MineAnPlay** [comment]
Seeing some stuff about durability of rotors, if you use redstone to turn of when there is no need, your turbines will last a very long time (most, efficient rotors last around 6-7 days if they run non-stop and if you use redstone it will last a month or two). 

One thing I can agree is that the Large Tungsten Steel boiler is the most efficient and most output per tick but it's gated behind IV. IMO we should change the Tungsten Steel with Titanium and replace the old Titanium with Stainless Steel? They should also get a slight buff, maybe 25% per tier? 

Also I really want the argument of oil being "finite" to stop. Oil is literally infinite with Crops, Bees or Pyrolyse Oven and if you have a decent oil well then by the time you deplete the 8x8 chunks you will be in ZPM etc to the point where you can count that as infinite too. I know this isn't about oil nerfing (which should be tweaked) but I wanted to put this here. 

Also what's with people saying 90% to the Large Turbines? Only the small rotors can achieve that and for proper EV+ power you need Large Rotors which with a good material is 140-170% efficiency. I'm also OK with the single block turbines getting a efficiency buff (95-90-85% like the other generators).

**Comment by WarlordWossman** [comment]
Even with redstone controll you have to keep in mind that the 24 vibrant alloy for your small turbine already eat up a percentage of the power you are making with it.
The material cost to set up a multiblock turbine with all the things you need for it seems way more expensive than making diesel and pumping it into a pretty efficient single block generator.

**Comment by Prewf** [comment]
Yea.. I didn't realize how much oil one can obtain with the GT drilling rig, it seems like it's effectively infinite but someone can correct me if I'm wrong about that.

>Also what's with people saying 90% to the Large Turbines? Only the small rotors can achieve that and for proper EV+ power you need Large Rotors which with a good material is 140-170% efficiency. I'm also OK with the single block turbines getting a efficiency buff (95-90-85% like the other generators).

I thought the same thing when I read the comments at first (I never even looked at small/normal rotors before this), but I think it's like that because optimal flow rate of small vibrant alloy rotors are the closest you'll get to matching the steam output of the boilers..that's the general impression I'm getting because everyone seems to be using vibrant alloy.

**Comment by WarlordWossman** [comment]
A small vibrant alloy turbine makes 405 eu/t with around 400k durability, there are plenty of options that have almost no durablity or make like 160 eu/t which is pretty pathetic if you think about the fact that you need HV circuits and stainless steel to set the multiblock up in the first place...

**Comment by sthegreat** [comment]
The reason everyone is discussing vibrant alloy turbines is because as far as I can tell the main object of this discussion is pre-moon HV tier. After you make it to the moon, steam becomes entirely different because there are better turbines, better dynamos, and steam can come from fluid reactors instead of boilers with charcoal.

Small vibrant alloy turbines, at 405 eu/t, are the best turbine that can currently be built and used without titanium. If multi-amp dynamos were to be added, the small shadow turbine from thaumcraft would be significantly better at 720 eu/t with the same efficiency.

**Comment by Vernam** [comment]
Steam is a very simple replenished resource, so it is logical that it has a low energy intensity and is not so effective, because it can easily be extracted and received energy indefinitely.

**Comment by Vernam** [comment]
thanks to such useless ideas, the assembly develops longer than it could, because Dream has to listen to all this and try to do something instead of closing the githab and accepting only those ideas that have clear logic. Such ideas, where there is nothing to complain about. Often on a github, you can see only very useless and extremely illogical proposals, which are spent time, which could go on improving the assembly to the ideal. Want casual assemblies - go to the project ozone and the like.

**Comment by sthegreat** [comment]
Really? Biodiesel and benzene are also very simply replenished resources, but they aren't nearly as weak as steam, even at a tier when you are quickly gaining access to new steam technology like the large turbine. Oil is also extremely powerful, and while it's hard to make infinite there is no reason for pumping up oil from buildcraft to be way better than everything else. It's good for balance and gameplay to have multiple options at each tier, and there's no reason to say steam shouldn't be competitive when there are plenty of boilers and turbines made for the tier (by Greg).

**Comment by Vernam** [comment]
steam is conceived as an initial / transitional stage to receive energy by other, more good ways. Improve pairs now - simplify part of the game, if not all. Benzene is not available immediately, as are other sources described above. Steam is available almost from the very beginning. this should give rise to the thought that you should not improve it. Where then development? to sit on a pair of the whole game? Greg made everything logical enough, and for a couple you will not sit out too long. You propose to improve it so that there will be no incentive to look for alternatives. You are looking for an easy game. But modpak is designed for development. At each stage There are already different options for obtaining energy, there is no sense in improving steam. I see in this just an attempt to simplify the game, so far there was no worthy argument that the steam should obviously be improved. And after all gregtech for a long time exists, and to anybody in a head did not come to improve steam. Do you know why? Because it does not need to be improved, and any attempts to fix it - an attempt to make the game easier. but the game is not complicated so that there is a need to simplify it

**Comment by Vernam** [comment]
I will even predict your future. Steam will improve, it will affect many mechanics at the global level. This will be tolerated until someone smart writes a post that it needs to be removed. So why this vicious circle? But this will happen, sooner or later. 

A similar story already happened with biogas. And how good is it now? he is not even worth it.

**Comment by sthegreat** [comment]
The steam buffs we are mainly describing are rather small. The most substantial additions are 2A dynamos, unless you can describe a balance issue that would be caused by these I see zero harm involved with what we're doing here.

**Comment by richardhendricks** [comment]
Biogas was never intended as a primary fuel source, and because the generation recipe was trivial and easy to exploit, it had to be removed. Go read the tickets for the history. It wasn't an arbitrary choice, biogas was a shit meta.

**Comment by draknyte1** [comment]
Greg's work exists in a sense that he wrote the base mod, but Greg has had zero to do with GT5u development for years. Myself and others have been the driving force behind the continued work. 

The proposed changes won't effect balance in any major way, as we've discussed the pros and cons in great detail. Unless you're going to contribute ideas or suggestions, please refrain from posting pointless statements.

**Comment by Vernam** [comment]
all this discussion is meaningless and irrational. I did not see the need to improve steam. So far I see "oh we are so hard, we do not want to have complex chemistry, give us a simple source of energy, it's hard for us further!"

**Comment by draknyte1** [comment]
@Vernam, Your opinion has been considered, thanks. 

This discussion is simply that, a discussion. Since you aren't contributing anything constructive to it, we'd all appreciate if you stopped. While *you* do not see the need, the rest of the community playing GTNH is interested enough to consider it. Please allow them to discuss this without further pointless contributions, or consider actually saying something useful.

**Comment by Vernam** [comment]
you yourself would think to bring something useful in the discussion)

**Comment by Lainiel** [comment]
> oh we are so hard, we do not want to have complex chemistry, give us a simple source of energy

Oh yes, I'm in EV/IV using burning cetane like a madman and just finished epoxy to complete fluid nuclear reactor. Guys I really need that Steam buff so I can progress further.

@Prewf 
> Of course, if you effectively have infinite oil (which it seems you do based on #github-dicussion), then this comparison isn't even fair in the first place because you're comparing infinite amounts of a dense power source vs infinite amounts of a sparse power source.

I've built that oil rig only recently. I reached EU mode nuclear reactor before I ran out of BC Oil.  I still even have 2 oil wells about 10-15 chunks away from my base. I understand it might not be possible to run just on BC Oil from LV to nuclear after the nerf, but I just wanted to say that Oil is really strong and much cheaper compared to Steam.

> 2A dynamo hatch and boiler buff

I'm all for it. I have just an issue with singleblock HV steam turbine. I don't want to see people using that to power their bases and get away with it. If you chose Steam you should be building large structures (for the reason that Steam is a energy sparse fuel). So either we should increase the gap between the HV singleblock steam turbine and Large steam turbine or disable the HV single block steam turbine completely.

**Comment by richardhendricks** [comment]
Yeah I think we should keep the efficiencies for the singleblock steam turbines as-is but improve the dynamos with a 2a version (would really prefer 3 or 4A myself) and the turbine selection to give options for each tier that produce appropriate amounts of power, and a small buff to the large boilers to make them viable.

For the boilers, what about this to stick within the 2A limits at HV+
Large Bronze Boiler
16,000 L/s = 800L/t = 400 EU/t, or 3.125 Araw @ MV, @80% Teff = 2.5A, player will probably still use MV singleblocks at 75%(2) or LV singleblocks at 85%(10).

Large Steel Boiler
32,000 L/s = 1,600L/t = 800 EU/t or 1.56 Araw @ HV, @115% Teff = 1.8A

Large Titanium Boiler
48,000 L/s = 2,400L/t = 1200 EU/t or .585 Araw @ EV, @150% Teff = .88A

Large Tungstensteel Boiler
80,000 L/s = 4000 L/t = 2000 EU/t or  .244 Araw @ IV, @150% Teff = .366A

I think this is a fair reduction in output current as you scale up, seems like you are less likely (at least at mid-tier) to need a full continuous amp of EV or IV (battery banks or power station can provide buffering as well), and it still provides a good incentive to transition to nuclear or large kinetics.

It doesn't make steam OP vs oil based fuels but for players who make the investment in large setups it makes their effort worthwhile IMO.

**Comment by Prewf** [comment]
I guess I'll put this here as a reference but one valid argument I read against higher amp dynamos is that it can theoretically reduce the number of Large Turbines you have to build for any given setup. This is because rotors scale linearly in terms of optimal flow (and durability) when going from small->normal->large->huge. So if, right now, I have a 10k/second optimal flow small rotor but I'm generating 30000 steam per second, I need 3 turbines each with 10k rotors to handle the total throughput of steam. But with something like a 3A dynamo, I could make do with 1 turbine with 1 equivalent material large rotor (which handles 3x optimal flow of the small rotor with 3x the durability).

It's just something to keep in mind because material cost is part of the argument when comparing steam infrastructure vs oil infrastructure vs other infrastructure. I'm all for 2A dynamos, but maybe no more than that.

**Comment by richardhendricks** [comment]
Not necessarily true, since those small rotors are probably .8 or .9 efficiency and a large rotor would be 140-150.  So you'd probably blow up a 3A dynamo without choosing a new turbine rotor type.

**Comment by Prewf** [comment]
It's possible in such a case you'd probably have to settle with 2 turbines then. Which is still less than what you'd have to build now. Point still stands that there's a lot more configurable rotor options available the more amps you introduce to a dynamo, making setups more compact.

**Comment by richardhendricks** [comment]
Honestly I don't see that as a negative.  It seems people are either doing 1 or 2 turbines or 20+

**Comment by Prewf** [comment]
Well of course you don't. People want compact setups. But the theme of steam is that while the resources required are easy to acquire, the infrastructure to process all the incoming steam is not supposed to be space efficient. I'm just saying too many amps will indirectly remove material cost and make it too convenient (i.e. it's not *supposed* to be "compact"; that's the advantage dense fuels have).

**Comment by Prewf** [comment]
That's just my general feeling about steam..it should be "unwieldy" for the most part, both in generation and processing it into EU. This part is pretty subjective I guess.

**Comment by WarlordWossman** [comment]
> That's just my general feeling about steam..it should be "unwieldy" for the most part, both in generation and processing it into EU. This part is pretty subjective I guess.

Steam setups are already more bulky esp with pyrolyse, large boilers and multiblock turbines. You should also keep in mind that due to fluid regulator and pipe values you might want to use more turbine multiblocks anyways.
The steel boiler buff from 24k to 32k already means that you have to do more bulky piping if you don't want to void stuff.
Should honestly be fine since it doesn't change all that much.

**Comment by richardhendricks** [comment]
4A dynamos added to game allow for more LBT flexibility. I think the rest of the concerns have already been addressed.
