### ISSUE TITLE
Usage for PBI

### ISSUE THREAD

**Issue by Zoko061602** [GTNewHorizons/NewHorizons#3179]
#### Which modpack version are you using?
2.0.4.5
#
#### What do you suggest instead/what changes do you propose?
Since PBI has no uses yet, here some of my ideas:
-  Plastic Circuit Boards: 1 Plate gives 8
- Circuit Boards: uses 9L gives 4
- Machine material for ZPM+ machines (Instead of PTFE)
- Material for Carbon Fibres: 4 Carbon dust + 9L PBI gives 8
- Assembler Liquid for EV+ Batteries 
- Fluid Pipes: same transfer rate as Tungsten Steel, 1000K heat limit

**Comment by 0lafe** [comment]
As long as it gets all the other changes it needs, this sounds cool.

**Comment by Dream-Master** [comment]
which other changes @0lafe  ?

**Comment by 0lafe** [comment]
Mostly changing the items that make it, unless that already happened. Having a high tier plastic use copper, zinc, manganese and coal is a little ridiculous in my opinion. I'd love to see it use high tier stuff, maybe even gate it in some good ways. Use naquadria, maybe some uu or even some neutronium dust from avaritia.

**Comment by Dream-Master** [comment]
Or change it to use high volate willd o too ? @0lafe

**Comment by noobyaran9** [comment]
>maybe some uu or even some neutronium dust from avaritia.

If the plastic are not used for anything above UHV, I don't recommend the usage of UU matter at least not in large amount(>100mb). Honestly speaking, i wouldn't suggest the use of UU matter on any items at all because this material is create for one sole purpose that is creating items from nothing (power).

If there is no better way of getting avaritia neutronium (getting from black plutonium or having few hundreds of neutrons collector is really bad method), I'd suggest just use GT neutronium or some other higher tier materials like samarium, adamantium, palladium or black plutonium.

**Comment by 0lafe** [comment]
On the subject of avaritia neutronium, there's totally ways to get more than enough of it, and using it by the thousands is expected it not by the hundreds of thousands. Even a quarry can hit those kinds of numbers, and that's probably only the 3rd best way to get it. 

>GT neutronium 

That's dumb. It's literally just cook time, you'll never run out of the dust once you reach a t5 planet. 
>Sammarium

Not even high tier, just needs an excessive input of whatever the ore it comes from is, I can't remember which right now. 
>Adamantium 

Similar to neutronium, just less useful, but I'd totally be down with putting this in simply because it has little to no uses. 
>Palladium 

Really dumb "high tier" material you're also swimming in once you reach like a t4 planet. I'd love to have it in this recipe. 
>Black plutonium 

No reason to not use neutronium. It's the same thing, just requires 1 more processing step, and also comes from other sources allowing you to scale to your needs better. I'd also love to see osmium and iridium make an appearance in this recipe, they too are extremely underutilized. 

If you want to be evil, make it cost indium, and like tons of it. Replication ftw, but it would need in the realm of 15-30 per 144L

**Comment by noobyaran9** [comment]
>On the subject of avaritia neutronium, there's totally ways to get more than enough of it, and using it by the thousands is expected it not by the hundreds of thousands. Even a quarry can hit those kinds of numbers, and that's probably only the 3rd best way to get it.

How many quarries are u running unless you're talking about using tiny piles of cosmic neutronium dust.

>That's dumb. It's literally just cook time, you'll never run out of the dust once you reach a t5 planet.

We will be using the dust, which doesn't requires cooking.

>If you want to be evil, make it cost indium, and like tons of it. Replication ftw, but it would need in the realm of 15-30 per 144L

Indium is kinda interesting.

Honestly, I'll list down the materials that fits this PBI recipe below.
Naquadria, Vanadium, Lithium, Osmium, Iridium, Indium, Neutronium, Palladium, Adamantium, Mithril, Chrome, Platinum, Electrotine, Samarium, Draconium, Black Plutonium, Bedrokium, Awakened Draconium, Europium, Americium, Mytryl, Quantium, Ledox, Callisto Ice, Niobium, Gallium and Yttrium.

**Comment by 0lafe** [comment]
I'm with you for most, but have some comments 
>Vanadium 

Eh, vanadium magnetite isn't really a high tier thing, and neither is having ore processing centrifuges/electrolyzers, they just aren't really needed. Yea you can replicate it, but no one really would. 
>Lithium 

Similar issue. Comes from tons of stuff, but it's just a pain to get. It's an LV material anyway. Once you hit DD lithium ore. It's not that interesting. 
>Neutronium 

If it's GT, it can't be dust unless it's like 3k dust per hull or something. The dust is so inexpensive, it's just the smelting time that makes it hard to work with. 
>Electrotine

If it has some better spawns (t7 planets/DD) then maybe 
>Awakened draconium 

Similar issue to neutronium. Really, apart from avaritia neutronium, I think most of this should be done in ingots. Smelting times matter.

**Comment by Dream-Master** [comment]
So for now i add a few uses and change recipes to use HV,EV,IV Tier to make it. Additinal changes can be add easily.

**Comment by Dream-Master** [comment]
Pipes and hull need a change not working now.

**Comment by Dream-Master** [comment]
workig now

**Comment by 0lafe** [comment]
![41124151-57c4a610-6aa1-11e8-86e4-5519622157e4](https://user-images.githubusercontent.com/21280852/41823495-cfac0260-77ce-11e8-9cd7-dba9fa1ef382.png)

I put some ideas in here, I used the flowchart that I originally saw the recipe on for it.

**Comment by Dream-Master** [comment]
not make it to unrealistic @0lafe look at the new recipes i gated behind iv/ev/hv abd look if this is not enought.

**Comment by 0lafe** [comment]
Did you just increase the voltage requirements? Because that wasn't really ever something I didn't like, I just think the materials used in it were wrong for what PBl seems to be

**Comment by Dream-Master** [comment]
ok but look for realistic recipe. Naquadria and uu matter might be the right tier but unrealistic

**Comment by 0lafe** [comment]
That's kind of the problem with late game, the high tier materials are either not real, or not used in useful ways. This recipe also doesn't use copper, it generates it, which seems bad.

**Comment by Dream-Master** [comment]
which recipe don't use copper?

**Comment by noobyaran9** [comment]
@0lafe I think instead of indium hydroxide, indium phosphide could be used as indium hydroxide is unrealistic to create.

And maybe black plutonium in replace of neutronium if its too cheap as using cosmic neutronium is stupid for this recipe and normal neutronium is too cheap according to you.

Also, i would like to see more uses for material like samarium, adamantium if possible.

**Comment by Dream-Master** [comment]
Yes i like to see this materials too but not for PBI.
https://en.wikipedia.org/wiki/Polybenzimidazole_fiber
