### ISSUE TITLE
Try creating a villager banker to trade coins - was [RFC] Move GT component coins quest to villager trades

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3206]
So, yet another option to consider when nerfing/etc the coins quest.  What about moving the trades to villagers?  I would do the maths so that the trades are for 1 item instead of the multiple items we have today in the coins tab.

This would be for part components like motors/pumps/conveyors etc, circuit components, chemicals, and ingots/wires.

For example, instead of 2 LV motors costing 30 coins, a villager would have 1 LV motor for 15 coins.  Instead of 8 resistors for 40 coins, a villager would have 1 resistor for 5 coins.

I would split villagers into types based on tier, and maybe on certain groupings.  IE, circuits would be an "electrical engineer", fluids would be a "chemist", cables/ingots (if we keep them, definitely need to be way more expensive) could be "metallurgist", vanilla piston/motor/conveyor/pump would be "hobbyist engineer", GT piston/robot arm/sensor/emitter would be "professional engineer"

This would naturally have some limitations built into the system, since villager trades would have to be reset to get frequently used items, so there is plenty of friction involved. I think we can also add some trade delays - maybe after 4 trades the villager says "I'm tired, come back tomorrow" and the player has to wait a minecraft day/night cycle. Players could trade items they don't want, or arc furnace them, and collect/horde/trade villagers. 

Player villages would also trigger zombie sieges, which would encourage use of automated defenses, another plus.

Would probably need to offer a couple villager spawn eggs or a coins quest, although players can still grind the healing axe, or use vanilla methods to cure villager zombies to start their own village.

Would add a couple of quests: trade station, doors for a new village, guard golems, etc.

Need to watch out for server load issues/lag concerns.

Discuss.

**Comment by Anarack** [comment]
Do we really want to encourage infinite villager breeders?
Why bother with delays when you can just kill them and make another.
As for zombie hoards its not that hard to seal something off without bothering with turrets or other active defenses.

**Comment by richardhendricks** [comment]
I think it's a better option than the coins.  No different than all the other things we "encourage" tbh.

Do villager spawners copy-exact?  I thought they were still random.

**Comment by richardhendricks** [comment]
And sure it can be trivially sealed off, but only if a player is smart enough to not locate the villagers near their base.  And siege zombies ignore normal lighting rules, so they can spawn anywhere.

**Comment by Anarack** [comment]
They are random when they spawn, but with how easy the are to make a ton I don't see a point in moving them out of the questbook into this. 

Also for servers you will have to do something like this anyway to as most villages that people have been near for any length of time will be dead. 

As for sieges there are ways to make sure they never successfully trigger, but if your getting that far into village mechanics you might as well make a iron farm at that point.

**Comment by richardhendricks** [comment]
Healing axe + villager zombie works.

The point is that it involves some effort and thought and planning and luck vs clicking a button and waiting for a cooldown.

**Comment by Dream-Master** [comment]
I am against the villager trades. with quest you can control it better. You can't set the repeat time to villages.

**Comment by MineAnPlay** [comment]
I agree, yes it's a good idea but it's very easily exploitable and very hard to control.

**Comment by Wolozo7** [comment]
General question, what's the purpose of coins in your opinion, guys?

**Comment by richardhendricks** [comment]
@Dream-Master I think we can intercept the villager trade event, and make it so that players have to wait for a cooldown that we can set in code or by config option.  Maybe after 4 trades the villager says "I'm tired, come back tomorrow" and the player has to wait a minecraft day/night cycle. Or we can do something after every trade, idk.

I like this idea because it uses an already-present mechanic in an interesting way vs just using the questbook. 

We could even add "banker" villagers who would trade coin types.  Maybe as a proof of concept we can introduce one of these, see how it feels.

**Comment by richardhendricks** [comment]
I think we might be able to modify the trade costs with each transaction as well, maybe globally.  Might be able to make a real economy, with the villager trades going down in cost if other items are purchased. I think there can be a lot of options there that shouldn't require alot of development.


https://skmedix.github.io/ForgeJavaDocs/javadoc/forge/1.7.10-10.13.4.1614/

**Comment by richardhendricks** [comment]
@Wolozo7 Check this ticket https://github.com/GTNewHorizons/NewHorizons/issues/3189

**Comment by Bryfer** [comment]
Seems easier to stay with quest book and just increase the prices of stuff that are too cheap. 
I also like the idea to trade dust/ores instead of ingots.

Coins right now is just something that got added too quickly without knowing what it would do, and now you can buy stuff with them, and the prices has not really been adjusted to how many coins there actually is available 

Stuff that is popular should increase in price, and the easiest way to do this is to manually adjust the prices based on player opinions.

People whom started prior to the coins coins coins quests have ALOT of coins already.

**Comment by richardhendricks** [comment]
OK, I will keep this ticket open to test a villager "banker" implementation, to see what we can do about fiddling with costs, trade cooldown times, etc. but in general issue is closed.

**Comment by boubou19** [comment]
it needs 20 minutes for a villager to be able to trade if you breed them, and according to wiki, bred villager is random. Plus if you consider the fact that there are trade limitations to avoid spamming them. As far as i know, players are able to only spawn villagers with Draconic spawner which need a villager soul a very rare drop, EIO villager soul vial is blacklisted from soulbinder, making it impossible to spawn a villager with EIO. So in my opinion farming villagers take much more time than making components.

**Comment by sthegreat** [comment]
Keep in mind that gtnh is 1.7 and the big villager overhaul was in 1.8. This means that making an infinite villager farm should be much easier than in recent minecraft versions since it won't need a very complicated setup and won't need crop input.

**Comment by Dream-Master** [comment]
yes but I don't want put all this trades to villages only. Let's nerf the things in the book first.

**Comment by richardhendricks** [comment]
@boubou19 I see those as advantages. It limits the return on villagers.  They can still be bred, and with a sophisticated system can be automated.  Seems like a perfect GT:NH system to me. 

Anyways, it's tabled for now.

**Comment by draknyte1** [comment]
Thing is, there is limits to villager trades, so chance to get the correct villager and then to try exploit it's trades to get the correct ones is low % sorta stuff. If you can only spawn them via DE, then this is rather moot to exploit I guess.

**Comment by 0lafe** [comment]
>only spawning villagers from DE

You can spawn them with thaum super easily, which is how I got my bee guys. You can also spawn the vanilla way. 

My honest opinion on villager trades instead of quests, is that this is a terrible idea. For the most part, it's gating the same problems the coin quests had, behind some dumb luck. Just make a villager spawner, then come check later and see what kinds you have, probably gonna have a coin guy or two, but it's not like there's much you can do to increase your odds or much else. 

This also doesn't help with the problem or people getting free items lol. I still don't see how crafting a mixer should give me a couple motors. The point of making a mixer is that you need it to make certain things, and it gives bonus output on some dust recipes. You shouldn't be making a mixer so you get a chance at some free tierer parts. 

I love coins helping with stuff like finding in world items that could be gone from other players taking them, or just annoying to find. I'd love to see more things like that added, maybe buying some monastic drones instead of needing to find a trade for them, buying some Pam's crops stuff would be cool too. Most of my complaints can be summarized in saying that I think the technician coin should be removed, as well as what it purchases (I'm pretty sure they're the ones used for motors/robot arms/etc...)

**Comment by DV666** [comment]
I am agree with @0lafe : villagers can be pretty cheat if you can spawn them a lot (just need some sorting to kept best villagers and that's all).

I suggest to remove spawner villagers from mods like Draconic Evolution (need blacklist on config), Thaumic Tinkerer (?) and other (EnderIO already blacklist Villagers).

I prefer the BQ solution imo but i am just curious @richardhendricks how you will do that :) Impatient to see your special villager.

`yes but I don't want put all this trades to villages only. Let's nerf the things in the book first.`

That can be interesting indeed. Maybe increase cost from BQ or reduce coin reward : we need to make perfect balance between this chapter and villagers.

**Comment by boubou19** [comment]
i think there is no need to remove villagers from DE spawner because by the time you can make a DE spawner you don't need items sold by the villagers, and you also need to kill villagers until you get a soul, a rare item even with Reaper V

**Comment by 0lafe** [comment]
>remove from thaumic tinker and DE

Yeah, DE is kind of late game, making it less OP. Not sure about thaumic tinker, I think I spawned mine another way. There's also vanilla villager spawners which seem a little harder to remove. 

Anyway, I don't think that villagers need a whole redo because quests are OP, just make quests less OP but still quests.

**Comment by Dream-Master** [comment]
give us a config option please @draknyte1 
I dont know now which trades we want/add now or later.
Thanks

**Comment by draknyte1** [comment]
If you'd like, I can just add an API function into GT++ so you can just add them into DreamCore?

**Comment by Dream-Master** [comment]
ok that would be good too.

**Comment by richardhendricks** [comment]
Superceded by #3051
