### ISSUE TITLE
Status of the goddess

### ISSUE THREAD

**Issue by Waisse** [GTNewHorizons/NewHorizons#3238]
#### Which modpack version are you using?

#2.0.4.6
#### If in multiplayer; On which server does this happen? 

#Delta

Vampires, werewolves and skilled witches can apply curses to players. I suggest to add a status of the goddess at spawn to prevent any future isssue concerning them. Or set AllowGoddessStatueRecipe to true to make it obtainable ingame.

**Comment by Dream-Master** [comment]
will check

**Comment by PoptartOverlord-Xabedo** [comment]
it should be noted that statue of the goddess is a little too op as it renders the progression in witchery useless, since removing curses is an end game witchery  thing, and making statue of the goddess renders most of the mod as unnecessary, so if you add the statue, make it hard to  craft and add  it to the thaumonomicon in the witchery tab

**Comment by Dream-Master** [comment]
Ah a nice engame Thaumcraft recipe or a 9x9 recipe can be added if we need it. Or a endgame quest reward is possible too.

**Comment by Waisse** [comment]
Keep in mind that Witchery curses are only for pvp. They also can't be lifted unless you are a skilled witch yourself. Since official servers are consensual pvp only, I don't see how making the status available for free will change anything.

**Comment by Dream-Master** [comment]
So what we need to do @Waisse @PoptartOverlord-Xabedo make it as a Quest reward or during Thaumcraft research or as super expensive 9x9 recipe?

**Comment by PoptartOverlord-Xabedo** [comment]
it could be a quest reward but then to which quest? and since its magic it'd be nicer if it was a thaumcraft infusion recipe after unlocking ichor researched in the witchery tab also maybe use the witchery item heart of gold , but keep in mind that the heart of gold is very heavily locked behind RNG, as you need a mob that spawns very rarely and to trigger that spawn event you need a mirror. so i recommend using 1 heart of gold max
anyway we could do the following recipe, since it should be an endgame witchery item
in infusion altar
1 heart of gold in the middle 
4 ichor 
2 soul of the world 
2 necromantic stones
4.koboldite ingots 
as for the essentia , i have no idea about the amount but here are the essentia 
Sano
ordo
Victus

**Comment by Waisse** [comment]
Curses only happen between players, they don't affect singleplayers so a quest wouldn't make much sense. On the other hand, the status was specifically created for server play with lax pvp settings like Delta.

https://sites.google.com/site/witcherymod/statue-of-the-goddess

> The statue is intended for server administrators to provide a way for players to remove curses at a known location in the world.

**Comment by Prewf** [comment]
There's a rite to remove curses. Isn't that all you need? Why does this statue need to be craftable/in-game?

**Comment by Dream-Master** [comment]
because people don't know either and choose only the easiest way.

**Comment by PoptartOverlord-Xabedo** [comment]
true as the rite is alot more efficient and should be alot cheaper but people still seek the easier way even if its a bit cheaty,so now players have 2 options the rite which is cheap but hard and the statue with is expensive but easy to get(as most people may not know how to witchery) i personally prefer the rite but also it'd be nice to craft a creative item ;3

**Comment by Waisse** [comment]
What's going to happen if a new player get cursed by someone else ? Tell him to suck it up for hundreds of hours until ha can remove it himself ?

**Comment by Dream-Master** [comment]
Maybe we add a passus in the rules not to do pvp and take curses on players. If somone did against the will of the second player we could ban him.

**Comment by PoptartOverlord-Xabedo** [comment]
to be honest i have a mixed opinion on that, as it is both logical but still really unexciting at all like getting banned for pranking a friend is ridiculous but at the same time getting banned for making it harder for new players to play is also bad, i personally dont have a good solution but i still prefer for curses to be a  thing.

**Comment by Prewf** [comment]
>What's going to happen if a new player get cursed by someone else ? Tell him to suck it up for hundreds of hours until he can remove it himself ?

Well if someone is griefing you, I don't see why a simple pm to an admin can't sort that out. If it's "consensual" pvp, both parties should properly prepare themselves, but it seems like you're more concerned about the griefing/trolling aspect of curses, in which case just tell an admin?

Most of the low-tier curse removal rituals won't take "hundreds of hours" and can honestly be done without delving too far into witchery. It's only vampirism and lycanthrope curses that might be slightly annoying, but from what I saw, all they require is high altar power and several low-tier witchery ingredients. You don't need a coven, you don't need any special chalk, no owl/frog breeding, no summoning demons or any of that annoying witchery stuff to do this. From what I saw, it actually takes a hell of a lot more effort on the part of the person doing the cursing, than the person trying to remove the curse.

There's also voodoo protection poppets that prevent curses I think. These are stupidly easy to make. There's also: don't let the other guy ever get near you to get a taglock on you? Don't let them into your base to get a taglock on your bed? That prevents this whole scenario altogether, but if it gets to harassment/griefing levels, again just contact an admin and I'm sure they'll sort it out. There doesn't need to be some creative-mode statue added in the game to fix this issue.

**Comment by Bryfer** [comment]
I totally agree with Prewf here, this is one those items that should never be nessesary to make on Delta/Epsilon since there is no PvP, and griefing is already agnst the rules
Other servers might have to add this statue if they allow PvP, but I don't see any reason to add it into the game unless the situation gets out of control.

So a question for you guys is, do we need to change anything in the rules or is the rules clear that magic can count as griefing aswell?
Also there is a constant reminder in-game that griefing can and will lead to ban.

**Comment by Waisse** [comment]
And how do you tell who cursed who ? You guys prefer to bother admins for each case other providing a statue that can do that at spawn. Curses can be done by witches but vampirism and lycanthropy are both available without any GT progression and can be spread without any witchery progression.

**Comment by boubou19** [comment]
Waisse keep in mind that you and xabedo might are the first players starting the pack using witchery. In 2 years that's the first time i see a warewolf player and a vampire player so the case you describe will be extremely rare

**Comment by PoptartOverlord-Xabedo** [comment]
alright i completely understand your points and i agree with some of them but im sorry to disappoint you, as you have mixed it up,see curses depends on how strong the caster is and so is removing them, as lets say a low level witch casts a curse, then the rite would be easy to remove, but if the curse is casted by a high level witch then the chances for the curse to be cured gets lower and lower, and yaknow that the rite of remove curse has a chance to fail that gets bigger the stronger the curse? and  vampirism and lycanthropy are high level curses by the way but their ways of infections aren't as easy, as vampirism requires you to drink blood(a human player is the one that drinks blood of a vampire or the lilith boss) but lycanthropy can be spread by hitting players a couple of times and that would be breaking the rules of no pvp unless both parties agree.
but anyway we're just thinking about the possibility of some asshole coming around and cursing everyone which is highly unlikely and their actions will count as harassment, but usually people cursing are friends with each other that the friend who cursed is highly likely to be the one that cures .
and as boubou has pointed out not many choose the route of witchery so its highely unlikely and extremely rare for people to go around cursing others.
but anyways in my opinion  i still recommend making the statue of the goddess craftable because i personally find it quite nice,but as i pointed before it shouldn't be cheap

**Comment by Wolozo7** [comment]
Xinobi is/was a vampire. But ye, in general I agree, the majority of players won't touch witchery, so this isn't really an issue. I wouldn't mind having a statue placed at spawn though, they look nice.

**Comment by PoptartOverlord-Xabedo** [comment]
agreed they look quite hot





i hope no one reads this comment

**Comment by Waisse** [comment]
A few cases that are most likely to happen : 

- Consensual pvp with a werewolf. The opponent catch the curse. Is it griefing ? What if both party have no way to remove the curse ?

-Someone want to try being a vampire and ask another vampire to become one. He then realize he don't want to. Same issue.

- Pranking a friend with curses. It's funny, but not when the curse can't be lifted and become stronger.

An healthy server environment is one where players are not afraid to interact with each other, so having the status available at spawn would be nice to have for everyone.

**Comment by Prewf** [comment]
>And how do you tell who cursed who ?

The other party has to taglock you. I don't see how it's possible where you don't notice someone walking around you trying to taglock you. And as for your bed, you can put that literally anywhere you want, away from the prying eyes of strangers. I'm giving you the benefit of the doubt and assuming that it's some random stranger trying to mess with you, not a friend (which trivializes this issue even further if this is the case). If it's a friend doing this to you as a prank, **then hopefully that friend is nice enough to help you remove it since they were certainly high tier enough in witchery to cast the curse on you in the first place**. If not, report them to an admin, especially since griefing isn't even tolerated in your server.

>curses depends on how strong the caster is and so is removing them, as lets say a low level witch casts a curse, then the rite would be easy to remove, but if the curse is casted by a high level witch then the chances for the curse to be cured gets lower and lower, and yaknow that the rite of remove curse has a chance to fail that gets bigger the stronger the curse?

You guys are making it sound like it's an impossible task to remove a curse. All it takes is one successful ritual. The actual ingredients in the ritual are not that far into witchery. Once an altar is set up, there's literally no other work involved besides letting it recharge, and gathering more of the (easy) ingredients you need for the curse removal ritual, and trying again.

>but anyway we're just thinking about the possibility of some asshole coming around and cursing everyone which is highly unlikely

This can't happen apparently in your server, so it's not even a case you have to worry about. Honestly, it's sounding to me like the vampirism/lycanthropy mechanic, without pvp, is something you *want* to intentionally put on yourself either for the aesthetics or the stat boosts/nightvision/whatever. If that's the case, it should be a pain in the ass to remove it, since it's a pain in the ass to apply it.

**Comment by Prewf** [comment]
>What if both party have no way to remove the curse ?

This is actually a pretty hilarious situation if it were to happen. So you two willing pvp'ed without knowing any way to undo the situation you're about to put each other in.

>Someone want to try being a vampire and ask another vampire to become one. He then realize he don't want to. Same issue.

>Pranking a friend with curses. It's funny, but not when the curse can't be lifted and become stronger.

Both of these are cases where the people involved didn't fully look into what it takes to undo their actions. If you make a mistake, it's not up to the server to magically fix it for you. There's a mechanism in game right now, without any creative-mode special items, that lets you do this.

**Comment by Waisse** [comment]
This thread is going way too far. I asked to add the status at spawn in the UNLIKELY case a curse goes wrong. Why bother an admin when a statue could be added to spawn ?  As I said multiple times curses only happen between players, they don't affect progression.

We can keep arguing it will never happen tho. But I can assure you a skilled witch can get taglocks from anybody on a server without getting caught.

Let's say something bad happen, someone get cursed by who knows who. What's an admin gonna do ? You will never know who did that and the admin will just spawn the statue to remove the curse from the player anyway. So can we just add one to spawn ?

What are we arguing with seriously ? Griefing isn't allowed, so why not add the damn statue to fix any possible grief, malicious or not ?

**Comment by Waisse** [comment]
> Both of these are cases where the people involved didn't fully look into what it takes to undo their actions. If you make a mistake, it's not up to the server to magically fix it for you. There's a mechanism in game right now, without any creative-mode special items, that lets you do this.

So now players have to lie to benefit from an admin intervention in case something goes wrong ?

`Someone cursed me and I don't know who, can an admin spawn the status please ?`

**Comment by Careface1g** [comment]
There should be a rule not to put curses on people you don't get their approval of. In cases you do get approval you should be able to remove them atleast.

As for Rite of Remove Curses for lycanthrope /Vampirism removal you do need a full coven and a cat familiar even if it dosen't say it in the book.

Statue of Goddess wouldn't solve the problem of Vampires/lycanthrope cure as it only cures curses (as seen here https://ftbwiki.org/Statue_of_The_Goddess) so that won't help in accidental infect.

**Comment by Prewf** [comment]
If the statue doesn't remove vampirism/lycanthrope, the two hardest curses to remove, what does adding the statue accomplish? Also, from what I understand, a coven isn't mandatory, it just betters your chance of a successful removal. Some rituals have mandatory coven, I don't think this is one of them.

The other curses are not difficult to remove through natural witchery means. The'yre all 2K'ish altar power rituals with a couple of ingredients that mostly require just the base witchery constructs. Again, this doesn't take more than an hour or two to achieve, starting from nothing. Curse level means very little if all you have to do on your end, is just simply re-do the ritual until it succeeds once.

>So now players have to lie to benefit from an admin intervention in case something goes wrong ?

I don't know how you came to this conclusion based on what you quoted. Look, you both have clearly set your minds on this from the very beginning with the false pretense of making it look like you're actually considering my points, but the fact of the matter is:
1. There's already a way to remove curses for like 80% of curses, and it's relatively easy compared to the rest of witchery. Setting up an altar is a one time process and most of the work goes into gathering the ingredients, which is not too difficult for a majority of the 2K curse removal rituals. **You guys realize what pack you're playing right?** How is adding a creative-mode **anything** in the spirit of this pack? Even for something like pvp. Your stance for adding this statue in is based on a situation that doesn't even happen right now. Is there a person harassing/griefing you with curses right now? What's with all these hypotheticals if you two are literally the only ones doing this pvp stuff in the server, AND the server has rules against griefing? We shouldn't have to add this statue in just so you two can freely mess around with curses all you want.
2. Again, if a person is repeatedly cursing you/griefing you, you can fix that by contacting an admin about it. Especially since these kinds of situations are few and far between on your server. According to your logic, with the statue added and your hesitance to contact an admin, you make it sound like you prefer to continue playing with a toxic player vs just banning them outright and not having to deal with them.
3. The remaining 20% of curses (vamp/lycan) you can't even use the statue like @Careface1g said, so what are you going to do here? Your only option is to actually delve into witchery or get help from someone who already has an altar.

I'm very strongly coming off as a "no fun allowed" grump, but this isn't even some widespread problem you guys are bringing up here. It's a one off case that already has a solution in-game.

**Comment by Waisse** [comment]
Griefing is not allowed, so curses are technically not, but it doesn't really matter to find a solution to a problem that never happened, therefore I'm closing this issue. I feel like I'm alienating people for trying to prevent a situation that happened on other servers with the same rules, so let's not talk about that anymore.
