### ISSUE TITLE
Special Mobs

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#327]
Special Mob update. Will we give the mod a second chance?

http://minecraft.curseforge.com/mc-mods/59968-special-mobs/files/2256147

**Comment by Namikon** [comment]
Sure, why not. But I don't see any changelog regarding tps / chunk issues. We're on the limit of the CPU already with the current setup if everyone is playing, so that should be verified on the testserver first, for at least one week, and monitoring the tick time in opis before and after adding this mod

**Comment by Dream-Master** [comment]
I get today this Error.

https://gist.github.com/Dream-Master/476dfa9fe11b3391d693#file-special-mobs

**Comment by Namikon** [comment]
Well you should report that to SpecialMobs, not here

**Comment by Dream-Master** [comment]
I did but i think we never get an answer there.

**Comment by Dream-Master** [comment]
Added
