### ISSUE TITLE
Ore Wand Quest

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#3271]
Maybe add a tier 2 Ore wand quest with more ores like Dias and co.

**Comment by WarlordWossman** [comment]
Tantalite vein is a bitch to find.

**Comment by Dream-Master** [comment]
ok maybe mica too?

**Comment by Scottishprog** [comment]
Yes, do this... especially tantalite... that gates EIO. Mica is nice, as well.

**Comment by richardhendricks** [comment]
Whoa, wait a minute.  Tantalite and mica?  Those ores are for well past LV.  Shouldn't a player be using @bartimaeusnek 's basic ore scanners instead of the wand?

**Comment by Dream-Master** [comment]
is this really a big exploit? Dias you need very soon. Ok Mic and Tantalite you can find by randomness but why not get a ore. i could make the quest choose one ore to proceed if this is less exploidable @richardhendricks

**Comment by richardhendricks** [comment]
I didn't specifically include Diamond ore since Coal ore can also be used to locate diamond veins.  Mica and Tantalite you should be using the LV+ finders IMO.

I don't think it's an exploit, but I think it makes sense to move players to technology solutions by that time (MV-HV).

**Comment by WarlordWossman** [comment]
The prospector scanners are totally not worth it, they have like 10 uses so you can locate 2 or 3 veins with the LV one and a few more with the heigher tiers (better chance of success).
I would rather just dig holes then spending ressources on those things. Make them actually last longer then a few rightclicks if you want people to use them.

**Comment by richardhendricks** [comment]
Give me some numbers on what you consider fair uses and we can adjust the damage per use.  We need to make sure we scale it appropriately with proper materials.

**Comment by WarlordWossman** [comment]
Hard to tell, I think the the durability you get from the higher tier materials gets negated by the higher tier scanners scanning more chunks at once. The succesrate thing doesn't really make too much sense imo since it just makes you burn through durability. I made 2 LV prospectors (using steel since it looked okay-ish and I cba to check 146 options; esp since some variations have 0 durability) and went out scanning. Found a coal vein, a magnetite vein and a limonite vein. For the price of 2 of them...
So yeah if tantalite is a vein you need 100 shafts for I am not going to make 50 of those scanners and spend 100 LV circuits rather then just digging.

Correct me if I am doing something wrong here or if most materials available in LV suck a lot and I have missed the one material with godly durability.
The big problem is that even if it sounds strong on paper that you can just scan without digging, most of the time it will display the common veins, which you probably found already...
The concept of the stone age rod only gives you a result for what you are actually looking for.

**Comment by Dream-Master** [comment]
wait a moment. Not change the values yet make the scanner very op. we need to find a value before change it.

**Comment by WarlordWossman** [comment]
> wait a moment. Not change the values yet make the scanner very op. we need to find a value before change it.

I am not saying they need an instant change, this was more about actually discussing how they perform.
My experience with them is very limited so I might be doing something wrong.

**Comment by Dream-Master** [comment]
@bartimaeusnek

**Comment by Dream-Master** [comment]
Ok charge able isnt a good idea but repair it with materials would be nice. @richardhendricks are you able to programm it?

**Comment by richardhendricks** [comment]
I already have a lot on my plate, so probably not soon.  Maybe this winter. :D

**Comment by richardhendricks** [comment]
Fixes for the basic prospector in place, will re-evaluate usage after next release.
