### ISSUE TITLE
Logistics Pipes Discussion Attempt #2

### ISSUE THREAD

**Issue by Bryfer** [GTNewHorizons/NewHorizons#3286]
**Welcome to Discussion Attempt #2!**
---

The last issue got very messy. Its a real pain to get any ideas at all what you (the players) actually want here.

In this thread I do NOT want any discussions at all. I just want **ONE** comment from each of you.

In this comment I want you to answere these questions, and add your additional thoughts of why you want LP to be added, or why you do not want LP to be added,
What questions you ask? Keep reading.

I have also added a bit of information to help you compare with the current available mods in the modpack. 

If you feel that I have missed any important questions here, Please contact me on Discord, Do not make a comment about it here, As Mentioned I just want ONE comment from each of you with your opinions.

---

Here is a list of current methods that exists right now

**Item Transportation**
Currently there is hoppers from iron (steam tier)
GT pipes (all tiers) + filter+ type filter(MV+)
Alot of small stuff in ( LV ) (can't remember all names sry)
Translocator (LV)
PR (LV-MV)
EnderIO (HV)
AE EV+
SFM (tier?)

**Storage Systems**
Jabba/drawers* (*requires PR or similar)
PR (MV) (this might be moved to LV see separate git issue)
EnderIO (HV)
AE (EV+)

**LIquid Transportation**
Buckets (Steam) (with gt pipes and hoppers)
Tinker's (Steam)
GT pipes (all tiers) + filters at MV(?)
EnderIO (HV+)
AE (EV+)
SFM (tier?)

**(auto)Crafter (ing tables)**
PR (disabled partly)
EnderIO (HV)
AE (EV+)

I have problably missed something in this miss, feel free to compare it to something else in the modpack if you wish.

---

**Here comes the questions.**

It would be nice if you could copy these questions into your answer, but there is no point in including my entire post.
You can also skip a few questions if you wish, but do include as much details as possible please.
*We want your personal opinion.*

How long have you played GTNH? (number please)

Which tier are you currently in? (just a tier is enough here)

Do you want Logistics Pipes to be added to GTNH? (Yes/No)

Which tier do you think LP would fit in? (just a tier is enough here)

Have you used LP before? (Yes/No)

if Yes how was your previous experience with LP? (Please motivate)

What would you like to use LP for? (Please motivate)

How many of the current mods are you familiar with? (number please)

Which of the current mods do you compare LP to? (You can compare to multiple)

What would LP give to GTNH that its currently missing? (Please motivate)

How is LP different to the other available mods? (Please motivate)

Is there anything else you wish to add? (The more information, the better!)

**Comment by Bryfer** [comment]
Here for you to copy easily

How long have you played GTNH? (number please)
(Respons here)

Which tier are you currently in? (just a tier is enough here)
(Respons here)

Do you want Logistics Pipes to be added to GTNH? (Yes/No)
(Respons here)

Which tier do you think LP would fit in? (just a tier is enough here)
(Respons here)

Have you used LP before? (Yes/No)
(Respons here)

if Yes how was your previous experience with LP? (Please motivate)
(Respons here)

What would you like to use LP for? (Please motivate)
(Respons here)

How many of the current mods are you familiar with? (number please)
(Respons here)

Which of the current mods do you compare LP to? (You can compare to multiple)
(Respons here)

What would LP give to GTNH that its currently missing? (Please motivate)
(Respons here)

How is LP different to the other available mods? (Please motivate)
(Respons here)

Is there anything else you wish to add? (The more information, the better!)
(Respons here)

**Comment by bartimaeusnek** [comment]
How long have you played GTNH? (number please)
~2years

Which tier are you currently in? (just a tier is enough here)
IV/LuV

Do you want Logistics Pipes to be added to GTNH? (Yes/No)
No

Which tier do you think LP would fit in? (just a tier is enough here)
MV

Have you used LP before? (Yes/No)
No

How many of the current mods are you familiar with? (number please)
~200

Which of the current mods do you compare LP to? (You can compare to multiple)
AE2, Project Red, BuildCraft, Gregtech, EnderIO, Railcraft, 

What would LP give to GTNH that its currently missing? (Please motivate)
Nothing really. There are plenty of ways to transport items, or manage a Storage System.

How is LP different to the other available mods? (Please motivate)
I don't see much difference compared to AE2, Project Red or Buildcraft.

Is there anything else you wish to add? (The more information, the better!)
Due to the Rending of the Pipes, the codestyle, ASM usage and Reflexion, the TPS impact would be horrible if people make larger systems, same applies to Project Red and BuildCraft pipes.

**Comment by alphaNOVAircraft** [comment]
How long have you played GTNH? (number please)
Started 2  years ago, but played around 1.5 years

Which tier are you currently in? (just a tier is enough here)
Late IV / start of LuV

Do you want Logistics Pipes to be added to GTNH? (Yes/No)
No

Which tier do you think LP would fit in? (just a tier is enough here)
For the basic pipes and chips required for storing items: MV
For autocrating and more advanced pipe systems: HV 

Have you used LP before? (Yes/No)
Yes, but not in it full potential, just for small storage systems

How many of the current mods are you familiar with? (number please)
around 200 mods

Which of the current mods do you compare LP to? (You can compare to multiple)
PR, AE2, EnderIO, SFM, GT, Buildcraft
What would LP give to GTNH that its currently missing? (Please motivate)
A slight improvement to the Project red pipe system, but you normally dont stick to pipes to long anyways.

How is LP different to the other available mods? (Please motivate)
It is defintly a improvement compared to the Project red pipes, but otherwise i dont see any aspect it is needed, for all automatisation AE2, EnderIO and SFT (maybe OC too) is covered, so i dont see any need in adding LP

Is there anything else you wish to add? (The more information, the better!)
Back when i was playing Infinity Expert mode, some bases featured massive LP systems, the tps on nearly all servers at this time sucked, also my client crashed a few times when i was visiting people with LP systems, even when my client survived i had massive laggs in that bases. I would not be interested in seeing more large LP systems.

**Comment by WarlordWossman** [comment]
>How long have you played GTNH?

~ 3,5 years

>Which tier are you currently in? (just a tier is enough here)

HV

>Do you want Logistics Pipes to be added to GTNH? (Yes/No)

No

>Which tier do you think LP would fit in? (just a tier is enough here)

MV

>Have you used LP before? (Yes/No)

Yes, for a short while; see below

>If Yes how was your previous experience with LP? (Please motivate)

Items getting stuck on chunkborders (not loading the next chunk) and various other laggy things (server and client side), that the main reason why I stoped using them.

>What would you like to use LP for? (Please motivate)

Nothing, everything it could do can be covered with better (less heavy) alternatives.

>How many of the current mods are you familiar with? (number please)

90%

>Which of the current mods do you compare LP to? (You can compare to multiple)

Buildcraft and Project Red, since those also don't teleport items to the destination after routing. Ender IO conduits and GT pipes do a better job at item transportation (even hoppers do).

>What would LP give to GTNH that its currently missing? (Please motivate)

Even lower tps on servers, more situations that the staff has to fix (tons of items piling up on chunkborders)

>How is LP different to the other available mods? (Please motivate)

Not too different from other mods.

>Is there anything else you wish to add? (The more information, the better!)

I think ender IO and GT have a lot of options for item transport even early on, more complex stuff can be done with SFM or AE2. I stay away from pipes who actually simulate the items going through rather than teleporting them to the routed destination for reasons I named above.
The people who have played with the mod might want it and see it as "always better to have more options" but I think we should keep in mind that adding laggy things is never a good idea, esp for people playing on servers.

**Comment by Scottishprog** [comment]
Here comes the questions.

It would be nice if you could copy these questions into your answer, but there is no point in including my entire post.
You can also skip a few questions if you wish, but do include as much details as possible please.
We want your personal opinion.

How long have you played GTNH? .75 Years

Which tier are you currently in? (just a tier is enough here)
.5 (Steam)

Do you want Logistics Pipes to be added to GTNH? (Yes/No)
Yes

Which tier do you think LP would fit in? (just a tier is enough here)
MV

Have you used LP before? (Yes/No)
Yes

if Yes how was your previous experience with LP? (Please motivate)
I found them to be useful, however I never made really large setups.

What would you like to use LP for? (Please motivate)
MV Level crafting automation, there just isn't any flexible options at that tier.

How many of the current mods are you familiar with? (number please)
75

Which of the current mods do you compare LP to? (You can compare to multiple)
RP (where it's worse, especially in current tuning.), GT pipes to a degree, and AE2 (which is much better)

What would LP give to GTNH that its currently missing? (Please motivate)
An easier to understand pipe based automation.

How is LP different to the other available mods? (Please motivate)
I find the scheme for routing items in LP to be more functional/easier to use than RP.

Is there anything else you wish to add? (The more information, the better!)
I am leaning towards having only one of the two, preferring that RP get dropped in favor of LP.  The real issue for me the lack of useful crafting automation in the MV age. GT pipes might work, if they were improved a bit... already use them for simpler tasks. The current solutions require too many materials/time for what they return in functionality.

**Comment by noobyaran9** [comment]
How long have you played GTNH? (number please)
1 Year maybe? (Actual play time is shorter)

Which tier are you currently in? (just a tier is enough here)
UV?

Do you want Logistics Pipes to be added to GTNH? (Yes/No)
Yes

Which tier do you think LP would fit in? (just a tier is enough here)
Starting from LV and slowly build upto EV/IV

Have you used LP before? (Yes/No)
Yes but not much

if Yes how was your previous experience with LP? (Please motivate)
It works decently.

What would you like to use LP for? (Please motivate)
Inventory management, Item regulating, automation and little bit of autocrafting.

How many of the current mods are you familiar with? (number please)
All except PR.

Which of the current mods do you compare LP to? (You can compare to multiple)
PR.
LP is way better than PR in all ways.

What would LP give to GTNH that its currently missing? (Please motivate)
Better item regulating system and automated item stocking.

How is LP different to the other available mods? (Please motivate)
LP provides more capability than what PR could do and its not as janky. 
Why would i compare it to translocators / EiO inventory panel / other method?
LP is providing functionality that all the mods mentioned but with easier manipulation.

For ex.
-Tranlocator can only regulate item between 1 block space while LP can provides it anywhere as long you provide it the proper configuration and it is connected to you're inventory.

Is there anything else you wish to add? (The more information, the better!)
1) I'm suggesting this mod as a replacement to PR
2) This mod provides integration with AE. No nid to rip out the whole PR system when replacing with AE.
3) *Correct me if im wrong with this* This mod requires power to run while PR doesn't which is already a nerf.
4) I know that PR autocrafting is disabled. But I wish that this is enabled if PR is in the pack with sufficient gating.
5) Provides an alternative to people who already sick of playing with SFM and AE or any other inventory management system.
6) LP actually provides tiering system to its upgrade.

**Comment by Hakameda** [comment]
How long have you played GTNH? (number please)
Over a year

Which tier are you currently in? (just a tier is enough here)
Hv, New World

Do you want Logistics Pipes to be added to GTNH? (Yes/No)
Yes

Which tier do you think LP would fit in? (just a tier is enough here)
Mv, Its already gated very well with chipset recipes etc

Have you used LP before? (Yes/No)
Yes

if Yes how was your previous experience with LP? (Please motivate)
It's an old mod, It was a basis for AE and many other newer systems

What would you like to use LP for? (Please motivate)
Everything, It can replace AE, plus or minus some features ae added. It also has support in both AE and Logistics pipes so they can work together very well in hybrid systems, Including power sharing and item sharing

How many of the current mods are you familiar with? (number please)
234

Which of the current mods do you compare LP to? (You can compare to multiple)
The only mod is only comparable to is AE and EIO. As they both use a similar system (Sort of for EIO). PR Transportation is a poor rip off of some very low level features of Logistics Pipes

What would LP give to GTNH that its currently missing? (Please motivate)
Choice, A personal preference to use other mods when its viable is nice. There shouldn't be cookie cutter style builds where one thing is viable

How is LP different to the other available mods? (Please motivate)
It's based on buildcraft pipes, Can be neat to see items whizzing around to do things. Different style of playing.

Is there anything else you wish to add? (The more information, the better!)
The last issue got really messy, Based on silly things like alot of people who have voted no, Not even using the mod. Yes it's item transportation , Does not make it the same as all other ways of using it. Most people stick to power creep mods and couldn't be bothered to use anything else. It's a logistics mod, Encourages neat builds for automation instead of just hear is an ae cable.

**Comment by Vernam** [comment]
How long have you played GTNH? (number please)

2 years

Which tier are you currently in? (just a tier is enough here)

Now LV, but early have zmp

Do you want Logistics Pipes to be added to GTNH? (Yes/No)

No

Which tier do you think LP would fit in? (just a tier is enough here)

Hv or highter

Have you used LP before? (Yes/No)
(Respons here)

Yes

if Yes how was your previous experience with LP? (Please motivate)

played long enough. not the best mod, and also lags

What would you like to use LP for? (Please motivate)

Some little auromatic, not more

How many of the current mods are you familiar with? (number please)

+-190

Which of the current mods do you compare LP to? (You can compare to multiple)

SD, PR, AE,EC(extra cells) JABBA, RC, GT, EnderIO, some staff from TW, Thaumcraft with addons(automagy), ExtraUtilitis, Translocators, OpenBlocks(some staff) . I think this is more mods that adds transporting items/fluids and autocrafting 

What would LP give to GTNH that its currently missing? (Please motivate)

LP gives nothing good for servers tps and fps, more lags, bags with pipes, modpack will be heavier, let's not forget about the new dupes

How is LP different to the other available mods? (Please motivate)

nohow. A common mod that will copy the functionality of other

Is there anything else you wish to add? (The more information, the better!)

I do not see the sense of trying to change lp recipes, the mod will kill the need for AE because it copies its functionality. It does not have channels, Lp is not limited as it is limited to channels ae. and of course, almost all recipes can be automated through an assembler, in which there are almost all the necessary recipes. LP will remove the need to use the GT functionality as well

**Comment by Ethryan** [comment]
**How long have you played GTNH? (number please)**
1,4 years

**Which tier are you currently in? (just a tier is enough here)**
LV

**Do you want Logistics Pipes to be added to GTNH? (Yes/No)**
Yes

**Which tier do you think LP would fit in? (just a tier is enough here)**
MV-HV (MV for storage, HV for autocrafting)

**Have you used LP before? (Yes/No)**
Yes

**if Yes how was your previous experience with LP? (Please motivate)**
Laggy, i made a autocrafting system that decreased my tick rate. But this was in 1.4.7 so i hope they have fixed the issues.

**What would you like to use LP for? (Please motivate)**
Combined with storage drawers and chests to make an auto-storage system. My manual system is a mess with chests everywhere.

**How many of the current mods are you familiar with? (number please)**
~210

**Which of the current mods do you compare LP to? (You can compare to multiple)**
Redpower 2 (Project Red), basic AE system, Buildcraft with logic.

**What would LP give to GTNH that its currently missing? (Please motivate)**
An earlier small-scale storage system. That can be beneficial since GregTech adds so many items that it's easy to get lost between all the chests. The auto-crafting can make tedious crafting easier and faster.

**How is LP different to the other available mods? (Please motivate)**
1. It's a smallscale auto-storage system that makes you able to request items through Buildcraft Pipes and allows you to search through the connected chests and storage drawer for blocks and items, similar to the EnderIO Crafting Panel. 

2. It's easier to use than the Project Red Pneumatic Pipes (prerequisite perhaps?) and highly configurable. The whole network can be configured to cost a "value" amount of power to keep active, if this is set to only accept EU and not RF it might need an MV amount of energy to keep the system active at all times (Crafting costs more obviously).

3. It would be a differnt solution for those that don't like the EnderIO storage system.

**Is there anything else you wish to add? (The more information, the better!)**
1. Suggestion for the basic logistics pipe recipe:
	Assembler.addRecipe(<LogisticsPipes:item.PipeItemsBasicLogistics> * 4, <ProjRed|Transportation:projectred.transportation.pipe:5> * 4, <ore:circuitGood> * 2, <gregtech:gt.metaitem.01:32651> * 2, <gregtech:gt.metaitem.01:32631> * 4,  <gregtech:gt.metaitem.01:2381> * 4, <ore:plateAluminium> * 8, <liquid:moltenRedstone> * 576, 800, 120);

Ingredients:
ProjRed|Transportation:projectred.transportation.pipe:5 = Routed Extension Pipe
ore:circuitGood = MV Circuit
gregtech:gt.metaitem.01:32651 = MV Robot Arm
gregtech:gt.metaitem.01:32631 = MV Conveyor Belt
gregtech:gt.metaitem.01:2381 = LV Lossless EU Cable
ore:plateAluminium = Aluminium Plate
liquid:moltenRedstone = Molten Redstone? (Might replace with other liquid)

2. It's easy to integrate a finished logistics system with AE 2 witch might be a plus when you reach that stage. Yes, Logistics Pipes don't have channels but a crafting system created with Logistics Pipes take a hell of a lot more room than an AE 2 crafting system. 

3. You can also make it costly through energy to build a large Crafting System through Logistics Pipes. If it costs EV amounts of power to craft things automatically in Logistics Pipes, then I think the systems will be kept smaller, and players will migrate to AE 2 when they are able to. This should reduce the amount of lag the mod generates since 70 % of it usually comes from having hundreds of autocrafters running and crafting at the same time (This was my main beef with LP in 1.4.7, they might have optimized the mod so it doesn't lag as much).

**Comment by CalterOK** [comment]
How long have you played GTNH? (number please)

2 years

Which tier are you currently in? (just a tier is enough here)

ZPM

Do you want Logistics Pipes to be added to GTNH? (Yes/No)

No

Have you used LP before? (Yes/No)
(Respons here)

No

What would you like to use LP for? (Please motivate)

+-200

Which of the current mods do you compare LP to? (You can compare to multiple)

PR, BuildCraft

What would LP give to GTNH that its currently missing? (Please motivate)

The principle of LP is analogous to the pipes PR and BuildCraft, respectively, the problems are the same. With small systems, this does not affect much, but it is worth creating something comparable to the ME network and making mistakes, as LP pipes will start to lag strongly due to the constant movement of objects along them.

How is LP different to the other available mods? (Please motivate)

Nohow.

Is there anything else you wish to add? (The more information, the better!)

I do not see the sense of trying to change lp recipes, the mod will kill the need for AE because it copies its functionality. It does not have channels, Lp is not limited as it is limited to channels ae. and of course, almost all recipes can be automated through an assembler, in which there are almost all the necessary recipes. LP will remove the need to use the GT functionality.

**Comment by MopningStars** [comment]
How long have you played GTNH? (number please)
4 months
Which tier are you currently in? (just a tier is enough here)
MV/HV
Do you want Logistics Pipes to be added to GTNH? (Yes/No)
No
Which tier do you think LP would fit in? (just a tier is enough here)
MV/HV
Have you used LP before? (Yes/No)
No
What would you like to use LP for? (Please motivate)
Feplacement AE2
How many of the current mods are you familiar with? (number please)
+-150
Which of the current mods do you compare LP to? (You can compare to multiple)
PR, BuildCraft

**Comment by LogicFalls** [comment]
How long have you played GTNH? (number please)
Around 6 months

Which tier are you currently in? (just a tier is enough here)
MV

Do you want Logistics Pipes to be added to GTNH? (Yes/No)
Yes

Which tier do you think LP would fit in? (just a tier is enough here)
MV, with more useful pipes scaling to IV

Have you used LP before? (Yes/No)
Yes

if Yes how was your previous experience with LP? (Please motivate)
A well refined, robust and deep system to work with Buildcraft pipes.

What would you like to use LP for? (Please motivate)
A Ghetto ME system alternative, and later precise automation where AE is impractical

How many of the current mods are you familiar with? (number please)
~150

Which of the current mods do you compare LP to? (You can compare to multiple)
Buildcraft, ProjectRed: Transportation

What would LP give to GTNH that its currently missing? (Please motivate)
PR-style pipes that aren't awful

How is LP different to the other available mods? (Please motivate)
LP pipes are fleshed out and robust, with a plethora of online documentation. PR pipes aren't user friendly, there's no real documentation to speak of, and they outgrow their usefulness past MV as the Inventory Pane becomes available, GT pipes are faster and EIO conduits are more intricate. LPs scale well, are compatible with AE, and are useful until the endgame.

Is there anything else you wish to add? (The more information, the better!)
These should be added as an alternative to projectRed, and should scale along side it using the power requirement as a natural offset for the price to utility.

**Comment by 0lafe** [comment]
How long have you played GTNH? (number please)

- 1.5Y

Which tier are you currently in? (just a tier is enough here)

- UMV was my farthest, but I'm in HVish right now

Do you want Logistics Pipes to be added to GTNH? (Yes/No)

- No

Which tier do you think LP would fit in? (just a tier is enough here)

- MV/HV

Have you used LP before? (Yes/No)

- No

if Yes how was your previous experience with LP? (Please motivate)

What would you like to use LP for? (Please motivate)

- Uh, probably nothing to be honest. Got everything I could ever want with AE/EIO, and I just dont need this kind of infrastructure pre moon. 

How many of the current mods are you familiar with? (number please)

- 234 (I honestly don't know how many mods there are, but I think I'm familiar with most/all of them)

Which of the current mods do you compare LP to? (You can compare to multiple)

- AE/EIO/projectred/sfm

What would LP give to GTNH that its currently missing? (Please motivate)

- Uhhhhhhhhhh better project red for people who like that I guess? Couldn't really tell you much, I don't see a difference besides it being a little better. 

How is LP different to the other available mods? (Please motivate) 

- It seems like a worse AE, that does less than AE, for more lag, so I guess it provides extra lag for endgame bases. 

Is there anything else you wish to add? (The more information, the better!)

- Maybe remove the project red pipe stuff, and add logistics for that tiering? It seems like a better project red but I think to have LP, there's no need for project red pipes and stuff. 

- there's a bunch of stuff thats problematic that I've stumbled onto in gtnh, but nothing that I think LP would fix.

**Comment by AndrewAmmerlaan** [comment]
> How long have you played GTNH? (number please)
7 Months

> Which tier are you currently in? (just a tier is enough here)
HV

> Do you want Logistics Pipes to be added to GTNH? (Yes/No)
No

> Which tier do you think LP would fit in? (just a tier is enough here)
MV/HV

> Have you used LP before? (Yes/No)
No

> How many of the current mods are you familiar with? (number please)
~150

> Which of the current mods do you compare LP to? (You can compare to multiple)
EnderIO/AE

> What would LP give to GTNH that its currently missing? (Please motivate)
I suppose that it looks a bit cooler then enderio conduits cause you can see the items move around.

> How is LP different to the other available mods? (Please motivate)
It's more buidcraft like, meaning it looks a bit more 'real' then other pipes/conduits

> Is there anything else you wish to add? (The more information, the better!)
Personally I think we have more then enough ways of transporting stuff around, so I don't think there's any point in adding yet more types of pipes. Also they may look cooler, but they are also more of strain on fps (and probably tps too). If this mod is added, I think it should replace some other transportation/storage mod.

**Comment by DV666** [comment]
How long have you played GTNH? (number please)
Since 05/07/2018 but that's my second hardcore GregTech modpack

Which tier are you currently in? (just a tier is enough here)
MV

Do you want Logistics Pipes to be added to GTNH? (Yes/No)
No

Which tier do you think LP would fit in? (just a tier is enough here)
EV (if equivalent to AE2) or HV

Have you used LP before? (Yes/No)
Yes (FTB Infinity Evolved Skyblock) but i am not an expert

if Yes how was your previous experience with LP? (Please motivate)
It's a cool mod : automation, crafting, storage, can use liquid too but everytime, i prefer replace it by AE2 ^^'

What would you like to use LP for? (Please motivate)
I prefer AE2 but i think it's great for players who like LP instead of AE or others.

How many of the current mods are you familiar with? (number please)
Idk... a lot, like >75% on GTNH

Which of the current mods do you compare LP to? (You can compare to multiple)
ProjectRed Transportation (but lite version lol)
Automagy (storage + crafting i think but never tested but limited i think)
Ender IO
Applied Energistics 2

What would LP give to GTNH that its currently missing? (Please motivate)
Nothing honestly (see last part)

How is LP different to the other available mods? (Please motivate)
Esthetic (pipes !!). Need to see if more effective than AE2 or if it's just a TPS eater.

Is there anything else you wish to add? (The more information, the better!)
Like Andrew said, we have enough transportation mods on GTNH : it's a hardcore modpack and you need to suffer a little (lol) if you need a good storage/crafting system.
That's why ProjectRed and Ender IO are here : there are limited but can help you a little waiting EV.

If LP need to be added, i think it's will be great for HV or EV => I see LP like an alternative for players who didn't like AE2.
However, as i said, we need to do some tests if servers like huge LP network or not ^^

**Comment by Dream-Master** [comment]
Ok i close this now. If we ever add LP it wull be mor mc 1.12 if available.
