### ISSUE TITLE
Mod suggestion for more building materials

### ISSUE THREAD

**Issue by MrGrader** [GTNewHorizons/NewHorizons#3293]
While playing GT:NH I experienced lack of building materials. There are many, of course, but it lacks many colors, and hence I want to suggest adding [Underground Biomes](https://minecraft.curseforge.com/projects/undergroundbiomesconstructs) as it provides a variety of different stones of colors currently missing in GT:NH.

**Comment by WarlordWossman** [comment]
We had that at some point and decided against it, GT does add recipes for different kinds of stones to be split up into elements which cannot be balanced if this mod is part of the pack. 
Additionally the mod spams your inventory with many different blocks when you start mining.
I think it would also make terrain gen more laggy on top of all the other things.

So yeah, I am clearly against it. And I don't think it's a good idea to change worldgen that often since this modpack takes a while to complete and you don't want any world resets for dumb changes.

**Comment by richardhendricks** [comment]
When in NEI, be sure to look at Ztones, stairs, chisel, there are a lot of different options for colors etc.

**Comment by 0lafe** [comment]
I'd love to see decocraft added in some way personally

**Comment by Dream-Master** [comment]
@0lafe add a new issue please.

**Comment by Dream-Master** [comment]
@MrGrader We tested Biome undergraiund allready and yes it is a nice mod replace all the boaring stone blocks. The downside on this mod the terrain gen gets very low and make the world unplayable if you generating new areas. So no we wont add this mod. You can add it by yourself if you play sp.
