### ISSUE TITLE
Combustion Engine and Arc Lamp

### ISSUE THREAD

**Issue by Highbeam** [GTNewHorizons/NewHorizons#3308]
#### Which modpack version are you using?
2.0.4.6
#

#### If in multiplayer; On which server does this happen? 
Epsilon
#

#### What did you try to do, and what did you expect to happen?
When Arc Lamps are placed near the Combustion Engine - the multiblock unforms/cannot form.
#

#### What happend instead? (Attach screenshots if needed)
I understand this is to do with how Arc Lamps manipulate the blocks to make more light.  I'm only speculating but I think this changes the blocks in front of the Combustion Engine so they are no longer recognised as 'air blocks' and therefore the multiblock cannot form or becomes an Incomplete Structure if previously formed.
#

#### What do you suggest instead/what changes do you propose?
Is it possible to update the Combustion Engine multiblock code to also recognise the 'light air blocks' in front of it?

**Comment by Highbeam** [comment]
copy of test world with issue for mitchej:
[arc lamp.zip](https://github.com/GTNewHorizons/NewHorizons/files/2195327/arc.lamp.zip)

**Comment by Highbeam** [comment]
Apparently this affects turbines too*

**Comment by alphaNOVAircraft** [comment]
Seems to be related to the multiblock check funktions then, but im not to sure about your light air block, otherwise no multiblock would be able to form unless you place ith surrounded only by air, and thats nearly never the case (you have at least some ground beneth them).

So it maybe just interacts with some wierd block updates when spreading the light level that prohibits the multiblocks to form
