### ISSUE TITLE
Suggestion: Nerf oil to light fuel production

### ISSUE THREAD

**Issue by Bluebine** [GTNewHorizons/NewHorizons#3376]
#### Which modpack version are you using?
2.0.4.6
#### What do you suggest instead/what changes do you propose?
So one concern I and others have brought up is how powerful light fuel is, in two main areas, compared to its alternatives.

1. Power. Light fuel produces generally more power than its alternatives (steam, benzene, bio-diesel, and more recently ethanol) while being very simple to set up (only 3 machines needed, a distillery, chemical reactor, and an electrolyzer, while steam is more challenging to use while the other 3 alternatives need more complex processing lines), all while producing an ABSURD amount of power (400 EU/t of light fuel PER DISTILLERY. Even accounting for the EU spent processing and pumping, it's still at least 330 or so EU/t). Three LV machines making 3 amps of MV is ridiculous. 
To make it EVEN MORE broken, you can add in multiple distilleries. You can run 4 distilleries off 1 electrolyzer and chemical reactor, producing a crazy number of ~1500 EU/t, after losses, with only 6 LV machines and 4 generators needed.

2. Ethylene. Severely steam cracking light fuel gives 40 buckets of ethylene per 200 of oil, whereas naphtha only gives 32. It makes sense that the dedicated cracking distillate should make more ethylene than one intended mainly for power production, but right now, it doesn't. Ethylene is the main thing that's cracked for in the early game, so until you get distillation towers there's no point to make naphtha at all.

My suggestion:
Reduce the amount of sulfuric light fuel given from distilling BC oil and raw oil from 25 to 10(number can be adjusted if you feel this is too strong of a nerf). This solves both of the above problems. 

1. Power is now a much more reasonable 160 EU/t, or around 120 EU/t after processing losses, which is fair for only needing a few LV machines. 
This ALSO gives more incentive to make diesel and cetane-boosted diesel instead of just using light fuel all the time, since distilling the oil to heavy fuel now takes up a much lower portion of the total oil yield, so it's more efficient to do so, and since you're making less overall diesel, cetane-boosting it is more necessary to get more efficiency.

2. Ethylene can still be made using light fuel, but it's now better to use naphtha, as (in my opinion) it should.

I could see this requiring the light fuel+heavy fuel to diesel ratio being revised. Maybe 2 light fuel+1 heavy fuel=1 diesel?

**Comment by Bluebine** [comment]
actually on second thought I think 10 is probably too low, 15 seems fairer. that's 240 EU/t per distillery, which is still pretty good but not excessively high

**Comment by sthegreat** [comment]
Personally I think the problem is not the ability to easily process oil, but the easy access to large amounts of energy-dense BC oil in the LV age. I think a better resolution would be to significantly nerf the size of BC oil wells, maybe to like 1/4 their current size (?). I feel like if early on oil was more of a finite resource to be collected and burned, it would be much more reasonable to have the current recipes and burn values. It would also make better oil production by drilling, oilsands, or renewables a bigger progression step, while right now you can get to the moon on earlygame oil spouts.

Nerfing the amount of light fuel from oil will also significantly damage diesel and cetane production from distilleries and also distillation towers, since these are already bottlenecked by the light fuel, as well as potentially hurting later chemical processing. It also makes it no longer efficient to use the light fuel -> propane -> ethylene max-efficiency cracking route though this is not a huge issue.

**Comment by Prewf** [comment]
>Power. Light fuel produces generally more power than its alternatives (steam, benzene, bio-diesel, and more recently ethanol) while being very simple to set up (only 3 machines needed, a distillery, chemical reactor, and an electrolyzer, while steam is more challenging to use while the other 3 alternatives need more complex processing lines), all while producing an ABSURD amount of power (400 EU/t of light fuel PER DISTILLERY. Even accounting for the EU spent processing and pumping, it's still at least 330 or so EU/t). Three LV machines making 3 amps of MV is ridiculous.
To make it EVEN MORE broken, you can add in multiple distilleries. You can run 4 distilleries off 1 electrolyzer and chemical reactor, producing a crazy number of ~1500 EU/t, after losses, with only 6 LV machines and 4 generators needed.

Can you explain the calculations behind 400 eu/t, 330 eu/t (after loss from processing oil), and 1500 eu/t from multiple distilleries?

**Comment by Bluebine** [comment]
Sure. One LV distillery makes 25L sulfuric light fuel in one second. That gets made into regular light fuel in a chemical reactor. 25L light fuel*320 EU/L=8000 EU per second. Divide that number by 20 to make it ticks, that's 400 EU/t.

The losses were just kind of a guess. My setup (one distillery, one chem reactor, one electrolyzer) consumes less than 2A of LV power, so it can't be more than that.

400 EU/t per distillery * 4 distilleries =1600 EU/t base. 4 distilleries consume 96 EU/t overall, plus another 2A at most running one chem reactor and electrolyzer, so subtract around 150 EU/t and you'll actually get around 1450 EU/t (the 1500, once again, was just kind of an estimate, not an exact number)

**Comment by Scottishprog** [comment]
I like the discussion that is going on...

 - Biomass is a viable alternative for running low power machines, did this in my previous base.
 - I would not nerf oil processing, I am with sthegreat - restrict supply. I used Light fuel/diesel for my EBFs only, until steam could take over... and the EBFs burned through the fuel quickly, especially in MV. Consumed a large spout + on that alone.
 - Steam needs a buff in Late MV/HV age.
 - If you do nerf oil, please do it in a way that ONLY has an effect in LV... a specific LV only recipe perhaps?

**Comment by draknyte1** [comment]
> Steam needs a buff in Late MV/HV age.

No it doesn't. 
There's ample boiler and steam generation options upto EV. 
Refer to https://github.com/GTNewHorizons/NewHorizons/issues/3371#issuecomment-409056093.

**Comment by Lainiel** [comment]
Yes it does.

To produce any usable amount of EU using Steam in HV you need:
Forestry farm (+ Thermoinic fabricator + Carpenter)
Pyrolyse oven (just the casings need 396 steel and bronze ingots)
GT Large Steel Boiler (192 steel just for casings)
Large Steam Turbine (144 magnalium and 48 blue steel just for casings)

That's 4 multiblocks. Just the amount of steel to build all these is just crazy and in the end you'll be producing measly 540 EU/t in the best case scenario.

24 000 L/s from the Large Steam Boiler = 1 200 L/t = 600 EU/t
Best turbine efficiency is 90% and assuming you get the optima flow exactly right that's
600 * 0.9 = 540 EU/t

Now compare that to light fuel:

1 MV distillery
1 LV chem reactor for desulfuring
1 LV electrolyzer to get hydrogen from water for desulfuring
1 HV combustion generator

This alone can produce the same amount of EU as the steam setup listed above

(optionally if you don't want to waste the H2S)
1 LV chem reactor to turn H2S into diluted sulfuric acid
1 LV distillery to turn diluted sulfuric acid into sulfuric acid
1 supertank to store the sulfuric acid
Few project red pipes and chips to automate the desulfuring

**Comment by richardhendricks** [comment]
@Lainiel It's even worse, since a 540 EU/t rotor (does one even exist?) would blow up an HV dynamo hatch. Realistically I think you'll need two large block turbines.

**Comment by WizardSleve280** [comment]
yeah i agree with the need to both buff steam and nerf light fuel, although i dont think the quantity should be reduced. When you first make power, the questbook directs you to steam turbines and then gives quests for getting all multiblock boilers, turbines, and charcoal farms. The obvious assumption would be that "oh, if the questbook makes me build steam, it must be good." In reality, the amount of steam needed is greatly increased per tier, plus they loose massive amount of efficiency with each upgrade, making them severely less viable. Even though this problem is fixed if you upgrade to a multiblock turbine, moving to just fuel is infinitely less expensive since at most, you would need to just distill the fuel and add some O2 to get fuel that is able to make 320,000 eu per bucket. If you were to make this equivalent with steam, you would need 640 buckets minimum (assuming efficiency is at 100%). The reason why i would say not to limit the amount of oil in the world is because how much oil is used for other things. Why limit one of the most important fluids just because of one super fuel? Just limit the amount of energy made from each cell and nerf the amount of fuel produced per cycle, while also buffing steam by increasing the amount of eu produced per mb.

**Comment by Prewf** [comment]
>while also buffing steam by increasing the amount of eu produced per mb.

If you're going to buff steam (imo this should be a separate discussion, not garbled together with this issue), buff the amount of steam produced from machines, not the actual ratio of steam->EU. You'll break a lot of existing large turbine setups if you do the latter.

**Comment by draknyte1** [comment]
@lainiel you neglected the three tiers of boilers which I add, which once rebuffed to their original production values, really alleviates the need for a pyro or multiblock boiler.. (maybe just buff the large boilers, if anything)

Don't know why you think you need a multiblock steam turbine at HV, when a HV turbine exists. 🤔

**Comment by Scottishprog** [comment]
I would go for NOT reducing the amount of fuel produced from a bucket of oil, but reducing the energy value of a Light Fuel cell.
Simpler change, less likely to have unintended consequences.

**Comment by Prewf** [comment]
Not to sound like a broken record or anything but I'd prefer if we started a new discussion altogether for buffing steam.

The topic at hand is specifically about nerfing light fuel, which I agree should be nerfed by lowering it's EU/L value. Changing oil distillation output or oil well sizes unnecessarily nerfs other areas of the game, so I don't agree with those options.

**Comment by richardhendricks** [comment]
Another of the main driving factors is that Light Fuel is also the best ethylene source.  Be nice to see some diversity there, with Naphtha used instead.

**Comment by Lainiel** [comment]
@draknyte1 

OK so let's see. GT++ HV boiler require titanium so they're out of the question when starting HV. MV Boilers produce 500 L/s of steam. To match the same output as the large steam boiler you'd need 48 of them.

Now let's do some quick material cost to build them:
-  576 stainless steel
-  432 aluminium
-  384 silicon carbide
-  1824 steel !!!
-  96 LV circuits
-  48 MV circuits

Plus if you don't build a forestry farm and pyrolyse oven I'd bet you'll be running out of charcoal even if the consumption is low.

Now with all that you'll be producing 24 000 L/s of steam. Let's say I listen to you and use a a single block HV steam turbine.

24 000 / 20 = 1 200 L/t
1 200 / 2 = 600 EU/t
600 * 0.66 eff = 396 EU/t

I'd really like to see you make EV voltage with Steam as you said in your first comment.

**Comment by richardhendricks** [comment]
Please take steam concerns and suggestions to https://github.com/GTNewHorizons/NewHorizons/issues/3124

**Comment by alphaNOVAircraft** [comment]
I would agree on merging light fuel. But simply lowering the burn value down to 240k should be enough.

**Comment by Prewf** [comment]
So is the proposed list of changes going to be this?

-Lower LF burn value to 305000
-New ratio of Oil:LF to be 2.5 : 1 (from 1 : 1)
-New ratio of diesel's LF:HF to be 2 : 1 (from 5 : 1)

This addresses:
-Too much EU/t from LF currently, even after processing loss. This change lowers it to around 100-150 eu/t down from 350-400 eu/t
-Naphtha being neglected as a source of ethylene. This change encourages naphtha->ethylene because LF is more scarce.
-Oil to diesel remains untouched this way since the ratios cancel each other out.

**Comment by Bluebine** [comment]
@Prewf 
That's pretty much my idea, except I thought the oil:LF ratio should probably be 25:15. 25:10 was my original idea but I think that's a bit too harsh. Maybe even 25:20, depending on what other people think.

**Comment by sthegreat** [comment]
25:10 is definitely too far. It will make light fuel significantly worse for power than even refinery gas, and that's without proposed buffs like #3389 and #3388. Even 25:15 is a fairly massive nerf imo, and still messes with people's chem processing, as well as harming potential gasoline production (#2987) since gasoline is effectively made out of lightly hydro-cracked light fuel. I would recommend we just nerf it by its fuel value even further if 305k isn't thought to be enough, instead of changing the ratios. Maybe 280k, or like 265k? Or we could even nerf heavy fuel a bit and put light fuel at 240k

And ethylene from light fuel could be easily nerfed just by reducing the amount of ethylene you get from each light fuel steam-cracking level by 30% or so.

**Comment by Prewf** [comment]
Yea that makes sense too since LF is used for things other than fuel. If the ratio was eased back up to 25:15 or 25:20, would it make sense to lower LF's burn value to still make it 100-150 eu/t in the end?

so for example,
for 25:15, LF should be lowered to ~203000
for 25:20, LF should be lowered to ~153000?

**Comment by 0lafe** [comment]
as long as you don't change the circuit in the diesel recipes 

>-Lower LF burn value to 305000
-New ratio of Oil:LF to be 2.5 : 1 (from 1 : 1)
-New ratio of diesel's LF:HF to be 2 : 1 (from 5 : 1)

This looks good to me

**Comment by sthegreat** [comment]
The really powerful drilling rigs are post-moon anyways, where burning light fuel is irrelevant and oil competes with nuclear and kinetics. And if the intention is just to make light fuel processing give less eu/t, then maybe the easiest way is to double or more the recipe time, so getting that 400 eu/t becomes a larger setup, closer to what you would need for biodiesel, steam, or benzene.

And if we really do want to nerf light fuel that hard, we need to also significantly nerf refinery gas and potentially even heavy fuel and naphtha, or else they will just become the new go-to oil fraction. That would be obviously incompatible with #3389 so some discussion and analysis of those options is probably needed.

**Comment by Prewf** [comment]
>And if we really do want to nerf light fuel that hard, we need to also significantly nerf refinery gas and potentially even heavy fuel and naphtha, or else they will just become the new go-to oil fraction.

I didn't want to be the one to say it..but yeah. All the immediate oil byproducts might need to be reviewed together.

**Comment by richardhendricks** [comment]
My issue is that LF supercedes naphtha for ethylene production.  If we cut the ratio on oil:LF and also rejigger the ethylene outputs for cracked LF and cracked naphtha, I am ok with 305k.

**Comment by Methes** [comment]
I love how numbers are flying through the air but there has never been a comprehensive comparison of EU demands and availability in each tier with different setups and material/maintenance cost.
Unless that thing exists you can never properly balance so many energy systems.
That's the only valid balancing tool IMO.

**Comment by sthegreat** [comment]
If we reduce ethylene from heavily steam-cracked light fuel to 150 and decrease other steam-cracked light fuels proportionally, naphtha should become better for one-step ethylene production. If we care about two-step cracking processes as well we need to check out propane outputs for moderately hydro-cracked light fuel and whichever hydro-crack is the best for naphtha.

**Comment by Methes** [comment]
Yep. And then in another 3 months you'll see a suggestion to boost or nerf that yet again without realizing the impacts it has on the whole energy ecosystem (and sometimes byproducts too).

**Comment by Prewf** [comment]
>Yep. And then in another 3 months you'll see a suggestion to boost or nerf that yet again without realizing the impacts it has on the whole energy ecosystem (and sometimes byproducts too).

I mean, that's literally what sthegreat and I just agreed on. You can nerf one thing (LF), but something is bound to take its place immediately after ("the new go-to oil fraction") if we just focus on issues locally like this, so all of the immediate oil byproducts might need to be looked at together. And yeah you can go one step higher than that and say all the energy systems as a whole probably needs a closer look, but that's much easier said than done.

**Comment by Kortako** [comment]
So I've been thinking about this a bit, and it seems like the big issue is that LF is basically usable forever, right?  It has a really good burn value when compared to the higher tier fuels (~320k vs Diesel's ~480k and Cetane's ~768k, which is really what we should be comparing it to), so why bother with the others?  If I can use LF from LV up to IV, etc, why change from that?  And it's already been said in this thread that just trying to nerf the numbers on LF will leave the possibility that one of the other basic oil products will become the new LF.

So here's a different idea that doesn't deal too much with messing around with the numbers:

What if we just prevent LF, Naphtha, and HF from being used in HV Combustion Engines and higher (including the LCE and rocket engines)?  I know it's possible, because Cetane and Diesel used to be unable to be used in LV diesel gens before that restriction was removed.  This could get around unintended consequences of trying to balance burn values, and would actually encourage people to move to the more intensive processing lines of Diesel and Cetane if they want to stay with liquid fuels.

**Comment by Scottishprog** [comment]
I agree it's a bit of a ticklish situation.
I don't know if it's possible to have a distillery recipe that gives a different amount of LF than the distillation tower equivalent....
But I see the need to restrict the LF production nerf to lower tiers.
Alternatively, look to the higher tiers, and buff the corresponding recipes to account for the lesser amount of LF. (Adjusting the Diesel recipe is a good start. Make sure the LCR recipes are looked as well.)

**Comment by Prewf** [comment]
@Scottishprog 

I think in code the multiblocks might just be reading recipes from the single block machine recipes anyways (not 100% sure).

As for the diesel recipe, if you follow what bluebine suggested, you'll see that the diesel (and cetane) recipe's yield remains unchanged if the ratios are done the way he's suggesting (they ultimately just need to cancel each other out). It's only LF that would be severely nerfed..except that isn't a true fix as other people pointed out since some other oil fraction would most likely take its place. 

I like what kortako mentioned, since it doesn't require any ratio or burn value changes at all. If we restrict what type of fuel is allowed to be used in each tier's respective combustion engines, we don't even have to mess with the complicated energy ecosystem. At the very least it'll force people to not be too complacent with their super-dense combustible fuels at the early tiers, but at the same time the fuels are dense enough to still act as an incentive to switch over from steam at LV.

**Comment by draknyte1** [comment]
Distil tower and LCR can have unique recipes, but also inherit from the singles. Just means adding the current recipe with a circuit for the tower and then nerfing the single block ones.

**Comment by Scottishprog** [comment]
Prewf, I was trying to say: "make sure everything else affected by LF is handled like diesel/cetane"

Don't mind the change, as long as all of the implications are handled, so things aren't inadvertently nerfed. If that is already getting considered, then one step ahead of me.

**Comment by Prewf** [comment]
Yup that's a good point. It's partly why I'm backtracking and liking kortako's idea of just not touching numbers and ratios since it's so easy to break other things when we mess around with fluid amounts in recipes.

**Comment by CalterOK** [comment]
Making calculations for the topic of gas strengthening, I compared it with light fuel in current realities. Based on the obtained data (Buff refinery gas), the only thing that needs to be changed in light fuel is to reduce its output from conventional oil by 25%.

**Comment by Prewf** [comment]
Like we've been saying..changing light fuel output amounts isn't that straightforward. Light fuel has uses other than just as a fuel and we'd be unnecessarily touching those aspects of the game by messing with output amounts/ratios.

**Comment by CalterOK** [comment]
The main problem is that BC oil is simply extracted and it is quite common, in contrast to the original sources of oil. Therefore, the change in the coefficient of obtaining light fuel is only for one type of  BC oil and not for all.

**Comment by Prewf** [comment]
But you said it yourself, it's the most common sources of oil we're talking about (BC oil; the stuff from spouts right?). This would affect everyone that's dependent on those spouts, not only for fuel. Chem processing lines and gasoline lines would be unnecessarily affected if we mess with BC oil->LF ratio.

**Comment by sthegreat** [comment]
So here are a couple more potential options for nerfing light fuel/oil that are unintrusive to later setups, don't mess with fuel production ratios, and should work quite well. I'd like to hear what people think about these.

-Reduce the density of BC oil. By making the current distillation recipes require 50 oil instead of 25 (making bc oil the same as raw oil), we effectively halve the size of already-existing BC oil wells. If this is done, we should buff renewable bc oil sources (bees + crops) by the same amount so they are unaffected.

-Increase the time needed to distill oil early on. Changing the time to 3 seconds means the per-distillery eu output is down to 133 eu/t from 400 eu/t, and this time can easily be tweaked to whatever is seen as balanced.

**Comment by Prewf** [comment]
Would the increased time to distill oil be for all the immediate oil byproducts or only oil->LF?

**Comment by sthegreat** [comment]
Hmmmm. Refinery gas would definitely need a time increase as well, and in that case the rest should probably get it for consistency.

But if we do that, while we don't have a problem with hv+ chemical processing, I now realize we do have a potential problem with early-game chemical processing. All of the current cracking paths for ethylene are already fast enough to make distilling the bottleneck (well I only checked 1-step naphtha but others are probably the same). Increasing distillery times would make it even more of a bottleneck, effectively nerfing early plastic production too.

I'm not sure how much of a problem it really is since plastic consumption is quite low at that point, but if it is a problem maybe naphtha and possibly heavy fuel (for toluene) shouldn't have their time increased and should instead get a massive burnvalue nerf so nobody ever thinks for a second about using them for power. Interestingly that would create a full 3 potentially viable early ethylene routes (assuming we nerf steamcracked light fuel too) - steam-cracked naphtha for simplicity, hydro-cracked naphtha -> steamcracked propane for the same speed but more efficient output, and hydro-cracked light fuel -> steam-cracked propane for max efficiency but it takes your fuel which is now pretty slow to make.

**Comment by CalterOK** [comment]
@Prewf Why do you consider the problem on the basis of BC oil only, without taking into account the sources of the oil of GT?
@sthegreat Reducing the production of light fuel by 2 times compared with the current value is too strong.

**Comment by Prewf** [comment]
Hey @CalterOK, thanks for doing that work for us. I read your sheet and came to a different conclusion in https://github.com/GTNewHorizons/NewHorizons/issues/3389. Just lower the burn value of LF I think.

**Comment by CalterOK** [comment]
@Prewf Excessive energy density of light fuel is observed only in BC oil, if I take other types of oil there, I have not noticed any problems there (not only because of other ratios but also because of large expenditures of energy for extraction).

**Comment by Prewf** [comment]
Ah yea, the eu/t would reduce for all the oil types, which isn't good. You're suggesting we change the ratio of BC oil->LF right?

What if we made the single block distillery do 15 oil to 15 sulfuric LF? instead of 25 to 25? That keeps the ratio the same, but raises the consumption cost (and affects consumption cost of plastics line dependent on LF as well) making the effective eu into 212 eu/t, but doesn't affect actual output amounts (it wouldn't affect the distillation tower recipe either because the ratio is kept the same).. I think.

**Comment by CalterOK** [comment]
@Prewf  Without changes in the conversion factor, this will only lead to a decrease in the production rate of light fuel, but will not change its efficiency.

**Comment by Prewf** [comment]
I don't use it to make ethylene either, but some people probably do... ¯\_(ツ)_/¯
At the very least, if the ratio is 1:1, the distillation tower recipe stays the same so it shouldn't affect HV+ people, only LV (lower eu/t and lower ethylene/plastic product yield, which is what we want right?).

**Comment by Bluebine** [comment]
Hi! I'm back, and after some consideration, I have a revised set of changes for you to look at, separate from my previous ones.
1. Change light fuel's energy value to 305k. This idea is already in the latest update, but not officially released yet, so I'm making a mention of it since my numbers are based on it.
2. All 4 BC oil distillery recipes now cost 35L of oil per recipe, instead of 25. This reduces the density of BC oil a bit, but not excessively. To keep renewable oil (oilberries and oil bees) balanced, increase their yield by 50% each. This keeps renewable oil in roughly the same place it was before.
3. Oil distillery recipes now take 1.2 seconds instead of 1. This nerfs oil for power generation a bit, like I was trying to do with my first idea, but better, without hitting it too hard. with this plus the 305k change, one distillery making light fuel would make 317 EU/t before losses. Still a good amount, light fuel would still be usable, but there's more incentive to make diesel and you'll need a few more distilleries.
4. Reduce the amount of ethylene severely steam cracked light fuel gives to 150L, instead of 250L. This provides incentive to make and crack naphtha for ethylene instead of using light fuel for it.

This would replace my original idea, I don't support that strong of a nerf anymore after seeing how strong some of the other options can be, and that original idea would mess with the numbers on refinery gas and other stuff too.

**Comment by Scottishprog** [comment]
I would support this.. .

Addresses the problem, without touching downstream oil.  By the time you are hitting distilling towers, you should have drained all of the BC oil spouts in you area anyways - and be pumping GT oil.

This combined with a slight strengthening of the other power options... I might actually use all three in my base this time through!.

**Comment by CalterOK** [comment]
@Prewf And I do not get ethylene from oil because this method is extremely inefficient (in the table that I threw off on page 1 I do not consider the use of oil at the existing distillation tower, as when it is required it is required to develop GT oil fields, BC oil serves for the initial stage of development and should not be competitive with GT oil.

**Comment by MineAnPlay** [comment]
Still working on it but making a GTNH Power Spreadsheet. https://docs.google.com/spreadsheets/d/1jgNw_n65-C3oKW0PG6e3WlR89P1vXGa-znA2BrapXBU/edit?usp=sharing
Also what are does values based on?
