### ISSUE TITLE
Suggestion: Buff refinery gas

### ISSUE THREAD

**Issue by Bluebine** [GTNewHorizons/NewHorizons#3389]
#### Which modpack version are you using?
2.0.4.6
#### What do you suggest instead/what changes do you propose?
Buff refinery gas to 240k EU per cell, instead of 160k. This would bring it almost (but not quite) on par with light fuel. As is, it's just the least valuable out of the 4 oil products- not nearly as good for EU as light fuel, not as good for cracking as naphtha and heavy fuel, and not needed for diesel like heavy fuel is.
It'd also work nicely with @richardhendricks 's suggestion for gas turbines to make less pollution, allowing you to trade some oil efficiency for less base pollution.

**Comment by sthegreat** [comment]
I think 240k eu is too much of a buff and 200k - 230k would be better. At 240k, refinery gas gets about 95% of the eu light fuel would from regular oil, and would burn with significantly less pollution (if the gas turbine pollution is decreased) for such a small eu reduction. With slightly less burn value (and enough pollution reduction) I think it would be a more meaningful choice.

**Comment by richardhendricks** [comment]
What's the output ratios on Refinery Gas and Naptha from BC oil?  Don't forget we have a 305k nerf on light fuel, and possibly more inbound based on the results of #3376.  I do like the idea of having 3 different fuels with different jobs/roles. LF for EU, RG for low pollution, Nap for chemicals production

**Comment by sthegreat** [comment]
Yep, my maths are taking those both into account.

1B oil -> 1.2B refinery gas -> 288keu at the proposed value. With Light Fuel at 305keu from 1B oil I don't see enough difference to warrant using light fuel as a power source at all for someone with any care about pollution.

Naphtha is 1B oil -> 400 naphtha -> 128keu. Definitely not a viable route for power though it has good ratios on ethylene (not as good as light fuel though, especially if you hydrocrack).

**Comment by Bluebine** [comment]
BC oil- per 25L oil, you get 25L light fuel, 10L naphtha, 15L heavy fuel, 30L gas.

I can see 240k being too much. Maybe 200k normally, and some way to buff the EU value? 
According to some research I did (aka a google search), there's a method of removing water using glycol, which is made from ethylene. I'd suggest a new set of recipes for making "purified gas", with a burn value of  400k, which is available at MV.
My suggested recipes: 
1 cell ethylene+1 cell water(or if this is too simple, 1 cell ethylene+1 cell O2= ethylene oxide, and 1 cell ethylene oxide+1 cell water, which is how it's made IRL)= 1 cell glycol.
8 refinery gas(amount of refinery gas per cell of glycol can be adjusted if needed) + 1 cell glycol= 8 cells purified gas+ 1 cell water. 
400k may sound high, but that's still less than diesel, and the new processing chain requires ethylene instead of heavy fuel like diesel so it's more complicated to make than diesel, and the additional oil requirements for the ethylene makes it more expensive than refinery gas is.

**Comment by sthegreat** [comment]
I support that, it sounds super cool, adds alternative fuels in mv age, and could bring viability to natural gas as well, in a balanced way.

**Comment by sthegreat** [comment]
Actually, on second thought - diesel is only worth 345k eu per actual bucket oil (assuming only bc oil) until you have the distillation tower in hv. If we set the value of the purified gas to 285k eu, it would have approximately the same oil efficiency with renewable ethylene, and a lower oil efficiency using ethylene also obtained from the oil. 400k, and refinery gases would likely be the new light fuel.

**Comment by richardhendricks** [comment]
I'd prefer to keep LF as the denser high EU fuel source.  RG/naphtha would be for lowered pollution. I don't think we want to completely replace light fuel/diesel/cetane, but offer a secondary fuel chain in high pollution environments like your pyro or EBF.

**Comment by richardhendricks** [comment]
I wouldn't assume BC oil for the heavy fuel - assume oilsands -> heavy oil -> heavy fuel.  It makes diesel way better.

**Comment by Vernam** [comment]
for whatever reason, everyone is so eager to simplify the game by offering unthinkable "ideas" ?! Greg and Blood have done a great deal of work on the balance, get your conscience at least a little and stop whining! Is it really so difficult to take and look at the recipes? there are no problems with the energy in the modpack! If you tackle your head, you can find very good options for extracting energy, polyethylene is not made from oil and God knows what else. Stop spraying the Dream's time to try and bother someone else's work for the sake of his laziness / I do not know what else.

there is no sense to improve the gas, it will not be of much use, just a waste Dream's time!

**Comment by Kortako** [comment]
Dude, calm down. These are just discussions.  Not everything suggested here has to be done, but if there's no discussion ever then what's the point of even trying to improve anything?

**Comment by Vernam** [comment]
Discuss the need for proposals that develop the assembly for the better. Improving the gas does not improve the assembly in any way. The question is simple - why then is it at all? It's just like begging steam to improve. Only with the steam it will lead to great consequences, a big waste of time, and in the end all will be returned as it was for it becomes clear that this was a stupid idea. I very rarely see good ideas here, mostly people complain about the complexity of the assembly. Although it is not difficult. Simply someone does not have neither the mind nor the patience to achieve results, but then with each update suffer simple players, which all suits. How do they suffer? Yes, constantly changing their chains of processing from updating to updating, because someone did not please something, the others supported without thinking.

**Comment by richardhendricks** [comment]
Slow your damn roll.

This does nothing to simplify the game.  It makes the game *richer* and more complex because you can have *choices* at each stage on what to do vs mindlessly following the meta.

Having a choice between steam for large quantities of cheap EU, LF for dense EU, refinery gas for less pollution, and naphtha for chemicals production allows player diversity instead of everyone sitting in the same old mold of steam till LV, then LF till MV, then diesel till HV then cetane until EV.

I say more than half of the **complaints** are about things being too simple anyways!

It is pretty damn arrogant to assume that X has done a perfect job of balancing the pack, when they aren't, you know, *balancing for the damn pack*.  It doesn't matter what Blood and whoever did, their choices were made without the level of knowledge and experience players *in the pack* have.  Did Blood balance for Twilight Forest materials? Galacticraft worlds? Thaumcraft magic materials?

This is exactly why we are having these conversations in the *open* instead of just a quiet PR that changes something without notification to the whole community.

**Comment by CalterOK** [comment]
Can you provide calculations on the basis of which you came to the conclusion that this revision is necessary?

**Comment by Vernam** [comment]
Why should the blood balance other people's modes? he played with his creation and knew. what did you do. In the assembly and so there are enough alternatives, it is enough to have the patience to go through the hv era, and you can see quite a lot of useful content. Only the variations of energy production through chemistry already speaks volumes and gives a lot of scope in terms of choice. For some reason, many do not want to see this, offering "variability" in the beginning, not realizing that the main content goes after hv, there is no sense in gas there either. There is no point, and the only argument is "variability". For the sake of variability, you can do a lot of things that are not suitable for the assembly, not the fact that this will be better.

If there was a real reason to improve Gas, I would not have written here. I would even support. I can still understand if we were offered to increase the yield of gas from oil for the sake of distillation, but only if it also makes sense. What is the plus in improving gas? modest assumption that maybe someone will burn it? but most people are unlikely to do this. So what's the plus for the whole community?)  

Yes,Can you provide calculations on the basis of which you came to the conclusion that this revision is necessary? a very good question, the answer to which will give me an understanding that it is necessary)))

**Comment by draknyte1** [comment]
@Vernam, Your opinion has been considered, thanks. 

@Blood-Asp has absolutely nothing to do with GTNH and it's development, nor its balance. 

This discussion is simply that, a discussion. Since you aren't contributing anything constructive to it, we'd all appreciate if you stopped. While *you* do not see the need, the rest of the community playing GTNH is interested enough to consider it. Please allow them to discuss this without further pointless contributions, or consider actually saying something useful.

**Comment by Vernam** [comment]
most of the community is interested in raping modpak through inadequate suggestions to make life easier.
You were asked a specific question - can you calculate and provide data on which gas should be changed. Why does no one try to show this if it is necessary?) Where is the calculation?) You were asked fairly adequately - if you think that you need a rebalance, then you can provide the data from which you made such an offer. Where then are the calculations?) Instead of answering my criticisms, you would have been able to provide data for a long time that would convince me of your rightness. I myself will support your proposal if it turns out that it's really worth it =)

I'm not an enemy, I just want to hear a weighty argument that this proposal has a place to be)))

**Comment by CalterOK** [comment]
Since you did not provide any calculations about the need to improve the gas, I had to do it myself. Based on the received data, I do not see the need to improve the gas.
![image](https://user-images.githubusercontent.com/35035276/43641456-6e152658-972c-11e8-96c6-9d697c844a5d.png)
A table with more detailed calculations:
https://docs.google.com/spreadsheets/d/1WmaMnCy5-S0EmAoysdk0bdJ2bPBtKE0FWXDbE7hyhKY/edit?usp=sharing

**Comment by WarlordWossman** [comment]
@Vernam my secret tip for people who cry about the fact that GTNH has a community that likes to discuss balance: Play SSP with the settings you want, nobody will stop you. 
Just ranting here will not help anyone, it just makes it harder to see what's being said on the actual topic.

@CalterOK if your information should be considered I would suggest posting it in english.

**Comment by CalterOK** [comment]
![image](https://user-images.githubusercontent.com/35035276/43675042-341a4518-97e6-11e8-85f8-c6a33e2b0010.png)

**Comment by draknyte1** [comment]
@calterOk, as this is an English language discussion area, please post it as such.. 🤔🤔🤔

**Comment by CalterOK** [comment]
@draknyte1 The final comparison of calculation results and so is translated, in the screenshot above.

**Comment by Dream-Master** [comment]
We not all english native speakers @draknyte1 and we have google translation.

**Comment by WarlordWossman** [comment]
>We not all english native speakers @draknyte1 and we have google translation.

If you cannot speak english but want to be part of the discussion (nothing wrong with that) it should be your move to translate the stuff you want to say, doesn't take too long tbh.
Just think about it: That way one person has to translate it once instead of everyone having to translate it every time they read through it again...

**Comment by Vernam** [comment]
@WarlordWossman 
smells like discrimination. And what now, if suddenly there will be a person who in any way can not in English? Is it really so difficult to accept? taking into account that the person did a great job with the calculation and compilation of the table? A person has done someone else's work, you need to be able to respect it. it's already worth it to a couple of people in the discussion made a couple of clicks in Google translator. This is called respect for someone else's work. In this case, no one showed such respect. And all because the calculation shows that no changes are required, which caused many people to be clearly indignant. But to answer something on the calculations did not work out, so the arguments related to the language of a couple of lines were used!

**Comment by Prewf** [comment]
Thank you @CalterOK for taking the time to do this.

So, to all english-speakers, do this:
1. Edit->Find and replace
2. Check "search using regular expressions"
Find: (^[^\d]+.*$)
Replace with: =GOOGLETRANSLATE("$1", "ru", "en")

Now for the actual content of the spreadsheet, the math is more or less correct. I found some cells with wrong contents but that doesn't really matter too much for the final numbers (for example, your "Fuel consumption per 1L" cells are all wrong, so take the reciprocal of what you're doing; this cell represents the EU loss per 1L of fuel). The numbers I had were:

oil->RG
211.2 eu/t total gain

oil->LF
369.3 eu/t total gain

heavy oil->RG
164.1 eu/t total gain

heavy oil->LF
283.3 eu/t

light oil->RG
864.4 eu/t

light oil->LF
134.9 eu/t

It's slightly off from what you're doing because I just did (total net EU/total ticks taken). But it's close enough.

It's interesting because when you look at the idea of "X liters of oil distills into Y liters of fuel" for single block distilleries, changing only X makes it so it doesn't touch any of the eu/t calculations. It only changes how much oil you need coming in (well...i guess technically, it *would* affect total eu/t because you also spend eu to actually pump the oil from the ground). So for Oil->LF, as long as you have 25 oil/s coming in, you will generate 369.3 eu/t. 

Take what I just said with a grain of salt because I'm only considering the single block distillery. The existence of the distillation tower means changes to the oil->LF ratio should also be followed with a change to the LF->HF ratio for diesel (unless you're intending to nerf/buff that too) and any other recipe that mixes LF with other immediate oil byproducts (or things derived from those byproducts). It gets complicated if you go down this route.

So things to notice:
-Changing only burn value doesn't seem to affect any ratios or times for that fuel's use in plastics.
-Changing any eu/t cost or the recipe time for the distillery or sulfide-cleansing chem reactor recipes affects the fuel's use in plastics (because you've effectively altered the total "consumption"). It can affect eu consumption and plastics throughput, depending on what you change.
-Changing Y (in "X liters of oil distills into Y liters of fuel") also affects the fuel's use in plastics, because it affects total "consumption" and time taken.

Oil to light fuel's eu/t is fairly high considering you have access to all of this at LV tier. Drilling rigs are available at MV tier (i think?), and even then the drilling rig oils->LF is nowhere near as high as plain old oil. So it has to be lowered. And it has to be lowered by changing burn value. Changing eu/t or recipe times affects things you can make with light fuel. You can change X in "X liters of oil distills into Y liters of fuel", but as I stated earlier, that will affect the distillation tower's output to diesel proportions, so I think the best way to go forward is only changing the LF burn value (relative to every other oil byproduct's eu/t)

Refinery gas is tough, and I have no say here. Someone else can look at the numbers for that. I'm tired :(

Like methes mentioned in the other thread, this sort of analysis doesn't even begin to touch the total energy ecosystem, so this scope is still "local" in a sense. If you want to begin balancing only the immediate byproducts of oils though, I guess this is a decent place to start.

**Comment by CalterOK** [comment]
@Prewf My indicators though close to reality, but still do not take into account many of the losses, such as the costs of mining raw materials, not 100% of the efficiency of the generators and losses in the wires. I do not understand why you decided that the cell "Fuel Consumption 1L" is not correct, it displays what was intended. If you count only on the basis of production, it will not be too accurate.

**Comment by Prewf** [comment]
Your units are EU/L, but your dividing as L/EU. Look at your cells. Read what I said.

**Comment by CalterOK** [comment]
@Prewf Ah, that's what it fixed.

**Comment by Prewf** [comment]
For english speakers, I forgot to mention the locale also needs to be changed.
File->Spreadsheet settings
In general tab, change locale to english (or whatever language you're comfortable with).

It's using commas as decimal points, so this will change that to periods.

**Comment by richardhendricks** [comment]
We can discuss this issue again after the next release with the Light Fuel changes. I think RG is OK now, but maybe we need higher tier fuels for gas turbines.
