### ISSUE TITLE
Make thermal centrifuge optional in LV

### ISSUE THREAD

**Issue by Lainiel** [GTNewHorizons/NewHorizons#3404]
#### Which modpack version are you using?
2.0.4.6

Already discussed here:
https://github.com/GTNewHorizons/NewHorizons/issues/1815

Both thermal centrifuge and ore washer have no good use in LV. You can get the byproducts without using them. Players in most cases do not have enough spare power in LV to run them fulltime processing ore and a few tiny dusts are not worth it.

#### What do you suggest instead/what changes do you propose?

Do not make the thermal centrifuge main quest. You can get both gallium and arsenic without it. Do not lock magnalium quests behind LV ore washer. Leave them both as optional for people that like to spend a lot of time in each tier. Good idea would be to make a few quests explaining how to build an ore processing line in HV.

**Comment by richardhendricks** [comment]
On the water issue, you can make more than one water siding tank.  You can also choose to base in a wet biome that increases the amount of water each generates. 

On the thermal...I kinda agree, maybe it belongs in MV or HV.

**Comment by Dream-Master** [comment]
I always using them especial in LV to get as much as possible out of the ores.
If i need one stack faster i using macerator and forge hammer but the rest goes into the washer. The Thermal Centrifuge is another thing.

**Comment by Bluebine** [comment]
Neither of these are actually NEEDED to progress. You can get the first byproduct by macerating, forge hammering, and centrifuging, and get the second byproduct by macerating, washing in a cauldron, forge hammering, and centrifuging. Since there's no actual NEED for the ore washer and thermal centrifuge, they should be optional. The magnalium quest should require either the ore washer OR the centrifuge to unlock, since that's all you need.

Me personally, although I'm forced to craft both machines, I've literally never used them in LV. I generally don't use them until HV, when the centrifuge really becomes necessary to get the 3rd byproduct.

**Comment by richardhendricks** [comment]
Well you chose to lair in a desert and didn't invest in infrastructure (I want to try experimenting with a cactus farm now that I understand the string-based option).  It's not like an orewasher uses up *that* much water. That's your choice, not a playerbase-wide necessity. 

Also, I don't see LV quests as optimal perfect processes, they are there to show new players routes and outputs and options. Once a new player has some time under their belt, they can then choose the paths they want to follow.

Gating the crossbow behind the orewasher is kinda weird.  I think it might have been done that way since orewashing is how you can get aluminium dust early game?
