### ISSUE TITLE
Suggestion Advanced miner

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#3530]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Use the advanced miner
#
#### What happend instead? (Attach screenshots if needed)
as it has a area of 49x49 it has a bigger area then a world anchor
#
#### What do you suggest instead/what changes do you propose?
adding a slot for chunkloader coin and making it load its own work area, but making it so that the coins only last maby half the origilan time or 1/3 so that players dont abuse this to load a bigger are in base,

**Comment by Dream-Master** [comment]
if somone code it why not.

**Comment by richardhendricks** [comment]
Chunkloaders are hard, the chances of this being done are 0. Or so I've been told, repeatedly.

**Comment by draknyte1** [comment]
Unfortunately Richard is correct. There's good reason most chunkloading mods are buggy, because dedicated chunk loading mods themselves can't get it right. 

Let's not reinvent the wheel (it seems nobody else has taken a look into the code for chunkloading besides me, but I like to think my opinion on the topic is considered as I've tried making chunkloaders prior) just be smarter about your current loader placements.

**Comment by Ghengis88** [comment]
yes more chunkloaders fix the problem, I will trust in your oppinion here, sad tho, would have been neat if you could use same loading script as ender quarry :/ 
well i close this one then
