### ISSUE TITLE
Infused Crops Drop

### ISSUE THREAD

**Issue by CalterOK** [GTNewHorizons/NewHorizons#3555]
Add-ons for taumkraft add many aspects and they can be obtained in seeded seeds, but nothing falls from them. I would like that to them the same harvest was added. Here's what the loot has the original aspects:
https://www.reddit.com/r/feedthebeast/comments/423ysg/infused_crops_and_you_totally_not_bees/

**Comment by Dream-Master** [comment]
Is this a new mod ? @CalterOK

**Comment by CalterOK** [comment]
The seeds themselves are added by the mod Thaumic Tinkerer.

**Comment by Dream-Master** [comment]
@CalterOK Any idea why ?

**Comment by CalterOK** [comment]
The remaining aspects are not added by the thaumcraft itself, so they do not have any harvest.

**Comment by Vernam** [comment]
There is no drop from the seeds, the aspects of which are added by other addons. For example, the aspects of gregtech are also not added by the thaumcraft, so the mod thaumik tinkerer only sees this new aspect and even has a seed. But does not give a drop, because the mod does not have such things and aspects.
I want to warn you immediately that the aspects added by gregtech and other modes are not many, but some of them are valuable enough for alchemy, so it's worth adding a drop for these seeds, but adding smartly so that there is no imbalance. Also there is the option to remove the possibility of getting those seeds that do not give a drop (but I'm not sure if it will be easy to do). Also there is an option even easier. leave it as it is.
Personally it seems to me that adding a drop to new seeds can lead to the requirement to rework many recipes of alchemy, which also takes a long time and will not have much value and meaning
