### ISSUE TITLE
Quests for books

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3604]
Bunch of different books being added.

Essentia generator book - any shard + LV circuit + book in assembler

GT++ has a book for the multimachine

**Comment by NeroOneTrueKing** [comment]
Or instead, have them as part of the questbook! If there are going to be quests for obtaining the books, why not make the quests grant the books directly?

Such as: a repeatable quest (that consumes resources) of:
1 book + any shard + LV circuit -> the essentia generator book
placed in the progression-appropriate spot in the questline.

It makes slightly more sense that the questbook can procure a written book out of a blank book and subject-appropriate-but-totally-no-good-for-writing-books-with items, rather than the assembler.

Just my $0.02

**Comment by richardhendricks** [comment]
The books are mod-specific, and those mods might be (shocker!) used outside of GT:NH.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57504775-6b877100-72bb-11e9-8306-632ae2bce8f4.png)
@draknyte1 Any more books?

**Comment by richardhendricks** [comment]
(removed modular baubles, has no recipe)

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57506180-a4761480-72c0-11e9-8a97-bca10613353c.png)
