### ISSUE TITLE
GT Miner / Pump break /home command on Delta

### ISSUE THREAD

**Issue by Wolozo7** [GTNewHorizons/NewHorizons#3614]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
When I have a Miner or Pump of any tier running, the /home command will often do nothing. Applies to both singleblock and multiblock versions.

**Comment by AlexBucket** [comment]
Happens on prospercraft to. Our tech admin (Black Ace) looked into it. The way the GT pump and miner and ore drilling rigs work is they create a fake player and it imitates the player mining or using a bucket on fluid. The player never receives a 'warp cancelled' message because it's sending the message to a fake player. Makes the fluid and ore multiblocks useless because you have to stand next to them while they run.

**Comment by AlexBucket** [comment]
My bad. The single block pumps do it, and from previous tests the multiblock ore drilling rig. I presume the oil one works in the same fashion.

**Comment by richardhendricks** [comment]
Ah wait, my helper status removes the 5s warmup for TP.  I'll test with a throwaway account.

**Comment by Ghengis88** [comment]
this is a issue on epsilon also
