### ISSUE TITLE
Can 2 infernal mobs aspects possibly be removed 

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/NewHorizons#3617]
#### Which modpack version are you using?
2.0.5.1

#### What do you suggest instead/what changes do you propose?
Can 1, webber, and 2, cloaking be removed because of how they mess up spawners. Webber will drop a web on you if you're fighting it, but when autokilled by a mob grinder they just randomly drop a web somewhere near them. The webs stack up and stack holding tons of items which can lag servers. It's not that hard of an ability to fight so removing it isn't really making it any easier. 
![2017-11-12_08 12 53](https://user-images.githubusercontent.com/21280852/45468590-60ac1a80-b6f3-11e8-847e-968573576bd5.png)
There aren't as many there as there ended up being, but that's the general idea of what happens. 

Cloaking is when they turn into a block, which is fine for the most part. It'll some times get you in a fight, but for the most part it gives you a free hit or two on them. However, I just noticed that mobs with this seem to be able to completely defy gravity, which makes a lot of mob farms harder. They just sit near the spawner, eventually there's enough that your spawner will just shut down. 
![2018-09-13_01 17 07](https://user-images.githubusercontent.com/21280852/45468663-cac4bf80-b6f3-11e8-8294-1c7a72070d99.png)
This room has a flat ceiling and all "blocks" there are cloaking mobs.

**Comment by MineAnPlay** [comment]
I don't think the latter is an Infernal effect, I think it's Special Mobs Ninja mobs.

**Comment by 0lafe** [comment]
Is that something that can be removed then?

**Comment by Dream-Master** [comment]
Next update i removed both mods. speical mobs and infernals

**Comment by 0lafe** [comment]
Thank you

**Comment by Dream-Master** [comment]
back to old boaring mob fights.

**Comment by Dream-Master** [comment]
But we need to rewrite the quest text in Quest 1 because you can go always outside the night then.

**Comment by 0lafe** [comment]
Oh wait, you don't need to get rid of the whole mods, just these 2 annoying parts of them

**Comment by AlexBucket** [comment]
Curious why the whole mods are being removed?? They create heaps of fun early game making going out and night and stuff a real hurdle to over come

**Comment by AlexBucket** [comment]
Curious why the whole mods are being removed?? They create heaps of fun early game making going out and night and stuff a real hurdle to over come

**Comment by DoomSquirter** [comment]
yeah, consider this another "why remove the whole mod" comment.  

I've run a wisp farm for a month or two.  infernals and otherwise spawn from it.  I've not had any webbing ones tho I'm not 100% positive they actually spawn from wisps.  skels are the only ones that spawn the ninja ones that mimic blocks.

I did however have a skele spawner I ran for a week and did get a bunch of those ninja ones but they would inevitably clear and get killed by the dynamism tablet which was what I was using.  they are definately not affected by corporeal attractors tho as soon as they shift form they are.

as far as webbing goes, use a better method for picking up the item drops like the advanced item collector which tp's items out and not sucks them in.  the webbings would still build up tho.

I consider doing a cursed earth farm a troublesome effort here for these and a few other reasons.  Having these to de-incentivize and have ppl make more directed farms aimed at certain mobs, to be a good balance.

Removing entire mods would be a terrible idea.

**Comment by draknyte1** [comment]
I think they don't need to be removed, just reconfigured.

**Comment by Dream-Master** [comment]
We remove about 50% allready so why we even need the mods? If we removed more nothing left over.
I asking for ages to recode special mobs/infernal mobs to make it better and using 100% of this awasome mods. Sadly i cant do it by myself.

**Comment by draknyte1** [comment]
25-50% of working features is still extra content. The fact the broken stuff can be disabled is a plus.

**Comment by richardhendricks** [comment]
Is there a way to distinguish between a fakePlayer and a real player? My guess is that it is getting killed by a fakePlayer and spawning webs because of that.

Doing lava mobs/special mobs has been in my queue, I can try to target updates for the next release.

**Comment by WarlordWossman** [comment]
> back to old boaring mob fights.

also back to working mobfarms which are far more interesting than combat in minecraft

**Comment by DoomSquirter** [comment]
what mobs spawn as webbers?  spiders?  then don't do cursed earth farms.  they -are- boring and here cause (I think) all the issues.  this leads to a clever connundrum where person does cursed earth in every pack, plays here, finds out hey, it doesn't work all that great, and fine tunes their approach.

I think that whole idea fits well within this pack.  I've avoided farming blazes and witches because of infernals specifically.  these are two mobs I ALWAYS farm in other packs.  forced me to take a different approach.  unintended consequences leads to interesting alternatives.  

cursed earth farms are just lazy.  there's no better way to state it.  cursed earth itself should def not be disabled tho.  it works quite well singularly under spawners to ensure they spawn mobs w/o player present.  This is in fact, what I do.  and I never have issues with webbers.

I've already stated my experience with the ninjas and they do resolve themselves eventually.  not much can be done about that.

**Comment by DoomSquirter** [comment]
so one thing I wonder is sort of a shrodinger issue.  run one of your spawners but don't stand anywhere near the spawn room.  stay away like a chunk at least.  I wonder if they continue to spawn webs.

I found some of the features only show up when there are actual ppl near the spawn room.  this may be one of them.

one mob type (unknown) spawns with wisps and for some reason when I'm near the spawner, I find mob drops 40 blocks above the spawner up inside my base for no reason.  but if I'm nowhere near the spawners at the time, this never happens.  I verified this the other day by disconnecting the setup I had to put stf dropped on that floor back to the mob room for sorting and left it sitting there and nothing showed up in the chest for the entire day or two.  

ninjas do show up tho but I've left the spawn area, gone back up to base to get something (a good 70 blocks or so away) and gone back and they were just all gone.  so I don't know what happens really.  I wonder if some of these kinds of things only happen when a player is nearby.

**Comment by MineAnPlay** [comment]
Webber is an Infernal effect and only happens when a player is within proximity. The effect can also be disabled via config file.

**Comment by 0lafe** [comment]
>Webber is an Infernal effect and only happens when a player is within proximity. The effect can also be disabled via config file.

What if the mobs come from a DE spawner set to work like a fake player? Anyway, the problem with it is that nothing is really attacking it so it shouldn't be doing that no matter how close you are to it. It also doesn't make fights any harder so why not remove it. All I see are negatives

**Comment by 0lafe** [comment]
As long as mobs I'm not fighting don't drop webs I'm happy.

**Comment by richardhendricks** [comment]
As an alternative, you could setup a timer to drop lava in the room to burn the webs. :D

**Comment by Novarek** [comment]
Sorry guys I want to add my 2cent here.
Special mobs are annoying and couse some troubles, thats true. But first off all the modpack is designed to be Hard ( on every aspect of the game), and 2nd most important, what could be a reason to have any better armor/ weapon than ordinary plane iron stuff if we ll have only vanilla mobs. It doesnt make sense to craft any better stuff if there are no harder mobs!. As someone said above, if you cant use vanila mechanics for farming mobs, find other solution. This modpack has OVER 200 mods! Just find other way to get that resources. It is not meant to be vanila game. 
So DM please dont remove the mods.

**Comment by MineAnPlay** [comment]
Webber does get activated by fake players but requires a player nearby to place cob webs, so if you don't get near it, it won't place any. I'm not sure with that Tablet from a Thaumcraft addon

**Comment by WarlordWossman** [comment]
> That depends on your weapons and tier. At lower tier, being webbed is definitely going to cause problems, especially when exploring a roguelike where a novice needs to be able to beat a quick retreat.

What are you smoking? 
You can literally just take torches and rush into a roguelike and light the place up, what are you going to lose on death? And even if you wanted to do them with your normal equip early on: A cobweb is broken by any cheap sword in no time.
In dungeons getting swarmed by mobs is actually less of a problem with cobwebs because you can avoid them while the mob AI is too stupid and gets caught in cobwebs all the time.

>As someone said above, if you cant use vanila mechanics for farming mobs, find other solution. This modpack has OVER 200 mods! Just find other way to get that resources. It is not meant to be vanila game.

And that's why this part of the pack feels super wonky.
Vanilla is what all the mods build on, why remove a fun part of the experience just because we have mods installed? If it had to be replaced by something to reach any gameplay goal - maybe, but in this case for a combat experience that you probably will only ever have pre LV (because carbon limb crossbows are retarded strong) we sacrifice a whole lot of the mobfarm concepts that would otherwise be possible.

The whole "hard pack" talk is just a meme, how many times did you actually lose your items?
If you fall into lava in vanilla and die your items get deleted, just putting that out there if you forgot.
GTNH (at least for me) always seemed like a "technic pack" instead of a "combat pack" and while mobs might seem super strong at first a bit of progressing gives you so much OP gear and flying options that you don't give a shit when you reach MV anyways (copterpack and crossbow = gg)

The fact that the hard mobs have to be on a chance so it doesn't totally break the balance in the beginning tells you that they don't work well. (Un-wanted randomness is just a bad side effect here - esp in a technic pack).

If you wanna make mobs harder do it in a non random way where people have to actually use their brain instead of just crafting the strongest crossbow and be done with it.
A system that doesn't break other things on the side would be a nice bonus on top.

In the end it seems like we want to keep that "shocking"- and "hard" effect tho, no matter how bad it's balanced or bugged. It's more important to be the ultra hardcore pack here instead of learning from actual game design.

**Comment by 648643579** [comment]
Hi, I also bother me mobs that cloaking behind blocks and make cobwebs.

Ok, recapitulation

Will they be removed, only those monsters that make these problems or will be removed, the mods that monsters add?
OR: special settings configuration mobs?
