### ISSUE TITLE
Thaumcraft Mirrors

### ISSUE THREAD

**Issue by Hakameda** [GTNewHorizons/NewHorizons#3645]
With thaumcraft Mirrors being able to move items between world's. There cost should be a bit higher or inline with ender chests and tanks. Bypasses some uses of cargo rockets on planets as well

**Comment by Vernam** [comment]
The recipe is already quite changed. Why produce senseless posts? this question has already been raised, the prescription has been changed. To change it more strongly there is no sense, since mirrors are used in mechanics Automagy in the Inventarium and essentia mirrors! mirror essence is quite a useful thing, and crafts from a regular mirror. Do you want to remove the opportunity to conveniently spread essences for infusions?

**Comment by Vernam** [comment]
Before proposing something to change, make sure that this does not affect other aspects of the Thaumcraft...

**Comment by Hakameda** [comment]
Generally exploits get fixed, while awesome for infusion not a deal breaker. It's definitely still cheap compared to other ways to move items. Eio transcievers, cargo rockets and ender chests

**Comment by bartimaeusnek** [comment]
@Hakameda they are all way faster than mirros....
