### ISSUE TITLE
industrial electrolyzer works when is shoud not

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/NewHorizons#3655]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
generate hydrogen with it  stop working when the hydrogen hach is full
#
#### What happend instead? (Attach screenshots if needed)
evry second it works for 1 sycle when the hydrogen hach is full 
#

**Comment by richardhendricks** [comment]
Don't all multiblocks void outputs they cannot place into inventories/tanks?

**Comment by botn365** [comment]
if that was the case it woud run consitently not for a split second evry second

**Comment by 0lafe** [comment]
>Don't all multiblocks void outputs they cannot place into inventories/tanks?

All except the ezmode gt++ multiblocks

**Comment by boubou19** [comment]
industrial electrolyzer is from GT++

**Comment by draknyte1** [comment]
It'll be running to refill the tank, or it won't run at all. It does space checks before even trying to run.

**Comment by Highbeam** [comment]
I remember reading that output hatch voiding was never intentional but it was kept as the norm (I'm sure it was a post from greg but don't ask me to quote it!).

I actually prefer the GT++ method that the machine stops when full.  I now use SFM to instantly move the outputs to a holding area (multiple drums) that all have multiple imports on the sides to AE/EIO.

The output hatch problem is especially true after the recent update where Iron 3 Chloride changed ID's and my chem reactor processed several million buckets of chlorine because there were no output hatches available.  The output hatch previously screwdrivered to Iron 3 Chloride had lost the selectedfluid and shoved something else in there with no space for the iron 3 anymore.  Now I'm using multiple other mechanics to stop the chem reactor/inputs if the outputs are full.

Just get faster transfer from the electrolyzer outputs.  Can't see why this would be a problem? :)

**Comment by draknyte1** [comment]
It's 100% intentional, according to Greg: Your loss is incurred because of bad IO management. Proper item/fluid routing wouldn't ever run into the issue of output voiding.
