### ISSUE TITLE
different eu cost for water electrolysis

### ISSUE THREAD

**Issue by Erixonich** [GTNewHorizons/NewHorizons#3689]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
singleplayer
#
#### What did you try to do, and what did you expect to happen?
Different approaches should have same cost in eu.
#
#### What happend instead? (Attach screenshots if needed)
Electrolysis of water in 2 different ways needs different ammount of energy.
First approach : 3 water cell -> 3 electrolysed water cell -> 1 oxygen + 2 hydrogen = 14700*3 + 900 = 45000 eu
Second approach : 3 water -> 1 oxygen + 2 hydrogen = 60000 eu

![2018-09-29_17 31 44](https://user-images.githubusercontent.com/12836717/46246974-abc16f80-c40d-11e8-8eb4-fb7ae7772b59.png)
![2018-09-29_17 31 47](https://user-images.githubusercontent.com/12836717/46246975-abc16f80-c40d-11e8-915c-dc5872e7cc1e.png)
![2018-09-29_17 32 22](https://user-images.githubusercontent.com/12836717/46246976-abc16f80-c40d-11e8-8ae6-d73978fc7100.png)

#
#### What do you suggest instead/what changes do you propose?
Change {water cell -> electrolysed water cell} recipe cost to 19700 eu.

**Comment by Highbeam** [comment]
I disagree, the first approach is done in a 2 machine set up making the overall process cheaper by using an expanded method

**Comment by Erixonich** [comment]
> I disagree, the first approach is done in a 2 machine set up making the overall process cheaper by using an expanded method

It is easy to do this with one machine and simple automation.

**Comment by richardhendricks** [comment]
That's the point - the purpose of the whole pack is to reward automation. 

NB - I do it the "expensive" way because it's easier for me to deal with in my setup.

**Comment by Highbeam** [comment]
if you make the 2 methods the same price then you may as well get rid of electrolyzing water in the first place...

and besides you are comparing 2 different processes.  Just because the end process is the same they have different steps and therefore different energy costs.

Also note you will typically have 2 machines working at the same time so you need to feed twice the EU/t still than just running 1 machine, even if it does work out as a slightly cheaper method.

There are a lot of different ways to make things in this pack and its upto you to find the cheapest that works for you :)

**Comment by Erixonich** [comment]
There are a lot of different approaches to get same thing e.g. 3 types of lv-circuits or resistors from different copper. But they are available on different stages. Water electrolysis available at same moment and they have same initial components, products, almost same but different energy cost.

Bottom line is that more effective processes (in matter of resource or energy) available later in tech-tree not simultaneously.

P.S. such serial processes should follow Hess's law.

**Comment by richardhendricks** [comment]
Well, that's a reasonable argument.  Maybe keep the same overall cost, but bump the recipe with electrolyzed cells to MV?

**Comment by WarlordWossman** [comment]
>That's the point - the purpose of the whole pack is to reward automation.

Why is the player buffed to no end then? Esp early game a lot of automation that is potentially doable is pointless.

**Comment by 0lafe** [comment]
>Why is the player buffed to no end then? Esp early game a lot of automation that is potentially doable is pointless.

It's more that required automation comes later, and you need to build up the stuff to make it. Inventory size/carry weight doesn't matter as much when you need to put 16000 platinum in a wiremill. Mining also gets automated kind of early, like MV-HV ish if you use the single blocks. Usually people automate oil in HV-EV ish. It's possible to just use big buffers, but ideally there will be a point that you can't pass without decently good automation, but that's just quite enforced hard enough yet. 

You're right though that it's mostly pointless. Kind of why I didn't get the reason to add logistics pipes. There's not much pre EV that you really NEED to automate, so a pre AE mod doesn't make much sense to me. 

Lotta stuff never really needs to be automated though, which is a little disappointing Imo. But I'm happy as long as it's required at some point, doesn't have to be early/mid game.

**Comment by WarlordWossman** [comment]
Exactly, you just rush the early stages to unlock easy mode automation with AE and so on.
Since most people focus on progression building up something time consuming early on is not really worth it.

And yes, there is no point in having a rail line going to an oil spot (actuall infrastructure) if you can just dolly tanks or bring stacks of fluid cells in your inventory.
It's kinda ironic that we want to be this "industrial pack" but it's easier to manually bring fluid than building an automated system (which would be benefitial in the real world)

**Comment by Scottishprog** [comment]
I will state - progression.

The oil example - you lock that down too much, then the player needs 2-3 K iron + wood + creosote just for the railroad. A railroad that is pretty much a dead end in SSP. Also, mass resource gathering can be difficult early on. Not to mention the time needed to actually set up the rail line.

I just worry about bogging the pack down too much.


Now... if that spout was _almost_ bottomless, becoming irrelevant due to max flow over time. (Not enough oil volume over time to power an early HV base on a constant basis for example.) Then demanding that sort of time investment might be reasonable. You make a one time investment, and get a long-lasting reward.

Another way.... oil is too difficult, it will just get ignored, Like oil sands at one point...

I understand the point, be I would be wary of bogging things down too much...
