### ISSUE TITLE
Get rid of gate caused by electrotine jetpack

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3754]
The electrotine jetpack is 95% useless.  Remove it as a gate from the coal jetpack and copterpack. PLayers could still build the electrotine as an emergency pack when mining straight down, but it is pretty annoying to use and lacks any real benefits.

**Comment by bartimaeusnek** [comment]
@richardhendricks if we get the license for Project Red (https://github.com/MrTJP/ProjectRed/issues/1414) we might be able to rework it, otherwise there is still ASM.

**Comment by richardhendricks** [comment]
I just don't see it fitting well where it is without extensive changes.  The coal jetpack  + glider is much more effective and way cheaper to run. If we doubled the run time and made it hoverable, that would at least make it slightly useful, but even then I would rush the copterpack vs wasting my time with building otherwise-useless infrastructure for this.

**Comment by WarlordWossman** [comment]
The quest for the useless PR jetpack is also gated by some batteries that not everybody makes so it's even worse. And yeah I wouldn't spend electrum dust to fly around, idk.

Copterpack should be HV instead of MV.

**Comment by shawnbyday** [comment]
That was my main thing with the electrotine jetpack was that it was behind batteries that I don't see the point in making and then the steam jetpack was behind the electrotine jetpack. Some people might like it so it could be an optional set of quests but since it "blocks" the other packs now it's sort of a problem. It doesn't stop you from making them but yea. Maybe the electrotine jetpack can be entirely reworked and available earlier somehow but otherwise meh.
