### ISSUE TITLE
Suggestion: Transformers to convert RF to EU

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3765]
#### Which modpack version are you using?
2.0.5.1
#
#### Oh hello there suggestion.

So my suggestion is to allow transformers to convert RF to EU; as it's easy enough to convert EU to RF; and as it is,  RF is kinda not that useful honestly,  yet we have possibly builds like the draconic reactor that doesn't really get any attention as it's easy enough to fuel the RF devices with EU>RF; but if it was able to convert to EU at a decent amount it'd allow for people to have some incentive to make the really cool multiblock reactor.

Few other things here and there that could make RF which would be nifty to convert to EU; and just in general would be kinda nice to have as a feature.

Unless transformers already can do this or there's another device that does that and I just never realized it- in which case just disregard this.  lol

**Comment by Teirdalin** [comment]
This post is being so buggy and giving on/off 404 errors. lol

**Comment by Bryfer** [comment]
RF to GTEU is meant to be disabled

**Comment by richardhendricks** [comment]
Github is having serious uptime problems, one of their storage servers had a meltdown.

https://developers.slashdot.org/story/18/10/22/0437245/githubs-website-remains-broken-after-a-data-storage-system-failed-earlier-today

**Comment by 0lafe** [comment]
Eio infinite RF -> EU. DE reactor is just bad, it would make like an amp of UV at most, eio does about the same for a cheaper cost. There's not that much that makes RF, but I don't think I'd like to see any of it be able to make EU.

**Comment by draknyte1** [comment]
GT transformers can convert it, but it’s default off. Just makes things too easy when you can turn 100rf into 1A of LV.

**Comment by Teirdalin** [comment]
Hmm, would it be reasonably possible to perhaps nerf the RF output of certain devices like the thing 0lafe talked about, maybe increase output of the Draconic reactor to be viable, and have a higher loss for RF>>EU?

**Comment by 0lafe** [comment]
I'd rather not considering there's like 4 things that use RF and I think the RF gens work well for it. Maybe buff the DE reactor but there's not much that needs RF. It would probably be used for EU generation, but 32:1 means it means like half an amp of zpm. Considering it has an input cost, plus is dumb expesnive, who wouldn't just make a zpm naq gen/kinetic/solar

**Comment by DoomSquirter** [comment]
every gt pack I've ever played, rf -> eu is always disabled.  I've grown accustomed to this fact and I strongly suggest it does not change.  

but, with that said, seeing that the draconic reactor (which I have never made nor probably ever will, scares the living crap out of me 🤣 ), is so end game, it seems kinda stupid to have the thing even exist cause there is very very little to use rf power for.  would be nice if somehow it and only it was able to do eu power.  if not, I don't see a real loss.

note: when I setup AE, I was perturbed that it took only 1A of EU.  I only needed like 1.5A of HV which I could provide but couldn't afford 4A of HV to convert up to 1A EV.  because of this I spammed EIO gens and utilized free lava to power it all.  Now that you can supply AE with > 1A thanks to mitch, I don't see myself doing that.  

only other thing I'd see using RF in a big way is the exu miner.  haven't made one in current game so don't even know what the power draw would be in rf.

**Comment by 0lafe** [comment]
Creative eio capacitors or even just GT EU can easily cover the cost of miners. My 1 creative thing powered like 16 quarries no problem. With the power draw on them upped a bit it'll be less but still multiple. It would be sick if we could use the DE reactor but output EU and take like fusion stuff instead of awakened drac.

**Comment by draknyte1** [comment]
I can make things do stuff they shouldn’t. (Possible content suggestion)

While not being able to force things to output EU, I could make a special adaptor that only accepts RF from whitelisted things. This would allow custom ratios per allowed object as well. (So we don’t have to follow 3.4 RF per EU rule)

**Comment by Teirdalin** [comment]
Ahhh; whitelisted sources would be nice.

**Comment by Ethryan** [comment]
@draknyte1 , How about a block the you can place right next to the DE reactor output, that outputs the energy as EU instead. A "Draconic Reactor Energy Converter" so to speak.

Bonus points if you can configure it's ratio.

**Comment by draknyte1** [comment]
@Ethryan, that’s exactly what I was suggesting. It won’t be a part of any RF-multi, but it would accept RF from specific whitelisted sources and could do so at a custom ratio per source.
