### ISSUE TITLE
Rebalance XP buckets

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3783]
With essence berries free to plant on ic2 sticks without breeding, XP has become super cheap early game to get.  This really skews XP buckets as an easy source of many resources.  This ticket is to discuss rebalancing (potentially removal) of the XP buckets mechanic for resources.

**Comment by richardhendricks** [comment]
I think there are enough ways to get gallium early game

Sphalerite dust - 72 Sphalerite dust ~ 1 gallium (RNGesus)
Gallium comb from Zinc drones - Not that hard to get, drop rate isn't great but if you let them run continuously easy to get enough to pass LV.
Impure zinc - available from small ores - 9 zinc impure/purified == 1 dust (guaranteed) in LV centrifuge
Crushed/Purified zinc - available from small ores - 9 zinc crushed/purified == 1 dust (guaranteed) in LV Thermal Centrifuge
If you get Galvania from IC2 crops, you can take 1 crushed zinc or sphalerite and turn it into 4 purified for the Thermal Centrifuge.
Finding ores now is super easy, and convenient. With the orewand and seismic/hand prospector players should be able to find any ore they need without spending too much time (> 2 hours IMO).

The XP buckets + the super cheap XP berries now make it trivial to skip the nether completely for any gallium, which is not what it was intended to do IMO. I would rather the XP buckets give the Galvania leaves (1 or 9 depending on how generous you are feeling - this allows bypassing ic2 crops though, so I would prefer a lower number.) - that would allow players to expand their current resource instead of completely bypassing it, and would require additional processing in a chemical reactor.

I dunno, I do know some players like setting up infinite supply farms, but doing all that via one single pathway feels wrong.

**Comment by Teirdalin** [comment]
Well as I said in the other post; perhaps we could have a distillation for liquid exp to make another magical liquid- like magic essence, which then we can combine with different shard dusts to make different types; which then can be put through chem reactors or other machines.

For example;   
liquid xp>>Distill>>Magic Essence
Magic Essence Chem Bath w/ Fire Shard Dust >> Liquid Fire Essence
Liquid Fire Essence >> Chem Bath with Ash >> Blaze Powder
Blaze Powder >> Chem Reactor w/ Liquid Earth Essence & Liquid Fire Essence >> Blaze Rod
Perhaps could even keep the idea of making basic metal resources by then using enough Liquid Earth Essence, enough magic essence, enough liquid order essence, and basic metal dust to make an additional of the basic metal dust.

i kinda would rather see liquid xp being used in machines rather than buckets; and to have a bit more processing before going right to itemization.  Although I can see that being a bit more work.

**Comment by 0lafe** [comment]
My vote is for the dust recipes to be removed then simple xp->mob drop recipes added to GT machines, but tiered well. No ender pearls til HV, stuff like that.

**Comment by 0lafe** [comment]
>What do you mean with XP->mob drops? Mob-only drops, like spider eyes or ghast tears? Or things like redstone and pistons? I'm not sure I understand.

More like spider eyes and rotten flesh. Vanilla mob drops, not like infernal stuff. 

>Considering the ender eyes are HV I'd think pearls could be MV if we were to go with that.

Maybe, I was thinking HV because the end is HV and a lotta e pearls there. People do sorta cheese it with endermen in smelteries anyway though so MVs fine

**Comment by richardhendricks** [comment]
It is something we definitely need to look at for 3.0.

**Comment by 0lafe** [comment]
What about removing the current recipes? Where we landing on changing those

**Comment by Teirdalin** [comment]
I'm pretty neutral with current recipes if not doing anything that major.
Honestly I think I'm the only one over on prospercraft that really does anything with liquid xp; and that's just because I don't feel like voiding all of it.  lol

**Comment by Lainiel** [comment]
If you're gonna change gallium from liquid XP then add at least some good source for the higher tier players. I'm fine with preventing people from skipping nether with XP berries, but getting enough gallium from bauxite is annoying.

You need about:
0.44 gallium for quantum EV circuit
0.88 gallium for quantum IV circuit
1.75 gallium for quantum LuV circuit
3.5 gallium for quantum ZPM circuit

Just for assembly line machine casing you need 90 ZPM circuits and 15 LuV circuits so that's 342 gallium. You get on averate 1 gallium from 5 bauxite ore, so you need to mine about 1710 bauxite just to get enough.

**Comment by 0lafe** [comment]
That's like 1-2 veins for the assembly line, that's not too bad. It used to be 3 veins of emeralds, but I'd take this over that any day. There's a source for higher tier players already, T6 planets have pure gallium ore. There's also bees that give a decent amount, and crops. UU is also a semi viable alternative at that point.

**Comment by Dream-Master** [comment]
I vote for let the poor mans uu mater in. Maybe we can adjust values. And xp berry bushes are disabled only via crop sticks which is harder as it was before.

**Comment by Teirdalin** [comment]
How much liquid xp is a level anyways if anyone knows?

I'm fine with exp crops being disabled.

**Comment by Dream-Master** [comment]
nah not really. The crops growing very slow .It's not that big issue.

**Comment by 0lafe** [comment]
Except you can breed them and get more sort of easily, and all you need is a Steve's cart, ExU transfer node, or any of the pre AE ways of autocracting. Now you have all the gallium you could want.

**Comment by Dream-Master** [comment]
ae is EV so not a big deal. I dont see a real balancing issue. If you have a better idea how to balance go ahead but i want some xp recipes in the pack.  @0lafe
