### ISSUE TITLE
Tiny Mostly Visual Suggestion:  Ore Finder Tech Themed

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3799]
#### Which modpack version are you using?
2.0.5.1
#
#### Seems unnecessary to change, what do you suggest?

So my suggestion is to make the ore finder more tech themed. A little handheld device that has a red light that flashes faster the closer to ore you are rather than pointing down- and with a bleep noise; instead of the weird watery sound.

Perhaps the recipe could use two gold plates, two silver rods, a redstone dust, and an iron handle too; so it'd still fit in the theme of being super early game.  Was initially going to say magnetic iron rods but then saw those were probably too late game for it.

![recipe](https://user-images.githubusercontent.com/37776581/47610937-449bd880-da16-11e8-9123-63895f70f8f5.PNG)

Thinking about it,  perhaps silver is a bit too hardcore to suggest;  maybe tin rods for the top.

Maybe the input slot could check the item inserted if it's a GT ore similar to how the type filter checks.

**Comment by Dream-Master** [comment]
will check

**Comment by Dream-Master** [comment]
No i like the recipe . Can add redstone to the two sides but make wand more hard.

**Comment by Dream-Master** [comment]
gold sticks are replaced by silver ones and two redstone dust added.

**Comment by Dream-Master** [comment]
Need IFU version 1.3

**Comment by richardhendricks** [comment]
I disagree alot with this change.  Requiring silver sticks puts this way above where it needs to be.  Are new players going to have to find small silver ores before using this wand now?  


We can change the behavior so it is more tech-y, but we already have a tech-y ore finder - the basic prospectors at MV.

**Comment by draknyte1** [comment]
Magnetic iron is earlier than silver~

**Comment by shawnbyday** [comment]
Silver is bad. Gold is better. Magnetic iron rod might be ok since you can technically make those pretty early. That way doesn't really reward newer players though because you don't get shown how to make magnetized iron rods until later. Ore finder wand seems targeted at newer players both to GT and to GTNH. While it might seem like an easy button compared to somethings making it too hard for the area it is available is sort of over tweaking. Gold, iron, tin, copper even bronze is something they should be able to make before they get to the rod. Silver they might be able to if they are lucky and have hit a small silver ore otherwise they have to wait until twilight forest to get it efficiently. 

Not opposed to change really but just want to make sure we're cognizant of where the wand is located, who it is intended for and the learning curve at the point where it becomes available.

**Comment by draknyte1** [comment]
I nearly always have iron and redstone before gold.. why I suggested magnetic iron.

Also a good reason to give new players more reason to mix redstone dust and iron rods. 🤔

**Comment by richardhendricks** [comment]
Magnetized iron rods are slightly preferable to silver, but even then it still requires players to find redstone (small or otherwise). 

If the problem is the wand is too powerful for the effort to make it, I'd prefer making it less powerful instead of harder to make.  Ban moon+ ores, etc.

Also, don't forget NEI does not provide information on small ores.  Silver is 20-60, redstone is 5-25, but both are fairly uncommon with an amount per chunk of 8. (vs iron at 16).

**Comment by Dream-Master** [comment]
so revert changes or use magnetic iron ?

**Comment by shawnbyday** [comment]
I'll defer to @richardhendricks to call this one outside of not using silver I don't really have much else to say.

**Comment by richardhendricks** [comment]
I guess leave it this way for now.  Maybe increase silver small ores to 16?  @bartimaeusnek is there any way we can add small ores dimension and depth information to NEI?

**Comment by richardhendricks** [comment]
How often is silver a loot item in chests vs gold?  This is also a factor.  Maybe we can add some to village smiths/roguelikes/dungeons?

**Comment by draknyte1** [comment]
Loot doesn’t matter in public environments. Unless you’re first to get it.

**Comment by richardhendricks** [comment]
Good points.   Another argument in favor of gold I think.  A stone age player can clear a large area and try farming mobs for gold bars.  Even if they cant kill them directly,  they  can let the sun kill the skeletons and zombies.

**Comment by shawnbyday** [comment]
Plus...magnetite is really common. There is a quest to find all the ores they need before the wand anyway. Makes sense to use forms of those.

**Comment by Teirdalin** [comment]
Aside from small ores, I was thinking people could just make silver with exp buckets.   But it is a good point that it does spawn in dungeon loot chests fairly commonly..

**Comment by richardhendricks** [comment]
Silver with XP buckets requires...buckets.... 8 of them no less.  I would prefer players play the game vs using the XP buckets for that.

Trust us, players had a lot of difficulty finding ores. And we have tons of information in the quest book, much of which isn't read, or understood (3 chunks apart sounds easy, but explain that to someone who's first language isn't English).

He doesn't mean vanilla dungeons, but roguelikes.

**Comment by draknyte1** [comment]
> Also saying dungeon loot doesn't matter online because other players can find it- that logic doesn't even really make sense unless people are kept in a very small area of space to mine, or if x-ray users are allowed to just roam freely. Dungeons are fairly common and there is no limit to the number that spawn in the world.

> there is no limit

But see, Any SMP server with > 5 players probably limits world size. Look at Epsilon & Delta. Dungeons in general are finite and not a valid way to allow progression. (Look how shit GC is as a result)

**Comment by Teirdalin** [comment]
> > Also saying dungeon loot doesn't matter online because other players can find it- that logic doesn't even really make sense unless people are kept in a very small area of space to mine, or if x-ray users are allowed to just roam freely. Dungeons are fairly common and there is no limit to the number that spawn in the world.
> 
> > there is no limit
> 
> But see, Any SMP server with > 5 players probably limits world size. Look at Epsilon & Delta. Dungeons in general are finite and not a valid way to allow progression. (Look how shit GC is as a result)

Oh,  yeah I guess that's a good point..
