### ISSUE TITLE
Bug: Void Dim AE2 Autocrafting GUI-  Strange.

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3807]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
Autocraft any item from a AE2 crafting terminal in a void dimension in some areas- in this example, 
x:17, y:66, z:-60
#
#### What happend instead? (Attach screenshots if needed)
If I have an item in the topright slot, the GUI closes on opening.
If something places an item into the slot while I'm pressing autocraft it crashes the entire server.
If nothing is in the slot then autocraft GUI opens normally.

It seems to differ a bit from player to player; for example one person no matter what it crashed the server with their void dim autocrafting,  while some people seem to be able to use theirs just fine. 
But since it seems to be kinda random based on position; like if I move it out a chunk,  it'll be working properly again sometimes; the people who have theirs working fine may just have it in a spot where it doesn't make issues rather than it being the players themselves..
#
#### What do you suggest instead/what changes do you propose?
Figure out why Void Dim interacts odd with AE2 autocrafts GUI perhaps.   It's a weird situational and kinda random rare occurring issue; but has come up like thrice now.

**Comment by Dream-Master** [comment]
@bartimaeusnek any idea about it ?

**Comment by 0lafe** [comment]
AE2 and void dims have had a weird relationship. Used to crash the server if you checked the crafting  status of anything from an AE terminal, but was fine with the wireless one. Lotta disconnected stuff too, for seemingly no reason. AE also seems to get pretty hard with the issue of stuff not saving when you teleport away (someone said this had something to do with a load queue I think)

**Comment by bartimaeusnek** [comment]
see https://github.com/GTNewHorizons/NewHorizons/issues/2483

**Comment by draknyte1** [comment]
Unless the dev is > 100% autistic, Dimensions should change ABSOLUTELY nothing on how GUIs work.
Void Dim probably is just buggy in general if you're getting disconnections, but then in saying that, Does ProsperCraft use Thermos? Because you know, no support there from any developers. (Especially AE2's Dev, he REFUSED to make Thermos/kCauldron compatible, nor do any legitimate binaries for such exist. Protik, the kCauldron Dev, has released fixed, unofficial builds, but unless you're gonna decompile them, I'd avoid them like the plague.)

**Comment by Teirdalin** [comment]
Well; considering this is minecraft we're talking about,  I wouldn't put it past some devs being autistic.

**Comment by npo6ka** [comment]
I also faced this problem.
I am playing on server version 2.1.0.0.
In the garden world, the crafting terminal is closed when clicking to crafting status.
I ran a series of tests and found out:
1) Me network may not be powered and have only terminals, even without a wire. The bug is reproduced.
2) The problem is directly related to the coordinates of the installation in the world. So if the terminal is set to coordinate X: 0, then the interface is closed if the player's zero slot is busy with something (the same slot that is selected by pressing the "1" key).
If the terminal is set to coordinate x: 8 and the eighth slot of the investor is busy, this problem also occurs.
3) If the inventory is completely empty, this bug will not be reproduced.
4) The problem does not depend on the coordinates y and z.
