### ISSUE TITLE
Update 1.0.7

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#382]
Things that we need to do before we can updating

- [x] make recipes for the Buildcraft Machines and Items Drobac suggest
- [x] make recipes for the adv Drill and the adv Chain Saw from Gravisuit
- [x] Gravisuit Unofficial is ready to use in the Pack
- [x] Core Mod with Gt Addons is ready to use in the Pack
- [x] Change Nano, Piko and Quantum Circuits recipes
- [x] Adding Recipes for Ender IO
- [x] Regen the planets
 - Will do when i update the Server
- [x] Building new configs
- [x] Adding Recipes for the new Flood Lights
- [x] Ender Zoo Recipes
- [x] Testing if Gregtech 05.09.** works now but we using 5.08 for now
- [x] Changing Core Mod be compatible with Galaxy Space 2.5
- [x] Lengendary BatPack need a recipe
- [x] Copying GT Molds and Extruder shapes
- [x] Adding Custom Bees

**Comment by Dream-Master** [comment]
Recipes for Gendustry, Remote Io, Extra Utilities are done so far.

**Comment by Dream-Master** [comment]
Adv Chanisaw and Adv Drill Recipes:

![image](https://cloud.githubusercontent.com/assets/2970688/10611474/96c9c976-774c-11e5-9620-2af2743464cd.png)

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/10611885/8bcb7b3a-774e-11e5-9ed6-c606e9285f17.png)

![image](https://cloud.githubusercontent.com/assets/2970688/10611894/92b84158-774e-11e5-90b6-e090210d1c76.png)

**Comment by Drobac** [comment]
Wasnt the Saw supposed to be  HV?

**Comment by Dream-Master** [comment]
Gt saw is hv level so the advanced saw is ev level.

**Comment by Dream-Master** [comment]
GT Saw lv, mv, hv 
Adv Saw ev
GT Drill lv, mv, hv
Adv Drill iv

**Comment by Namikon** [comment]
Ok then I need to change the stored energy. We agreed that the Chainsaw is HV, and therefore it got the 1million storage, which is HV level. (In fact, Lithium is even more than 1 Million, so it can hold even less). If the Drill is EV, then the Chainsaw will get 10 Million EU storage

**Comment by Dream-Master** [comment]
Ok maybe have to change it. I think it is better the Avd Drill is iv and Chainsaw is ev.
If you change the values i can add maybe the new Batterys to the recipes instead of the ic 2 crystals.

**Comment by Dream-Master** [comment]
The Problem is how i can make the adv Chainsaw then more expensive ? (because of the Gt hv Chainsaw) Or you think the adv Chainsaw isn't that powerfull?

**Comment by Namikon** [comment]
It's not an OP item if you mean that. It has Treecapitator, but so does the SteamAge Lumber axe. And it uses Energy while harvesting each block, not for the tree as "Tree". It's more a fun/alternative item to have. Moving that to EV will make it a bit too late game in my opinion. You need those tools early on. I haven't cut down a single tree since I reached the moon, so having the Chainsaw at EV will basically move it "out of interest" for people. They will just continue using their lumber axe or the thaumcraft axe (Around HV/EV) by then, and those don't even use EU and can have auto-repair.

The Drill however is different, as you will need better, faster broad mining tools, than the default tinkers ones. Even HV for the Chainsaw is pretty high, but you can craft it while you are in your Mid-MV age, which is a good place, IMHO. I never used those Gregtech chainsaw/drills because they don't have anything special. Even the HV one is just a regular saw, that uses Energy instead of durability. Afaik they are not even good for crafting, as they will loose durability instead of EU if you do autocrafting with them. Forcing people to use those will result in "noone uses it"

**Comment by Dream-Master** [comment]
So Cutting saw have to be hv Level and Advanced Drill iv Level right ?

**Comment by Dream-Master** [comment]
Hv tools from Greg using TungstenSteel allready.

**Comment by fewizz** [comment]
soon™ 
![image](https://cloud.githubusercontent.com/assets/8060034/10647128/6506560e-783f-11e5-86be-ca405d40eb37.png)
![image](https://cloud.githubusercontent.com/assets/8060034/10647152/7ae8a904-783f-11e5-9d88-cf0ac56dd934.png)

**Comment by Dream-Master** [comment]
NICE

**Comment by fewizz** [comment]
http://minecraft.curseforge.com/projects/notenoughthaumcrafttabs

**Comment by Dream-Master** [comment]
:+1:

**Comment by Dream-Master** [comment]
@Drobac 
@Namikon 

If you complain about recipes please not comparing the new recipes with the old not right nerfed recipes.
The new recipes have to fit with the new tiers we made.
If you want to changing some recipes please make a suggestion for a new one and we can talked or chat about that in the next days.
And please switch of tf the rage mode when looking in to it. I spend a lot of time redoing every mod.
So if you tiered from work or not in the right mood, play on the Live server have fun and check them later. The Test Server will run for more than a few days.
I wish constructive criticism.
Thanks

**Comment by Dream-Master** [comment]
http://forum.gtnewhorizons.com/showthread.php?tid=62

**Comment by Dream-Master** [comment]
Renew all configs. So have to look if everything is working.

**Comment by Dream-Master** [comment]
TESTSERVER is up to date for Testings.
1.11.2015 Version 1.0.7.0h 13:00.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/10871402/2d18eb8a-80e6-11e5-83b2-610962784b28.png)
Electrical Steel

**Comment by Drobac** [comment]
Warn us before you regen the planets, we got some quarries going

**Comment by Dream-Master** [comment]
ok

**Comment by Dream-Master** [comment]
Working on Bees atm.

**Comment by Dream-Master** [comment]
@Drobac 
@Namikon 
@fewizz 
@UltraPeeks 
@Teteros 
@Methes 
TODAY UPDATE!!!!!

**Comment by Dream-Master** [comment]
TEST SERVER IS UP AND READY FOR TESTING.

**Comment by Dream-Master** [comment]
DONE
