### ISSUE TITLE
Cannot craft/use GTNH quartz sand

### ISSUE THREAD

**Issue by TheRailfan** [GTNewHorizons/NewHorizons#3843]
#### Which modpack version are you using?

#GregTech New Horizons V2.0.6.0
#### If in multiplayer; On which server does this happen? 

#NA
#### What did you try to do, and what did you expect to happen?

#Tried to make some GT: New Horizons quartz sand for building the Bricked Blast Furnace. Expected to see the same recipe as was used to make glass dust
#### What happend instead? (Attach screenshots if needed)

#No recipe was available for the GT: New Horizons version, and when some was brought in from NEI, it was immediately converted to the GregTech version of quartz sand, which is unusable in most recipes, including the bricked blast furnace.
#### What do you suggest instead/what changes do you propose?

#Fix the quartz sand so that it can crafted and does not convert to the unusable GregTech version, or add the GregTech version as a valid entry into the recipes

**Comment by Dream-Master** [comment]
i ordict stuff before. will what I can do

**Comment by Dream-Master** [comment]
ok thanks will check it.
@wlhlm btw how far are you code changes with infernal mobs ?
And thanks you take care about this mod to make it better.

**Comment by wlhlm** [comment]
> btw how far are you code changes with infernal mobs ?

The changes are done/ready to be reviewed. I have attached a test build to the PR.

**Comment by TheRailfan** [comment]
The quests appear to be able to work correctly now (I am unable to 100% confirm as I have already completed these quests using 2.0.5.1). This is based on the ore dict being used for the quests now, which should allow either type of quartz sand to be used. The recipe to make glass dust is however, still dependent on the GTNH quartz sand, so crafting of glass dust appears to be broken as well.

**Comment by ddejong42** [comment]
For anyone coming here looking for a workaround, here's what I did.  Add the following lines at the end of Gregtech.zs:

//--- Glass dust
recipes.addShapeless(<gregtech:gt.metaitem.01:2890>, [<gregtech:gt.metaitem.01:2939>, <gregtech:gt.metaitem.01:802>]);
//--- Concrete
recipes.addShaped(<dreamcraft:dreamcraft_Concrete_bucket>, [
[<gregtech:gt.metaitem.01:2823>, <minecraft:bucket>, <gregtech:gt.metaitem.01:2299>],
[<gregtech:gt.metaitem.01:2823>, <minecraft:water_bucket>, <gregtech:gt.metaitem.01:2939>],
[null, <gregtech:gt.metaitem.01:2805>, null]]);


And in DefaultQuests.json, replace "dreamcraft:item.SandDust" with "gregtech:gt.metaitem.01" and change the "Damage" line in that entry to have 2939 instead of 0.  You will need to run "/bq_admin default load" in game to pick up that change.

This covers the quests and the crafting I'm running into at the moment, though I'm pretty early in this run and there may be other things impacted.

You should remove those changes before upgrading to the version with Dream-Master's proper fix.

**Comment by Dream-Master** [comment]
@ddejong42 i will push an 2.0.6.1 update soon

**Comment by GWLAN** [comment]
2.0.6.2 still have this issue

**Comment by hausfath** [comment]
@Dream-Master Looks like the multiblock main quest "Time to get some steel" is broken at the moment, as it won't accept the GregTech version and the GTNH version cannot be crafted.

**Comment by Anarack** [comment]
It is fixed in my 2.0.6.2 version. make sure you update the quest book. using default load.

**Comment by hausfath** [comment]
@Anarack Dumb question: in a single player game when I try to do "/bq_admin default load" it produces an error that I don't have permission. How do I enable admin permissions in single player?

**Comment by Anarack** [comment]
use open to lan to enable cheats then run the command. or use the default load block from better questing.
