### ISSUE TITLE
The One Ring chat spam

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/NewHorizons#387]
Minor bug:
Today I've found The One Ring from Electro-magic-tools.
When equipped the chat is spammed by "Your magic bubble of protection fades..."

I'm too scared to wear it anyway though.

**Comment by Dream-Master** [comment]
No it isn't a Bug.
You get when you respawn 30 seconds a magic protection (get not any damage) from our own mods.
After this Time the baubles fade and you are vulnerable.
When you respawn and loading the scripts you can't escape form some Mobs like the Wither and die multiple times. To prevent this we have this feature enabled.
If you moving more than a few Blocks the Baubles will fade immediately and you get damage again.

**Comment by Namikon** [comment]
Issue confirmed. The problem is, that the OneRing makes you invisible, *and* invulnerable.

The AngerMod (Bubble 'o Protection) does the same, and removes that protection if you move away too far from your spawn point, the time is up, or you attack/interact with something. 
The Spam "You bubble fades.." is a loop between EMT and AM; EMT Adding Invulnerability and AngerMod removing it a tick later.

Guess I have to whitelist the one Ring. It shouldn't do any harm, except for the excess spam. (Prolonged use however is not recommended :) )

**Comment by Dream-Master** [comment]
Ok i did't know that.
Will add those rings to the config.
