### ISSUE TITLE
IC2 more config values

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#389]
Ic2 789 Give us new config values

````
; Lava -> PahoehoeLava
heatExchangerLava = 1.0
; Hot Coolant <-> Cold Coolant
heatExchangerHotCoolant = 1.0
; Hot Water <- Water
heatExchangerWater = 1.0`
````

**Comment by Namikon** [comment]
Nice, but the Problem with those IC2 HeatExchanger setups is, they generate IC2 EU. So you need a GT Transformer after each Generator, since the IC2 cables are disabled. That's for any EU Generator we have. Semifluid, Water, Wind,.. So I think it's better to stay with GT.
The IC2 Nuclear Reactor is quite different, as you really need only a few of them in total for all your needs. For the 5x5 reactor and steam, to match our power requirements, you would need like.. 20 for each reactor with the current capped max output of the Generators. However, if that limit would be removed, then I could imagine starting to play with those values again

**Comment by Dream-Master** [comment]
Maybe we can tweaking this inside the gt code.

**Comment by Dream-Master** [comment]
will reopen it if we need it
