### ISSUE TITLE
Infernal mobs - Issues with certain effects

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#391]
There seems to be an issue with Ender and Ninja effects, whenever a mob with one of those spawns and i try to kill it, the server seem to "pause" for about 5 seconds. Not sure if that is just for people in the close by area or the entire server.

**Comment by Namikon** [comment]
I can agree that there are some serious lag spikes now and then. Until now I thought it's caused by new chunks being rendered. But as you where in a Dungeon by that time, it must've been one of those mobs then. The Ender effect was also the reason why I disabled the Blaze farm; They where all stuck in a wall. Seems those TP effects aren't very well designed; Or not meant for servers with people spawning a ton of mobs

**Comment by Dream-Master** [comment]
So you think we have to disabled this effects than?
Ender = Teleport?
Ninja = ?

**Comment by Namikon** [comment]
Ender is random teleport, ninja, not sure. But I think the mob TPs to you if you hit him. I'd want to test if disabling those effects solves the lag spike problem

**Comment by Methes** [comment]
IIRC when you strike Ninja mob it becomes invisible and teleports.

The wiki says:
Ninja - Can teleport to dodge attacks, reflecting damage on the Player, 4 second resistence buff after teleport

**Comment by Dream-Master** [comment]
Ok what we have to do here?

**Comment by Drobac** [comment]
Disable those 2 effects, should solve the issue. Unless you can find the source of the issue

**Comment by Drobac** [comment]
+1, still causing problems

**Comment by Dream-Master** [comment]
#420
