### ISSUE TITLE
Quest Good Circuits #717 bugged

### ISSUE THREAD

**Issue by rekongstor** [GTNewHorizons/NewHorizons#3988]
#### Which modpack version are you using?
2.0.6.2
#
#### If in multiplayer; On which server does this happen? 
Single, LAN
#
#### What did you try to do, and what did you expect to happen?
Detect items for quest Good Circuits #717
#
#### What happend instead? (Attach screenshots if needed)
Nothing happened. I think this issue is about Steel Casings which are IC2 variants (no longer possible to make due to GT unification)
#
#### What do you suggest instead/what changes do you propose?
Fix pls

**Comment by Dream-Master** [comment]
i fixe all casings but i will re check it.

**Comment by MrRorshah** [comment]
2.0.7.0.
Fix pls

**Comment by Dream-Master** [comment]
@rekongstor 
@MrRorshah 
did you reload the quests with this command 
/bq_admin default load
?

**Comment by Dream-Master** [comment]
as you can see if you reload the quest file is is fixed since 2.0.6.8
![image](https://user-images.githubusercontent.com/2970688/54082926-1c55ac00-431d-11e9-800b-5a6536b8da71.png)
![image](https://user-images.githubusercontent.com/2970688/54082928-211a6000-431d-11e9-9480-7a7147bd3c99.png)

i did the quest on zeta in survival mods no cheats
