### ISSUE TITLE
diphenyl isophtalate recipes in chemical reactor void some cells

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#4036]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
I was making closed loop setup of diphenyl isophtalate with a chemical reactor.
I expected it to run fine after i set it up.
#
#### What happend instead? (Attach screenshots if needed)
some cells were missing and it comes from the diphenyl isophtalate in chemical reactors:
![image](https://user-images.githubusercontent.com/12850933/51856975-5fd9f500-2331-11e9-9628-df2b14b66244.png)
![image](https://user-images.githubusercontent.com/12850933/51856998-6ec0a780-2331-11e9-98f8-6792ba72cc51.png)
![image](https://user-images.githubusercontent.com/12850933/51857022-7bdd9680-2331-11e9-9072-592a3f63bc2d.png)

#
#### What do you suggest instead/what changes do you propose?
On the recipes above you can see that two cells are missing in the output. As i'm not a pro of the chemistry i don't know the balance of the recipes so i'll suggest to just add 2 empty cells at the output excepted for the second one that only need 1 empty cell.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/51935537-6edea700-2406-11e9-8319-4a0faace29db.png)
![image](https://user-images.githubusercontent.com/2970688/51935543-71d99780-2406-11e9-8d46-7f8b6d68040f.png)
![image](https://user-images.githubusercontent.com/2970688/51935548-743bf180-2406-11e9-8916-e675753b3242.png)
Should be fixed in 2.0.6.6a.dev
