### ISSUE TITLE
Fuel efficiency of Combustion generator

### ISSUE THREAD

**Issue by nwmqpa** [GTNewHorizons/NewHorizons#4038]
#### Which modpack version are you using?
2.0.6.2
#
#### If in multiplayer; On which server does this happen? 
Singleplayer, not tested in MP
#
#### What did you try to do, and what did you expect to happen?
I tested several energy setup using creosote as fuel, and I expected the amount of energy, generated by a combustion generator, to decrease over tier
#
#### What happend instead? (Attach screenshots if needed)
It did not decrease as expected for MV.
LV: 6396 EU/L (should be 95% of max energy)
MV: 6660 EU/L (should be 90% of max energy)
HV: 5904 EU/L (should be 85% of max energy)

#
#### What do you suggest instead/what changes do you propose?
Either change the sub description, hich is misleading, or better, make the maths accurate.

**Comment by bartimaeusnek** [comment]
How did you test this? There are many variables that could cause such a behavior in game.

**Comment by Methes** [comment]
Try also adding the internal energy of battery buffer so in total:
Engine internal storage + battery buffer internal storage + battery charge.

**Comment by richardhendricks** [comment]
There is also an internal buffer within the generator, and I believe there must be a minimum amount before it will emit EU.  Instead of doing just 1 B of creosote, try doing 10.

**Comment by Beyond-Veil** [comment]
Ok, tried this with 12 cells of light fuel @305k each for a total of 3.660.000 EU base power.

LV = 3.293.184  (90% / 95% nom)
MV = 3.223.552 (88% / 90% nom)
HV = 3.106.816 (84.9% / 85% nom)

The problem seems to be the (relatively massive) loss of voltage at LV even directly going into a battery buffer, almost completely offsetting the efficiency of the generator. So the conclusion is both correct and wrong. There is indeed no measurable difference in performance between LV and MV. However this seems to be caused not by a wrong efficiency of the block, but by losing 2EU(?) inserting into the buffer.

LV (30/32)*0.95 = 89 %
MV (126/128)*0.9 = 88.6%
LV (510/512)*0.85 = 84.7%

seems to roughly match the numbers of my run. No real difference in LV vs MV seems to be more or less correct in the "real world"

**Comment by Dream-Master** [comment]
Are you using cables or wires between machines and generators ? @Beyond-Veil

**Comment by draknyte1** [comment]
Anything that emits EU has loss; seperate to cables and efficiency.

**Comment by Beyond-Veil** [comment]
> 
> 
> Are you using cables or wires between machines and generators ? @Beyond-Veil

No cables. Direct insertion into the buffer. It is just that the relative loss at LV (as also mentioned by drak) is so much higher. So that is what is eating the difference in efficiency of the gen itself. LV power generator is more efficient, but the EU loss kills the benefit compared to MV. personally i don't really see that as an issue, it was a small trade-off to begin with and it does prevent the LV option to be significantly worse than MV.
