### ISSUE TITLE
some other typo in en_Us quest lang file

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#4101]
#### Which modpack version are you using?
dev
#
#### What did you try to do, and what did you expect to happen?

#
#### What happend instead? (Attach screenshots if needed)
I was reading the en_Us quest lang file on github and i spotted weird symbols in the quest descrption of number 1275, 1329 and 1353. There might be others i don't read the file deeply.

**Comment by draknyte1** [comment]
Related to https://github.com/GTNewHorizons/NewHorizons/issues/3975#issuecomment-463855006

Also #4100 is the same. Someone needs to implement standards for modification of the quest files. Otherwise this will continue to happen so long as people outside of (US/UK/Can/Aus/etc) contribute. Windows itself doesn’t even use UTF-8 as standard, so you can’t just make minor adjustments in day notepad without ruining encoding for the entire file.

**Comment by bartimaeusnek** [comment]
@draknyte1 AFAIK BQ doesnt even use UTF-8 but some own  format...

**Comment by richardhendricks** [comment]
One other thing - do not use "%" in BQ quests, it causes that "formatting error" message.  I've removed them and replaced them all with the word "percent" because of that.

**Comment by richardhendricks** [comment]
It's not a keyboard issue, it's an issue when we went from the builtin BQ file to the per-lang ones. The per-lang files do not support the BQ color tags etc either.
