### ISSUE TITLE
Thaumcraft Wands crash the Game

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#412]
Not crafting any Thaumcraft Wands atm because this will crash the Game.

**Comment by UltraPeeks** [comment]
What I think happens is:
- Galacticraft only showed up because it triggered an player update
- tainted magic tries to use the wand for the calculation of some attack damage(?) and wants to read the amount of vis
- crashes because the wand doesn't have any nbt tags

A solution for the problem would be to replace the output of the wand the recipe with:
<Thaumcraft:WandCasting>.withTag({aqua: 0, terra: 0, ignis: 0, ordo: 0, perditio: 0, aer: 0})

The game stops to crash as soon as the wand has a nbt compound named "tag". So you don't need all the tags I listed, but it makes the wand tooltip show up correctly.
All other wands have some kind of tags. That's why no other wand crashes the game.

Maybe the other wands should have these tags, too, when crafted, just to be sure

**Comment by Dream-Master** [comment]
Yes i will try later. Thanks for digging into it.

**Comment by Dream-Master** [comment]
Ok fixed i think.

@UltraPeeks 
Need to be tested.

**Comment by Dream-Master** [comment]
fixed via Minetweaker.
