### ISSUE TITLE
New coil rebalance (1200K+)

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/NewHorizons#4126]
#### Which modpack version are you using?
2.0.6.8

#### What do you suggest instead/what changes do you propose?

Right now the fluxed/awakened drac coils boost heap capacity by 3k each, while coils normally boost heat by 900. With them being >3x what normal coils are, they give some crazy speed bonuses, especially when combined with gt++ ebf. I suggest changing them to the default progression, of flixed giving 9900K and awakened drac doing 10800K. This way they're still good improvements, but aren't gonna make you smelt things like 2x faster. 

Things that would need to switch down to 10800K or less would be infinity, infinity catalyst, cosmic neutronium, UHV superconductors and the base, tritanium, pure neutronium dust, 

Things that would need to be switched to 9900K or less would be awakened drac, raw neutronioum, UV superconductors and the base,

**Comment by 0lafe** [comment]
@scriptedpiky I know  you at least have seen the OPenis of these to some degree, so I"m curious what you think

**Comment by ScriptedPiky** [comment]
Ah yes, I remember the testing sessions we were doing with GT++ and these coils. Before GTNH 2.0.6.8, you could cook neutronium dust (9000K at 250 seconds recipe at the time) in around 27 seconds at 8 per operation because of the absurd heat boost capacity.

I do agree that they should be reduced down to their similar default progression line. Though some of the GT++ EBF recipes would also need changing, as some of them are tired around the 10000K - 15000K range. But I am totally on board with the change
