### ISSUE TITLE
GregTech Wrong Circuits in Recepten LuV,ZPM,UV

### ISSUE THREAD

**Issue by Glammi** [GTNewHorizons/NewHorizons#4128]
#### Which modpack version are you using?
2.0.6.8
#
#### If in multiplayer; On which server does this happen? 
MyFTB.de
#
#### What did you try to do, and what did you expect to happen?
try to make Elite Fluid Extractor II (ZPM)
#
#### What happend instead? (Attach screenshots if needed)
The recipe requires UV Circuits

The following recipes are affected:
LuV machines needs ZPM Circuits, 
Zpm Machine needs UV Circuits,
UV Machine needs UHV...

Crop Gene Extractor
Crop Replicator
Crop Synthesiser
Circuit Assembling Machine
Microwave
Brewery
Canning MachineChemical Bath 
Chemical Reactor
Diasassembler
Fermenter
Fluid Canner
Fluid Extractor
Fluid Heater
Naquadah Reactor
#
#### What do you suggest instead/what changes do you propose?
Adjust the recipe

**Comment by boubou19** [comment]
i think it's intended as you can craft the circuits.

**Comment by Glammi** [comment]
@boubou19
IV Fluid Extractor need IV Circuit
LuV Fluid Extractor need ZPM Circuit, i don´t think that's right

**Comment by boubou19** [comment]
look at solar panels: they need higher circuits than their tier and it's perfectly intended

**Comment by Glammi** [comment]
The solar panels need this from the beginning, not only from LuV

**Comment by richardhendricks** [comment]
It was a poor design decision to give the circuits "tier" names.  They should be thought as a partially independent system of their own. IE, tier A/B/C/D for power levels and tier 1/2/3/4 for circuit levels. You can make a higher tier "circuit" than the power tier you are using.

**Comment by 0lafe** [comment]
As moron said each tier has access to tiers of circuits T+1, and T+2 after the circuit assembler of that tier is made. Circuit assemblers at least starting with EV need T+1 because that's the best you can make before them. 

LuV become available in EV, ZPM in IV and so on. It's up to the usefulness of the machine to decide which type of circuit to use, and in doing so, how to position it in the tier. Some of those seem a little weird, but crop stuff needed T+2 seems fair, CA needing T+1 makes sense, naq gens at T+2 would be ideal, but maybe we don't need the microwave that high? Or the brewery?

**Comment by Glammi** [comment]
I still have an old auto crafting recipe for Assembling Machine ZPM and they still needed ZPM Circuits, not UV.

**Comment by 0lafe** [comment]
Not sure why, those should probably be T+1. Imo useful but needed singleblocks should be T+1, useful but not needed T+2, and most tier multis T+2 somewhere to put them post new circuits of that tier.

**Comment by Glammi** [comment]
ZPM Assembling Machine needs T+0 and
ZPM Plasma Arc Furnace needs T+0
but why
ZPM Fluid Extractor needs T+1 and
ZPM Fluid Canner needs T+1?
