### ISSUE TITLE
Crop or bee for wood log production / Prevent tree farm lag

### ISSUE THREAD

**Issue by kekzdealer** [GTNewHorizons/NewHorizons#4177]
Addition of a bee or crop that produces wood logs!
They have to be powerful enough to replace tree farms. Crops/bees should have a much smaller impact on server performance.

**Comment by richardhendricks** [comment]
Concern is with farming stations, the high speed growth/harvesting of trees can be bad for TPS.  Also the products left lying on the ground if the farming station is full.

Ideally a crop that is used in a typical sized forestry farm at 10/10/10 has equal speed to a farming station at max size.  Since normal trees can be accelerated with so many low cost ways (sprinklers etc) I think it would be OK to make this crop pretty fast growing, like 400 points to mature final stage.

Call it dwarf oak/spruce/whatever.

**Comment by damug** [comment]
Scrub oak is a thing that probably comes closet, thematically, https://en.m.wikipedia.org/wiki/Scrub_oak

Most variants don't grow taller than 6 feet to my knowledge.

**Comment by bartimaeusnek** [comment]
im not sure if this would decrease server load tbh...

**Comment by richardhendricks** [comment]
high speed tree farm with block updates up and down the tree is probably a lot more load.  Also there would be lighting updates.

Plus if the inventory is full, the forestry farm won't leave garbage on the ground, unlike the farming station.

**Comment by richardhendricks** [comment]
Bart added bonsai trees to Crops++
