### ISSUE TITLE
Titanium Dust with Nitrogen same EU cost as without Nitrogen

### ISSUE THREAD

**Issue by Kanisof** [GTNewHorizons/NewHorizons#4261]
#### Which modpack version are you using?
2.0.7.0
#

Titanium Dust costs 4,416,000 EU to process into Hot Titanium Ingot, regardless of whether you use Nitrogen or not. 

Small and Tiny Piles with Nitrogen do however have a reduction, with a cost of 3,724,800 which is roughly a 1.185x difference

#### What do you suggest instead/what changes do you propose?
Aluminium is 144,000 EU with Nitrogen and 204,000 EU without
Stainless steel is 576,000 EU with Oxygen and 816,000 EU without
Tungstensteel is 4,800,000 EU with Nitrogen and 5.760.000 without

Aluminium and Stainles Steel is 1.4166666666666666666666666666667x more expensive than using liquid. Tungstensteel is 1.2 times more expensive. 

My suggestion: is to meet somewhere in the middle:
Titanium without Nitrogen = Default cost of 4,416,.000
Titanium with Nitrogen = 3,340,000

This is roughly a 1.32 difference.

**Comment by Dream-Master** [comment]
120 without and 90 sec with gas
1,333

**Comment by Jocroy** [comment]
I assume those times are for 1920EU/t smelting? In 5.1 Ti needed 97s at MV, which is 24s at EV. So you just increased the time by a factor of 3.7 (when using gas, which wasn't possible before). Not counting the serious increase in total EU required, which went way up as well through forcing EV smelting. This means 8h of straight smelting for a 6 chamber reactor (not counting the plate bending and other stuff). The new total EU required is also nearly as high as Tungstensteel and way higher than stainless steel. I think this scaling is off, especially since HV (when you smelt Ti) doesn't offer that much more powerful power options than MV.
