### ISSUE TITLE
Let's talk about the Superconducting Coils for Fusion

### ISSUE THREAD

**Issue by Kanisof** [GTNewHorizons/NewHorizons#4335]
### Which modpack version are you using?
2.0.7.0
Official Server play

---
I've tried to be thorough here, but I may have missed some things out, so please correct any mistakes. 

I want to talk about the quite frankly, utterly insane amount of waiting around you need to do to create these 32 coils. Let's talk some numbers.

Let me preface this by saying that this is all based on 4 amps of LuV power, which isn't exactly the easiest thing to achieve for someone who is pre-fusion. Your options for this are many Mox reactors, incredibly laggy fluid reactors, 20x Large Generators (and the means to fuel them), 16x IV (LuV is Europium) Naquadah Reactors (with the huge waiting costs involved in making the naquadah fuel), The wonderful (and insanely pricy) essentia generator or by far the most reasonable choice of all: 4+ High Kinetics. 

Also this will all be on a standard EBF/Vacuum Freeze (not GT++, as balancing around that shouldn't be the focus of a GT pack) using Naquadah Alloy Coils as Electrum Flux is 500,000 eu/t. I used an Industrial Information Panel for the processing times. 

I'm going to quickly mention the LuV Motor and Pump even though Olafe made a suggestion that if implemented will render it all useless. But, on current build it takes 40+ hours to process the 8192 Osmiridium at 18 seconds per process which is needed to make the 65536 Fine Wires for the 512 Motors (which you then need to use to make 512 Pumps and that has nearly 9 hours of HSS processing involved)

The main issue (apart from the Osmiridium I previously mentioned) is the Superconductor LuV Base Ingot. 

In order to make a Fusion reactor, you must make 32 Superconducting coils. This requires 64 2x Superconducting LuV wires (4096 wires). The other recipes need at least Europium which is gated behind Fusion.

This means you need to process 2048 Dusts. In the EBF, this takes 31 seconds, which would put the time at 17 hours, but that's not the main issue (although, 17 hours is a heck of a long time by itself imo) but the main issue is when you come to using the vacuum freezer. A 4a LuV Vacuum Freezer with 2 LuV Hatches processes each ingot in 112 seconds. This leads to a MASSIVE 63 hours of nothing but processing/waiting around. 

What is the alternative to this? Making 4 more amps of LuV (....................) and even then you're still down to 31 and a half hours. What next? 12 amps of LuV pre-Fusion? You're now down to 16 hours...  Asking people to make this sort of power without a Fusion Resctor is unrealistic. 

On the current build you're at 100+ hours of processing/waiting with what is considered a very decent amount of power pre-fusion. 60+ of that is purely for the Superconductor LuV Ingots (the bulk of the rest is spread among Osmiridium and HSS-S)

#### What do you suggest instead/what changes do you propose?
I'll let other people more experienced deal with this, but I don't think anyone would agree that this amount of waiting around is a good idea.

**Comment by kekzdealer** [comment]
As much as Olafe hates it, but GT++ multis are the IV+ multis GT was always supposed to have. They also happen to be super strong, but it should be clear enough that this won't change anytime soon. 

So what's the problem about asking players to build a GT++ EBF and cut down the processing time to a perfectly reasonable length?
I'm having a hard time understanding why having it balanced around GT++ is a problem.

**Comment by ScriptedPiky** [comment]
The problem with the GT++ argument is that you're either forced to go GT++ to speed it up or wait for a million years on normal GT standards. And assuming if the changes of most GT++ multi's go through, it might make the Adv. Blast Furnace and Freezer post-Fusion.

However, it should NEVER take you that many damn resources, time, and waiting to complete that fusion reactor when you also might need more of that in the future. There's also the problem with LuV ingots taking a stupid amount of time to complete. Why does the LuV superconductor ingots take 450 seconds to cooldown a single ingot at LuV? The thing is, yes, you can parallel process more ingots (up to a max of 8 on the Adv. Blast Furnace and Freezer) and cut the time by around half and then some.

However, no one is really taking into account or really tested the damn Adv. Freezer to test resource costs. For instance: while the Adv. Freezer says "Consumes 1L/t", it actually doesn't, it consumes Cryothium based on the time of the recipe, unlike the Adv. Blast Furnace consuming 1L/t. So let's say that we have 450 seconds of freezing time for the recipe, you now have to provide 10x the amount of Cryothium for that one ingot, or 4500 Cryothium for one ingot. One Cryothium produces 250L of Liquid Cryothium, if you freeze the Blaze rod (HV voltage at 48-ish seconds, someone re-check this please), you get 3 Blizz dust worth, or rather, 750L from one blaze rod. You would need 6 blaze rods worth to get 1 LuV ingot, not including the other costs as well. This means you have to have a MASSIVE blaze into blizz production facility (blaze farm, plants, bees, etc.) just to keep up with the already absurd costs. But the Freezer will ONLY reduce the time by half. Yes, I know there are Pyro and Cryo bees as well.

Now, let's say that the superconductor change https://github.com/GTNewHorizons/NewHorizons/issues/4333 goes through, yes, it will make this a lot more forgiving. Yes, it will help reduce the time as well. However, the change to reduce the time on the superconductors will be needed.

Mid Late-game isn't even entertaining, it's a waiting simulator with poorly rushed balancing decisions.

**Comment by Kanisof** [comment]
Your entire comment is based on the assumption, with absolutely no evidence whatsoever, that gt++ is going to reduce 100+ hours of pure wait time (not even factoring in gathering, or post-smelting/freezing component crafting) into something "perfectly reasonable"

No facts, no figures, no numbers. Literally nothing but some overly defensive gripe because I mentioned how I feel the game should be balanced

This is Gregtech New Horizons. Not GT++ New Horizons (yet)

Now, let's just assume it's perfectly ok to balance one of the most iconic blocks in Gregtech history around the processing speeds of some overpowered multiblocks. Let's just test this to see just how close to "perfectly reasonable" we can get, because I know for a fact you haven't

Osmiridium in Adv EBF - 2 Ingots every 34 Seconds

Congratulations, now it only takes 39.8 hours. You saved yourself a whopping hour or 2!!

Superconductor Base LuV in GT++ Freezer. Not possible. You need a ZPM core to run 4a LuV which requires a ZPM Assembler, which in turn requires Fusion. You can test times for LuV yourself if you want.  Next update removes need for cores, but then your crafting time becomes a "perfectly reasonable" 16 hours instead.. 

Add that to your Osmiridium and you've got a "perfectly reasonable" 55 hours for those 2 ingots alone.

**Comment by kekzdealer** [comment]
As far as I can tell the Adv EBF has a base parallelism rate of 8. That means 100h turn into 12.5h. That's not even counting the speed bonus.
![image](https://user-images.githubusercontent.com/31353359/55521446-11263f80-5681-11e9-91e3-e23300804a79.png)

**Comment by ScriptedPiky** [comment]
MAX parallelism isn't achievable unless it is +2 EU tiers above the current recipe. So let's say that we're running the Adv. Blast Furnace at LuV and the recipe is LuV. It only processes 1 ingot per process but reduces the time obviously. At LuV, it's 1, at ZPM, it'll be 4, at UV, it'll be 8. Same goes for the Adv. Freezer

**Comment by 0lafe** [comment]
The fact grade ebf should be post fusion minimum, so it's mostly irrelevant to this. As well as the vac freezer being most of the complaint here, it also should be post fusion for this reason. You don't really get pushed to use either too hard until you get to fusion. 1-2 tier ebfs can hold you for a while. Here it doesn't, which is why giving them after isn't a bad idea. You've finally used them to about their limit ( 

>12 amps of LuV pre-Fusion? You're now down to 16 hours... Asking people to make this sort of power without a Fusion Resctor is unrealistic

There's your issue, it's more than doable. There's IV naq gens which can do at least 2A LuV, more once the generator array gets a recipe. IV kinetics too, which are essentially just an amp of IV. Yes LCEs, it's not amazing but works. Ti isn't a huge issue by LuV, but you'd need a bunch which does suck. Yes Bart's multi is there, and does like zpm+ iirc if you feed it right. There's the ++ rocket gens. I'm not sure what the eu/t rates of the fuel production are, but once they work that's single block amps of LuV. There's nukes, 95k is 3A LuV. Make 2 and that's over an amp of zpm. Fluid nukes do well, I think someone made like a 200keu/t+ setup recently with them. XL turbines help a bunch with that. There's also Bart's new solars lmao, which are technically options for 10k maybe even 100k eu/t if you go hard with the LV circuit production. Doable stuff, just hardish. 4 Mox reactors can give you ~12A LuV alone. Mox sorta sucks, but by this point you can make Nq* rods for it, which are GTs Mox. You can also use normal Nq for some decent outputs from fluids, which are laggy? What's the lag associated with them. 

Now let's look at the power output of the reactor. Using an mk1 for He plasma, you're looking at 1M eu/t. Assuming it asks for an 8A LuV input to make in a reasonable time, that's a 4x return on power gen, which almost make GT sense. 

Also, the SC change I proposed should minimum lower the LuV pump cost but about 2x, by making 15 at a time instead of 8. Could lower cooling times on LuV SC to 300s? Not sure if it's needed but it's a thought. 

>Mid Late-game isn't even entertaining, it's a waiting simulator with poorly rushed balancing decisions.

If you don't push your power gen/processing then sure, but many of these things range in the day-2 day for a tier up multi if you have good infrastructure. You'll really, really, *really* feel it if you're not optimising stuff. If you look at it as "how can I achieve this in a reasonable time" instead of "can my setup do this" you start to see more options. 

>and waiting to complete that fusion reactor when you also might need more of that in the future. 

Idk if you mean you'll need more OsIr, LuV SC, or reactors, but all aren't the same post fusion. Osmiridium/LuV SC arent in coils ever again as you have zpm SC for the coils. And as for their uses elsewhere, you have 2A UV to work with now. Even if you jump straight into another reactor, it'll be much faster to make with all the power you now have. Yes, this is assuming you create the infrastructure to run the reactor, but with ++ multis you can easily create the H-2 and H-3 needed. 

>not GT++, as balancing around that shouldn't be the focus of a GT pack) using Naquadah Alloy Coils

So uh, first naq alloy coils are post fusion, so no. On the ++ part, woah isn't that true. It would totally be great if we didn't have to balance around it, but with the bonus they give at the costs/tiers it's impossible not to. Anything made difficult for GT will be easy with ++, there's no getting around that. We can either cut the multis from the pack, or incorporate them to progression, but not really much else. Good luck with the first one. However, having this discussion be about ++ at all is pointless, as the multis that would assist you aren't obtainable until after you have to do all of this.

**Comment by sleepylucy** [comment]
> This is Gregtech New Horizons. Not GT++ New Horizons (yet)

You do know what the GT in GT++ stands for right? And it’s not as if the GT++ Moddev isn’t in constant contact with Greg to talk about Designs. GT++ is basically the IV+ expansion of GregTech

**Comment by Kanisof** [comment]
>As far as I can tell the Adv EBF has a base parallelism rate of 8.  That means 100h turn into 12.5h.

You didn't even bother to test it yourself but decided to add your incorrect theory anyway. Seriously, stop it. Everything you have said has been inaccurate and harmful to the discussion. 

>Oh and cores are no longer required in the newest GT++ build.

Did you even read what I said? I acknowledge this and it's STILL not "perfectly reasonable". 

All of this is utterly irrelevant anyway if what people are saying is true in that they're being gated behind post-Fusion eventually

>You do know what the GT in GT++ stands for right?

Congrautlations, you can read. Rest of your post is irrelevant and wrong, in that order

Now I see why Olafe gets frustrated when people don't even test what he proposes and go purely off "theory" and "feelings". Now let me respond to someone who actually put some thought and effort into this and didn't just spew inaccurate "theories" and irrelevant non-information

>There's your issue, it's more than doable. There's IV naq gens which can do at least 2A LuV

I don't see where this is. Do you mean the Naquadah Reactor Mark XII? Current build doesn't have a recipe for the controller block but the Naquadah hatch for it is post-Fusion anyway (ZPM Energy Hatch).  For the regular IV (LuV is post fusion) reactors you'll need 48 of them, and around 30,000 Enriched Naquadah Rods (quick math) to power them until completion. You'd need another EBF and some reactors purely to make the fuel for these, but I didn't test out exactly how many ingots per hour you'd need so I'm not sure what power EBF you could get away with. Either way, 48 Reactors and the processing of 10s of thousands of Enriched Naquadah is too much of an ask for this stage in the game. 

>Yes LCEs, it's not amazing but works. 

You can fuel over 60 LCE in parallel for nearly a full time? Not realistic. 

>Yes Bart's multi is there, and does like zpm+ iirc if you feed it right. 

Yea, the highest you can get from this is Terminus which is 199k EU/t (Nebrisum 198k / Meto 189k / Fabrico 180k) which is half of your 12 amps. That is one freakingly expensive and time consuming machine to make though. 

>There's the ++ rocket gens.
Now this one is interesting. I forgot about these because they were recently nerfed. This could be a good idea, provided they were in a dimension without rain/vegetation or you have some scrubbers. All depends on how fast you can make the fuel

You also reminded me of the Turbo Geothermal Engine which generates LuV from pahoelava / lava. I'm not sure on the input needed to run 12 of those in parallel, but if it involves dozens of everburn urns, we're screwed with the lag. 

>There's nukes, 95k is 3A LuV. Make 2 and that's over an amp of zpm
Fluid ones, or regular ones? I already mentioned about Fluid ones being insanely laggy/TPS destroying. If you have a 95k non laggy regular reactor though, feel free to link an image so that everyone can benefit. 

>There's also Bart's new solars lmao

Best you can get on current build is 6k in a thunderstorm. More realistically you're looking at 2k for the best solars so have fun making nearly 200 of those. 

>4 Mox reactors can give you ~12A LuV alone.
Build please. If this is true, then that's a game changer and I would like to add it to the wiki so that other people who come up against this insane timegate can benefit. 

>Now let's look at the power output of the reactor.

Power jump is one of the benefits sure, but the bigger issue with Fusion is the materials it produces to move up tiers. Power output shouldn't be the sole focus here. 

>Could lower cooling times on LuV SC to 300s? 

I reckon you could go lower than that and it would still be quite excessive. 450 is definitely too high though. Why it takes longer to cool down than it does to smelt is baffling. 

>So uh, first naq alloy coils are post fusion, so no. 

Yea, I forgot they needed ZPM assemblers (or maybe you could cheese it with GT++ assemblers) but even with regular Naquadah coils the time is the same anyway so it doesn't really matter. 

>However, having this discussion be about ++ at all is pointless, as the multis that would assist you aren't obtainable until after you have to do all of this.

Indeed. Speaking about those is just derailing the issue now.

**Comment by botn365** [comment]
> There's your issue, it's more than doable. There's IV naq gens which can do at least 2A LuV
those will require 8 pu241 wich is prety much imposible to get at LuV

**Comment by 0lafe** [comment]
@kanisof

>Naq gens

Yes IV, make 16 and that covers half your ebfs. Also only uses 10k naq. Make 32 and that beings your fusion time down from 100h to 25h. Assuming you calculated it with 4 LuV ebfs. 

>LCEs

Fueling them isn't really the issue, it's building/placing them all. 

>Essentia

Less expensive than fusion though, and 200k + naq gens brings you to like 18h for the coils

>Geothermal

That's just a worse but more sustainable fluid nuke. If those have issues then these will too. 

>Nukes

What part of fluids lag? Never used one but seen people use them without issue. Normal nukes with mox can hit 95k. Don't have a design myself because I never used one, but ask on discord and I'm sure someone will answer. 

>solars

*New* solars. They go up to 100M. The 10k should be doable, and maybe even the 100k, which is decent supplimentary power for this. 

>power

There's 2 parts to it though. It helps with LuV+ power, but is also a material gate. Both sort of need to be addressed, but neither alone really work. If you can barely make the reactor with pre fusion power, how will you do the things in the next tier that need even more. But you also can't get there until you can make the materials for it. Idk there's 2 things here that are semi dependant on each other, but each also needs it's own balance. Little weird. 

>2/3 SC time

Lowering it to 2/3 the time means 2/3 the power needed to make it a day of processing. Only 8A LuV, which isn't nearly as much. Now 3 mox's can do it with excess, easily fluid nukes, probably naq alone tbh if you push it. Even the essentia gen is almost enough 200k < ~250k 

Also can't cheese coils, at least fusion tier wise. ++ Multis don't use the TT hatches so you need a zpm hatch which is post fusion. Holy fuck I just realised while writing this, ++ does add an IV ish fusion reactor single block, which can probably make europium and let you do zpm shit without an mk1 reactor. That's probably something we should look at changing if that's true

**Comment by Anarack** [comment]
While the Pu vein isn't that rare weight wise, the height range means you will be lucky to find one from what people have complained about searching for it. Think regular tin veins.

**Comment by botn365** [comment]
> What part of fluids lag? Never used one but seen people use them without issue. Normal nukes with mox can hit 95k. Don't have a design myself because I never used one, but ask on discord and I'm sure someone will answer.

my 450keu/t fluid nuke made to be as efeicient droped my tps from 14 to 7 but was probebly by a design problem but the ting cost 24k titanium wich wasn't easy to get pre nerf and the 84 iv energy haches it is not somting i recomand you build

**Comment by sthegreat** [comment]
For anyone who wants it, here is a 95k mox design:

https://media.discordapp.net/attachments/181078474394566657/513161900826296321/2018-10-11_22.23.15.png?width=1277&height=684

Note that it needs vacuum freezers, sfm/oc for control, and a LOT of plutonium.

**Comment by voidlogic** [comment]
General Thoughts:

A huge portion of progression and time gating in the pack is based around the blast furnace. I think this design decision is realistic and acceptable, and I thoroughly enjoy it.

The fusion reactor is supposed to be one of /the/ end game multiblocks. Its perfectly fine for it to take several days of planning and processing to construct it.

I will agree that some of the vacuum freezer recipes could do with some looking at. The cryogenic cost for the gt++ ones is obscene imo. I currently run 30 normal ones at UHV and it still feels like I can't freeze stuff fast enough sometimes.

**Comment by ScriptedPiky** [comment]
> >Essentia

>Less expensive than fusion though, and 200k + naq gens brings you to like 18h for the coils

Weeeell, it actually costs 400 primordial pearls in total. Or about 1600 Ichorium or 3200 infusions + many more :v And a bunch of Terminus essentia (I guess you can get it from Wisps easily?)
But it is infinite energy at that point, so I can't exactly complain. It can make up to 30k+ EU/t with the right essentia's, even more with a heavily optimized setup; basically, the more complex the essentia is, the more EU/t you generate and runs in parallel! Yes, I did actually test this thing in SP.
Does anyone also know an optimal setup for gathering large amounts of essentia in one place without the use of AE2 shenanigans? Cause that doesn't work for the Large Essentia Generator

**Comment by 0lafe** [comment]
>Does anyone also know an optimal setup for gathering large amounts of essentia in one place without the use of AE2 shenanigans? Cause that doesn't work for the Large Essentia Generator

Wym "doesn't work" is it just too fast of usage for the export busses? You can generate it with beans fairly easily, but what are the usage rates like? WA'd lamped beans can do some crazy essentia gen. 

>Note that it needs vacuum freezers, sfm/oc for control, and a LOT of plutonium.

What about using Nq* instead? What's the rod usage rate like?

**Comment by ScriptedPiky** [comment]
>Wym "doesn't work" is it just too fast of usage for the export busses? You can generate it with beans fairly easily, but what are the usage rates like? WA'd lamped beans can do some crazy essentia gen.

It doesn't export at all using the essentia export busses. That's why I asked if there's a setup without the use of AE2 or a means of transporting multiple essentia's at once. The usage rate is 1 essentia every second; where the input hatch determines how much and how many different essentia's can be inside.

>What about using Nq* instead? What's the rod usage rate like?

You can't use Nq* until ZPM and UV Naquadah Generators. Plus it's 25 seconds at ZPM

**Comment by 0lafe** [comment]
You can use naquadria rods in ic2 nukes for the same effect as Mox, and it uses the dust not the ingot. As to the export busses, why not export to a jar then pull from the jar to the generator? Or do you mean the export busses won't export to anything? That seems like a bit of an issue

**Comment by sthegreat** [comment]
>What about using Nq* instead? What's the rod usage rate like?

Rod usage is just based on number of rods so it's 40 quad rods every 10 000 seconds for mox and 40 every 100 000 seconds for Nq*. However once you get the starter plutonium, mox rods actually net some Pu so there's not a great reason to use Nq* if i understand everything right, unless you absolutely can't get the amount of Pu you want (and with electric prospectors scanners I'm sure you could find some veins pretty easily).

**Comment by 0lafe** [comment]
That's not too bad. I was mostly wondering about Nq* because I thought you mean it has a high usage rate not barrier to entry. Is it mostly just a uranium cost then? Mostly wondering if constantly running ~4 of them is reasonable in IV. Seems so, but I've never done it so idk for sure

**Comment by bartimaeusnek** [comment]
@voidlogic if youre uhv just make the mega vaccum freezer...

**Comment by sthegreat** [comment]
> 
> 
> Mostly wondering if constantly running ~4 of them for a few days is reasonable in prefusion LuV. Seems so, but I've never done it so idk for sure

The only running cost is a bunch of uranium as well as some iron and lapis. Such a setup is feasible anytime IV+, a LuV player shouldn't have any trouble as long as they can work sfm/oc.

**Comment by voidlogic** [comment]
> @voidlogic if youre uhv just make the mega vaccum freezer...

Ah. still on 2.0.5.1  Didn't think about new multiblock. Maybe recipe is fine with that. dunno.

**Comment by Anarack** [comment]
Fusion in terms of LuV Blast furnaces and IV Vac freezers
 the vac freezers are faster than ebf's at this point so making them LuV would be pointless

1xLuV BLAST/IV FREEZER 629 hours  1.25 AMP LUV
 2xLuV BLAST/IV FREEZER 314.5 hours  2.5 AMP LUV
 3xLuV BLAST/IV FREEZER 209 hours    3.75 AMP LUV
 4xLuV BLAST/IV FREEZER 157 hours    5 AMPS LUV
 8xLuV BLAST?UV FREEZER 78.625 hours 10 AMP LUV

Heres my napkin math for fusion costs https://pastebin.com/DCamtmjN

**Comment by 0lafe** [comment]
Lowering the SC cost in the coils by 2x, 15x/pump LuV SC crafting, and a 250s cooling time for LuV SC base ingot, you get 20h smelting/cooling times on a 1A zpm ebf/vac freezer

**Comment by 0lafe** [comment]
Small update, using 450s cooling times also still leaves you at 20h for the overall craft, you'd have to increase the cooling past 900s to impact the overall wait time

**Comment by richardhendricks** [comment]
@0lafe , others, can we get a summary of the changes requested?
