### ISSUE TITLE
Suggestion: Alternative way to make Glycerol

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#4336]
Glycerol currently can only be made of fishoil or seedoil. Both don't need that much processing. As stated in [https://en.wikipedia.org/wiki/Glycerol](url) glycerol can also be made of propen. I am not well know to the chemistry but that way would be a more complex reaction chain. 

The easiest way to add this is the electrolyzing of epichlorohydrin to glycerol.

**Comment by richardhendricks** [comment]
Don't you normally *use* glycerol to make Epi?

**Comment by sthegreat** [comment]
We already have the allyl chloride route for epichlorohydrin so an oil based way to make glycerol itself isn't really needed. The only thing it would really enable would be oil-based dynamite, and we have plenty of other explosives.

**Comment by DietmarKracht** [comment]
Well in reallife glycerol is made from epichlorohydrin by electrolyzing. So thats why it should be added so we have the natural way via seed/fish oil and the sythetic way via propen

**Comment by septemberWaves** [comment]
It is true that synthetic methods of making glycerol do exist, but in reality they are often pointless to use due to overproduction of glycerol from biodiesel. I would not be opposed to a synthetic method of making glycerol, but I do think that forcing biodiesel as the _initial_ way to make it is a good idea (cetane-boosted diesel from biodiesel is a very effective fuel source that would be unwise to ignore). Perhaps an EV-tier recipe for synthetic glycerol would be best, so that it forces players to produce glycerol the organic way _at least_ up to the space age.
