### ISSUE TITLE
Fix exploitive hydrogen loophole

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4348]
@draknyte1

 5B methane + 10B water = 40B H2 + 5B co2

**Comment by Bluebine** [comment]
or 1 methane + 2 water= 8 H2 in a regular chem reactor. will need to change both chem reactor and LCR recipes.

**Comment by draknyte1** [comment]
They’re the same recipe. Multis don’t simplify them. Look at any Multi vs single recipe.

**Comment by septemberWaves** [comment]
In what way is it exploitative? Are you simply referring to the amount of hydrogen the recipe outputs? I am not _fully_ sure if it adds up nicely, but in reality water and methane do react to produce hydrogen (apparently this is the main industrial source of hydrogen as a primary product). That said, the water+methane reaction requires the water to be gaseous and at a high temperature, so it would make sense to change this recipe to consume steam rather than water.

**Comment by Bluebine** [comment]
1 methane + water> 8 hydrogen
8 hydrogen + carbon > 2 methane
2 methane + water> 16 hydrogen
and so on
that's the main problem. you can make an infinite loop like that, which only consumes water and carbon and produces a bunch of hydrogen

**Comment by septemberWaves** [comment]
The additional hydrogen comes from the water. According to the Wikipedia article on hydrogen production (I am aware that this is not a primary source, but the chemistry works out), there are two reactions occurring here:
CH4 + H2O → CO + 3 H2
CO + H2O → CO2 + H2

If it takes 4 buckets of hydrogen to produce one bucket of methane in-game, that means that one bucket of hydrogen corresponds to one hydrogen atom rather than one hydrogen molecule. The combination of these two reactions (which happen as part of the same process, when producing hydrogen industrially) therefore adds up perfectly to give the 8 buckets of hydrogen as an output from the reaction you are taking issue with.

Perhaps the problem is not the infinite hydrogen from water and carbon (although carbon is not _quite_ as easy as hydrogen to produce endlessly), but the energy cost compared to infinite hydrogen from water electrolysis. Replacing the water component of this recipe with steam (a large amount of steam, since Gregtech accounts for expansion in that case) would hopefully help to make the recipe seem more balanced. Ultimately though, the chemistry here works out perfectly, and the steam reforming process is used over water electrolysis in reality presumably because it has a lower energy cost. If water was a finite resource in GTNH (an actually finite resource, not simply finite in-world) it may be more apparent that this reaction is not a bug.

**Comment by draknyte1** [comment]
Basically this recipe doesn’t follow the same ‘mass’ implications as the rest of GT. 

GT generally assumes 3000L of Water = 2000L H and 1000L O. 

This recipe assumes 1000L H2O = 2000L H and 1000L O. That’s the issue at hand. The person who added these recipes didn’t follow standard convention and as a result 99% of them have already been removed.

**Comment by dragagon** [comment]
So, i get rather irritated that GT does this only one way. Basically GT says 1000H + 2000O = 1000H2O, but to break it down, 1000H2O is only 333H + 667O. There is no equal exchange...

**Comment by draknyte1** [comment]
It should give 3000L water.

**Comment by 0lafe** [comment]
Can we just change it to the real syngas recipe instead? It's 1B methane + 1B steam = 1B CO and 3B H2. Then an additional reaction of 1B steam + 1B CO =  1B CO2 + 1B H2 . This means recycling the H2 to make methane is not an H2 positive system, it's completely neutral. It also means methane becomes a semi viable H2 source, which seems to be realistic, while also giving a better option in game. net loss on eu generated too, so you cant use it for better H2 power.  Although the time would need to change to make it worth it in any way. 6.25s at HV is the equivalent of water electrolysis, so anything longer means it's a longer processing chain for a worse output. 2.5s HV seems good, and then 2s MV for the CO + steam one. Even changing it to 6.25s HV would be fine. It would be a better overclocking version of water electrolysis, for more interesting set of inputs.
