### ISSUE TITLE
[2.0.7.0] IC2+Nei+Plugin does not display crop breeding

### ISSUE THREAD

**Issue by EvgenijM86** [GTNewHorizons/NewHorizons#4354]
For some reason when I click on a seed in NEI it does not display the menu for how to breed it. It only displays quest rewards and scanner recipes.

**Comment by bedrill64** [comment]
It is intended behaviour. 
Mod creator removed it as he updated mod because it was hell inaccurate and caused problems, use cropnalyzer, it got tweaked, you do not need seeds anymore to check possible results of them as you can choose from full list of crops. Also now it shows real percentage chance to breed stuff instead of random numbers.

**Comment by EvgenijM86** [comment]
Thanks for info. I will close this then, because working as intended.
