### ISSUE TITLE
Planet fluids severely needs to be looked at

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#4360]
2.0.7.0

using this spread sheet to get the fluid yeilds for all tiers of drills leads to some interesting conclusions in regards to what should be given a drilling fluid and what should not. 
https://docs.google.com/spreadsheets/d/1wtGEzVmpsWRwci72GD9KCXC2EVZxQiLOSjvWnYD-4Ws/edit?usp=sharing 

TL:DR Don't give something a planet fluid if you ever want it to be a resource cost after that point except in amazing quantities.

**Comment by sthegreat** [comment]
Potentially unbalanced fluids (just from a quick look):

molten naquadah -- gives some stupid amount of eu when centrifuged and put in naq gens. It's also on T4 planets, just 1 planet tier above the first time you can reasonably obtain it. It also gives unlimited amounts for crafting purposes and allows the player to avoid needing to ebf/freeze naquadah

molten lead -- T4 planets so I'm not totally sure if it's op. just a hilariously large amount of lead, totally trivializes anything one could possibly use lead for, which is not a huge amount but still

chlorobenzene -- should not be on a T2 planet, which it currently is. We already have saltwater on the planets so there is no need for this, let people get benzene and actually mix it with chlorine from the salt water at this tier

liquid air -- this is on *callisto* (t3). While it yields quite a bit less than other fluids, it will still trivialize argon pretty decently

ethylene -- again not totally sure if op as it's on t5 planets, but it is pretty unlimited.

enriched naquadah -- this is only on t8 planets but you can get pretty much unlimited fuel for UV naq gen by centrifuging this.

Other fluids seem fine. I actually wonder about the usability of very heavy oil due to it needing to go through a singleblock distillery first. Maybe a faster distill tower recipe is in order?

Suggestion: shift chlorobenzene, air, maybe lead, and maybe ethylene to higher tiers. Move naquadah to like deep dark or remove. Add some fillers like lava, maybe some regular OW oils, maybe some regular helium to go with the He-3.

In general, I feel like planet stone dusts should be occupying the niche of providing "free" metal and fluids from planets. They require macerating + centrifuging so they are much easier to balance effectively, compared to underground fluids which are fast and virtually unlimited. One problem with this, however, is the lack of auto-mining for them until the ender quarry is available.

**Comment by ScriptedPiky** [comment]
![2019-04-14_19 29 43](https://user-images.githubusercontent.com/41557212/56104198-b0ea9580-5eeb-11e9-866c-a18f8142a23d.png)
Going to add this here too. This is just around 10-15ish minutes of drilling, and it still has ALL of this left go through. For instance, that is 8,643,156 ingots worth of enriched naquadah and that's not even all of it. There's still so much left and this is barely scraping the surface of all the potential fluids
![2019-04-14_19 16 43](https://user-images.githubusercontent.com/41557212/56104204-bfd14800-5eeb-11e9-88ab-5cc67f7c82c3.png)

**Comment by 0lafe** [comment]
Just wanna point out, fluid pumping rates of pretty much anything can be lowered to about 1L/t at UVish. The quantities in them can also effectively be lowered as well. So it doesn't need to be infinite too fast vs non existent. At least that's what the config seems to show. 

There should be ways to lower it even more while compensating the current fluids. Increasing the cycle time, then increasing current deposits by the same multiplier (maybe even using the min in some way?), effectively decreases the min pull rate setting a 1 in the config gives. There's also a setting for amount decrease/opperation so quantity and rate are mostly freely adjustable. 

So uh for what's there, lead seems weird but it's like a pre LV mat kinda so I don't hate it. I think it's realistic or something? Nq on T4 is a little much yeah. Maybe T5? Fluid naq also should be rate lowered to at least ebf speeds, if not slower, with a total ingot amount higher than a normal vein? Maybe the opposite but that seems less useful with faster than ebf but less than a vein of total ingots. If it's better in all ways, it sorta trivializes naq production, and makes the usage cost for the gens effectively the power of the pump, which is extremely low in this case. Each Nq ingot is 1/18 of an enriched ingot, which is 250M eu/ingot in a naq gen, before the eff bonus. Basically any high rate makes fueling naq gens trivial, and essentially makes them infinite power gens. If we want pumping naq to be fuel viable, giving it maybe 1/4 the overall output as an input req puts it in a decent spot. It does make Nq a dirt cheap material on it's own, even removing the smelting/Ar req. It makes naq seem more like a high tier oil, which some cool stuff could be done with, but as it is it's just OP. Max efficiency the conversion process of fluid Nq to fuel ready Nq+ takes a little less than 1/20 the fuel of the ingot, which isn't really noticable. I'd also recommend changing the decrease to give the field 5000 ingots max or so, to make it a little worse than mining. That's ~130B Eu per vein. 

Fluid air on T3 seems early, I can see it as a good alternative when compressors/vacs start to suck, but that's not T3, that's not even really T4. T5 liquid air seems better, with the products of it being earlier as they're much less useful. Like O2 and N2 maybe on T3/4, and fluid air on T5? It replaces compressors and vacs, leaving just the centrifuge for air production, which is sort of the lowest eu using part of the chain. 

Lava is a good one to put somewhere, considering our other lava options are mostly magic based. IO seems like a good pick for it, but maybe some small amounts in the nether too? 50max and 600max maybe? Might be kinda high. 

Also yeah, chlorobenzene is a bad one, especially for where it is. Removing it seems nice. Ethylene too. Maybe more simply hydrocarbons like CO and CO2? We got methane already. Something like naphtha/LF would be kinda useful for T6 maybe? It just eliminates distilleries, which really fall off in the later tiers, especially towers. Then again, nothing uses rates that like HV/EVs can't keep up with, so it's more like a generation pending a use, instead of giving it for any reason. Could be a reason to hold off I guess? I don't mind phasing out machines with shitty overclocking (vac/DT) in favor of pumping on high tier planets with high eu/t, seems like a decent idea.

**Comment by Dream-Master** [comment]
@richardhendrics any balancing thing thoughts

**Comment by richardhendricks** [comment]
I don't have experience post-moon, so I have no opinion on the balancing.  Others at higher tiers are going to have to set how useful fluids are to them, and if they are balanced in location and volume.
