### ISSUE TITLE
The Shop sucks, loot bags suck

### ISSUE THREAD

**Issue by redmage17** [GTNewHorizons/NewHorizons#4377]
This is more general gripe. Ever since some fucktard nuked the shop into oblivion, half the coins have no purpose and despite some promises lootbags largely consist of junk that is scrapped.  There is no incentive for veteran players to use the quests at all and little reward for newer players. Coupled with the stupid amount of steps in quests that hinder players that are smart with their time. This needs fixed before any more nerfs.

**Comment by 0lafe** [comment]
As the fucktard I feel like I'm in a good spot to explain it. The shop is there as a place to help people in the early game, until around EV or so. After which, it's more than reasonable for you to be forced to make everything you want yourself, instead of relying on free stuff as even a bonus. The current amounts of items given to you in the shop are more than enough, and still act as bonus items for anyone in the tiers that unlock them.

Lootbags are great in a similar way. Up to the T6 bags, they're pretty nice. Even if they have junk sometimes, they'll give a few good items due to how many you'll get. Anything they give you is a free bonus item, so I don't get the complaint. It's a decent amount of free stuff. We got to make 6 dimensional transceivers pre EV CA because of some lootbag circuits. 

LuV+ is less reliant on quest rewards. You now have all the tools to make what you want, and the power to back it up. It's no longer trade x coins for y reward, it's x inputs and y power. It's also entirely unnecessary for those tiers to get useful rewards from the quest book.

**Comment by redmage17** [comment]
Oh look I have 90% chance to get decorative block so worth it.  Several coins have 0 use. Such as the space, blood magic, and witchery coins. This is what happens when you push a dumb change through with no actual QA or people double checking.

**Comment by 0lafe** [comment]
Coins having no use has no relation to the shop nerf. When I nerfed the shop all I did was lower amounts by 4x on any base part (pipe/ingot/rod/etc), and removed the ability to buy more rockets. 

>Oh look I have 90% chance to get decorative block so worth it

Pretty sure it's not 90% but even then, thats a 1/10 to get something fairly useful for free. I feel like you don't notice that everything from quests is a bonus. You don't do anything for the completion of the quests, you just play the game. You're rewarded for each "quest" through progression in whatever mod you made something for. Giving you additional items based on that progression is entirety a bonus. A 1/10 for a fairly useful item is completely fair for a FREE item. There's never a time you wouldn't open a lootbag because of the trash chance, unless you want to upgrade it with fortune. The only bags I really see this being useful for are the DE bags, which give such good rewards (some totaling in the hundreds of Nt ingots) that being able to only get the rewards is worth upgrading them. 

It's a source of free items. You're complaining the rate at which you get free stuff is too low, I think that you get them at all is more than enough. Guess we're back to the quest debate 🎉

**Comment by redmage17** [comment]
it's not free stuff autist. You have to follow quest lines. This often requires more materials than necessary and rather than being efficient you have to wait till first all the primary components are finished updating, the intermediate components, then the final components. Also often including extra unneeded components or items. Often forcing people to either go back and recraft garbage or if your in SP edit the quest. But whatever I'm just going to ignore you from now on since you ignore anyone who does not agree with you.

**Comment by sthegreat** [comment]
If quest lines require more than is actually needed to progress, then make issues for those. The purpose of the questing system is to guide players through the modpack's progression and provide a little bit of free loot to help them out. The current shop is fine for that purpose.

**Comment by Hakameda** [comment]
We have been insanely lucky on lootbag drops. Like zpm circuits in ev bags, jetpacks in HV bags. You'll find alot of quests even give you back a fair bit of stuff. Like HV gives you back circuits used for crafting iirc

**Comment by richardhendricks** [comment]
Stop opening unfortuned bags. If you fortune 3 the bags, you get *0* items from the junk table.

Yes, they are not perfect.  Yes, there are plans to rebalance coins, a banker to swap coins, rebalance rewards, etc. Will it happen soon?  Probably not! There are higher priority issues with quests and bugs that need fixing.

The modpack is continually *in development*.  If you want rewards for the blood magic or witchery coins, *propose them instead of general bellyaching*.

Players who haven't used those mods, don't have much idea on *what would be useful, fair, and balanced* as a reward.
