### ISSUE TITLE
[suggestion] Completing the final task in a crafting quest should complete the quest.

### ISSUE THREAD

**Issue by voidlogic** [GTNewHorizons/NewHorizons#4380]
Players frequently lament that they finished crafting a big ticket item before manually submitting each of the crafting prerequisites in the quest book.

For example, the Dire Crafting Table quest has 7 'pages' of crafting materials to submit. These are very useful guideposts for making the item, but if you forget to manually submit all of them before crafting the Table, you are needlessly locked out of the rest of the space race quest line until assembling a second set of crafting materials.

Detecting the end goal, the 'Dire Crafting Table' in the players inventory should complete the quest regardless of the status of previous 'pages'. Similar treatment for all other crafting quests as well.

**Comment by Dream-Master** [comment]
that's how the quest book works. Not sure if there can anything changed.

**Comment by richardhendricks** [comment]
I guess this request is to break up larger quests into a bunch of small "get these items" quests and then a final quest? Or just make all quests retrievals, without any ingredients included?

**Comment by voidlogic** [comment]
Didn't know this feature wasn't possible.

For secondary quests it probably doesn't matter. But a few of the big crafting primary quests might benefit from having all of the pre-crafting steps moved to a satellite secondary quest that sits next to the primary quest.

Up to you if you think it is worth the effort. I haven't really interacted with the quest book for a long time now.

**Comment by jacobwilki01** [comment]
I'm just butting in here because I saw this issue.

I think, though this may be in newer versions of BQ only, it is possible to make only certain 'pages' or 'tasks' required to complete the quest. So you could, for example, make crafting the Dire Crafting Table be the only required step.

Not sure if this is possible in you all's modified version of BQ, but I think I remember seeing something like this in a pack.

**Comment by 0lafe** [comment]
Could break important crafting into separate quests, with only the final one being the main quest, and the rest just displaying the steps/items needed. Mad inefficient for quest #s, but idk it that's important to keep low.

**Comment by Dream-Master** [comment]
i think we let it like it is and tell people to do quests step by step. Quests are a bonus and explanation but  you don't need it.

**Comment by richardhendricks** [comment]
If you can suggest which quests really need to do this, I can look at breaking them up.  The prelim quests will definitely be low/no rewards though to prevent reward bloat.

**Comment by Dream-Master** [comment]
Again i am against it. Quest are optinal and a info/warning at start will be enough.

**Comment by Hakameda** [comment]
Other packs let things count even if your not on that quest? Is it possible to do it like that? Once you know how to make an iron ring it doesn't change until you get an extruder

**Comment by richardhendricks** [comment]
Our BQ does that already, the problem is that a page of "retrieval" requirements does not complete unless all items are present in your inventory at once. This causes problems with larger builds because players don't put all their items into the inventory at one time, and end up building the final product without ever "completing" the first part.

Separating it into two separate quests (a "fetch" quest and a "build it" quest) would help prevent players from making that mistake.

**Comment by richardhendricks** [comment]
I'll try adding warnings instead of splitting quests then @Dream-Master 

Still, need a list of quests that people commonly screw up like this.

**Comment by DietmarKracht** [comment]
The chemical quests are a problem as they require the player to have large amounts of fluid in cells in their inventory
