### ISSUE TITLE
Fluid nukes are horrible compared to vacuum freeze nukes

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#4406]
Vacuum freezer nukes massively beat out fluid nukes in raw eu/t for much lower infrastructure costs.

While they should be good I feel one should not beat out the other by such a large margin the other is rendered pointless in comparison.

**Comment by Anarack** [comment]
Personally I am iffy on just nerfing vac nukes but I would like to see fluids buffed due to the complexity of setting up and running them.

**Comment by richardhendricks** [comment]
Need a new steam, hyperheated steam. :D

**Comment by NoriSilverrage** [comment]
I wanted to add that Vac Nukes do not need a nerf. They are the perfect example of a risk reward and they are significantly less fuel efficient than other types. Additionally they require smart logic setups and are far from just plug and play. These combined make them just right where they are.

The issue is that fluid nukes are simply not good. They require so much extra work and their only real upside is a decent EU/t and really good fuel efficiency. 

I'm not sure how fluid nukes should be made better TBH...

**Comment by botn365** [comment]
the vacuum nuke is more efficient then a regular nuke the only nuke more efficient are fluid nukes wich have huge cost attchet to them

**Comment by NoriSilverrage** [comment]
Ah yes you are right. I was hung up on how many fuel cells are put in. Fluid nukes however, are crazy efficient.

In anycase, my comment stands. VAC nukes feel good right where they are. They are tough to setup safely and many people will not bother because of the explosion/problem risk and the inherent logic required.

Some additional thoughts I have are that transitioning from HV to EV and IV is rough because the setup changes significantly from the single block gens. Any changes that should be made would be to provide more viable options (like better fluid nukes) vs making anything worse.

**Comment by richardhendricks** [comment]
The problem is that any "change" is likely to blow up people's already existing bases. More HU/t? Now you're not providing enough coolant, boom. More superheated steam/HU? Now your closed loop isn't so closed any more, and you are voiding steam, boom. More EU/t for superheated steam? Now your turbine isn't rated for it, boom.

**Comment by Anarack** [comment]
ya, I agree with you moron on fluid nukes, think its going to end up being what kekz is working as its buff since we can't really touch ratios, though people really should put control and safety systems on something that could level a base.

**Comment by botn365** [comment]
One way of making fluid nukes better id by making t2 heat vents that only work in fluid nukes so you make the energy per nuke better and you avoid the problem with peopels nukes exploding if they dont know about the update.
the heat-> Hu shoud stay the same

**Comment by NoriSilverrage** [comment]
Because of fluid nuke efficiency, I think they aren't in a bad spot. The issue is with all the extra stuff attached. You need LHEs and SH turbine and steam turbines. That is a lot of complexity. If a single LHE could handle most fluid nukes, and you only need one SH turbine and 2x regular steam, then it'd start to look far more attractive because you get as much or more power and high eff.

Alternatively (or in conjunction), a simple change would be to tier SH turbines one lower. They are quite expensive now.

**Comment by richardhendricks** [comment]
Tiering the SH turbines one lower doesn't make the nukes better, just cheaper to get.
