### ISSUE TITLE
OB Mobs

### ISSUE THREAD

**Issue by ItzzGamma** [GTNewHorizons/NewHorizons#4440]
Lets face it. Mobs are annoying af, but even more annoying when they have super-abilities and too much damage like Infernal and Brutish mobs. I mean its okay to find a Brutish mob few times during your exploration, but finding them under your tree house every single MC night whilst being a Newbie with only a flint sword is not fun for anyone. 

I'm recommending that you lower the spawn rate of Brutish, Infernal and those types of Mobs because they are too strong. I had a person with me yesterday on Zeta while we were fully geared (Dark steel, protection III diamond) and we both got one shot by a Brutish zombie which is insane and they spawn too often. If possible you can also lower their damage or something because they have too much damage and they aren't that easy to kill with weapons that are available to player under MV. This is especially annoying for new players and ruins the beginner experience because you have to kill a zombie that has too much health, too many abilities and can one shot you with a damn flint sword.
Also it would be nice if the skeleton grave spawning could be reduced a bit since i'm pretty sure i had mobs spawn every 10 seconds on my grave which made it almost impossible to get my items back without a weapon.

And for you who is saying just make a town, tell that to a person who is new to the mod pack and who just wants to have some fun but can't because they keep on encountering mobs like these. 
I had the similar issues back on Epsilon as well so it's not only Zeta and i believe many of players are being annoyed with this as well. I am not asking for OB mobs to be removed, i'm asking for a Nerf and i'm pretty sure most of the people will agree with me.

EDIT: The brutish zombie on zeta broke the Dark Steel armor completely and the diamond armor was on 10% durability after the attack. (Both were almost full durability)

**Comment by Hakameda** [comment]
The night is dark and full of terrors. Make a torch

**Comment by ItzzGamma** [comment]
@Hakameda Made torches, placed them but they still come from nearby chunks and places that are not completely lighted. The point isn't in making a torch its in the damage those mobs deliver.

**Comment by richardhendricks** [comment]
You haven't accidentally setup near a spawner have you?  The wicker men have spawners underneath, eerie biomes will also spawn nasty stuff at night, and greatwood trees with spiderwebs have spawners and loot chests underneath them.

Rebalancing the mobs pack-wide is already on the todo list, but there are plenty of ways to mitigate until that happens. 
- Don't go out at night
- Light up your area
- Use a monster repellator or chandelier or magnum torch
- Charge your darksteel armor so it uses RF instead of durability
- Build walls
- Build defensive turrets
- Keep an iron golem inside your base
- Make thaumcraft guard golems
- Get reputation in a village, replicate villagers and turn them into guards (haven't tested this, but possible https://sites.google.com/site/witcherymod/village-guard). Or just steal some with a golden lasso.
- Tame a cat
- After Mars, use an arc light to repel monsters

**Comment by Hyperic88** [comment]
all of those mentioned are correct, but when i got instakill even in full dark steel armor and that armor is cut down 3/4 durability during that IK, thats not normal...

**Comment by Hakameda** [comment]
It is fine

**Comment by Hakameda** [comment]
Mobs instead of having no effect, are quite dangerous and makes people be careful. Plus if you have mobs coming from other chunks or unlit areas you could also use torches..

**Comment by Hyperic88** [comment]
like really? :D zombie that gives you instakill in mid-tier armor? i would accept that when no armor or low tiered like leather... but this way? ..."lovely"..

**Comment by Hakameda** [comment]
Oh those brutal mobs 1 hit you in high tier armor too

**Comment by ScriptedPiky** [comment]
To elaborate more on what causes these enemies to do such enormous amounts of damage. I have had the most experience in this and most frustration in fighting specific mobs, however, through many tests, deaths, and regular time playing, I identified these key things: Thaumcraft "Champions" or more specifically "Mighty" Champions, Brutish enemies in particular and the Pain Enchantment.

To explain these Thaumcraft Champions, they have various stats and are much stronger than your normal mobs, hence their name. However, the Mighty version of the champion does around 18x more damage than normal from my testing and hearing from other people (source would need to be checked). Which is why you might wonder "how did that endermen/pigmen/brutish mob 1 hit me through diamond/dark steel/thaumium fortress armor with a 20 heart pool"

Now on the Brutish enemies and the Pain Enchantment. In my testing, I have seen these Brutish Zombies  carry a Pain enchanted item, this item ranges from (from what I've seen) to a torch, an arrow, and a wooden sword. Brutish Skeletons have been seen holding "Agony" bows, exactly the same to the Pain enchantment but on a bow. The Pain/Agony enchantment has the ability to ignore armor and go straight to your health pool, regardless of your armor. At the current moment, it appears to deal an incredible amount of damage, even going into the hundreds if you have an extreme amount of health or if the enemy mob has an extreme amount of health (I.E. Using the pain enchantment on a witch from 1000 hp down to 0 in 1 hit), but the source would need to be checked and clarified

**Comment by Hakameda** [comment]
I can also elaborate on the path of least resistance when it comes to these mobs

https://minecraft.gamepedia.com/Torch

**Comment by ItzzGamma** [comment]
I would be fine with brutish mibs onr shotting me. But the fact i'm seeing them everytime i go outside my town makes it impossible to do anything. And if they ignore armor why did the darksteel get completely destroyed?

**Comment by richardhendricks** [comment]
Check for an eerie biome near your base. Or for obsidian totems with an eerie node.
