### ISSUE TITLE
Thaumostatic Harness questline

### ISSUE THREAD

**Issue by sthegreat** [GTNewHorizons/NewHorizons#4455]
#### Which modpack version are you using?
.7.0
#
#### What do you suggest instead/what changes do you propose?
This useful item removes the mining speed penalty for flying. It needs to be equipped in it's own special slot you can find from pressing the book icon in your inventory. It is gated by infusion so a quest for it in the basic thaumaturgy tab would be good.

**Comment by richardhendricks** [comment]
Since there are no Thaumostatic Harness quests either, I created a bunch.
![image](https://user-images.githubusercontent.com/1214811/57594420-9bc25000-7505-11e9-8c01-06888e76b712.png)
![image](https://user-images.githubusercontent.com/1214811/57594430-a7157b80-7505-11e9-8995-c9bfc751b29d.png)
![image](https://user-images.githubusercontent.com/1214811/57594438-b3013d80-7505-11e9-90d8-e5576145e9e0.png)
![image](https://user-images.githubusercontent.com/1214811/57594465-cf9d7580-7505-11e9-90f9-f297bbd3c62b.png)
![image](https://user-images.githubusercontent.com/1214811/57594476-e17f1880-7505-11e9-96cd-ac23e3a59eb1.png)
