### ISSUE TITLE
Better waila? 

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/NewHorizons#4523]
Is it possible to add more information to waila? Like if it shows you how much steam the steam machines/boilers have in their buffer or like telling you how much power battery buffer has in total.

**Comment by richardhendricks** [comment]
Please download and try out the 7.2 beta version.

**Comment by Impos913** [comment]
I cant try now, did you done this already?

**Comment by richardhendricks** [comment]
I'm pretty sure some new features were added to WAILA by Mitch, including showing steam in boilers.  Not in the machines though, since we don't get to see how much EU is in the buffer for voltage machines either until you get the scanner.

BTW, you do know about the hand scanner right?  I believe it's after the EBF quest now.

**Comment by Impos913** [comment]
I know scanner. So its already done I am closing this issue.
