### ISSUE TITLE
endless evolution nerf

### ISSUE THREAD

**Issue by BlackFlameTNT** [GTNewHorizons/NewHorizons#4584]
#### Which modpack version are you using?
2.0.7.3
#
#### If in multiplayer; On which server does this happen? 
test world
#
#### What did you try to do, and what did you expect to happen?
![image](https://user-images.githubusercontent.com/43831847/58449285-80fdf700-8113-11e9-9fa8-574c121f991a.png)

#
#### What happend instead? (Attach screenshots if needed)
so it did change and 90% disagreed with this change 64 infuser is not fun.
#
#### What do you suggest instead/what changes do you propose?
change the recipes not using this much infusing and something more fun and the old quest did not teach you how to auto craft the the ichor it teach you how to auto craft the thauminite.

**Comment by 0lafe** [comment]
The old quest can be changed, but I'm still very unsure what the issue is with the infusion amount. You do tons of GT recipes, at significantly longer times to make the other items. You need to do 64 fusion recipes just to make 1 normal core, and 64^2 for the awakened. Compared to the ichorium that's a ton, but it doesn't really mean much. It's all autocraftable and quickly done with a good setup, so I fail to see whats wrong with it. It enforces the placement of DE items as an endgame tech/magic mix, but using a lower tier magic item kinda kills that point. Especially one only made in a crucible

**Comment by BlackFlameTNT** [comment]
how about 90% who disagreed with this change its not only me.

**Comment by 0lafe** [comment]
If any of them wanna come in and say what's wrong with infusions for you, I guess that works too. But I'd hope you understand what you're saying enough to elaborate on the problem alone

**Comment by BlackFlameTNT** [comment]
dream him self say it need balance with the number maybe it should give 64 instead of 16

**Comment by 0lafe** [comment]
Kinda makes them super cheap though, what is wrong with them that they need a 4x cost decrease? You still haven't said the issue with infusion amounts or how they're relevant. This is an item for a purely player based upgrade that's meant to be fairly lategame. Nt sorta got cheaper in some ways, so I'm really not sure the issue with the core cost

**Comment by BlackFlameTNT** [comment]
the core cost is too much now the infuser is not 100% stable thing to auto craft with it 24h and 16 ichor that mean 32 infuser to make the the quest and its not a fun way to do it.
and why not move to another metal other then infuser how about making new ore or ingot and why not making the deep dark give ichor as ore and make the deep dark need 2 chaotic core.

**Comment by 0lafe** [comment]
Kinda kills the point of the infusion altar if it just uses an ore. You can also WA infusers to need less, I'm not sure anything that really needs more than 1. It's also stable if you set it up right and use the creative wand, or you setup a charging automation for the wand, and even worse wands are stable.

**Comment by BlackFlameTNT** [comment]
killing the infusion will be the point because that point you done it over 100 times and killed the DE dragon and that make the DD more expensive in a fair way and a lot of metal become cheaper like titanium or tungsten at 1st you need more then 1 step to get the ingot and latter you get it as pure ore.

**Comment by ScriptedPiky** [comment]
My main issue is using ichorium as the main magic material here. Yes it's far better than what it used to be (Thauminite), but it's far more annoying than difficult. Ichorium requires several steps. First, it needs two nether stars, which, are obtainable from withers or the more standard option of using null catalyst and salis, ghast tears that can be obtained from crops or killing ghasts or Twilight Forest ghasts, and both Enderman and Pigman farms, and they must be done in both the End and Nether respectively. Both of these can be done via simple Ender IO farms or utilizing regular MC spawning mechanics or manual farming.

Next, it requires the infusion process to make the Ichor. The process is somewhat fairly simple, but time consuming, especially if you aren't using any World Accelerators at all, but let's assume that no one is using it. You would need a total of 32 infusions, various materials and essentia. Now that you've got this covered, it's onto making the Ichorium itself. Using the 4 Ichor, 2 void ingots, 1 osmiridium ingot, and 2 flawless diamonds, you will obtain. In total, the player would need to obtain various resources and go back and forth through various places. It'll end up leading up to an annoying process that you will have to do every single time that you will want 16 cores. Along with getting the Neutronium.

Overall, the process is more annoying than difficult and extremely pointless of how little gain in return from the cores. With how many cores you will need, no one will really want to do that quest with how many infusions and other resources, time, and effort they'll put into very little gain. An overall tedious process than difficult

My suggestion would be to buff the core amount from 16 to 64, that way, the player feels rewarded

**Comment by 0lafe** [comment]
You can make nether stars with the T7 through ore
>especially if you aren't using any World Accelerators at all, but let's assume that no one is using it. 

By DE tier, if you aren't accelerating it, you're accepting the speed being slow

>It'll end up leading up to an annoying process that you will have to do every single time that you will want 16 cores. Along with getting the Neutronium. 

Only if you have no automation for it. If you do, it's as simple as clicking the craft in AE. 

>Overall, the process is more annoying than difficult and extremely pointless of how little gain in return from the cores. With how many cores you will need, no one will really want to do that quest with how many infusions and other resources, time, and effort they'll put into very little gain. An overall tedious process than difficult

If you do it really poorly yes, but it's really just bragging rights gear. You can essentially be invincible and fly/do tons of damage before DE. It's not really tedious or difficult if you set it up well. The spawners are much, but you'll probably need an auto infusion altar, which is really just a plus. You click craft on the parts, and they show up soon after. It's the same as anything else, but the setup is different, and harder in some ways. Both seem good for a lategame item. 

>My suggestion would be to buff the core amount from 16 to 64, that way, the player feels rewarded

But you're still rewarded with the current amounts? 16 is completely fine with the costs, and is still really just limited by Nt

**Comment by BlackFlameTNT** [comment]
if it is easy why there is no quest to show you how to auto craft the core the old one show you step by step and it is still in the quest book and that make no and the new way is not showing you any thing of how it is setup .

**Comment by 0lafe** [comment]
Because quests don't go that far, and there wasn't a quest made for this. Quest book primarily stays away from automation, besides giving you quests explaining what the parts do.

I think most blocks/multis aren't in the quest book, and including all the things those can do, it's missing a bunch. It's not something I think it needs either, but I'm not against it.

**Comment by BlackFlameTNT** [comment]
![image](https://user-images.githubusercontent.com/43831847/58452028-7bf27500-811e-11e9-9852-04904a0648f2.png)
 "not teaching you"

**Comment by Methes** [comment]
Hold up, you're mixing more stuff together to seemingly back up your cause.
Recipe difficulty and lack of automation quests in the book. The questbook was always ment as a hint how to progress through the pack, not to take your hand and show you everything.
As far as the recipe goes, I have never been this far into the modpack, but the process you're describing is actually not bad at all.
3 mob farms you should have anyway and an automated process to make what you want? I find it easier than dealing with liquids honestly.

**Comment by richardhendricks** [comment]
> The questbook was always ment 
Always? I don't think that's really the right thing to take away from the quest book.  

Dream isn't an expert in every mod.  Neither am I. Just because something is not in the quest book does not mean a conscious decision was made to not include it. If you have not, I suggest going into single player and doing

/bq_admin edit

and looking at the quest lines we now offer. Many of those questlines were proposed and/or created by players. As far as automation goes, we've now got every early automation tier covered, by quests mostly made by players.

Project Red, AE2, OpenComputer, Steve's Factory Manager, TecTech - all questlines generally created by players.

If someone wants to come up with a questline for magical automation (separate tab or incorporated into tabs we already have) I am happy to work with them to include it into the quest book.

As I said, I'm not an expert on mods, esp. DE or other top tier magic stuff. But I do a lot of documentation writing IRL and take a lot of pride in it.  So I want a questbook that is as useful to players as possible, allowing pointers to wiki etc pages where pictures are necessary.

Per Dream's comment previously,


Dream-Master commented on Oct 6, 2018
in my eyes ichorium is the best choice. Only the amount need to be balanced.

I was the one who chose 1:1, so what we'll do is change it to 1:4.  The main gate is the material. But changing it to 1:4 still makes it very worthwhile to automate, but if a player doesn't want to, then it is a reasonable amount of suffering.

**Comment by richardhendricks** [comment]
Instead of doing 1:4, we will lower the ichorium cost to 4 ingots. This leaves the other requirements as-is.

**Comment by richardhendricks** [comment]
Supercedes #4013

**Comment by richardhendricks** [comment]
Related to #3654
