### ISSUE TITLE
[Bug?] Enderio Farming Station RF Usage

### ISSUE THREAD

**Issue by NoriSilverrage** [GTNewHorizons/NewHorizons#4625]
#### Which modpack version are you using?
2.0.7.0

#
#### What did you try to do, and what did you expect to happen?
I hooked up a farming station and it consumes far more energy than expected.

#
#### What do you suggest instead/what changes do you propose?
Investigate why this is the case.

#
#### More Info
I have a tree farm I've been using forever. I am changing the power and wanted to measure how much it needs. I hooked up a 25m RF capacitor and once full I removed the EU intput. Over the next 200 seconds 5m RF was drained. This equals out to about 331eu/t. I shared this finding on discord and Bluebrine said it didn't need nearly that much.

So I tested, I kept the EU hooked up but I changed the capacitor to only allow 250RF/t out (66eu/t). I assumed the output would decrease, but despite the station saying it was out of energy, it seems to run normally and I am still gaining plenty of logs (output may have decreased some, but certainly not as much as reducing energy 5x would indicate).

With the max capacitor upgrade installed the station is only supposed to have a passive draw of 90RF/t. I know it uses more to harvest, but it seems it will harvest even if it doesn't have enough energy supplied.

This is quite inconsistent and should be looked into.

**Comment by Bluebine** [comment]
So, here's my understanding of how it works:
There's the passive draw. That's just being drawn, all the time.
Every time the farmer harvests a tree, it consumes a bit of RF per log. It's a LOT- I think over 10,000 RF per log, and overshadows the passive draw in any reasonable farm.
BUT if there's not enough power to harvest every log, it'll STILL harvest the whole tree. Even if there should only be enough in the buffer to harvest one or two logs, it'll still harvest the whole thing, and harvests the rest of the logs for free. Thus, the most optimal way to run the farm is to have JUST enough power supplied to harvest ONE log in each tree with the buffer almost empty.
I think THAT'S why the farm is so inconsistent with its power draw.

Thus my suggested solution: Fix this (if possible) so the farm needs to have the energy to chop the WHOLE tree. Then reduce the power cost per log to something like 1,000 RF per log, because with the current rates the farm would eat a pretty major percentage of the power generated by your wood.

**Comment by richardhendricks** [comment]
It would be a hard change to implement safely.  How should it determine if it has enough power? If it checks all the logs in an every every tick and fails every tick for many ticks, that will seriously impact TPS. If it only cuts a log if it has enough RF it might leave logturds around in the air that it doesn't "see" anymore because they don't touch the ground. If it does it from the top down, it still has to search the whole area for logs and run out of RF. 

Seems like the only best solution is to increase the chopping cost ~10-20x and only have it be a flat rate. IE, if you cut 1 or 100 logs, it's the same cost.

**Comment by DoomSquirter** [comment]
WE NEED TO USE THE WORD LOGTURDS MORE OFTEN

**Comment by Bluebine** [comment]
if the chopping cost becomes a flat cost, that'd buff spruce even harder while pretty much making every other tree type worthless. 
I'd recommend removing the log-cutting cost, and increasing the passive draw. Or just increase the passive draw and don't change the log-cutting cost, since that cost doesn't matter very much.
Maybe 240 RF/t (2A LV, roughly) for no capacitor, 480 RF/t (1A MV, roughly) for the multi-layer capacitor, and 960 RF/t (roughly 2A MV) for octadic. This would be an increase to the power a farming station currently needs (right now it needs 1A LV for no capacitor and ~3A LV for an octadic) without making it worthless.

**Comment by richardhendricks** [comment]
That could work

**Comment by NoriSilverrage** [comment]
Yeah I'd say just remove the log cutting cost and increase the passive. Those number look good to me.
