### ISSUE TITLE
Wither spawed with 21 permernent Warp and 30  normal warp

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#464]
Today Wither spawn with 21 permanent Warp and 30 normal warp in SG_tec Base.

The config is set to 80 (server and client i check it)

@Namikon
Is it possible that the config not working ? Old values i remember were 50.
30 and 21 = 51 warp.

**Comment by Drobac** [comment]
If i remember what namikon said, there is some kind of multiplier if you get all the warp at the same time or in a short time period

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/12818178/018c94a2-cb56-11e5-8c87-4c788340f616.png)

**Comment by Namikon** [comment]
![image](https://cloud.githubusercontent.com/assets/7611392/12818777/7f34422c-cb58-11e5-814f-260bd0060332.png)

**Comment by Namikon** [comment]
Well his total warp is 72, since the multiplier for permanent warp is 2:
(https://github.com/GTNewHorizons/NewHorizons/blob/master/config/WarpTheory.cfg#L22)
But it's still not 80; Which is somewhat weird. Maybe he got some items with warp;
I might check that when I have some spare time.

And yes, Drobac is right. Thaumcraft has some weird mechanic when it comes to warp; The more you research, the more you're considered to be an evil mage. But I haven't done any further research on that yet

**Comment by Namikon** [comment]
New trigger levels are active by now (0aba38f). A page is going to written for the very first researches in the thaumonomicon in order to describe the dangers of warp in this pack
