### ISSUE TITLE
Upgrading AE Interface

### ISSUE THREAD

**Issue by WizardSleve280** [GTNewHorizons/NewHorizons#4665]
#### Which modpack version are you using?
2.0.7.0
#
Adding a recipe that would allow for you to make an AE Interface with 30 slots for recipe storage (or some increase in slots) instead of the current amount, which would greatly compact automation and reduce lag in turn. (in this video it has been done so it is possible to do, despite having different mods installed: https://youtu.be/3w6ksBh8GtM?t=1465)

**Comment by 0lafe** [comment]
Increasing interface amount doesn't really decrease performance to a large degree, especially in the amounts that would be reduced with this. You can do any amount of inputs with 9 slots, so I'm not too sure on the benefit

**Comment by Scottishprog** [comment]
I don't think he is talking about recipe items, (9 is fine) but the number of recipes that can be placed in an interface.

**Comment by WizardSleve280** [comment]
yeah im saying to be able to add more patterns to an interface before you need to make a new machine/interface

**Comment by Xav101** [comment]
I'd suggest not adding this mainly because cramming more patterns into an interface, while it seems like a good idea, has the possibility to reduce the performance of an ME system. Your interface will effectively end up bottlenecked by molecular assemblers, especially if multiple of the patterns are items which a large amount of are required and also get crafted at the same time.

**Comment by boubou19** [comment]
that's up to the player if he wants to end his me system bottlenecked by molecular assemblers, but imo having bigger pattern storgage in interfaces is great to place patterns rarely used at the same place, or to have 1 place to store all your GT components patterns like wires for exemple: to deal with that we need to redirect to a chest then extract the chest content into the machine but this works only for single item recipes, for multiple recipes we need to use transvector interfaces to add more sides to the machine. So upgrading the capacity of ME interfaces will decrease chanels used in large automation room, potentially decreasing cpu load caused by idling ME systems. Also we could add this as an upgrade, meaning you need to progress into the game to unlock bigger me interfaces.

**Comment by DietmarKracht** [comment]
I only agree with this if the larger interface has the same functionality as the regular 9x interface. I use them with crafting cards eg. If this is missing in the 30x interface we don't need the larger interfaces actually

**Comment by Folanlron** [comment]
There's a way too extend it out without needing another style Interface ..

Chests and EnderIO Item conduits, you could go even farther with the Transvector Interface, and use a full 32 channels, if needed..

**Comment by boubou19** [comment]
The point is to reduce the channel needed for large automation.

**Comment by Anarack** [comment]
You don't use that many channels... I use 3-4 dense cables in IV and that takes care of most of my needed automation.

**Comment by boubou19** [comment]
do you still craft tons of things by hand?

**Comment by Anarack** [comment]
Machines some, sub components or casings no.

**Comment by Xav101** [comment]
Frankly, channels have never been a problem with AE2. Making a controller with a large surface area has never been difficult, and quite a few designs can be found on the internet for the unimaginative. P2P tunnels just further compound this.

**Comment by boubou19** [comment]
thing is i am UHV and the server is suffering from my ae so i'm for a reduction of used channels if possible

**Comment by Folanlron** [comment]
Multiple networks is a easier solution vs adding a new style Interface, that's the way I've done it, never had problems with servers.

**Comment by boubou19** [comment]
do you have link/guide for this?

**Comment by Folanlron** [comment]
I do 3-4Networks(depending on if Thaumcraft is going for full automation)

1 Network takes care of Ore Processing
1 Network is a storage only network, Quantum Chests/Storage Drawer Controller/Quantum Tanks
1 Network is only for auto-crafting, 

I will only have 2-3 ME drives thru the whole network setup, keep Import/Export's too a min(Both Fluid and Items, Fluid bus is incredibly bad), use Storage bus instead of the normal bus(this is 99% the problem) don't use smart cables everywhere, I usually just setup areas with smart cables, then once done pop the smart cables off and replace them with covered glass cables.

Use the enderIOs Mutiple channels network(You can setup 16 different fluids off of 1 network of pressurized conduits)

A lot of this is just trial and error until you get the hang of it, there is no link/guide it's just being smart with setups instead of constantly throwing more and more AE at the problem.
