### ISSUE TITLE
Iron bucket duplication bug

### ISSUE THREAD

**Issue by TOFUFreak** [GTNewHorizons/NewHorizons#472]
-Recipe: 8 wood pulp + 1 water bucket = 2 paper
-ProjRed Project Table
-> 1 bucket in the inventory, 1 in project table, both are usable (no interface bug)

**Comment by Dream-Master** [comment]
@Teteros 
Any Idea ?

**Comment by Teteros** [comment]
Not limited to the projectred table, it happens in the forestry workbench too.

**Comment by Teteros** [comment]
With further testing, it seems this persists with any crafting table/menu which has 'ghost' or templates for the items (and take them from some inventory other than the player. The forestry worktable does have a custom patch to prevent this behaviour, but other crafting devices like the workbanch backpacks or the project table do not.

**Comment by Dream-Master** [comment]
https://github.com/MrTJP/ProjectRed/issues/992

**Comment by Teteros** [comment]
I found out the problem and fixed it already, posting it here so you don't bother finding a solution.
(Go on IRC and I'll tell how, will edit this and post commits after more testing)

**Comment by Teteros** [comment]
Fixed in 0493545782189799ca4d7fa741525d04eb5a712, but some crafting devices use different than vanilla crafting.
See [here](http://forum.gtnewhorizons.com/showthread.php?tid=60&pid=368#pid368).

@GTNewHorizons
@TOFUFreak 

In the future, please report exploitable issues like this in the [dedicated forum section.](http://forum.gtnewhorizons.com/forumdisplay.php?fid=14)
