### ISSUE TITLE
BetterQuesting causing timeouts [In-depth look]

### ISSUE THREAD

**Issue by BlackAce21** [GTNewHorizons/NewHorizons#4743]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
ProsperCraft
#

Here's the basis of the problem. Over the course of the last few months I have been noticing performance issues with our server and random timeouts for the players. At first I attributed this to the size/age of the server and just the normal "minecraft is badly coded" problem. Minecraft 1.7.10 is notorious for having timeouts especially during chunk generation so I didn't think anything of it. As it became more of a problem even with low player count and no one traveling I slowly started to take a harder look into the problem.

To skip a lot of the boring in between bits, everything culminated in this image here. 
![chrome_2019-01-08_19-45-11](https://user-images.githubusercontent.com/6268489/59924517-e20fa680-9403-11e9-935e-44ca4fbbca03.png)

I'd like to take a moment to explain my interpretation of this. It's a screen from a warmroast session which for those not familiar is an external Minecraft server monitoring program. I had a conversation with the guy using the Blood Magic magnet and when this particular slice of the profile was happening, he was mining and picking up items with his BM sigil very quickly.

My theory? The BM sigil is picking up a lot of items on the same server tick which is throwing a great deal of item pickup events. This combined with a slow lookup time on each individual event is causing the server to have to pause to process all the information because its happening within the main server loop and causing clients to time out. It could be because our server has thousands of player entries in the questdata.json file (name might be wrong but you know what I mean) and that part of things is taking a while. It could also be that the quest lookups are taking their sweet time because GTNH has a few thousand quests that it has to sort through. Whatever the case I am growing more and more concerned with every update that is constantly adding quests to the mod pack that it is expanding this problem by orders of magnitude. I have flirted with the idea of banning magnets on the server but this won't completely eliminate the problem, like if someone breaks a chest and picks up all the items at once, we would have the same effect. Dream informs me that there is a pending update to BQ3 from BQ1 but in the interest of everyone involved I thought it important to point out this problem in case BQ3 is handling this specific aspect of quest lookups in the same way.

I'd love to say I have time to sort through the code, find the problem, and offer a solution but I simply don't. Perhaps the decision will be made that it isn't worth the time/trouble and if thats the case I understand and we'll simply have to deal with it but I wanted to make sure this got under the eyes of people involved in the development of this mod pack and BQ1/3 so it can be reviewed as an instance of the mod under pretty severe stress. Thanks for taking the time to read this o/

**Comment by Funwayguy** [comment]
BQ3 does not handle this in the same way and is much better about dealing with item pickup events (and many other task specific events) at scale. Until GTHN updates to BQ3 there is nothing I can do to mitigate this impact. There are many other HUGE problems in BQ1 that will also bring a server to a halt.

**Comment by richardhendricks** [comment]
Thanks for the detailed report, and thanks for the reponse @Funwayguy 

Couple of thoughts:
1.  A cheap and easy way to mitigate this issue is to disable all item pickup event lookups.  Is this configurable in BQ1/3? I didn't see anything in the config file.  this would probably be easy to implement.

2. A better way to handle it is to create a pre-sized hashmap of all required items for quests, with the id/metaid (many of our required items are GT items so you have to look at the metaID too) as key and the quests using them returned as a list of quest IDs.  This would take a small amount of time to generate on server start/questbook change, but then lookups would essentially change from O(n^2) to O(n). Is this what BQ3 implements?

Updating to BQ3 is definitely on our radar for this summer.

**Comment by Funwayguy** [comment]
1. Nope. No configurable option for this because it's fundamental to BQ1's item based tasks. BQ2's implementation was better but not by much. It's not even an issue in BQ3 so disabling it would pointless besides breaking all your item tasks.

2. I'm not doing work on BQ1. I burned that code base down for a reason and it's a waste of time and effort to try and fix it. The slowdown is more a problem with walking the quest database trying to find which quests the player has active (BQ1 and BQ2 has no mechanism to cache this). BQ3's databases are waaaay faster and player's have their active quest cached for faster lookups. The task already know's what it's looking for and even then, a hash wouldn't work when partial NBT matching, item subtyping or ore dictionary is involved.

**Comment by BlackAce21** [comment]
I said this on the discord but I'll say it here again just because. Thanks for the detailed response to this. I am now looking forward to BQ3 more than ever.

**Comment by richardhendricks** [comment]
Thanks for the detailed update @Funwayguy 

@BlackAce21 Please keep this ticket open so I know to verify this performance aspect when we migrate.

**Comment by BlackAce21** [comment]
rgr that

**Comment by Dream-Master** [comment]
@Funwayguy let me know when nei support is fully implemented for BQ3.
After this we can start to test the quests with BQ3.

**Comment by Funwayguy** [comment]
I don't really see how NEI prevents you from testing BQ3 but... okay? NEI support wouldn't affect compatibility with expansions or the quest data, it's just drop in code I need to put in like I did with 1.12.2's Standard Expansion. Personally I think the performance, bug fixes and new editors far outweigh waiting for NEI specific functionality.

**Comment by richardhendricks** [comment]
I can do testing etc but NEI integration is pretty key for a modpack as complex as ours.

**Comment by Dream-Master** [comment]
@Funwayguy most of recipes are custom so switching between book and nei need to long. @mitchej123 are you able to help add nei support to BQ3 for 1.7.10 ?
