### ISSUE TITLE
Mega EBF needs higher tier glass and coils

### ISSUE THREAD

**Issue by observeroftime02** [GTNewHorizons/NewHorizons#4757]
#### Which modpack version are you using?
2.0.7.5

The mega EBF needs glass for UHV+ tiers. I could not get coils past Naquadah Alloy to work in them, presumably because of the glass tier. 

It would be great if UHV+ tiers could be added for glass, so the mega ebf is usable for higher tier metals, and compatibility with all range of coils could be established.

**Comment by bartimaeusnek** [comment]
UV glass should work with NqAlloy and other coils aswell. please send me screenshots (either in discord or here) since the check for the glass tier will be disabled with UV glas.

codepice for the coils:
https://github.com/bartimaeusnek/bartworks/blob/c5cf7b202c2d537f4b6690fc24219ff8fbe86003/src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/mega/GT_TileEntity_MegaBlastFurnace.java#L296

codepice for the glas check
https://github.com/bartimaeusnek/bartworks/blob/c5cf7b202c2d537f4b6690fc24219ff8fbe86003/src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/mega/GT_TileEntity_MegaBlastFurnace.java#L256

**Comment by observeroftime02** [comment]
![2019-06-23_01 58 43](https://user-images.githubusercontent.com/43228249/59973930-725fff80-955a-11e9-9086-c7810bc62279.png)

For example

Awakened Draconium Coil Blocks, powered by 3 UHV Hatches with creative energy buffers, trying to process Superconductor UHV Dust results in the input being consumed, but no output being produced. 

I'm not sure what's going on, but any recipe needing 10800k heat capacity does not process. Perhaps I'm doing it wrong?

**Comment by bartimaeusnek** [comment]
@observeroftime02 how many amps do the "creative energy buffers" supply? you need 2A per Hatch.

**Comment by observeroftime02** [comment]
@bartimaeusnek depending on setting between 1A - 16A, I set 4A per hatch. It's the same with 16x battery buffers as well, so I think the amperage is not to blame. 

Another example I've found is processing tungstensteel dust (with / without gas) with the above setup (UV Borosilicate Glass, Awk Draconium Coils, 3 UHV hatches with 4A each). Input is consumed, no output produced, and that is a recipe that only needs 3000k and 1920 eu/t. Even using lower tier coils does not get it to work at all. At this point I am unsure whether it's related to the tier of glass or just a bug in general. 

Energy going to the hatch:

![image](https://user-images.githubusercontent.com/43228249/59982244-fac6ba80-95c3-11e9-8c9d-e8c945b8b5fb.png)

Mega EBF with HSS-G Coil blocks and UV-Tier Borosilicate glass:

![2019-06-23_14 33 52](https://user-images.githubusercontent.com/43228249/59982258-1cc03d00-95c4-11e9-87b1-709879f3b463.png)
