### ISSUE TITLE
bug still exists in item type filters?

### ISSUE THREAD

**Issue by DoomSquirter** [GTNewHorizons/NewHorizons#4822]
#### Which modpack version are you using?
7.5
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
item type filters - broken or not
#
#### What happened instead? (Attach screenshots if needed)
related to this fix:
https://github.com/GTNewHorizons/NewHorizons/issues/3367
after this fix was made, there is no issue for it but it was well known that something happened to item type filters and they were allowing items to pass through that weren't part of the filter.  iirc moron fixed this?  since I don't see a ticket about it, I just have to assume fix got put in.

I was talking to mamitomoe in discord just now and he said that bug still exists in 7.5 which is really worrisome to me.

#
#### What do you suggest instead/what changes do you propose?
verify that bug doesn't exist anymore or ???

**Comment by observeroftime02** [comment]
Filtering, specifically during situations where TPS < 20 causes type filters to let through items that are not allowed by the filter. 

Best way to test this is to set up some infinite JABBA barrels with several types of ore processing products (crushed, centrifuged, pure, impure, tiny dusts), merge them together into one huge quantium pipe, and then separate them using type filters while hammering the server (6 or 9 max tier drilling rigs in the DD ought to do the trick). 

While I was still using type filters to process the output of my drilling rigs, items would routinely make it past the filter that weren't supposed to be there, especially while TPS were low and teleporting to different dimensions via rocket. 

Some speculative ideas: Filter checks get skipped during low TPS situations when the server lags, and items are allowed to pass through. Just speculation of course, since I haven't looked at any code. The worse the TPS and skipped ticks becomes the more items would make it past the filter. I haven't done any concrete testing, so this is empirical observations only.

**Comment by ivanpu** [comment]
I think I have the similar issues, but at 20tps.
Both on versions 2.1.2.0 and 2.1.2.3qf of the pack.
I have item filter set to blacklist an item, but it's passing thru anyways.
Should I post the screenshots here, or open a new issue?
