### ISSUE TITLE
Unable to reconnect after Timeout/Kick; SP non-functional

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#487]
After playing on a Server, you're unable to go into Single Player (Noticed by Drobac; Not yet verified by a second person)
Also, if you get a Timeout or get disconnected from the Server, you can't login again. You're just reset to the Server screen or Main Menu with "Fatal Error occurred". (Noticed by me, verified by Drobac)

I assume both problems are related to each other; Hence the combined issue.
I highly doubt that it is related to Thermos, as I've joined/parted the Thermos server with all of its plugins in place, but without any Forge mods, multiple times without any problems

**Comment by Teteros** [comment]
>After playing on a Server, you're unable to go into Single Player (Noticed by Drobac; Not yet verified by a second person)

Can also confirm, as I test a lot. The client just spontaneously crashes when attempting to load back to SP.
That's on the live server, didn't have a chance to visit test server yet.

**Comment by deeplyarnab** [comment]
I can verify it too, wasn't able to login to the server after i disconnected and then even the single player didn't work, minetweaker 3 says modtweaker 2 crashed due to a dependency error after agricraft registers all the crop mutations

**Comment by Namikon** [comment]
Probably found the cause. It's a NPE in modtweaker2 while trying to undo a Thaumcraft page; So it's related to the Minetweaker Thaumcraft Scripts. I could verify this by deleting my local Thaumcraft*.zs files and load a SP world, exit that world and connect to the Test Server right after it, which worked just fine. Then the Thaumcraft scripts were loaded from the Server, I disconnected and was unable to go to SP or reconnect to the Server due to the mentioned NPE.
This could probably also be the reason why you weren't able to reload your scripts @Dream-Master 

Related crash-messages:
https://gist.github.com/Namikon/168ae58f6e4f439fe836

**Comment by Xavion3** [comment]
Just to note the solution I used when dealing with prereqs, as I experienced weirdness even with different placements of moving and doing other things. Remove the research and then add an identical looking replacement, it has the downside that people will have to research it again but it totally gets by any oddities with moving researches and it looks identical to the user as they don't see internal research names.

**Comment by Dream-Master** [comment]
@Xavion3 
Did you have some example for me.

**Comment by Xavion3** [comment]
So the issue with what we had was cinnabar purification, we moved the witching gadgets one over to the rest of the purifications. However it bugged obviously. So I swapped us to [this](https://github.com/JasonMcRay/InfiTech-1.7/blob/master/scripts/thaumcraftclusters.zs#L117-L134).

As far as doing it for the four researches that you've moved, basic process is to orphan and remove the original, remove the original recipe, add a new research with the same icon and research requirements in the right location, then just add in the name, tooltip, and pages and you've got something indistinguishable. The biggest hassle potentially is you also have to add it as a prereq for anything it was a prereq for, doesn't look like that will be much of a concern.. For an example

You've got a moveResearch [here](https://github.com/GTNewHorizons/NewHorizons/blob/ba9443345d5cc8fc671247c54709291fab77bc6d/scripts/Magic-Bees.zs#L281-L293), without the minetweaker log after crashing I couldn't tell you if that was what it crashed at (The log reports actions when attempting them, so the last noted action before it cuts off should be what failed). However to modify that to a replacement instead of moving I'd end up with the following code

```
// --- Magic Frame
mods.thaumcraft.Research.orphanResearch("MB_FrameMagic");
mods.thaumcraft.Research.removeResearch("MB_FrameMagic");
mods.thaumcraft.Research.addResearch("NH_MB_FrameMagic", "MAGICBEES", "ordo 15, terra 12, aer 9, perditio 6", -4, 0, 4, <MagicBees:frameMagic> * 1);
game.setLocalization("en_US", "tc.research_name.NH_MB_FrameMagic", "Magic Frame");
game.setLocalization("en_US", "tc.research_text.NH_MB_FrameMagic", "[MB] Putting magic into beekeeping contexts");
mods.thaumcraft.Research.addPrereq("NH_MB_FrameMagic", "INFUSION", false);
mods.thaumcraft.Research.addSibling("NH_MB_FrameMagic", "INFUSION");
mods.thaumcraft.Research.addPage("NH_MB_FrameMagic", "tc.research_page.MB_FrameMagic.1");
mods.thaumcraft.Arcane.addShaped("NH_MB_FrameMagic", <MagicBees:frameMagic>, "ordo 8, terra 8, aer 8, perditio 8, ignis 8, aqua 8", [
[<ore:screwSteel>, <MagicBees:wax:1>, <ore:screwSteel>],
[<MagicBees:wax>, <Forestry:frameImpregnated>, <MagicBees:wax:2>],
[<ore:screwSteel>, <Thaumcraft:ItemResource:7>, <ore:screwSteel>]]);
mods.thaumcraft.Research.addArcanePage("NH_MB_FrameMagic", <MagicBees:frameMagic>);
mods.thaumcraft.Research.addPrereq("MB_DimensionalSingularity", "NH_MB_FrameMagic", false);
```

Think that should be a valid script, haven't actually tested in a world.

**Comment by Dream-Master** [comment]
fixed i guess.
