### ISSUE TITLE
One more HP Solar Boiler bug

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/NewHorizons#4883]
Zeta; 2.0.7.5 as well as other instances from others.

Currently, the HP Solar Boiler will not produce heat beyond 1/3rd or 1/4th of its total heat capacity. While the heat it produces certainly reaches the threshold of producing steam, it never reaches its fullest heat potential as generally seen in the GUI interface. This may be due to it reaching an internal cap?

**Comment by Dream-Master** [comment]
@bartimaeusnek any idea ?

**Comment by richardhendricks** [comment]
maxProgressTime was changed, but there was a hard limit in the base class. I removed the hard limit, but went ahead and changed the max progress time back to normal anyways.

Instead, I changed how it decreases heat so that it is about 60% slower at losing heat than the base solar boiler. HP solar should last about 5 minutes now without sun. Basic solar will last about 3 minutes.

**Comment by Methes** [comment]
Related to this issue is that the water capacity seems to be higher than the GUI shows - GUI is filled up to top long before the boiler stops accepting more water.
Haven't done any real testing or number crunching, going from a feeling while using HP boilers for days.

**Comment by richardhendricks** [comment]
Yeah it is listed as having 2x the capacity, but I don't think boilers properly handle it, so that's probably why.  It's a minor visual bug imo.
