### ISSUE TITLE
[RFC]Remove ruby dust from redstone centrifuging

### ISSUE THREAD

**Issue by basdxz** [GTNewHorizons/NewHorizons#4886]
Redlions crops allow for near-limitless redstone which in turn can be centrifuged into ruby. Ruby being centrifuged into chrome is a problem as it makes the base IV metal too easily obtainable. Removing ruby dust from redstone centrifuging would give more relevance to ruby ore and ruby bees. Perhaps a ruby plant could later be figured out.

**Comment by Methes** [comment]
I fail to see how this is a problem. Apart from another 'oh man infinite resources are so OP and problematic!'
Steel is renewable from a mobfarm.
Aluminum is renewable from clay.
Stainless is renewable from mobfarm+redstone
Titanium is renewable from stone
Tungsten is renewable from lava
Chrome is renewable from redstone.
All of above is renewable from bees, crops and I'm sure other sources.

So what? If you make a contraption to reap these benefits, so be it. You've invested time, thought and materials to get it.
You're still gated by technology.

**Comment by repo-alt** [comment]
redlon is a bit too cheap/early accessible, otherwise it is fine I think.

**Comment by DoomSquirter** [comment]
I keep on wondering why the hell do these kinds of issues still get created and gain traction.  don't we have actual problems to solve first or again, is there some time limit on these kinds of nerfing actions?  Like if we don't tackle this issue now, we forever lose our ability to change them later on?   it just seems that someone gets a hair up their ass and decides that hey, this needs to be nerfed without really any thought put into the greater context of a constantly changing pack.  

I don't have a problem discussing this and other things like it, but I'd rather discuss them together weighted against a currently balanced pack instead of individually every time someone feels the urge to vent.  

Would be nice if for each milestone someone made a master ticket of boost/nerf options on the table and ppl got a chance to vote on them all side by side, looking at the greater scheme of things instead of just an individual task.  if we can't come up with enough traction on one of the items either way, the task is put away till next milestone.  again, it gives you an ability to compare things since the pack itself is a moving target, subject to change.  

as for the issue at hand, redlon, cheap or not, there are multiple other options available other than just redlon.  I am of a firm belief that you have crops/bees and there should be a lesser but somewhat useful way to get infinite of a thing for ppl that don't want to do crops or bees.  it shouldn't be as well developed as bees/crops but having an option out there is still a good thing.

**Comment by richardhendricks** [comment]
Redlon is fine, as a crop. If the free duplication with fortune is removed, that's more than enough to balance it. 

To automate production using redlon requires significant infrastructure, and I don't see that as an issue at all.

**Comment by mitchej123** [comment]
Let's stop with the nerf suggestions without running the math.  "Plz nerf this" is not a valid ticket, a valid ticket would be an analysis of the available options, and support for why it's overpowered.  If you want it changed, it's on you to show why not "cuz I feelz like it"

**Comment by 0lafe** [comment]
>tier mats are renewable

Stainless takes a little more than that. You need Ni and Mn. This also doesn't stop it from being infinite, just means you need a little more of a setup for it. 

>To automate production using redlon requires significant infrastructure, and I don't see that as an issue at all.

You need a macerator, acentrifuge for Ruby, and maybe another for chrome depending how you do it. Then some way to break blocks. That's kind of nothing.

**Comment by richardhendricks** [comment]
> Then some way to break blocks
No, it's not nothing. These aren't cheap, and you need one for every potential redlon spot. Vs a harvester that can do a 11x11 field, or a Forestry farm.

**Comment by Scottishprog** [comment]
And do keep in mind, that redstone is only a minor step in things...
Once you have access, you go through a bunch of it. (OHH! a whole Three stacks! does not work here!)
One thing the nerf proposals don't seem to consider is the overall "drag" that a pack has.  If there are too many rabbit holes to advance, people will quit. It's a balancing act, which implies something other than jumping on one end only.
