### ISSUE TITLE
IC2 crops moveable

### ISSUE THREAD

**Issue by AlexBucket** [GTNewHorizons/NewHorizons#4906]
#### Which modpack version are you using?
2.0.7.5

#
#### If in multiplayer; On which server does this happen? 
ProsperCraft

#
#### What did you try to do, and what did you expect to happen?
Move planted IC2 crops with dislocation foci

#
#### What happened instead? (Attach screenshots if needed)
Crops were moved

#
#### What do you suggest instead/what changes do you propose?
Disable it from working

**Comment by CalterOK** [comment]
And why shouldn’t he bear the Crops?

**Comment by AlexBucket** [comment]
Because crops aren't supposed to be moved in this way.

**Comment by richardhendricks** [comment]
To clarify, part of the difficulty of raising crops is that as you get higher tier crops, the chances of getting a seed when you break the crop goes down with tier (and certain stats). 

Being able to transfer crops without that risk makes growing them much easier.

On the other hand, tiering up Thaumcraft to get the dislocation focus is a lot of work, so maybe being able to do crops easier is a fair reward.

**Comment by CalterOK** [comment]
You can also move them with teleposers from bloody magic.

**Comment by observeroftime02** [comment]
I have absolutely no issue with crops being moved at all. If anything, this further cements the role of Thaumcraft as something that is absolutely essential to work through for a lot of QoL stuff, as I've talked to quite a few players that completely leave this mod and others related to it by the wayside (I used to be one of them, until I really found out about the awesome utilities contained within).

I am not opposed to tiering it in a sensible manner however, whatever that would look like. Simple removal of something "too powerful" is just lame, and it seems gating it at the correct tier would make more sense to give someone a goal to strive for.

**Comment by repo-alt** [comment]
Seriously, if you have dislocation focus, I think you deserve to be able to move crops.

**Comment by ScriptedPiky** [comment]
If the Dislocation Focus is too "easy" to obtain compared to the level of power it can yield, crops in this case, then perhaps a recipe to increase the difficulty of the recipe is needed instead of removing something? This the current recipe by the way.
![ThaumFusion](https://user-images.githubusercontent.com/41557212/62511176-483f6580-b7c7-11e9-80aa-12c97350a8be.PNG)

So I present a new recipe to adjust the power accordingly. 
![ThaumFusion1](https://user-images.githubusercontent.com/41557212/62511523-0c0d0480-b7c9-11e9-9884-5ea463756fc2.PNG)
This is purely a recipe change. The essentia remains the same. Now it requires 2 Exquisite Ambers, 2 Diamonds, 1 Yellow Garnet, and 1 Red Garnet. 2 Nether Star Plates, 2 Nether Quartz Plates, 2 Quartz Plates, and 4 Vibrant Alloy Plates. I miiiiight've over nerfed this item just by the recipe alone. It is a concept that doesn't over tier it to EV (Titanium) but tiers it to a somewhat high-HV level of shenanigans. Thoughts? Over nerfed too hard? Adjustments?

**Comment by DoomSquirter** [comment]
dislocation is tangently useful for only a couple things here.  recipe change isn't going to affect much really.  I'm averse to crops but I say same thing as repo above.  if you have dislocation focus, you should be able to move crops.  

only thing is that recipe won't fit on my altar I don't think lol  

yeah I have 12 peds on my altar.  would have to add 4 more.  booooooo lol

**Comment by ScriptedPiky** [comment]
Ohhhh right, heh. That's a good issue at hand. Hmm, would a nerf actually be needed in this case? Since the Dislocation Focus has such a niche mechanic that is practically not going to change the game drastically. Moving crops is something I never even knew but can provide a nice way to properly move a special crop to somewhere to a breeding area of sorts. But that's about it. Moving spawners is doable with those Dolly's but it the focus doesn't take damage and uses vis instead.

But yeah, niche mechanics that don't impact or break the game, so now I realize that perhaps there is no need to nerf or remove it just because it can move a crop to a new location. I'd say that the effort going into Thaumcraft is more than enough to be rewarded

**Comment by richardhendricks** [comment]
Use the original recipe, except change the Ambers to 2xDiamond Dollies. Seems fair to me, since it would replace them, right?

**Comment by DoomSquirter** [comment]
I wouldn't put dollies in there.  to me, they don't replace dollies.  dollies are cheaper to make, have a durability and are separate so you can grab more than one spawner at a time.

**Comment by observeroftime02** [comment]
Diamond dollies require a not insignificant amount of nether stars. 2 are actually required, and to get those two plates, one needs to get 9 of them first to compress them into a block and then slice them up to get the plates. I did early nether star duping via null catalyst and and really does take time and effort. Would I say that's a bigger effort than getting the amber? Probably, though it might be easier for some people, while duping nether stars is easier for other people. If anything, using a single dolly in this recipe would actually be more expensive in a way, since it's 9 stars for 1 plate, instead of 9 for 2, meaning the commitment on this is deeper (now I have 7 or 8 other nether star plates that I don't have a use for). So, why not both?

**Comment by richardhendricks** [comment]
Dollies can only grab what, 2 spawners before breaking? So this is a significant upgrade to that. Can we change the "cost" to use it as well?  That might be another knob to balance with.

How dangerous is it to use this focus on eg Gregtech machines? Thaumcraft devices? Multiblocks? Onoe concern would be highlighting these and then they end up causing bugs.

**Comment by richardhendricks** [comment]
Ideally, we can set the cost per block type to move, in that case I would take ~75% of the vis from the wand tier you can make this at to move a crop. That would be base, so you can reduce it with all the various vis reduction items at your disposal. And as you tier up in wands, you can move more crops before needing a refill. 

I think that's pretty fair if we can do that.

**Comment by CalterOK** [comment]
So the focus itself raises the cost of vis 20 times if it is not an ordinary block that is mixed (chest, spawner, etc.). This greatly limits its use on low-level sticks. If the transfer of poles is also increased 20 times from that indicated on the knob then this will be enough.
