### ISSUE TITLE
Questline: Tier 2 Rocket and Tungstensteel

### ISSUE THREAD

**Issue by leglerm** [GTNewHorizons/NewHorizons#4917]
#### Which modpack version are you using?

2.0.7.5

#### What did you try to do, and what did you expect to happen?
For the T2 Heavy duty plates you now need molten Tungstensteel in the assembler however tungsten processing doesnt open up until you have been on mars for which you need the T2 rocket. 

#### What do you suggest instead/what changes do you propose?
adjust the questlines to get tungstensteel pre-Mars

**Comment by richardhendricks** [comment]
Tungsten is available from moonstone and lava centrifuging.

**Comment by boubou19** [comment]
endstone too iirc

**Comment by ScriptedPiky** [comment]
It is also available from Ender Goo (Hardcore Ender Expansion) with a 75% for a single small Tungstate dust from 1 bucket. However, finding them in large quantities is rather difficult because there are generally three types of generating sources. The small specks appearing out of the sphere, but not withinside. The covered sphere, but with nothing inside. And the normal sphere (small to large) but with the entire inside being filled with Ender Goo. Insides range roughly from 100-500(?) buckets per sphere and depending on size. Can be pumped via GT pump

**Comment by leglerm** [comment]
True and i know that especially since you only need 3 ingots for the t2 rocket. 
It is more that the questlines and descriptions dont match/open as expected. 
The quest for t2 plates also doesnt mention tungestensteel either (not sure when it was added into the recipe)

Right now its make t2 rocket (space race) - go to mars (in ev) - make tungstensteel. 
However the last step is required to even start with the t2 rocket. 

Maybe change it so the tungstensteel ingot quest comes before the rocket plates . There is allready a moon dust quest in place which could be used to open up the tungstensteel ingot.

**Comment by richardhendricks** [comment]
Okay that's fair.

**Comment by richardhendricks** [comment]
ok copied tungstensteel quest with just 3 ingots needed and placed after moon dust and HV centrifuge quests.
![image](https://user-images.githubusercontent.com/1214811/71536438-eea21980-28d4-11ea-889e-9b441b4b8f90.png)
![image](https://user-images.githubusercontent.com/1214811/71536443-f8c41800-28d4-11ea-86e5-c0216df48e97.png)
![image](https://user-images.githubusercontent.com/1214811/71536474-59535500-28d5-11ea-9a62-0b5a02e69cdf.png)
