### ISSUE TITLE
IV assembler quest inconsistency

### ISSUE THREAD

**Issue by leglerm** [GTNewHorizons/NewHorizons#4940]
#### Which modpack version are you using?
2.0.7.5
#

To make the t3 rocket to go to ceres you need an iv assembler for the heavy plates. However the iv assembler quest only opens up after the quantum processor which entire line depends on the t3 rocket as you need naquadah.

Change the quest requirement for the iv assembler to require "you gonna hate this 1-4 in IV" propably as it is supposed to be.

**Comment by AmberSherbet** [comment]
Similarly for the LuV quests, you must make the first 4 parts and you must make the LuV assembler in order to access the Tier 4 Rocket, but in order to unlock the quests for those you must visit the Tier 4 Planets. A solution would be to simply change the quest order so that the quest that requires you to go to the tier 4 planets is after the assembler.

**Comment by richardhendricks** [comment]
removed dependency on quantum processor for IV assembler
![image](https://user-images.githubusercontent.com/1214811/71500463-b7772e00-282a-11ea-8364-c4afdcce3a6f.png)

Looks like LuV line is already fixed? Not sure if anything needs changing here.
![image](https://user-images.githubusercontent.com/1214811/71500486-d37acf80-282a-11ea-8ee8-7fe516b2a008.png)
