### ISSUE TITLE
Malachite ore mining level

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/NewHorizons#495]
As of 1.0.7.6, Malachite ore requires iron mining level to mine.  This means you have to either make an iron gregtech hammer to smash the ore out, or construct a smeltery early to make a better tcon pick.

Since the copper quest seems meant to be completed early, perhaps malachite ore should be removed from the quest requirement, or the quest should be changed to simply detect copper ingots?  ProjectRed copper ore is all over the place anyway.

**Comment by Dream-Master** [comment]
Thanks for report i will look into it.

**Comment by Teteros** [comment]
>ProjectRed copper ore is all over the place anyway.

It's supposed to be disabled. The server you play on propably generated some land with the old (invalid) config. 
It's been fixed since, see https://github.com/GTNewHorizons/NewHorizons/commit/242be105e3587a4ff5e038dae3e75c4bfce70936.

>Since the copper quest seems meant to be completed early, perhaps malachite ore should be removed from the quest requirement, or the quest should be changed to simply detect copper ingots?

I think the whole idea of requiring malachite ore for that particular quest was to make the player aware how veins work in gregtech's ore generation. Malachite is found sporadically in the iron veins rather than copper, way deeper.

I'd also rather not have it mandatory to progress in the questline due to its rarity, which often enough is the main reason for stalling early on in HQM.

**Comment by Dream-Master** [comment]
I am sure you will find a pickaxe head in a village (copper) and upgrade it through mining and complete the Quest.

**Comment by Dream-Master** [comment]
I adding a Iron Pickaxe Head Quest btw so you not completly helpless.
