### ISSUE TITLE
Ar in W smelting instead of N2

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/NewHorizons#4954]
#### Which modpack version are you using?
2.0.7.w/e
#

#### What do you suggest instead/what changes do you propose?

W smelting uses N2, which is a weird choice for IV. The production of the gas is extremly simple by that point. You are able to make an extreme excess of N2 even in EV, using it as an IV gas is quite silly. Ar is craftable in HV, with all needed parts being almost free themselves in IV. The production of the gas will take about 1.5M EU if you use EV vacs and 750k with HV vacs. The EU saved on W smelting is 4M, so it still acts as a bonus to use, but gives the bonus a better IV spot than N2. 

For comparison, N2 costs around 14k to make with vacs, netting you additional outputs of O2 and Ar. It costs less EU if you make it without a vac. For comparison in IV, this means the production of multi thousand L/t of N2 is entirely reasonable. W at 4A IV would use an astounding 1.6L/t of gas. 

Overall it rewards you doing something that's almost IV, instead of essentially only having a 500s recipe.

**Comment by mitchej123** [comment]
I'd be fine with swapping with Ar if we decreased the time.  For the current difference, I think N2 is fine.

**Comment by observeroftime02** [comment]
Argon is more expensive to create than nitrogen, obviously. If that increase in difficulty for the gas was offset by a shorter smelt to keep the overall power of the process the same, I would not be opposed to it. Otherwise this will just make tungsten as a whole more difficult overall.

**Comment by 0lafe** [comment]
The increase in time/power for Ar is almost unnoticeable when ran in parallel, and really not there when running something like liquid air. The difference in EU comes out to ~20s of the smelt. Reducing the time with Ar to 480s seems fine, but I wouldn't say it's needed.

**Comment by observeroftime02** [comment]
Also, Bart is coming out with a few new gasses (such as neon, xenon and krypton, not the GT++ krypton) that could be considered depending on the final processing chain involved in their acquisition. Actual liquid air distillation yielding realistic amounts of constituent ingredients is going to be a thing, as opposed to simply centrifuging it that could make things more fun. Nitrogen and oxygen are going to be more easily obtainable, and this is going to include argon as well. 100k L of air are going to be distilled at once, and then the output matches that of the atmospheric composition. Not sure how this will ultimately affect this, because liquid air in such volumes is not easily obtainable yet (sure, you can compress and vac air cells, but that's going to take a long time for that amount).

Lets see.

**Comment by draknyte1** [comment]
> krypton, not the GT++ krypton

But mines `krypton` as much as Steam is `steam`. 
Barts wouldn’t be krypton nor would GT utilise it, if it were, then only one will register and the one which is will be used by all mods.

**Comment by observeroftime02** [comment]
Well yes, I made that differentiation to point out that there is another Krypton.

![image](https://user-images.githubusercontent.com/43228249/64068762-76ab3780-cbf1-11e9-9486-d8907364aa99.png)

![image](https://user-images.githubusercontent.com/43228249/64068763-83c82680-cbf1-11e9-972a-b1a9adc12c40.png)

**Comment by draknyte1** [comment]
That’s no different two four copper ingots from four mods. 
They’re equal so far as Forge cares. `cellKrypton` is the same regardless. Barts couldn’t be tagged as such and therefore wouldn’t be Kypton so far as anything else cares. Barts kinda in a tight spot as I already add every element in some capacity upto Pu, minimum. I’ve generated and oredicted the items already and GT already considers them default.
