### ISSUE TITLE
All GT++ Multiblocks don't need core module

### ISSUE THREAD

**Issue by Kiwi233** [GTNewHorizons/NewHorizons#4984]
#### Which modpack version are you using?

#2.0.7.5

![GT++](https://user-images.githubusercontent.com/42833050/64482729-f6588800-d229-11e9-9e11-9ff2465f79b1.jpg)

I test these GT++ Multiblocks, all of them don't need core module, some of them with core module will show "incomplete structure"(Ore Washer, Thermal Centrifuge, Amazon Prime, Energy Station).
[https://github.com/GTNewHorizons/NewHorizons/issues/4877](url)

Did GT++ cancel the core module?

**Comment by noobyaran9** [comment]
> Did GT++ cancel the core module?

Yes

**Comment by ScriptedPiky** [comment]
Posting this here as well from the other GT++ thread.
This was intentional as multiblocks do not need cores after a certain point in GTNH's version history (post v6.2+?). This was done due to various complaints about it when the cores were first introduced and were made optional in the config file of GT++ (or were hardcoded to be off).

**Comment by observeroftime02** [comment]
You can enable them in the GT++ config again if you wish I believe, though I am not sure which particular option that would be.
