### ISSUE TITLE
Vacume Freezer NEI Interface

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#5042]
The NEI interface should have amperage be unspecified because otherwise it looks like you can't use the same multi hatch overclocking system that the ebf follows.

This has made multiple player think they can't advance into EV.

**Comment by dvdmandt** [comment]
To clarify, the EBF lists both amperage and voltage as unspecified and only list usage. Other multiblocks lists voltage and amperage even though they behave like the EBF. This made me think the EBF was a special case and that the others need to have hatches accepting the listed voltage, which is apparently not the case.

For progression, the primary point of confusion is probably the vacuum freezer, which needs two HV hatches to be able to cool the first tungstensteel ingots you make, which can then be used to make EV hatches. But this seems to apply to more GT multiblocks, such as the LCR and perhaps the DT? If so, the recipe presentations should ideally be standardized to follow the EBF format.

**Comment by sthegreat** [comment]
I think all multis should have the voltage and amperage requirements removed in nei in favor of lines for required voltage *tier*, e.g. LV or MV, and total usage measured in eu/t. The current system is very misleading and not really based in the way GT voltage actually works. It's not just the ebf and freezer -- all regular multis which can accept multiple energy hatches work like that (with the exception gt++ behaving a bit differently due to only accepting 1a per hatch).

**Comment by Dream-Master** [comment]
i can set "showAmperageInNEI" to false if this help

**Comment by Dream-Master** [comment]
if not i reverse it

@Anarack 
@dvdmandt 
@sthegreat
