### ISSUE TITLE
Xenoxene liquid uncraftable

### ISSUE THREAD

**Issue by Josh5minus1** [GTNewHorizons/NewHorizons#5049]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
SSP
#
#### What did you try to do, and what did you expect to happen?
Use NEI
#
#### What happened instead? (Attach screenshots if needed)
The xenoxene requires bacterial vat that needs the xenoxene culture in a dish, which shows no recipe. Xenoxene is required to make raw radox which can be distilled, then some of the outputs can be used to convert 1 naquadah -> 3 Enriched Naquadah -> 9 Naquadria.
#
#### What do you suggest instead/what changes do you propose?
Add recipe for making the xenoxene culture in the dish.

**Comment by bartimaeusnek** [comment]
There is a recipe, its just now shown in NEI jet, due to the pure complexity of the breeding/modifying of bacteria. 
To actually craft the Xenoxene Culture:
1. Get a Petri Dish of "Barnadafis Arboriatoris" (Barnada Logs in the BioLab)
2. Get a Petri Dish of "TCetiEis Fucus Serratus" (TCetiE Seaweed in the BioLab)
3. Duplicate the Petri Dishes or just make a few of them.
4. Get the Plasmid of the "Barnadafis Arboriatoris" Bacteria. 
(Extract the DNA with the DNA Extraction Module; 
![2019-10-10_13 57 59](https://user-images.githubusercontent.com/33183715/66566793-20250780-eb66-11e9-975a-82bedf065670.png)
then use the PCR Thermocycle Module to the DNA into a Data Orb;
![2019-10-10_13 58 10](https://user-images.githubusercontent.com/33183715/66566966-86118f00-eb66-11e9-8271-b6149da44ffe.png)
Then use the Plasmid Syntheses Module to Synthesize it, you need eColi Bacteria for this step aswell;
![2019-10-10_14 02 30](https://user-images.githubusercontent.com/33183715/66567024-a5a8b780-eb66-11e9-861e-a7dbb1fca9c7.png)
)
5. After you have Obtained the Plasmid, you can inject the "Barnadafis Arboriatoris" Plasmid into the 
"TCetiEis Fucus Serratus" Bacteria with the Transformation Module:
![2019-10-10_14 03 59](https://user-images.githubusercontent.com/33183715/66567184-f5877e80-eb66-11e9-9bab-8be10d52c353.png)


For more Information about Development or Questions join the BartWorks discord and contact me either directly in the voice chat or request writing permissions from me in any of the OffTopic channels.
https://discord.gg/jFvhQD6

**Comment by Josh5minus1** [comment]
Ok, thanks!

**Comment by Josh5minus1** [comment]
Help! When I try to do the instructions above, the output is just the TCetiE culture. Is there a chance to output the xenoxene xenoxis? Or maybe im doing it wrong?

**Comment by Prometheus0000** [comment]
@bartimaeusnek Did you change the eColi to beta-Lactase? And the fluid to Liquid DNA? Because that worked for me to create the plasmid. And it's what NEI says.

**Comment by Prometheus0000** [comment]
There's a quest for it now if you have trouble.
