### ISSUE TITLE
Questbook the 4th quest "Crafting time" pick one...only one choice

### ISSUE THREAD

**Issue by ProsperCraft** [GTNewHorizons/NewHorizons#505]
It says to pick one after you make the crafting table, but there is only one to choose from.

**Comment by Teteros** [comment]
Can you clarify? There seems to be two branching quests: "Easy Crafting" and "Storage for days".
![<HQM image>](https://cloud.githubusercontent.com/assets/5067989/13589669/7ce3ceba-e4d1-11e5-8d3e-57cff696dcc3.png)

Although, the bottom one: "Easy Crafting" needs to be removed because the translocator crafting grid was disabled since.

**Comment by ProsperCraft** [comment]
Crafting time is a quest...in the REWARD it asks you to chose one, but there is only one to choose from.

**Comment by Namikon** [comment]
The branched table is removed in the latest HQM file. 

For the single choice reward, I assume I also fixed that while redoing the entire lootbag system; But it might be a minor derp. I'm sure there are more issues like this one, as the number of quests increased by 250% compared to the last version. We'll see, iirc the quests have been released just a couple hours ago

**Comment by Dream-Master** [comment]
fixed.
