### ISSUE TITLE
GalaxySpace 1.10+

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#510]
You may or may not know the modpack is currently using GalaxySpace **2.6 Beta**.
Since then, the mod was rewritten and released with many releases starting from 1.0.0.

Updating to this new, _stable_ version of GalaxySpace is not straightforward. Many current recipes we have from 2.6 will need to be reconsidered and written from scratch as known features/planets are added and removed between the two versions. For example, we are not sure when rocket tiers and moons such as [Callisto](http://forum.micdoodle8.com/index.php?threads/1-7-10-galaxy-space-stable.5298/page-19#post-40154) will be reimplemented into the stable 1.0.0+ GalaxySpace releases.

As a result, future of GalaxySpace in the modpack is unknown.
Currently we need to fix known problems with 2.6beta and observe the development of newer GalaxySpace.
Update will come when the time is right.

**Comment by Dream-Master** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2412548-1-7-10-galaxy-space-addon-for-galacticraft-3?comment=205

**Comment by Dream-Master** [comment]
Ok the new Version GS 1.0.8 works.

After The Mod Author change so much and remove so much items i will replace the Nasa Workbench with the Avaritia Table for Crafting the Rockets, Moon Buggy etc.

We can using most of the old recipe and change them a bit we have too.
Since no one can add Modtweaker support for GC or GS NASA Workbench i see no chance to change recipe her. With Avaritia i have all the Freedom of recipe maing i need.

**Comment by Teteros** [comment]
Who knows, maybe it might not be too hard to add fluid and/or thaumcraft aspect support to that table.

Then filled things like rockets (if not fuel loaded) and TC wands/items could be crafted within.

**Comment by Dream-Master** [comment]
Roadmap to update to GS 1.0.8

x [ ]

**Comment by Dream-Master** [comment]
I think the crash have somethig to do with the Biome IDs

**Comment by McFrugal** [comment]
The crash is probably because the current Biome IDs conflict already.  If you try to use the same Biome IDs they will continue to conflict, and it sounds like there's new error checking code for that.  If not that, then maybe new code that crashes when the conflict happens, instead of working despite it.

The IDs have to change.

**Comment by Dream-Master** [comment]
fresh installed game with only gs and gc no other mods crash too.
I will wait for the fix in 1.0.9 and test again.
Hopfully BlesseNtumbe fix ite Biome ID cant be set.

**Comment by Dream-Master** [comment]
We not have a 1.0.9 Version. Hope we get it soon.

**Comment by Dream-Master** [comment]
1.0.9 have the same error when start a new game.

**Comment by Dream-Master** [comment]
Have to try if solved with 1.10.

**Comment by Dream-Master** [comment]
OK now it works have to change a lot of Content.

**Comment by Dream-Master** [comment]
Open up a new Issue for it.
