### ISSUE TITLE
Experimental Deep Earth Drilling Platform MKI not forming

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/NewHorizons#5165]
#### Which modpack version are you using?
2.0.8.0.b
#
#### What did you try to do, and what did you expect to happen?
Build the Experimental Deep Earth Drilling Platform MKI and it is not forming.

Side question : What is this multiblock supposed to do ?

**Comment by richardhendricks** [comment]
It's the GT++ void miner, AFAIK. It's not completed yet.

**Comment by draknyte1** [comment]
It works, it’s intentionally disabled.

**Comment by botn365** [comment]
if we want it to be enabled we have to provide a table what it should make in each dim 

![afbeelding](https://user-images.githubusercontent.com/42187820/70464769-d7cf8a80-1abf-11ea-8a4b-7546e15f7263.png)

**Comment by Dream-Master** [comment]
@Alexdoru why you close this issue?

**Comment by Alexdoru** [comment]
I closed it because now I know that the multiblock does not form because it is intentionnally disable. And that if we want it to be enabled we have to provide a table of oregen

**Comment by Dream-Master** [comment]
@Alexdoru suggest the ores and let it open so long it is enabled

**Comment by Alexdoru** [comment]
I made another post for this purpose #5166
But thing is I can't really do more than the post I did considering I know nothing about coding in java and I don't know how the ore generation works with the different mods in the game

**Comment by draknyte1** [comment]
I think @botn365 is going to prepare the entire list as code for it to be inserted into the core mod. 

Ore, dirt and stone types should be provided for every dimension (dimensions are mapped by ID at this point, but I’m open to suggestions), so that planet stones and stuff can also be mined. Also means everything is dimension locked, plus bonus ores can be added Per dimension as an incentive for using the lag free miner ;)
