### ISSUE TITLE
HQM quests issue.

### ISSUE THREAD

**Issue by Technus** [GTNewHorizons/NewHorizons#528]
Due to last Quest line changes redoing all quests require recrafting all the stuff.

Even if machines are available to do the crafting, to complete the quests it is required that the player do it in a crafting table (preferably in vanilla one without shift clicking).

Suggestion Change Crafting quests to detect Quests.

(From what i know it should be done already unless it was ommited.)

**Comment by Teteros** [comment]
It's the early game quests that still have the crafting tasks I believe.
Supposedly later quests don't have it anymore, but @Namikon can confirm when available.

**Comment by deeplyarnab** [comment]
Well, i did suggest it before too. I think there should be a repo to manage quests, will help reduce task, make it pull req only so that nami will be able to merge the changes.

**Comment by Namikon** [comment]
HQM uses a binary blob to store the quest data, and the json im-/export is not an option either as its just not functional and reliable enough to work with. That's the reason why there is no repository for it, and why there is a timecode at the initial HQM page. The only way to keep consistency to that is to have one dedicated person taking care of the file. 

Due to the fact that HQM is likely to cause resets, I'm accumulating bug reports and try to keep the amount of updates at a minimum

**Comment by Dream-Master** [comment]
I guess nothing we can do against it, only not updating the Quest file any more.
