### ISSUE TITLE
More random quest suggestions

### ISSUE THREAD

**Issue by Bluebine** [GTNewHorizons/NewHorizons#5338]
#### Which modpack version are you using?
2.0.8.1

I've assembled (yet another) list of random minor quest things that annoyed me and other people, and have changes to suggest about the quests.

- [x] Division Sigil quest shouldn't require golden lasso "Gotta catch em all" quest in LV (1101 requires 117)
- [x] LV Chem Reactor should be doable after Welcome to Tier 2 (543) CHANGED TO NEED STEAM-A-LICOUS #70
- [x] LV Centrifuge should be doable after Welcome to Tier 2 (539) CHANGED TO NEED STEAM-A-LICOUS #70
- [x] Dire Table shouldn't be a prereq to start making rocket parts (812 and 823 shouldn't require 809)
- [x] Add some suggestions to the initial LV quest- start with wiremill and bender to make everything else cheaper (88)
- [x] LV Macerator should not be main quest, not required (94)
- [x] LV Extruder should not be main quest, not required or even very useful (673)
- [x] All of the GC oxygen gear and rocket component quests shouldn't require ingredients- you can get them from lootbags too (817, 824, 822, 823, 830, 818, 816, 819) LEFT MOON LANDER ALONE
- [x] Rocket fuel quest should need 1 canister instead of 8- no need to craft that many (827)
- [x] TC Greatwood wand shouldn't need the stainless quest- it only needs 1 stainless, vs 64 for stainless quest (235) CHANGED TO "Are you prepared for HV?"
- [x] Monocrystalline silicon shouldn't be locked behind clay electrolyzation (760)
- [x] Thaumium Fortress armor quest should be gated behind infusion, not thaumium wand caps (290)
- [x] Mob killing quests shouldn't be required (10 should be optional, 12 should be replaced with wool retrieval instead of killing sheep)
- [x] Silicon plate quest is pointless and should be removed (752) NOT GOING TO DELETE QUEST
- [x] Quests for circuit components shouldn't have their own components as a requirement (835, 66, 834, 747, 785, 1019) NOT GOING TO CHANGE, CIRCUITS ARE COMPLEX FOR NEW PLAYERS TO UNDERSTAND, SO THEY SHOULD GET THE COMPONENTS.
- [x] Add separate tab "tips and tricks", near the top of the questbook, with all the "basic information" quests that don't have rewards (quests 1500, 1834, 1501, 2145, 1495, 1496, 1497, 1498, and my next suggestion). Would be good to add a lot of the "accepted wisdom" shared in the discord, and basic info newbies might not know, like making stuff in big batches and that machines explode in the rain.
- [x] Add quest mentioning F3+H to show quest IDs

**Comment by chochem** [comment]
As someone who also just played through the early tabs again, I mostly agree with the suggestions. In particular, I like the idea of a Tips & Tricks Tab to collect lots of the early game text blocks!

Only exception is (88), as imo a bender really isnt that important compared to e.g. the chem reactor. but it really depends on your resources, so we shouldnt railroad the players to hard here.


Also, let me add a few suggestions of my own:

[ ] Enchanted Fabric Quest (1995) should ask for 18, not 16, as 18 are needed in the follow up quest.

[ ] LV Battery Buffer 9 Slots (664). Quest should be not a main quest, fully optional (or even just removed) and not required for arc furnace (662) which should just be based on the 4 slot battery buffer (619). 9 Slots is nonsense for arc furnace and noob trap for EBF due to power loss in LV (even though it is possible to use it there).

[ ] Soularium and Soul Vials (166, 168) are available in MV and should probably be moved there (from HV). They are important as a defensive mechanic and to catch (regen) enderman. Although 168 would need to be reformulated.

[ ] EBF Quests (77, 1853). The main problem all new players have with the EBF seems to be power. The one line in (77) doesn't really help much. So best to expand on that topic in the guide (1853). Power loss is really the killer of many new players EBF. Basically: either power directly 2A to each energy hatch with a single 2A cable each or use 2 battery buffers with 2 batteries each directly attached to the energy hatch.

**Comment by richardhendricks** [comment]
- [ ] Wrought iron quest should be mainline and made larger.

**Comment by richardhendricks** [comment]
- [ ] Look at simple automation quest and build 10 coke ovens quest. Setup quest so that players can decide which automation route to use. Also, look at stacking coke ovens vertically?

**Comment by richardhendricks** [comment]
- [ ] Look at how unlocking legendary tab works, maybe change from 1 ore, or document in the tab info what's needed.

**Comment by richardhendricks** [comment]
- [ ] add a mandatory quest that says "quest IDs are now locked behind advanced tooltips, aka F3-H"

**Comment by richardhendricks** [comment]
- [ ] Bonsai quests - how hard are they locked out now? Should make them easier. Maybe after the first coke oven.
