### ISSUE TITLE
Nightvision Goggles recipe broken

### ISSUE THREAD

**Issue by malianx** [GTNewHorizons/NewHorizons#5440]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
private
#
#### What did you try to do, and what did you expect to happen?
Craft Nightvision Goggles
#
#### What happened instead? (Attach screenshots if needed)
Recipe does not function, tried both ticon grid and vanilla.
#

**Comment by Methes** [comment]
Would be nice to also change their nightvision effect to the same as the regular enchantment (like the helm enchant, Dark Armor enchant, potion effect and adventurer's backpack) because right now the goggles are a lot worse. The colors are a bit off iirc but also the daylight blinding effect is annoying. Was excited the other day to improve my nano helm and found out how useless they are.

**Comment by mrTeroblaze** [comment]
Have you checked EVERY item in the recipe? Becouse there is stainless steel BOLT and SCREW.

**Comment by chochem** [comment]
The recipe works. Nothing else to say.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/73138649-8fffc500-4065-11ea-8842-ac9acde67110.png)
use a screw and a bolt will work

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/73138663-aad23980-4065-11ea-99d7-d2cda20c1015.png)
