### ISSUE TITLE
Better documentation for Thaumcraft Progression

### ISSUE THREAD

**Issue by Goofyschooler** [GTNewHorizons/NewHorizons#554]
Create A book with pictures showing all Valid recipes to the Wands, as trying to find the correct recipes is very difficult and tedious to do.

**Comment by Teteros** [comment]
Yep that's why [Enchiridion2](https://mods.curse.com/mc-mods/minecraft/enchiridion) is in the pack, we just need content makers.

**It's planned.** General documentation for blocks/items that really need it will be in the ingame minecraftopedia ('h' menu by default) and I'm thinking _strategy_ or _tips and tricks_ type of info will be **hidden knowlege** contained in books. Such knowledge that would require a significant time investment from the player (best nuclear designs? step by step large turbine multiblock builds? [TC essentia pipe systems](https://imgur.com/a/Kfnac)?) would be within such special tomes as a... choice of a quest reward perhaps?

There's a thing going on in some questlines where you have someone assigning you a quest, with the whole reputation system.

As well as via TC research in some tab, similar to Thaumcraft Machina "Concepts" possibly.

The priorities at the moment are mostly balancing and adapting mods' recipes not yet changed, the often used 'gregifying' term comes to mind. Still, documentation shall not get neglected much longer, I hope.

**Comment by Goofyschooler** [comment]
Ohokay I understand, do you (or anyone else) have the correct Recipes for the Wands. I can go into Single player and add them and send you (or DreammasterXXL ) the scripts.

**Comment by Dream-Master** [comment]
any news here ? Prospercraft Drop GTNH Pack.

**Comment by Dream-Master** [comment]
@Goofyschooler any new or ideas here?

**Comment by Dream-Master** [comment]
@Goofyschooler any new or ideas here?

**Comment by Dream-Master** [comment]
Basic and Greatwood wand very good covered up in Quests. Maybe i add some more advanced Wand Quests later.
