### ISSUE TITLE
redstone alloy weak exploit

### ISSUE THREAD

**Issue by PoptartOverlord-Xabedo** [GTNewHorizons/NewHorizons#5560]
#### Which modpack version are you using?
epsilon live

#### What happened instead? (Attach screenshots if needed)

![image](https://user-images.githubusercontent.com/40670872/74181526-2af1c500-4c4a-11ea-9528-7d8b38e84015.png)

#### What do you suggest instead/what changes do you propose?
keep the mixer recipe as is, instead change centrifuge to only give 3 redstone back
this will make an alternative cheaper way to make the alloy besides alloy smelter, to reward those who explore nei, it wont actually matter though as redstone is already hella cheap after you find your first vein or dirt cheap once you make any other form of farming redstone

alternatively you could go the easier route and just patch it up by making mixer require 4, your choice

**Comment by Prometheus0000** [comment]
Isn't the idea that mixer recipes are supposed to be cheaper compared to hand done ones? Or in this case, the alloy smelter vs grinding copper into dust, mixing it, then resmelting it. I think the centrifuge one should be reduced instead of increasing the mixer one. And I certainly don't think that redstone is 'dirt cheap' considering that you have to use red alloy a ton in LV and MV circuits.
