### ISSUE TITLE
Apiarist Database 

### ISSUE THREAD

**Issue by Alexusmaster** [GTNewHorizons/NewHorizons#5668]
v. 2.0.8.3

Delta server

Trying to craft the Apiarist database at the Carpenter. It accepts all the materials except the Beealyzer and such can't complete the recipe and can't craft the item. Same for the Treealyzer.

![Capture](https://user-images.githubusercontent.com/61656706/75627469-106f9380-5bd9-11ea-9ffd-6a014f7f43b6.PNG)

Please fix, also because of this I can't continue questline.

**Comment by dragagon** [comment]
I had that happen. had to craft a fresh one and not right-click it before putting it in the carpenter.

**Comment by boubou19** [comment]
could be cool if we had a way to "clean" the nbt like a shapeless recipe that takes in entry the beealyzer/treealyzer already used and give in output the "cleaned" beealyzer/treealyzer

**Comment by Dream-Master** [comment]
I can add  recipe to clean nbt.

**Comment by leagris** [comment]
I did not test it, but if you remove everything from the alyzer (bees and honey drops, it shall be exempt from NBT. If not, then this can probably be fixed, either making it so that the alyzer becomes NBT-less once you remove everything from its internal inventory, or fix the carpenter, so that it ignores the NBTTagCompond, but in this case it could cause loss of the alyzer's content.

To make some progress, can you please post here the output of:
- `/mt hand` on freshly crafted beealyzer
- `/mt hand` on a used beealyzer with content removed

**Comment by boubou19** [comment]
it did not worked to remove all the items in it. i'll post the result of the /mt hand as soon as i'll boot my instance tomorow

**Comment by Ngar1** [comment]
a new build bealyser work, but if you have had somthing in it - and also if cleaned, it woudn work in this receipt. Easy solution: build a new one.
