### ISSUE TITLE
Chaos Islands

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#576]
Did anyone find a Chaos Islands in the End. I read that this Island is generated in the empty space of the End. We have asteroids in the End and HEE Island so i am not sure the Island is generated.

@Drobac 
@Technus

**Comment by Technus** [comment]
De world gen : every 10 000 blocks (grid pattern) from 0,0

**Comment by Dream-Master** [comment]
@Technus Did you find some?

And did anyone find a Ender Comet?

**Comment by Technus** [comment]
Yes.

Ender comet , you mean sphalerite / stardust sphalerite? Yes.

**Comment by Dream-Master** [comment]
No the Comets have a lot of Draconium it. Maybe have Gt Ore too not sure about it.

http://ftbwiki.org/Ender_Comet

And the Caos Isalnd

http://ftbwiki.org/Chaos_Island

**Comment by SanMan911** [comment]
Well, Idk if this helps, but yeah, I saw the Chaos Dragon in The End dimension, although in single player (creative), but then again, it might help because the pack is the same, be it sp or multiplayer. And it was a random seed, if that counts.
I was trying out the epic Avaritia sword, and expectedly it one-hits the chaos dragon as well since it has infinite attack damage.

Coming to your question about Comets... Tbh, I didn't see any comets, not even above the Chaos dragon, where I normally get my Draconium from. All it had, were islands with some pink (harmful) liquid falling off into the void. There were a tonne of different kinds of ores, but I didn't find draconium. Not even in one of the end 'dungeon', which housed around 5  (definitely more. I removed 5, and yet they were spawning in huge swaths) endermen spawners, but the loot didn't have any draconium either. I did find 2 different music discs in there from a different mod, but was unable to play it using the JukeBox - it kept giving an error and kept ejecting the CD out before it even went in.

**Comment by deeplyarnab** [comment]
If draconic ore is rare (or not spawning) then we can make n use a high tier recipe to allow it to be made.

**Comment by SanMan911** [comment]
Confirmed:
Comet [sighting](http://prntscr.com/b1ay2f)
Although I reckon the spawn rate is very, if not extremely, low.

**Comment by Dream-Master** [comment]
Gt Draconium ore will be soon available. I will disabled Draconium from DE.

**Comment by Dream-Master** [comment]
Ok for Draconium Ore Mix i will open up a new Issue.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/606
