### ISSUE TITLE
Plugin Request for EU server

### ISSUE THREAD

**Issue by SanMan911** [GTNewHorizons/NewHorizons#602]
I was wondering if you could add the teleport plugin and/or the towny plugin to your EU server. Teaming up/Basing up with friends, both new and old, is to have fun playing and helping each other. It really feels bad to see oneself helpless in situations like where your friend is in some other dimension, and dying repetitively or is in a dying loop.
Furthermore, since after respawning, the hunger bar is reset to half, it really makes it extremely difficult to walk/run for those 500+ blocks without any food, tools, armour or help from friends to cover or escort...
You could have some rules like in your US server, about ranking up vs available commands, to give some 'incentive' to aggressive gamers, but then again, it's your call... This is just a suggestion :))

**Comment by SanMan911** [comment]
Apart from the towny, teleport & economy plugin, one more plugin I'd really like to suggest, would be the PEx plugin [Permissions Ex] for helping with the ranking system.
Should the need arise, I'd be available to help configure it :)

**Comment by Namikon** [comment]
PEX was heavily broken back in the days when i tried to use it. Since we've switched to Cauldron, we're using Essentials/GroupManager, and it runs perfectly fine; So far, there is little that you can't do with it.
In fact, I was already playing with some sort of donation system, (And the different usergroups, aka. "Ranks") but since the Minecraft EULA forbids these systems, and due to the fact that this server is being operated in Germany, I'm still debating what I can give to people willing to donate without violating any law.
As for economy; Vault is available and running. However: All commands for teleportation, "/home" and stuff for kits, and everything related to "ingame currency" are disabled intentionally.
As for regions, there is WorldGuard running, and we're heavily relating on that one.
MyTown2 was about to be added, but there was some internal reasons to not do it; Mostly related to people/mods being to busy to learn to use/manage it. But it was configured and almost ready-to-use. It's not as complex as Towny, but it comes with an (almost) perfect Anti-Grief System for Forge mods.

So far, the plugins we have are selected and configured to work with each other.
We can of course talk about changes, but it's not as easy as dropping in a new mod.

**Comment by SanMan911** [comment]
Yeah, like, after all, all that we guys CAN do, is only suggest things...
I don't know if the rules are or are not AS strict in America, but your US server DOES have something akin to ranking vs In Game currency vis a vis donations, so thought to drop in a word.
About commands being intentionally disabled, with all due respect, I don't see any valid reason there (except of course, if they clash with something else), because like I said earlier, I feel that MC is more enjoyable when you can actually play with your friends and help them in times of need. We were even mulling about 'charging' something for it. Although it might be taking things too far, but it's whatever... I'm here only to help in my capacity (I was playing in your US server before this, and hence I keep referencing or 'relying' on it).
Last but not the least, the towny mod. I just thought that having a grief protection plugin would've only comparatively reduced your guys' work by stopping the trolls, etc from griefing in the first place, rather than them letting grief and then either risking loosing out the victims (and of course the perpetrators), or risking increasing your work because of complaints/"issues" on the forums.
But like I said earlier, obviously, it's your call ;)

**Comment by SanMan911** [comment]
BUMP!
Any updates,  @Namikon & @Dream-Master ?

**Comment by Dream-Master** [comment]
Plugins i cant say much about it. Will ask Namikon.

**Comment by Technus** [comment]
Closing since batter communication channel is available
