### ISSUE TITLE
Make Draconium Ore Mix on Mars Moons Phobos and Deimos

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#606]
If we can update to Galaxy Space 1.0.X we can Ore Mix of Draconium to extraterrestrial Planets like Alpha Centauri or so and disabled the Draconium Ore in the Nether and in the End.

**Comment by SanMan911** [comment]
Alternatively, making an HV(+) recipe for it might also be made available...  as an 'incentive' for people who really have gone through a lot of (extra) grind, maybe?
The dragons could be made available in ET planets and disabled from the End so that no one can just 'rush' through to the end in the beginning of the pack or as soon as the End dimension is reset... And since the ritual of draconic resurrection requires a tonne of draconium ingots, not everyone would be able to spawn the dragon every now and then.
Besides, it will make a player kill the dragon first before even getting some draconium, which would be kinda interesting. Lastly, of possible, the number of original dragons could keep on increasing with planets farther away, so, for instance, the Moon could have 1, Mars, 2, Asteroids, 3 and so on, or Moon & Mars 1, Asteroids and Phobos 2, or something like that. It will also make things more challenging. However, at no point, should there be a chaos guardian, except for in The End :P

**Comment by Dream-Master** [comment]
The Dragon spawn i cant change but i can change the Draconium Processing. You need allready a EBF Tier 3 (5000K) for the Ingots so maybe we let the Ores in the Nether/End or maybe on some Tier 2/3 Planets which havent yet any reason to fly to it. (Phobos/Deimos).

**Comment by SanMan911** [comment]
I see... Hmmm.... Well then, yeah, I guess we could keep it in the Nether and Tier 2/3 planets, because nether itself is infernal enough for anyone to even TRY mining anything out; and the advancing on the ET planets would look something cool. Also, it might be made that ore spawn on Phobos/Diemos could be bumped up a little so as to provide an incentive for coming this high up [Pun intended :P]

**Comment by Dream-Master** [comment]
Ok i will let Draconic Ore in the End Dimension and add it to the Mars Moons Deimos and Phobos to give you a reason to visit this planets.
Will be in the next Version 1.0.8.6.
