### ISSUE TITLE
Switching Crafting Quests to Retrieval Quests [Suggestion]

### ISSUE THREAD

**Issue by Nenluen** [GTNewHorizons/NewHorizons#619]
Hello guys as a suggestion a lot of Crafting quests would work better as retrieval quests, meaning that the player only has to have the item in question instead of crafting them in a very specific way.

There are a few benefits, one being that should something happen to the quest history, advanced players can pick up their old machines again, to check off previously completed quests.  Another, that should a player get lucky, say finding a village with a smeltry, then they don't have to go through making all of the seared bricks, when they could very well already have more than they need for the quest.  The third is that it could stimulate a server's economy, with some players offering to sell some machines for progression, or to catch new players up, this point is a double edged sword, in that some could 'buy' their way through progression, but on older servers, that could be an option or a draw.

I think some of the quests very early on are fine for 'crafting', like the "It Begins" tier, which introduces players into the new recipe formats and new ways of doing the very basics of Minecraft.  But beyond that, just 'retrieval' for the finished product for quests, or putting some parts as optional, might work better from a player perspective.

For Example:
Coke Oven:  
Retrieval Quest: 26 Coke Oven Bricks (1082:7) 
Optional: Retrieval: 104 Unfired Coke Oven Brick (7393) 
Optional: Retrieval: 104 Coke Oven Brick (7521)

**Comment by Namikon** [comment]
While this being a valid suggestion, and I can understand the reason for it, for some items it's just impossible. We are using the quests to tier the pack a bit more than it would be possible with just recipes and GregTech. As for "just skip the progression" and "boost the server's economy, this is exactly what we're trying to prevent here. You are supposed to do it yourself, at least at the beginning. 
People were running around to find villages and loot the items/smeltery blocks instead of doing it themself. Also: We're already working on another progression system which will prevent you from using/placing machines that you are not yet meant to have.
I can fully understand the problem with quest-resets, but those will be gone in the near future, as this is something people are working on for quite a time now. In fact, even the switch from HQM to BQM was due to this problem.

Anyways, making a few things a bit more "optional" seems to be a valid request. Most quests should be configured to "detect" already; But we'll probably verify this once the conversion to BQM is completed and all bugs are fixed there.

**Comment by Nenluen** [comment]
I would caution against forcing players down a set path. Having a path that they can follow if they choose is fantastic, but demanding that they follow a single path that isolates them from the rest of the community I think will only frustrate players, when the objective should be to challenge them.

Removing progression items (such as village smelteries/tinker shops) from world generation, would eliminate the desire for players to scrounge for those progression items, but still allow for player interactivity, such as trading or towns choosing to specialize in one field.

For example on our server, one of the players went very deep into thaumcraft research, but made an arrangement with another town to get the materials for his wands and equipment in exchange for the Tome of Knowledge Sharing when he got a decent way though the research.

Again, i do feel strongly about not forcing players into a set path they have to follow, and I recommend against anything that arbitrarily restricts players.  

Such restrictions could also have issues with creative world experimentation

**Comment by ProsperCraft** [comment]
I completely agree that if you have an item you should not be forced to craft it, if I steal a cauldron from a hobgoblin why would I be forever to craft it.

**Comment by Namikon** [comment]
We'll discuss this further on IRC, as this is some sort of ongoing talk.
There was a suggestion to remove the *requirement* to do quests, so you can directly go the path to unlock draconic evolution, and do anything you wish (Steal cauldrons, Smeltery blocks, you name it).

However: If we will provide such a way, the questbook will be locked in some way. Or at least the couple of special/secret rewards will be limited/removed; Like creative Items, ZPM, or Legendary Lootbags. These items are meant only for those who go the hard and tedious path of completing all the quests, be it alone or with a team (Which makes it a lot easier already). 

As I said, ongoing discussion

**Comment by Dream-Master** [comment]
Any news here?

**Comment by Dream-Master** [comment]
Ok we have to look at the Quest first which one can be changed and which not. I close this here.

**Comment by Gintas2002** [comment]
> While this being a valid suggestion, and I can understand the reason for it, for some items it's just impossible. We are using the quests to tier the pack a bit more than it would be possible with just recipes and GregTech. As for "just skip the progression" and "boost the server's economy, this is exactly what we're trying to prevent here. You are supposed to do it yourself, at least at the beginning. People were running around to find villages and loot the items/smeltery blocks instead of doing it themself. Also: We're already working on another progression system which will prevent you from using/placing machines that you are not yet meant to have. I can fully understand the problem with quest-resets, but those will be gone in the near future, as this is something people are working on for quite a time now. In fact, even the switch from HQM to BQM was due to this problem.
> 
> Anyways, making a few things a bit more "optional" seems to be a valid request. Most quests should be configured to "detect" already; But we'll probably verify this once the conversion to BQM is completed and all bugs are fixed there.

Its annoying, the only ones that are annoying are crafting quests cause you skip those and thats it progression stops and youre locked... you have to follow each quests like a dog, so fucking annoying, i would thing its the whole point of a hard modpack like this and sandbox game like miencraft to read guides or guide book to do stuff how you want to do it... i hate quests, not to mention how it literally has lootbags and a chance for good items, i dont like that, why not make it cosmetic only... and why not just have a quests list rather than progression... if you want progresion in your modpack and everyone not rushing then remove fucking EVERYTHING! by that i mean villages, chests, etc, so its imposible to skip, and even then you can easily skip it i can see, but when you have dumb shit like dungeons that give crazy shit like steel... so like bruh.
