### ISSUE TITLE
dungeons loot be buffed 

### ISSUE THREAD

**Issue by deathxfighter** [GTNewHorizons/NewHorizons#658]
can you buffed the duneons loot? cause right now its not the best and there are multiple floors and like 82+ spawners  

cause mose we get is some enchanted books
gold bar here and there 
 some string and bread

**Comment by Dream-Master** [comment]
Make suggestions what you like to see. Make some list etc. After I am done with Galaxy space 1.10 migration I will look into it. There is a mod by Father Toast if I don't remember wrong which can control loot lists.

**Comment by SanMan911** [comment]
I agree with death. Maybe making some good, or at least, decent loot available in the chests would incentivize going there.
Also, I'd like to ask if dungeon spawn rates of mobs could be dropped BY a factor of maybe 0.3x, because at the moment, the lowest level of dungeons are just totally impossible to breach without having some pretty OP armour and tools. Since the Tier 1 schematics are found only in these levels of dungeons, making such op armour that early is not possible. Just an opinion :)

**Comment by Dream-Master** [comment]
I will give you the loot tables and you put there some loot in it ok ?

**Comment by deathxfighter** [comment]
that works

**Comment by Dream-Master** [comment]
Not find loot tables for Rouge like Dungeons. Have to make some config options for it.
