### ISSUE TITLE
Void Seeds uncraftable

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#738]
Void Seeds uncraftable only on Servers.

**Comment by Technus** [comment]
Another one of this Script voodoo desync bugs?

**Comment by Technus** [comment]
Quote:
Hijoushiki - Dziś o 03:28
Been poking around minetweaker to try to fix this void metal issue.
And I see minetweaker is added recipes for Void Metal (GT) and Void metal (thaum) with the differences being in the case.
I feel like this is probably breaking it.
Since you can't make Void Metal (GT) at all, except when you make Void metal (thaum) and shapeless recipe it.
its probably trying to reference/output the wrong type or something.

**Comment by Dream-Master** [comment]
Ok will will check that. But Void Metal works fine it is only the Void Seed (Nugget)

**Comment by Dream-Master** [comment]
After i remove all void seed recipes from mt script you cant make the seeds anymore.

**Comment by Excaerious** [comment]
Void metal ingots also cannot be made for me on the Dirthuts GT-NH server. Its probably related to the Void Seed issue. Using the Void Seeds you can get from killing Crimson Cultists you cannot make Void Metal ingots. You can see in the below picture that despite the fact that I have more than enough Metallum hooked up it will not allow me to click or craft using these void seeds. 

![void metal](https://cloud.githubusercontent.com/assets/6412128/19427113/c1271c06-940f-11e6-84c2-cf20dba1f600.png)

This is also Hijoukishi by the way.

**Comment by Dream-Master** [comment]
Working on a Solution.

**Comment by Dream-Master** [comment]
https://cdn.discordapp.com/attachments/237161000183267330/237475108652974080/unknown.png

https://cdn.discordapp.com/attachments/237161000183267330/237475149631324160/unknown.png

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/19428598/3f50a7d8-944b-11e6-8091-749933bfd70e.png)

![image](https://cloud.githubusercontent.com/assets/2970688/19428605/4728be32-944b-11e6-9524-ce66025725ac.png)
