### ISSUE TITLE
Nuggets -> Ingots recipe still exists in 3x3 crafting

### ISSUE THREAD

**Issue by Wavepon** [GTNewHorizons/NewHorizons#804]
Title.

**Comment by Technus** [comment]
Applies For:

- lead
- draconium
- awoken draconium
- pulsating iron
- vibrant alloy
- semi-stable (should be ok? not sure)
- silver
- thauminite

There might be multiple types of the same nugget so @Dream-Master i suggest looking at all nuggets in nei when removing recipes. (Better to remove the recipes since sometimes players can get non greg-unified variants from odd sources)

**Comment by Drobac** [comment]
Semi stable leave as is

**Comment by Technus** [comment]
iirc dream added alloysmelter recipe

**Comment by Dream-Master** [comment]
And I thought I catch all recipes.
