### ISSUE TITLE
Lootbag issues

### ISSUE THREAD

**Issue by deathxfighter** [GTNewHorizons/NewHorizons#809]
im tired of tier 6 bags giving 99% trash this is stupid like shit it should be 

tier 6 loot bag goes from tier 4-6 loot no trash and/or have getting trash at 15-30% 

im tired of wasting time having to combine 3 loot bags for tier 6 and get trash

**Comment by Mylezz** [comment]
ive looked into the config and its a 75% chance to get "trash" the group is named TRASH!!!!
and the %'s are off!! in the config!!!! the total # in each group must be 100% not 1405%?!?!?!

Plz fix

**Comment by bigbass1997** [comment]
Mylez the percentages for each item are just that. A chance for EACH one listed. So for 1 bag, there's an x% chance for item A, and a y% chance for item B, and so on. If it was the way you describe, then you would only get 1 type of item per loot bag.

**Comment by Mylezz** [comment]
Look Ik that but it also has a chance of getting from the last group aswell as trash group But the %'s are Broken! Each Group needs to add up to 100%, what u have going is 60% 60% 60% 40% 30% 100% 50% 30% and that add's up to 430% when u need it to total 100% at EACH GROUP or else it breaks the %'s.

with the way u have the config the drops are going to be from the trash group because the %'s are broken.... to fix it make the total % in each group add up to 100%
Please fix ur %'s and configs so the pack can be played the way it's ment to be or atleast fix it so the trash group dosent give 99% of the time...

in the 10 bags ive opend i have only got from the trash group.
 in SP i did a test from 100 bags i got 99% trash items 1 nano crystal from T-6 bags


Thanks
Mylez_

**Comment by deathxfighter** [comment]
big i want tier 6+ loot not just 5 and 4 cause honestly ur saying that upgrading bags are just pointless which honestly is pointless since you get just about 99% garbage and well should i say saplings and bushes its like the reward system from loot bags are bad they need to definely be revamped cause people get tired of opening a bag and all u get is garbage

**Comment by Methes** [comment]
Have you tried applying Fortune III to the lootbags to get better items?

**Comment by Dream-Master** [comment]
The Lootbag xml file is on github so every body is free to add some stuff via pull request.

**Comment by Namikon** [comment]
- The  _chances_ are not (I repeat, **not**) percentages.
  I don't expect you to understand Java code, but please, read about the concept of "weight-based chance" first before you complain.

- Lootbag groups are considered to be random. They are in each mod that has those. Even in Thaumcraft, the red treassue bags might give you "junk".
The concept of ELB is as follows: Each group is merged with the so-called "trash" or "default" group, unless:
    - It is specified by config that this group shall not be merged
    - The Lootbag has Fortune 3 enchantment (And it is not disabled in the config of course)

- Lootbags were never meant to give 100% pure good loot. It is a "you have a chance to get a TierX reward". If you can't accept getting trash, then seriously, grab a book, put Fortune 3 on it, put Lootbag and Book in an anvil and remove the trash-merging

- Writing in caps, even if in rage mode, is considered bad behavior by most people. You can talk about this, you can ask questions, you are welcome to help.
But please do it politely. We are all doing this in our free time; It is our hobby. Nobody wants to get yelled at, or have his work to be considered "stupid shit"

And about opening pull requests:
The repository is public, yes. But make sure you fully understand what you are doing before opening a pull-request. I don't want to fix issues after someone tried to "fix" it.

**Comment by Dream-Master** [comment]
@Namikon 
With pull request i mean suggestions (written) too. I not pull code i not test....  most of the time ;-)

**Comment by Mylezz** [comment]
I've tried enchanting them on several occasions and even in creative mode on a single player world and they wont enchant. With fortune 3 in an anvil.

Also no one sad it was "stupid shit" he sad 
"This is stupid, this shit should be" not as to call the pack or its creator's stupid but to call the random trash stupid, we love this pack and enjoy playing it! Its just frustrating to get crap 99% of the time when u open rewards u worked hard to obtain. ;D

And also yeas the thaumcraft red bags do have a % to drop lesser items but the % is not as high as the lootbags.

The idea of changing the bags to have a better drop rate is simply to have a more enjoyable experience not to say "hay im getting shit i want better items!@ this pack sucks etc etc" because getting berry bushes from a T-6 bag is kind of silly :D

So the point is this
1# the packs is totaly awesome and we love to play it
2# we know the pack is (WIP) and we like that its a (WIP) modpack because its more fun when the players and dev's get to talk and see what needs buffing and what needs balancing.
3# we only want to suggest ideas to help u guyes out not to belittle the mod pack.
4# thanks for making the pack and for bring together people from around the globe to play a 16 bit game about building blocks

**Comment by Mylezz** [comment]
Also my apologies for thinking that the percentages were actually weight-based chances.
I'm so used to code % in unturned configs for mapping  I had forgotten how the Minecraft Java system worked.

So my apologies for that @Namikon

**Comment by deathxfighter** [comment]
i still think tier 6 bags shouldnt get stuff from the trash loot instead get items at least from 3-6 tier due to the fact a player has a very higher chance of getting trash then decent items

**Comment by deathxfighter** [comment]
even sanman ask for the loot bags to get buffed cause even he thinks its bs 


For example

deathxfighter:  legendary bag- 8 eggs
sanman- legendary bag - 5 bushes
boubou- legendary bag - a few sticks and a plank

what are the chances for 3 players to get absolute trash when used at same  time 

like it doesnt matter how many bags we get out of 10 bags 8 are for sure to be garbage

**Comment by deathxfighter** [comment]
@Namikon   in the loot bag code out of each teir what is the base chance of it going to combine trash group?

**Comment by Namikon** [comment]
It always combines trash with the current group. It mainly depends on the weight an Item has how often it will appear. Oh and by the way, thanks to how Vanilla enchanting works, the "Fortune III" ability is broken.
We might add recipes for that; Depends on DreamMaster is he has some spare time

**Comment by Dream-Master** [comment]
any recipe suggestions?

**Comment by Mylezz** [comment]
Lapis  and diamond blocks with the fortune book?

**Comment by Drobac** [comment]
To add Fortune I id say diamond, Fortune II, Nether stars, Fortune III Mysterious crystal or some similar space material, Fortune IV, some Neutronium tier gem

**Comment by Mylezz** [comment]
agreed

**Comment by Technus** [comment]
Closing this, duplicate. Added Ref.

**Comment by Technus** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/815
