### ISSUE TITLE
Pack Simply freezes during launch

### ISSUE THREAD

**Issue by ghost** [GTNewHorizons/NewHorizons#853]
simply freezes on my and if i do manage to open it the pack crashes loading a world have 6GB allocated to it and i have a total of 16GB of ram

Sorry but not the best pack takes so long to load when it does actually load.

**Comment by Tyecon** [comment]
On my PC it takes 7 minutes to launch, and another 2 minutes after joining the server for stuff to load. I ran profiling on it and most of the time (3 minutes) is calculating the ore-dictionary for gregtech which makes it's recipes recursively meaning easier to code but laggier to run and it creates a ton of useless recipes. https://drive.google.com/open?id=0B4Oxvk4QgzFGODhxV00tV0xsNjg Also calculating thaumcraft aspects. It tends to say not responding for the 3 minutes of gregtech loading because it stops updating the window to gain extra processing power. There is no way to fix this, it is just how the mods are made. Just go get snacks or watch a video while it's loading.

**Comment by bigbass1997** [comment]
As Tyecon mentioned, the modpack takes a long time to load, and its for everything that it takes a relatively long time in comparison to other modpacks. But just because it takes longer to start up doesn't somehow reduce the quality of the modpack.

If you have the launcher console window open you can see that it is still running and in fact still loading, even if the main window appears frozen or unresponsive.

Load time varies depending on the user's system hardware (not just RAM). Mine takes around 6-7 minutes also and about 20-30 seconds to load into multiplayer. (little longer for single player as there is more to start up when loading single player worlds).

Now the crashes you experience: We will need a crash log file in order to help you further with that.

**Comment by EvgenijM86** [comment]
Freezes for me too (in 1.2.1.0). I can go to start screen (after ~5 min loading), then I start my single player world. After ~1-2 min loading time players appears on screen and I start falling down into nothingness. Screen rendering does not lag, but chunks are not loaded for some reason. Tried waiting ~10 more minutes with no effect. And I cannot quit game without forcefully shutting down minecraft. It seems there is an endless loop that does not respond to actions.

debug.log stops at:
```
[B#347] 2016/12/04 17:34:46 [INFO]  [17:34:46] [Client thread/INFO] [INpureCullingEngine]: Loading: AppliedEnergistics2.js
[B#347] 2016/12/04 17:34:46 [INFO]  [17:34:46] [Client thread/INFO] [INpureCullingEngine]: Loading: Tcon.js
[B#347] 2016/12/04 17:34:46 [INFO]  [17:34:46] [Client thread/INFO] [INpureCullingEngine]: Loading: MFR.js
[B#347] 2016/12/04 17:44:51 [INFO] TimeoutException
```

**Comment by Dream-Master** [comment]
@ghost Any news here?

**Comment by Dream-Master** [comment]
I dont see any problems here.
