### ISSUE TITLE
Sgcraft and Enhanced portals appear to be redundant

### ISSUE THREAD

**Issue by Saereth** [GTNewHorizons/NewHorizons#898]
These 2 mods seem to have no way to obtain their items and are essentially just there, perhaps future implementation? Not sure why they were in the pack so figured I'd post up here in case it was an oversight.

**Comment by Drobac** [comment]
SGCraft and Enhanced Portals were added for our own server use. iI the beginning as we didnt have plugins that allowed teleportation. EP was used as portals to players bases and SGCraft is used because we have a schematic of Atlantis in our overworld that we use as spawn and that gate can be used to access outposts on all other dimensions (to reduce the needs to use rockets all the time). Both mods will have their recipes soon so they can be crafted in normal play

**Comment by Dream-Master** [comment]
9x9 recipes for Late/endgame are planed.

**Comment by Saereth** [comment]
awesome, thanks for the clarification!

**Comment by Drobac** [comment]
Givf stargates plx

**Comment by bartimaeusnek** [comment]
@Drobac done. https://github.com/GTNewHorizons/NewHorizons/blob/e62d0bbba74f0d3e889e422734151dcb3818d58a/scripts/SGCraft.zs#L68
