### ISSUE TITLE
Add The BetweenLands mod as a HARD quest line

### ISSUE THREAD

**Issue by Mylezz** [GTNewHorizons/NewHorizons#912]
This mod is Progressive adventure mod similar to Twilight forest its hard hard hard and your guaranteed to die alot...

Overworld food rots when u enter this place, here flint and steel wont work, improved combat system when in this place revolving around 3 gems you obtain from here

decay of the player and his/her food and tools aswell as
Over 250 new sounds, including 7 immersive ambient tracks and 33 music tracks, 

Aswell as integrated custom shaders to improve your playing experience

Please please please take a look at it, it belongs in this pack!!!

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1441135-the-betweenlands-a-dark-hostile-environment-1-10-2

**Comment by Namikon** [comment]
This should not be considered a "mod", but instead an (almost) total conversion.
This mod adds:
- 35 new Potion effects (Which will most likely exceed the current maximum of potionIDs we have available. Need to verify that)
- 7 new Biome IDs (The BiomeID list is also heavily crowded due to RTG and GalaxySpace. Could cause issues)
- 651 new Items/Blocks (Of which at least 50% have individual recipes, and are tiered within the mod as part of its progression system)
- 9 new Ores (Of which "Sulfur" is a duplicate and might cause Oredict-balance issues, both ways)

Even if we put the possible issues with overlapping IDs aside, this mod needs to be torn apart "block-by-block", so to speak, and integrated to our own progression system. That being said, this will also involve serious work on our side to cover with the changes in our own wiki (and theirs is large..) as we can't keep the vanilla recipes it comes with.
Also, most likely tools and items we have will just make you overpowered for that dimension.

After the first look at this mod, I'd estimate the time required to integrate this mod and all of its items/blocks in GTNH to at least 5 to 7 weeks. Adding recipes and combine our progression with theirs, even more time.

In the end, it is up to DreamMasterXXL if he wants to put time into that. It did give me goosebumps while playing it the first hour, and I had a few "Quake 1" moments (Sounds, textures, light levels,..). As a stand-alone mod, or in combination with the mods it's meant to work with (Apparently Thaumcraft, and maybe some other magic-related mods) this is an awesome addition. And I will definitely play it (When I happen to have time to play again one day) 

But in my opinion, for our Modpack, no. It's too much, too different, and we would've to destroy its tiering/progression in order to add it.

Also, a lot of people put a ton of effort into this. Sure, nobody can prevent anyone from changing recipes, but the way *we* take apart mods and add it to our pack is different; We'd at least have to get in contact with them to ask for permission to do such massive changes;
As people will, of course, run to their page if they have issues with that mod/dimension and ask for help, or complain about broken recipes.

**Comment by Mylezz** [comment]
Alright!
im Willing to help Dream if he wants to add this,
il keep looking for more adventure style mod's that are "Smaller" ;D

**Comment by Dream-Master** [comment]
Will look into this mod first.

**Comment by Dream-Master** [comment]
Will close it now because we have enough mods i guess and the pack becomes slower and slower.
