### ISSUE TITLE
[Suggestion] Creating Salt with machine

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/NewHorizons#956]
Currently there's only very inconvenient way of creating Salt:
Pot + Water Bucket in Shapeless Recipe.
Considering Salt is needed in a lot of food recipes this is very tedious.

Having a machine extract Salt from Water would be great addition.

**Comment by kokochicken** [comment]
There is salt ore veins , I believe that should work for salt recipes

**Comment by Dream-Master** [comment]
The problem is we dont have salt water and make a recipe extracting sault aut of fresh water is a bit unrealistic. Adding some saltwater to worldgen is maybe possible but not on the server. (existing World)

**Comment by Drobac** [comment]
Seeing as the normal recipe for making salt has normal water in the bucket in its recipe, dont see why we would need a new type of water. Atm you can automate the salt using an Ender io crafter or some other autocrafter machine combined with a fluid canner. But it would be a good idea to add a recipe like methes suggested because getting salt the autocrafting way is rather slow and using GT machines it can be sped up like all the other GT processes.

**Comment by Dream-Master** [comment]
Any suggestion about the recipe @Methes , @Drobac

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/21824629/86624a32-d780-11e6-90ff-d91f9bb05ff3.png)

I can do this recipe to the assembler if someone will automation.

**Comment by Dream-Master** [comment]
But if i see right the recipes not make any sense. Better is find some salt vein which isnt that hard.

**Comment by Methes** [comment]
Fluid solidifier
Water 500ml + mold (ingot)
4 EU/t, 20 seconds
Produces 1 salt.

**Comment by Dream-Master** [comment]
We have huge gt veins with salt Ore. Fresh water normaly dont have any salt if i informed right :)

**Comment by Saereth** [comment]
You can also autocraft salt with extracells easily

**Comment by Dream-Master** [comment]
O if you have a better realistic recipe i will open this issue again.
